= Compactor


Tiered Storage uses a partitioned, synchronous, incremental, garbage-first, and moving compactor, working on the disk only.

It's partitioned in the sense that compactions happen for each Hazelcast partition, offloaded from Hazelcast's partition operation threads.
This allows operations assigned on the given partition operation thread to execute, including operations of the same partition, of different IMaps or data structures.

Tiered Storage compactors are triggered before and after the operations, allocating data enough to reach the configured thresholds either for each partition or globally.
This means the compactor runs synchronously to the operations of the same partition and map.

Being incremental means that the compactor scans only a fraction of the used disk space at once to free the partition of the IMap as soon as possible.

The compactor of Tiered Storage is based on statistics.
When it comes to reclaim some space on the disk, it scans the area with the highest garbage ratio to be as efficient as possible, because working with garbage requires no further action.

The alive entries the compactor finds get moved to the memory, temporarily decreasing the efficiency of the hot cache.

The compactor scans the disk linearly, and moves the alive entries to the memory linearly.
This means the IMap entries adjacent on the disk before compaction will still be adjacent after the compaction.
This can help access patterns that need to take entries in order.

=== Configuration Parameters

The compactor can be fine-tuned by properties.
For information on the parameters, see xref:tiered-storage:configuration.adoc#fine-tuning[Fine-tuning].
