= Tiered Storage
:description: Hazelcast’s Tiered Storage feature offers an extension to Hazelcast map which allows you to store a larger data set than available memory.
:page-aliases: ROOT:tiered-storage.adoc
:page-beta: true
:page-enterprise: true
[[tiered-storage]]

{description}

NOTE: Currently, the Tiered Storage feature is available to our customers who already have a Hazelcast Enterprise license.
Starting with Hazelcast 5.2, this feature will become a separately licensed feature, i.e., you will need a new license.

== What Can You Do with Tiered Storage?

* Have fewer Hazelcast members for large maps: If you have a map with 1TB of data, you may need
around 10 Hazelcast members if all data is kept in the memory, With Tiered Storage, you would need one
or two members depending on your cluster’s availability needs.
* Size-comfortable SQL operations: When you do table joins in SQL, the intermediate result may become
too large to fit in the memory; with Tiered Storage this is not an issue. 

== How Does Tiered Storage Work?

Tiered Storage uses the following:

* An in-memory index to allow faster access to map entries.
* A special memory manager to decide which entries to store in the memory tier or the disk tier. If a map entry is not accessed for some time, it gets flushed to the disk. If a map is frequently accessed, it stays in memory.

== Not Yet Supported

- Data recovery from persisted data: When a Hazelcast member has Tiered Storage enabled and it fails or shuts down, you are not able to use the local device files of Tiered Storage for data recovery. Data recovery will be supported in the future releases.

- xref:query:indexing-maps.adoc[Map indexes]: You cannot yet create indexes for maps that are configured to use Tiered Storage.

