= Overview
:description: Hazelcast’s Tiered Storage feature offers an extension to Hazelcast Map which allows you to store a larger data set than available memory.
:page-aliases: ROOT:tiered-storage.adoc[]
:page-beta: true
[[tiered-storage]]

{description}

NOTE: The Tiered Storage feature is in BETA state; it is not recommended to use in production environments.

NOTE: Currently, the Tiered Storage feature is available to our customers who already have a Hazelcast Enterprise license.
Starting with Hazelcast 5.2, this feature will become a separately licensed feature, i.e., you will need a new license.

== What Can You Do with Tiered Storage?

* Have fewer Hazelcast members for large maps - if you have a map having 1 TB of data, you may be needing
around 10 Hazelcast members if all data is kept in the memory; with Tiered Storage, you would need one
or two members depending on your cluster’s availability needs.
* Size-comfortable SQL operations - when you do table joins in SQL, the intermediate result may become
too large to fit in the memory; with Tiered Storage this is not an issue. 

== How Does Tiered Storage Work?

Tiered Storage uses

* an in-memory index to allow faster access to map entries
* a special memory manager, i.e., HybridLog, to decide which entries to store in the memory tier or disk tier -
if a map entry is not accessed for some time, it gets flushed to the disk; if it is a frequently accessed data, it stays in the memory.
Note that an entry cannot be available in both tiers.

== Not Yet Supported

When a Hazelcast member with Tiered Storage enabled fails or shut down, you are not able to use the local device files of Tiered Storage for data recovery.
This will be supported in the future releases.

