= Tiered Storage
:description: Tiered Storage offers an extension to Hazelcast map, which allows you to store a larger data set than available memory.
:page-aliases: ROOT:tiered-storage.adoc[]
:page-enterprise: true
[[tiered-storage]]

{description}

NOTE: If your Enterprise license was generated before Hazelcast Platform version 5.2, you'll need a new Enterprise license that enables Tiered Storage.
See xref:deploy:enterprise-licenses.adoc[].

Tiered Storage allows you to work with datasets that are larger than memory using the same Hazelcast map API. It allows you to optimize infrastructure costs and performance by combining a fast in-memory layer with a cost-effective, high-capacity disk-based storage layer.

Furthermore, with a extended data capacity per member, Tiered Storage can also reduce the number of deployed Hazelcast cluster members.

Consider using Tiered Storage if one of the following is true for your use-case.

- The data size Hazelcast manages exceeds the capacity of the memory.
- You are willing to trade off performance for lower ownership costs.
- The hot set of entries fit in the memory.
- You have significant temporal access patterns inside a very large dataset.
- Your project uses MapStore and you intend to use local disk to improve the access latency of the entries not fitting in the memory of your machine.

== Limitations

- Data recovery from persisted data: When a Hazelcast member has Tiered Storage enabled and it fails or shuts down, you are not able to use the local device files of Tiered Storage for data recovery.Data recovery will be supported in the future releases.

- Time-to-live (TTL) expiration is not supported by the Tiered-Storage-backed maps.
This means that methods, such as `IMap.put`, throw `UnsupportedOperationException` if a TTL value is provided.
If the default TTL setting is present in the map configuration, `InvalidConfigurationException` is thrown during the member startup.

- Max-Idle expiration is not supported by the Tiered-Storage-backed maps.
This means that methods, such as `IMap.put`, throw `UnsupportedOperationException` if a Max-Idle value is provided.
If the default Max-Idle setting is present in the map configuration, `InvalidConfigurationException` is thrown during the member startup.

- Eviction is not supported.
If an eviction policy is configured for a Tiered-Storage-backed map, `InvalidConfigurationException` is thrown during the member startup.

- Data Persistence and Tiered Storage are mutually exclusive features.
If both are enabled simultaneously, `InvalidConfigurationException` is thrown during the member startup.

- SQL is not supported for the Tiered-Storage-backed maps. `UnsupportedOperationException` is thrown when SQL query is executed.
To avoid this, use xref:query:predicate-overview.adoc[Predicate API] instead.

- Dynamically adding local devices is not supported.

== Supported Devices

Hazelcast supports only NVMe (local) SSD devices for Tiered Storage.
While HDDs and some network storages work with the same file abstraction that local SSDs do, and technically speaking such setups work, the access latency of these devices compared to that of the modern SSDs are so high that using Tiered Storage with such devices are not supported.

== High-Level Design Overview

The Tiered Storage feature for IMaps is backed by a special-purpose, addressable data structure called HybridLog.
It is called HybridLog because it seamlessly combines in-place updates with a traditional append-only log.
This data structure spans over the memory and the configured disk making the aggregated capacity of the resources available for storing IMap's entries.
There is a HybridLog data structure for every partition of every IMap.

The IMap entries stored in these HybridLog instances are internally referenced by their logical addresses.
The key to logical address mapping is done by a hash index component.
These hash indices are hashtables using separate chaining for conflict resolution.
The table of these hash indices are stored in the native memory, whereas the chaining information of the buckets are stored on the disk.

Tiered Storage makes sure every accessed IMap entry is available in the memory to build a hot cache of entries.
This means, if an entry is on the disk, first it gets relocated to the memory inside the HybridLog hosting the entry, and its previous location on the disk becomes unreachable.
As more and more entries are relocated to the in-memory region of the HybridLog, the memory space occupied by the unreachable entries on disk are reclaimed.
This reclamation is done by a compactor running synchronously with regards to the IMap operations of the same partition.
