= Troubleshooting

In this section, we list common problems and their corresponding solutions.

== Too Many Open Files

Tiered Storage is backed by files on the disk. Therefore, it increases the open file descriptor count of the operating system by the number of files it uses.
When Tiered Storage reports "too many open files", the open file descriptors in the operating system have reached the maximum open file descriptors setting.
In this case, Tiered Storage can't open more files, and might fail to read or write data from, or to, the disk.
Failed writes retry until they succeed to guarantee the consistency of the internal state of Tiered Storage, but failed reads might get reported to the client.

By default, every map with Tiered Storage enabled, and every configured index on these maps, use a maximum of 128 files.

== Tiered Storage Rejects Storing Big Entries

Storing big entries might be rejected by Tiered Storage with an exception message similar to the following:

```
The requested Tiered Storage record (combined key + value) size: <entry_size> is bigger than the maximum size of 524284. Increase the hybrid log page size to store bigger values.
```

The HybridLog data structure is internally organized in pages and the size of the page defines the maximum record size it can store.
If this problem is experienced with big entries, increase the page size by setting `hazelcast.tiered.store.hybridlog.page.size.in.mb`.
For further information about this property, see xref:tiered-storage:configuration.adoc[].
