= Configuring with System Properties
[[configuring-with-system-properties]]
:description: You can use system properties and environment variables to configure Hazelcast and override existing settings in a root configuration file. Environment variables are useful for configuring members in containerized environments.

You can use system properties to configure some aspects of Hazelcast. You set
these properties as name and value pairs through declarative configuration,
programmatic configuration or JVM system property. Following are examples for
each option.

.Using Java?
NOTE: If you use xref:configuring-programmatically.adoc#builders[configuration builders] or the `new Config()` constructor with the Java member API, you cannot override existing configuration with system properties and environment variables. To override existing configuration, you must use xref:configuring-programmatically.adoc#loaders[configuration loaders].

You can set
system properties as name and value pairs through declarative configuration,
programmatic configuration, or JVM arguments:

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <properties>
        <property name="hazelcast.property.foo">value</property>
    </properties>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
    ...
    properties:
      hazelcast.property.foo: value
    ...
----
====

**Programmatic Configuration:**

[source,java]
----
Config config = new Config();
config.setProperty( "hazelcast.property.foo", "value" );
----

**Using JVM's `System` class or `-D` argument:**

`System.setProperty( "hazelcast.property.foo", "value" );`

or

`java -Dhazelcast.property.foo=value`

All Hazelcast system properties
are listed in the xref:ROOT:system-properties.adoc[System Properties appendix] with their
descriptions, default values and property types as a reference for you.
