= Configuring with System Properties and Environment Variables
[[configuring-with-system-properties]]
:description: You can use system properties and environment variables to configure  some aspects of Hazelcast and override existing settings in a configuration file.

{description}

include::partial$warning-override.adoc[]

You can set
system properties as name and value pairs through declarative configuration,
programmatic configuration, or JVM arguments:

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <properties>
        <property name="hazelcast.property.foo">value</property>
    </properties>
    ...
</hazelcast>
----
--

YAML::
+
--
[source,yaml]
----
hazelcast:
    ...
    properties:
      hazelcast.property.foo: value
    ...
----
--

Java::
+
--
[source,java]
----
Config config = new Config() ;
config.setProperty( "hazelcast.property.foo", "value" );
----
--
JVM::
+
--
.Java command
[source,shell]
----
java -Dhazelcast.property.foo=value
----

.JAVA_OPTS
[source,shell]
----
JAVA_OPTS="-Dhazelcast.property.foo=value"
----
--
====

== Naming System Properties and Environment Variables

The names of system properties and environment variables follow a consistent pattern, where the names match those in the YAML declarative configuration file. See xref:configuring-declaratively.adoc[].

NOTE: All entries need to mirror the YAML configuration structure which differs slightly to XML. And, you cannot configure settings that use YAML lists.

The names of environment variables follow this pattern:

* Each configuration entry needs to start with `HZ_` for member configuration or `HZCLIENT_` for client configuration.
* A new configuration level should be introduced with an underscore (`_`).
* Dashes (`-`) should be removed.
* Names should be in upper case.

The names of system properties must follow these rules:

* Each configuration entry needs to start with `hz.` for member configuration or `hz-client.` for client configuration.
* A new configuration level should be introduced with a dot (`.`).
* Names should be in lower case.

For example, consider the following configuration settings.

[source,yaml]
----
hazelcast:
  cluster-name: dev
  network:
    port:
      auto-increment: true
----

You can override these settings by using the following environment variables or system properties:

.Environment variables
[source,shell]
----
HZ_CLUSTERNAME=dev
HZ_NETWORK_PORT_AUTOINCREMENT=true
----

.System properties
[source,shell]
----
hz.cluster-name=dev
hz.network.port.auto-increment=true
----

All Hazelcast system properties
are listed in the xref:ROOT:system-properties.adoc[System Properties reference] with their
descriptions, default values, and property types.