= Configuration Files
:description: You can declare settings for Hazelcast members and clients, using a YAML or XML configuration file. Although Hazelcast members and clients read from a single configuration file, you can store settings in multiple files and import them into a single root file to enable reuse.
:page-aliases: using-variables.adoc, overriding-configuration-settings.adoc, variable-replacers.adoc

{description}

== Configuration Files

Hazelcast comes with the following configuration files in the  `/config` directory:

[cols="20%m,80%a"]
|===
|Configuration File|Description

|
ifdef::snapshot[]
link:https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-default.xml[hazelcast-default.xml]

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-default.yaml[hazelcast-default.yaml]
endif::[]
ifndef::snapshot[]
link:https://github.com/hazelcast/hazelcast/tree/{page-component-version}.z/hazelcast/src/main/resources/hazelcast-default.xml[hazelcast-default.xml]

https://github.com/hazelcast/hazelcast/tree/{page-component-version}.z/hazelcast/src/main/resources/hazelcast-default.yaml[hazelcast-default.yaml]
endif::[]
|Default configuration file for Hazelcast.
The configuration for Hazelcast's storage and streaming engines in this file should
be fine for most users. If not, you can tailor this file according
to your needs by adding/removing/modifying properties. You can browse through the Clustering Configurations
section to learn about configuring Hazelcast's several aspects including xref:clusters:network-configuration.adoc[networking]
and xref:configuration:jet-configuration.adoc[Jet engine].

|
ifdef::snapshot[]
link:https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-full-example.xml[hazelcast-full-example.xml]

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-full-example.yaml[hazelcast-full-example.yaml]
endif::[]
ifndef::snapshot[]
link:https://github.com/hazelcast/hazelcast/tree/{page-component-version}.z/hazelcast/src/main/resources/hazelcast-full-example.xml[hazelcast-full-example.xml]

https://github.com/hazelcast/hazelcast/tree/{page-component-version}.z/hazelcast/src/main/resources/hazelcast-full-example.yaml[hazelcast-full-example.yaml]
endif::[]

|Configuration files which include all Hazelcast configuration
elements and attributes with their descriptions.
You can use these files as a reference document to learn about any element
or attribute.

|
ifdef::snapshot[]
link:https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-client-full-example.xml[hazelcast-client-full-example.xml]

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-client-full-example.yaml[hazelcast-client-full-example.yaml]
endif::[]
ifndef::snapshot[]
link:https://github.com/hazelcast/hazelcast/tree/{page-component-version}.z/hazelcast/src/main/resources/hazelcast-client-full-example.xml[hazelcast-client-full-example.xml]

https://github.com/hazelcast/hazelcast/tree/{page-component-version}.z/hazelcast/src/main/resources/hazelcast-client-full-example.yaml[hazelcast-client-full-example.yaml]
endif::[]

|Complete Hazelcast client example configuration
file which includes all configuration elements and attributes with their descriptions.

|
ifdef::snapshot[]
link:https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-client-failover-full-example.xml[hazelcast-client-failover-full-example.xml]

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-client-failover-full-example.yaml[hazelcast-client-failover-full-example.yaml]
endif::[]
ifndef::snapshot[]
link:https://github.com/hazelcast/hazelcast/tree/{page-component-version}.z/hazelcast/src/main/resources/hazelcast-client-failover-full-example.xml[hazelcast-client-failover-full-example.xml]

https://github.com/hazelcast/hazelcast/tree/{page-component-version}.z/hazelcast/src/main/resources/hazelcast-client-failover-full-example.yaml[hazelcast-client-failover-full-example.yaml]
endif::[]

|Complete Hazelcast client failover example
configuration file which includes all Hazelcast client failover configuration elements and
attributes with their descriptions. Read about Blue-Green Deployment and Disaster Recovery in the
xref:clients:java.adoc#blue-green-deployment-and-disaster-recovery[Java client docs].

|===

== Setting the Path to a Configuration File

Before looking for configuration files either in your working directory or in the classpath, Hazelcast checks the following system properties:

- `hazelcast.config` for member configuration
- `hazelcast.client.config` for client configuration

You may want to set these properties if you have configuration files for different environments and you want to start members with different configurations. For example, you may have a test configuration file and a production configuration file.

```
-Dhazelcast.config=`*`<path to the hazelcast.xml or hazelcast.yaml>
```

The path can be a regular one or a classpath reference with the prefix `classpath:`.

[NOTE]
====
The suffix of the filename is used to determine the language of the configuration.
If the suffix is `.xml` the
configuration file is parsed as an
XML configuration file. If it is `.yaml`, the configuration file is parsed as a
YAML configuration file.
====

For details about precedence, see xref:understanding-configuration.adoc#configuration-precedence[Configuration Precedence].

If you use the Java member API, you can also xref:configuring-programmatically.adoc#config-file[use a configuration file].

[[composing-declarative-configuration]]
== Importing Configuration Snippets into Files

If you want to reuse the same configuration settings in multiple files, you can store sections of XML and YAML configuration in separate files and import those into a single _root configuration file_. For example, you may want all development clusters to be called `test`. In this case, the `cluster-name` configuration can be stored in one file and imported into the root configuration file:

[tabs] 
==== 
XML:: 
+ 
-- 
.development-cluster-config.xml
[source,xml]
----
<hazelcast>
    <cluster-name>test</cluster-name>
</hazelcast>
----

To import a file into another, use the `<import/>` element.

.Root configuration file
[source,xml]
----
<hazelcast>
    <import resource="development-cluster-config.xml"/>
</hazelcast>
----
--
YAML:: 
+ 
-- 
.development-cluster-config.yaml
[source,yaml]
----
hazelcast:
  cluster-name: test
----

To import a file into another, use the `import` key.

.Root configuration file
[source,yaml]
----
hazelcast:
  import:
    - development-cluster-config.yaml
----
--
====

You can also import files from the classpath and file system into a root configuration file:

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    <import resource="file:///etc/hazelcast/development-cluster-config.xml"/> <!-- loaded from filesystem -->
    <import resource="classpath:development-network-config.xml"/>  <!-- loaded from classpath -->
</hazelcast>
----
--
YAML:: 
+ 
-- 
[source,yaml]
----
hazelcast:
  import:
    # loaded from filesystem
    - file:///etc/hazelcast/development-cluster-config.yaml
    # loaded from classpath
    - classpath:development-network-config.yaml
----
--
====

Importing resources with <<variables, variables>> in their names is also supported:

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    <import resource="${environment}-cluster-config.xml"/>
    <import resource="${environment}-network-config.xml"/>
</hazelcast>
----
--
YAML:: 
+ 
-- 
[source,yaml]
----
hazelcast:
  import:
    - ${environment}-cluster-config.yaml
    - ${environment}-network-config.yaml
----
--
====

== Overriding Configuration with System Properties and Environment Variables
[[overriding-configuration]]

You can override the settings in a configuration file
without having to modify it. For example, you may want to make some configuration changes for a specific environment. In this case, you can use system properties or
environment variables to override the settings in the file.

include::partial$warning-override.adoc[]

See xref:configuring-with-system-properties.adoc[].

[[variables]]
== Using Variables

In configuration files, you can use
variables to set configuration settings.

To set the variable's value, you can use a system
property either in your code or in the command line interface.

To use a variable
in a configuration file to access the values of the system properties you set, use the `$\{variable-name}` syntax.

For example, the following command sets the `cluster.name` variable to `test`, using a system property.

```
-Dcluster.name=test
```

You can reference this variable in your configuration file. When the cluster starts, this variable is replaced with the value that is set in the system property.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    <cluster-name>${cluster.name}</cluster-name>
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  cluster-name: ${cluster.name}
----
====

If you do not want to rely on the system properties, you can use the
`XmlConfigBuilder` or `YamlConfigBuilder` and explicitly
set a `Properties` instance, as shown below.

[source,java]
----
Properties properties = new Properties();

// fill the properties, e.g., from database/LDAP, etc.

XmlConfigBuilder builder = new XmlConfigBuilder();
builder.setProperties(properties);
Config config = builder.build();
HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
----

== Variable Replacers

Variable replacers are used to replace custom strings during startup when a cluster first loads a configuration file. For example, you can use a variable replacer to mask sensitive information such as usernames and passwords.

Variable replacers implement the interface `com.hazelcast.config.replacer.spi.ConfigReplacer`. For basic information about how a replacer works, see the 
https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/replacer/spi/ConfigReplacer.html[Javadoc^].

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <config-replacers fail-if-value-missing="false">
        <replacer class-name="com.acme.MyReplacer">
            <properties>
                <property name="propName">value</property>
                ...
            </properties>
        </replacer>
        <replacer class-name="example.AnotherReplacer"/>
    </config-replacers>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
    ...
    config-replacers:
      fail-if-value-missing: false
      replacers:
        - class-name: com.acme.MyReplacer
          properties:
            propName: value
            ...
        - class-name: example.AnotherReplacer
    ...
----
====

The `config-replacers` setting contains all the configuration options for replacers. You can define one or more replacers in the same file:

* `fail-if-value-missing`: Specifies whether the loading configuration process
stops when a replacement value is missing. It is an optional attribute and its default value is true.
* `class-name`: Full class name of the replacer.
* `<properties>`: Contains names and values of the properties used to configure a replacer.
Each property is defined using the `<property>` sub-element. All of the properties are
explained in the upcoming sections.

The following replacer classes are provided by Hazelcast as example implementations of
the `ConfigReplacer` interface. Note that you can also implement your own replacers.

* `EncryptionReplacer`
* `PropertyReplacer`

NOTE: There is also a `ExecReplacer` which runs an external command and uses its
standard output as the value for the variable. See its
https://github.com/hazelcast/hazelcast-code-samples/blob/master/variable-replacers/src/main/java/com/hazelcast/sample/replacer/ExecReplacer.java[code sample^].

=== EncryptionReplacer

This example `EncryptionReplacer` replaces encrypted variables by its plain
form. The secret key for encryption/decryption is generated from a password
which can be a value in a file and/or environment specific values, such as MAC
address and actual user data.

Its full class name is `com.hazelcast.config.replacer.EncryptionReplacer` and
the replacer prefix is `ENC`. The following are the properties used to
configure this example replacer:

* `cipherAlgorithm`: Cipher algorithm used for the encryption/decryption.
Its default value is AES.
* `keyLengthBits`: Length of the secret key to be generated in bits. Its default value is 128 bits.
* `passwordFile`: Path to a file whose content should be used as a part
of the encryption password. When the property is not provided no file is
used as a part of the password. Its default value is null.
* `passwordNetworkInterface`: Name of network interface whose MAC address
should be used as a part of the encryption password. When the property is
not provided no network interface property is used as a part of the password.
Its default value is null.
* `passwordUserProperties`: Specifies whether the current user properties
(`user.name` and `user.home`) should be used as a part of the encryption
password. Its default value is true.
* `saltLengthBytes`: Length of a random password salt in bytes. Its default
value is 8 bytes.
* `secretKeyAlgorithm`:  Name of the secret-key algorithm to be associated
with the generated secret key. Its default value is AES.
* `secretKeyFactoryAlgorithm`: Algorithm used to generate a secret key from
a password. Its default value is PBKDF2WithHmacSHA256.
* `securityProvider`: Name of a Java Security Provider to be used for retrieving
the configured secret key factory and the cipher. Its default value is null.

NOTE: Older Java versions may not support all the algorithms used as defaults.
Please use the property values supported your Java version.


As a usage example, let's create a password file and generate the encrypted
string out of this file as instructed below:

. Create the password file: `echo '/Za-uG3dDfpd,5.-' > /opt/master-password`
. Define the encrypted variables:
+
```
java -cp hazelcast-*.jar \
    -DpasswordFile=/opt/master-password \
    -DpasswordUserProperties=false \
    com.hazelcast.config.replacer.EncryptionReplacer \
    "aCluster"
$ENC{Gw45stIlan0=:531:yVN9/xQpJ/Ww3EYkAPvHdA==}
```
+
. Configure the replacer and put the encrypted variables into the configuration:
+
[source,xml]
----
<hazelcast>
    <config-replacers>
        <replacer class-name="com.hazelcast.config.replacer.EncryptionReplacer">
            <properties>
                <property name="passwordFile">/opt/master-password</property>
                <property name="passwordUserProperties">false</property>
            </properties>
        </replacer>
    </config-replacers>
    <cluster-name>$ENC{Gw45stIlan0=:531:yVN9/xQpJ/Ww3EYkAPvHdA==}</cluster-name>
</hazelcast>
----
+
. Check if the decryption works:
+
```
java -jar hazelcast-*.jar
Apr 06, 2018 10:15:43 AM com.hazelcast.config.XmlConfigLocator
INFO: Loading 'hazelcast.xml' from working directory.
Apr 06, 2018 10:15:44 AM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [aCluster] [3.10-SNAPSHOT] Prefer IPv4 stack is true.
```

As you can see in the logs, the correctly decrypted cluster name value
("aCluster") is used.

=== PropertyReplacer

The `PropertyReplacer` replaces variables by properties with the given
name. Usually the system properties are used, e.g., `${user.name}`.
There is no need to define it in the configuration files.

Its full class name is `com.hazelcast.config.replacer.PropertyReplacer`
and the replacer prefix is empty string ("").


=== Implementing Custom Replacers

You can also provide your own replacer implementations. All replacers
have to implement the interface `com.hazelcast.config.replacer.spi.ConfigReplacer`.
A simple snippet is shown below.

[source,java]
----
public interface ConfigReplacer {
    void init(Properties properties);
    String getPrefix();
    String getReplacement(String maskedValue);
}
----

== Updating Member Configuration Files at Runtime

When a member is running, you can use dynamic configuration to add some supported configuration to a configuration file at runtime. See xref:dynamic-config.adoc[].
