= Configuration Object
:description: You can use a configuration object (config object) to configure members and clients with any Hazelcast client or the Java member API. To create new instances of members or clients, pass the config object to those instances.

{description}

For example, in Java, you can create a `Config` object, set/change its properties and attributes
and use it to create new instances of members and clients. The following example configures some network and map properties for a member.

[source,java]
----
include::ROOT:example$/ProgrammaticConfSample.java[tag=pcs]
----

To create a Hazelcast member with the configuration object, pass it to a new `HazelcastInstance` object:

```
HazelcastInstance hazelcast = Hazelcast.newHazelcastInstance( config );
```

NOTE: All configuration must be completed before creating the `HazelcastInstance` object. The `Config` object cannot be modified after the instance is started.

[[config-file]]
== Loading Configuration Files into the Configuration Object

With the Java API, you can use the following methods to load the contents of a configuration file into the configuration object.

Configuration files allow you to store member or client configuration settings in YAML or XML format. You should consider using configuration files if you want to persist changes that you make to <<dynamic-configuration, dynamic configuration>>.

.Configuration Loaders
[cols="3,7"]
|===
|Method|Description

|`loadFromFile`
|Creates a configuration object (`Config`) based on a Hazelcast configuration file (XML or YAML).

|`loadDefault`
|Loads `Config` using the default lookup mechanism to locate the configuration file. Loads the nested
Hazelcast configuration also by using its default lookup mechanism.

|`loadFromClasspath`
|Creates `Config` which is loaded from a classpath resource.

|`loadFromString`
|Creates `Config` from the provided XML or YAML string content.

|`loadFromStream`
|Creates `Config` from the provided XML or YAML stream content.

|===

All configuration loaders take an optional `properties` parameter.
The default behavior uses the `System.getProperties()` method to resolve the configuration file.

To build a `Config` object from the XML declarative configuration:

* `Config cfg = new XmlConfigBuilder(xmlFileName).build();`
* `Config cfg = new XmlConfigBuilder(inputStream).build();`
* `Config cfg = new ClasspathXmlConfig(xmlFileName);`
* `Config cfg = new FileSystemXmlConfig(configFilename);`
* `Config cfg = new UrlXmlConfig(url);`
* `Config cfg = new InMemoryXmlConfig(xml);`

To build a `Config` object from the YAML declarative configuration:

* `Config cfg = new YamlConfigBuilder(yamlFileName).build();`
* `Config cfg = new YamlConfigBuilder(inputStream).build();`
* `Config cfg = new ClasspathYamlConfig(yamlFileName);`
* `Config cfg = new FileSystemYamlConfig(configFilename);`
* `Config cfg = new UrlYamlConfig(url);`
* `Config cfg = new InMemoryYamlConfig(yaml);`

By default, Hazelcast searches for
`hazelcast.yaml/xml` files in the classpath and
working directory, but you can control the name of the files using the
relevant system properties such as `hazelcast.config`.

Here is the sample code for creating a new Jet engine configuration using
the configuration loader:

[source,java]
----
String yaml = ""
   + "hazelcast:\n"
   + "  instance:\n"
   + "    cooperative-thread-count: 64\n"
   + "    flow-control-period: 50\n"
   + "    backup-count: 2\n"
   + "    scale-up-delay-millis: 5000\n"
   + "    lossless-restart-enabled: true\n";

Config config = Config.loadFromString(yaml);
HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
----

Or using properties:

[source,java]
----
String yaml = ""
   + "hazelcast:\n"
   + "  instance:\n"
   + "    backup-count: ${backup-count}\n"
   + "    scale-up-delay-millis: ${scale-up-delay-millis}\n";

Properties properties = new Properties();
properties.setProperty("backup-count", "2");
properties.setProperty("scale-up-delay-millis", "5000");

Config config = Config.loadFromString(yaml, properties);
HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
----

== Updating Member Configuration at Runtime

You can add configuration for some supported features at runtime. See xref:dynamic-data-structure-configuration.adoc[].