= Configuring Hazelcast in Embedded Mode
:description: You can use a configuration object (config object) to configure members with the Java member API. To create new instances of members, pass the config object to those instances.

{description}

You can create a `Config` object, set/change its properties and attributes,
and use it to create new instances of members and clients. The following example configures some network and map properties for a member.

[source,java]
----
include::ROOT:example$/ProgrammaticConfSample.java[tag=pcs]
----

To create a Hazelcast member with the configuration object, pass it to a new `HazelcastInstance`:

```
HazelcastInstance hazelcast = Hazelcast.newHazelcastInstance(config);
```

NOTE: All configuration must be completed before creating the `HazelcastInstance`. The `Config` object cannot be modified after the instance is started.

[[config-file]]
== Using a Member Configuration File in Java

xref:configuring-declaratively.adoc[Configuration files] allow you to store member configuration in YAML or XML format.

To use a configuration file to configure members, you can use one of the following:

- link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/Config.html#setConfigurationFile-java.io.File-[`Config.setConfigurationFile()`]

- <<loaders, A configuration loader>>

- <<builders, A configuration builder>>

[[loaders]]
=== Configuration Loaders

Use one of the following methods to load a configuration file into a config object:

.Configuration loader methods
[cols="3,7"]
|===
|Method|Description

|link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/Config.html#loadFromFile-java.io.File-java.util.Properties-[`Config.loadFromFile()`]
|Creates a configuration object based on a Hazelcast configuration file (XML or YAML).

|link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/Config.html#loadDefault-java.util.Properties-[`Config.loadDefault()`]
|Loads `Config` using the default lookup mechanism to locate the configuration file. Loads the nested
Hazelcast configuration also by using its default lookup mechanism.

|link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/Config.html#loadFromClasspath-java.lang.ClassLoader-java.lang.String-java.util.Properties-[`Config.loadFromClasspath()`]
|Creates `Config` which is loaded from a classpath resource.

|link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/Config.html#loadFromString-java.lang.String-java.util.Properties-[`Config.loadFromString()`]
|Creates `Config` from the provided XML or YAML string content.

|link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/Config.html#loadFromStream-java.io.InputStream-java.util.Properties-[`Config.loadFromStream()`]
|Creates `Config` from the provided XML or YAML stream content.

|link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/XmlConfigBuilder.html[]

|===

[[builders]]
=== Configuration Builders

Use one of the following classes to build a config object.

NOTE: If you use configuration builders or the `new Config()` constructor with the Java member API, you cannot xref:configuring-with-system-properties.adoc[override existing configuration with system properties and environment variables]. To override existing configuration, you must use <<loaders,configuration loaders>>.

[tabs]
====
XML::
+
--

- link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/XmlConfigBuilder.html[`xmlConfigBuilder`]
- link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/ClasspathXmlConfig.html[`ClasspathXmlConfig`]

- link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/FileSystemXmlConfig.html[`FileSystemXmlConfig`]

- link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/UrlXmlConfig.html[`UrlXmlConfig`]

- link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/InMemoryXmlConfig.html[`InMemoryXmlConfig`]
--
YAML::
+
--
- link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/YamlConfigBuilder.html[`yamlConfigBuilder`]
- link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/ClasspathYamlConfig.html[`ClasspathYamlConfig`]

- link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/FileSystemYamlConfig.html[`FileSystemYamlConfig`]

- link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/UrlYamlConfig.html[`UrlYamlConfig`]

- link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/InMemoryYamlConfig.html[`InMemoryYamlConfig`]
--
====

By default, Hazelcast searches for
`hazelcast.yaml` or `hazelcast.xml` files in the classpath and
working directory. You can control the name of the files that Hazelcast searches for, using the
relevant system properties such as `hazelcast.config`.

This sample code creates a new Jet engine configuration using
the configuration loader:

[source,java]
----
String yaml = ""
   + "hazelcast:\n"
   + "  instance:\n"
   + "    cooperative-thread-count: 64\n"
   + "    flow-control-period: 50\n"
   + "    backup-count: 2\n"
   + "    scale-up-delay-millis: 5000\n"
   + "    lossless-restart-enabled: true\n";

Config config = Config.loadFromString(yaml);
HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
----

All configuration loaders take an optional `properties` parameter.
The default behavior uses the `System.getProperties()` method to resolve the configuration file:

[source,java]
----
String yaml = ""
   + "hazelcast:\n"
   + "  instance:\n"
   + "    backup-count: ${backup-count}\n"
   + "    scale-up-delay-millis: ${scale-up-delay-millis}\n";

Properties properties = new Properties();
properties.setProperty("backup-count", "2");
properties.setProperty("scale-up-delay-millis", "5000");

Config config = Config.loadFromString(yaml, properties);
HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
----

== Updating Member Configuration at Runtime

You can use xref:dynamic-config.adoc[dynamic configuration] to add configuration for some supported features at runtime.

TIP: If you want to persist dynamic configuration changes, you need to use a <<config-file,configuration file method>> that sets the `configurationFile` field of the `Config` object such as  `Config.setConfigurationFile()` or `Config.loadFromFile()`.