= Update and Reload Dynamic Configuration in REST
:description: You can use the /config/update and /config/reload REST endpoints to add dynamic configuration for some supported features at runtime.

You can use the `/config/update` and `/config/reload` REST endpoints to add xref:dynamic-config.adoc[dynamic configuration] for some xref:dynamic-config.adoc#supported-dynamic-configuration-changes[supported features] at runtime:

- <<update, `/config/update`>>: Include a declarative configuration file in the request parameter.
- <<reload, `/config/reload`>>: Edit the configuration file that a member has already loaded and then reload it.

Changes are broadcast to the entire cluster. If you reload the configuration, you only need to edit one member's configuration file to affect the whole cluster.

NOTE: You cannot send configuration changes through lite members.

== Before you Begin

The REST API and the `CLUSTER_WRITE` endpoint group must be enabled on your cluster. See xref:maintain-cluster:rest-api.adoc[].

You need an Enterprise license.

include::partial$prereqs-dynamic-config.adoc[]

[[reload]]
== Editing and Reloading a Configuration File

. Open a member's configuration file and add some new configuration. For example, you may want to configure a new map with a backup count.
+
NOTE: Keep all existing configuration the same. You can only add new configuration blocks. To see what you can add see xref:dynamic-config.adoc#supported-dynamic-configuration-changes[Supported Dynamic Configuration Changes]
+
.Example of a new configuration
[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    <map name="new-map">
      <backup-count>
        2
      </backup-count>
    </map>
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  map:
    new-map:
      backup-count: 2
----
====

. Send a `POST` request to the `/config/reload` endpoint of a cluster member.
+
- If your cluster has security enabled, send the cluster password in the request.
+
[source,shell]
----
curl -X POST -H "Content-Type: text/plain" --data-urlencode "<cluster-name>" --data-urlencode "<cluster-password>" http://localhost:5701/hazelcast/rest/config/reload
----

- If your cluster does not have security enabled, send the password as an empty string.
+
[source,shell]
----
curl -X POST -H "Content-Type: text/plain" --data-urlencode "<cluster-name>" --data-urlencode "" http://localhost:5701/hazelcast/rest/config/reload
----

[[update]]
== Updating Configuration

To update a member's configuration, without editing the configuration file, use the `/config/update` endpoint.

This endpoint takes a URL encoded string of either YAML or XML as parameter. You only need to pass the new configuration blocks that you want to add with the `hazelcast` root. All existing configuration settings remain unchanged. However, you can include existing configuration blocks as well. The member will just ignore them.

For example, when a member has configuration for `map-1` and `map-2` in its configuration file, you can pass in a new configuration block for `map-3` in the following ways: 


- The `hazelcast` root and the new `map-3` configuration block.
- The `hazelcast` root, `map-1` and the new `map-3` configuration block.
- The `hazelcast` root, `map-2` and the new `map-3` configuration block.
- The `hazelcast` root, `map-1`, `map-2` and the new `map-3` configuration block.

The outcome of these dynamic configuration changes is the same: A new configuration block for a map called `map-3`.

NOTE: The configuration string must be URL encoded.

If your cluster has security enabled, send the cluster password in the request.

[source,shell]
----
curl -X POST -H "Content-Type: text/plain" --data-urlencode "<cluster-name>" --data-urlencode "<cluster-password>" --data-urlencode "
hazelcast:
  map:
    map-3:
      backup-count: 2
" http://localhost:5701/hazelcast/rest/config/update
----

If your cluster does not have security enabled, send the password as an empty string.

[source,shell]
----
curl -X POST -H "Content-Type: text/plain" --data-urlencode "<cluster-name>" --data-urlencode "" --data-urlencode "
hazelcast:
  map:
    map-3:
      backup-count: 2
" http://localhost:5701/hazelcast/rest/config/update
----

NOTE: If you are using XML file format, please use it with `xmlns` such as `<hazelcast xmlns="http://www.hazelcast.com/schema/config"></hazelcast>` instead of `<hazelcast></hazelcast>`.

include::partial$dyn-config-partial-propagation.adoc[leveloffset=+1]

== Request Response

When the member receives a dynamic configuration request, it will check if the configuration already exists and propagate any new configuration across the rest of the cluster as well as members that may join the cluster later.

You should see the new configuration in the response's `addedConfigs` field:

```json
{"status":"success","message":"Configuration Update successfully finished.","result":{"addedConfigs":[{"sectionName":"map","configName":"new-map"}],"ignoredConfigs":[]}}
```

The REST endpoints are idempotent. If you add a dynamic configuration for a block that already exists, the member will ignore the request and return the change you requested in the `ignoredConfigs` field.

.Example ignored response
[source,json]
----
{"status":"success","message":"Configuration Update successfully finished.","result":{"addedConfigs":[],"ignoredConfigs":[{"sectionName":"map","configName":"existing-map"}]}}
----
