= Updating Member Configuration at Runtime
:description: You can use the dynamic configuration feature to temporarily or permanently add new configuration to members at runtime. This feature is useful if you want to configure a running cluster without having to restart the members.
:keywords: dynamic configuration

{description}

== Supported Configuration

Dynamic configuration is supported for the following features:

- Map
- Cache
- Queue
- List
- Set
- MultiMap
- ReplicatedMap
- RingBuffer
- Topic
- ReliableTopic
- Executor
- DurableExecutor
- ScheduledExecutor
- CardinalityEstimator
- PNCounter
- FlakeIdGenerator
- WAN (only with the REST API)

[[persist]]
== Persisting Configuration Changes

By default, dynamic configuration changes are stored in-memory and are lost when a cluster restarts.

To allow changes to be persisted, you must do the following:

- Configure the member, using a xref:configuring-declaratively.adoc[configuration file] or xref:configuring-programmatically.adoc#config-file[loading a configuration file into a configuration object].

- xref:dynamic-config-options.adoc[Enable and configure persistence] for dynamic configuration.

== Adding Dynamic Configuration

To add dynamic configuration at runtime, you can use the following options:

- xref:dynamic-config-java.adoc[Java client API or Java member API]
- xref:dynamic-config-rest.adoc[REST API]

== Dynamic Configuration and User Customizations

Some dynamic configurations settings may reference
user customizations, such as a `MapLoader` implementation that is referenced
by in a map's configuration. User customizations can usually be configured using either of the following:

* Specifying a class or factory class name, such as `MapStoreConfig.setClassName`, and letting the
Hazelcast members instantiate the object.
* Providing an existing instance, such as, `MapStoreConfig.setImplementation`.

When dynamically adding a new data structure configuration with user customizations,
take the following considerations into account:

* For the user customizations submitted as a class name or factory class name, the referenced
classes are resolved lazily. Therefore, they should be either already on each member's local
classpath or resolvable via xref:clusters:deploying-code-on-member.adoc[user code deployment].
* When the user customizations are submitted as instances (or similarly factory instances),
the instances themselves have to be serializable. This is because the entire configuration needs
to be sent over the network to all cluster members, and their classes have to be available on each member's local classpath.