= Configuration
:description: To configure a Hazelcast cluster or client, you can choose either static or dynamic configuration. Explore the options and decide which one is best for your application.
:keywords: configuration, configuring hazelcast

{description}

TIP: Before configuring Hazelcast, we recommend trying the defaults, which are set in the `hazelcast-default.xml` and `hazelcast-client-default.xml` file of your Hazelcast package.

== Static Configuration

Static configuration allows you to configure Hazelcast members and client before runtime by providing either configuration files or using the API.

To use static configuration, you have the following options:

- xref:configuring-declaratively.adoc[Configuration Files]: Use configuration files to configure a cluster or client before startup.
- xref:configuring-programmatically.adoc[Configuration Object]: Use a client or member API to configure a cluster or client.
- xref:configuring-with-system-properties.adoc[System props and environment variables]: Use system properties to configure some aspects of Hazelcast or override settings in a configuration file.
- xref:configuring-within-spring.adoc[Spring configuration]: Configure Hazelcast for Spring integration.

The following topics are also relevant to static configuration:

- xref:pattern-matcher.adoc[Configuration Pattern Matcher]
- xref:using-wildcards.adoc[Using Wildcards]

NOTE: Hazelcast performs schema validation through the `hazelcast-config-{full-version}.xsd` file,
which comes with Hazelcast libraries. If an error occurs in declarative or programmatic configuration, Hazelcast throws a meaningful exception.

Static configuration cannot be changed at runtime. However, you can add <<dynamic-configuration, dynamic configuration>> for some data structures.

=== Configuration Precedence
[[checking-configuration]]

Hazelcast members and clients looks for static configuration options in the following order:

[cols="10%a,45%a,45%a"]
|===
|Order|Member|Client

|1
|`Config` object provided by programmatic configuration
|`Config` object provided by programmatic configuration

|2
|`hazelcast.config` system property
|`hazelcast.client.config` system property

|3
|`hazelcast.xml` declarative configuration file in the working directory
|`hazelcast-client.xml` declarative configuration file in the working directory

|4
|`hazelcast.xml` declarative configuration file on the classpath
|`hazelcast-client.xml` declarative configuration file on the classpath (Java)

|5
|`hazelcast.yaml` declarative configuration file in the working directory
|`hazelcast-client.yaml` declarative configuration file in the working directory

|6
|`hazelcast.yaml` declarative configuration file on the classpath
|`hazelcast-client.yaml` declarative configuration file on the classpath (Java)

|===

If Hazelcast does not find any of these configuration options, it loads the default configuration file (`hazelcast-default.xml`), which comes with your Hazelcast package.

== Dynamic Configuration

Dynamic configuration allows you to add configuration blocks for some features at runtime.

If you use a configuration file to configure a member, you can choose to persist any dynamic configuration to that file.

For more information, see xref:dynamic-config-overview.adoc[Dynamically Adding Data Structure Configuration on a Cluster].
