= Configuration Options
:description: To configure a Hazelcast cluster, you can choose either static or dynamic configuration. Explore the options and decide which one is best for your application.
:keywords: configuration, configuring hazelcast

[[understanding-configuration]]

{description}

TIP: Before configuring Hazelcast, we recommend trying the defaults, which are set in the `hazelcast-default.xml` file of your Hazelcast package.

== Static Configuration

Static configuration allows you to configure Hazelcast before runtime by providing either configuration files or using the API. Static configuration cannot be changed during runtime.

To use static configuration, you have the following options:

- xref:configuring-declaratively.adoc[Declarative configuration]: Use configuration files to configure a Hazelcast cluster before starting it.
- xref:configuring-programmatically.adoc[Programmatic configuration]: Use the Java API to configure a cluster in embedded mode.
- xref:configuring-with-system-properties.adoc[System properties]: Use system properties to configure some aspects of Hazelcast.
- xref:configuring-within-spring.adoc[Spring configuration]: Configure Hazelcast for Spring integration.

The following topics are also relevant to static configuration:

- xref:overriding-configuration-settings.adoc[Overriding Configuration]
- xref:pattern-matcher.adoc[Configuration Pattern Matcher]
- xref:using-variables.adoc[Using Variables]
- xref:using-wildcards.adoc[Using Wildcards]
- xref:variable-replacers.adoc[Variable Replacers]

NOTE: Hazelcast performs schema validation through the `hazelcast-config-{page-component-version}.xsd` file,
which comes with Hazelcast libraries. If an error occurs in declarative or programmatic configuration, Hazelcast throws a meaningful exception.

=== Configuration Precedence
[[checking-configuration]]

Hazelcast looks for static configuration options in the following order:

. `Config` object provided by programmatic configuration
. `hazelcast.config` system property
. `hazelcast.xml` declarative configuration file in the working directory
. `hazelcast.xml` declarative configuration file on the classpath
. `hazelcast.yaml` (or `.yml`) declarative configuration file in the working directory
. `hazelcast.yaml` declarative configuration file on the classpath

If Hazelcast does not find any of these configuration options, it loads the default configuration file (`hazelcast-default.xml`), which comes with your Hazelcast package.

== Dynamic Configuration

Dynamic configuration allows you to temporarily change the configuration of some data structures.

For more information, see xref:dynamic-data-structure-configuration.adoc[Dynamically Adding Data Structure Configuration on a Cluster].
