= Using Variables
[[using-variables]]

In your Hazelcast and/or Hazelcast Client declarative configuration, you can use
variables to set the values of the elements. This is valid when you set a system
property programmatically or you use the command line interface. You can use a variable
in the declarative configuration to access the values of the system properties you set.

For example, see the following command that sets two system properties.

```
-Dcluster.name=dev
```

Let's get the values of these system properties in the declarative
configuration (XML/YAML) of Hazelcast, as shown below.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    <cluster-name>${cluster.name}</cluster-name>
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  cluster-name: ${cluster.name}
----
====

This also applies to the declarative configuration of Hazelcast Java Client,
as shown below.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast-client>
    <cluster-name>${cluster.name}</cluster-name>
</hazelcast-client>
----
--

YAML::
+
[source,yaml]
----
hazelcast-client:
  cluster-name: ${cluster.name}
----
====

If you do not want to rely on the system properties, you can use the
`XmlConfigBuilder` or `YamlConfigBuilder` and explicitly
set a `Properties` instance, as shown below.

[source,java]
----
Properties properties = new Properties();

// fill the properties, e.g., from database/LDAP, etc.

XmlConfigBuilder builder = new XmlConfigBuilder();
builder.setProperties(properties);
Config config = builder.build();
HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
----
