= Using Wildcards
[[using-wildcards]]

Hazelcast members and Java clients support wildcard configuration for all distributed data structures that
can be configured using `Config`, that is, for all except `IAtomicLong`,
`IAtomicReference`. Using an asterisk (*) character in the name, different
instances of maps, queues, topics, semaphores, near caches, etc. can be configured by a
single configuration.

A single asterisk (*) can be placed anywhere inside the configuration name.

For instance, a map named `com.hazelcast.test.mymap` can be configured using
one of the following configurations:

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <map name="com.hazelcast.test.*">
        ...
    </map>

    <!-- OR -->

    <map name="com.hazel*">
        ...
    </map>

    <!-- OR -->

    <map name="*.test.mymap">
        ...
    </map>

    <!-- OR -->

    <map name="com.*test.mymap">
        ...
    </map>
    ...
</hazelcast>
----
--

YAML::
+
--
[source,xml]
----
hazelcast:
  map:
    com.hazelcast.test.*:
      ...
    com.hazel*:
     ...
    "*.test.mymap":
      ...
    com.*test.mymap:
      ...
----
--
====

Notice that when the "*" character prefixes a value, the whole value should
be in quotes when you use the YAML configuration.

A queue named `com.hazelcast.test.myqueue` can be configured using one
of the following configurations:

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <queue name="*hazelcast.test.myqueue">
        ...
    </queue>

    <!-- OR -->

    <queue name="com.hazelcast.*.myqueue">
        ...
    </queue>
    ...
</hazelcast>
----
--

YAML::
+
--
[source,xml]
----
hazelcast:
  queue:
    "*hazelcast.test.myqueue":
    ...
    com.hazelcast.*.myqueue:
    ...
----
--
====


[NOTE]
====

* You can use only a single asterisk as a wildcard for each data
structure configuration.
* If you have matching wildcard configurations for a data structure,
the most specific (longest) one is used when configuring it. Let's say
you have a map named `mymap.customer.name` and you have map configurations
`mymap.\*` and `mymap.customer.*`. Hazelcast uses `mymap.customer.*` to
configure this map.
+
As another example, assume that you have a map named `mymap.customer.name`, and
map configurations `mymap.\*.name` and `mymap.customer.*`. Hazelcast uses `mymap.customer.*`
to configure this map. As you see, the longest character length before the asterisk makes
it the most specific, so it wins the configuration.
====