# typos configuration file
# See https://github.com/crate-ci/typos/blob/master/docs/reference.md for more information

[files]
extend-exclude = ["pom.xml"]

[default.extend-words]
Idexes = "Idexes"
synax = "synax"
IY = "IY"
Daa = "Daa"
PN = "PN"
pn = "pn"
Hashi = "Hashi"
Ture = "Ture"
GTI = "GTI"
ACI = "ACI"
ALOG = "ALOG"
ARAY = "ARAY"
Accuray = "Accuray"
ARRY = "ARRY"
ASND = "ASND"
Asure = "Asure"
CALD = "CALD"
MIS = "MIS"
CHEK = "CHEK"
DELT = "DELT"
ESGE = "ESGE"
FORR = "FORR"
Ser = "Ser"
Onl = "Onl"
IIN = "IIN"
IHS = "IHS"
MENT = "MENT"
Psychemedics = "Psychemedics"
Senes = "Senes"
Synopsys = "Synopsys"
STAF = "STAF"
TAST = "TAST"
THST = "THST"
TPIC = "TPIC"
USEG = "USEG"
VALU = "VALU"
jave = "jave"
AKS = "AKS"
ba = "ba"
EDE = "EDE"
vertx = "vertx"
Vertx = "Vertx"
verticle = "verticle"
Verticle = "Verticle"
