= Using the Generic MapStore
:description: With the xref:working-with-external-data.adoc#options[generic MapStore], you can configure a map to cache data from an external data store. This topic includes an example of how to configure a map with a generic MapStore that connects to a MySQL database.
:page-beta: true

{description}

For a list of all supported databases, see the xref:external-data-stores:external-data-stores.adoc#factories[built-in data store factories].

== Before you Begin

You need a xref:external-data-stores:external-data-stores.adoc[data store connection] that's configured on all cluster members.

== Quickstart Configuration

This example shows a basic map configuration for an external datastore called `my-mysql-database`. See xref:data-structures:map.adoc[] for the details of other properties that you include in your map configuration.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <map name="myMapName">
        <map-store enabled="true">
            <class-name>com.hazelcast.mapstore.GenericMapStore</class-name> <1>
            <properties>
                <property name="external-data-store-ref">my-mysql-database</property> <2>
            </properties>
        </map-store>
    </map>
    ...
</hazelcast>
----
--

YAML::
+
--
[source,yaml]
----
hazelcast:
  map:
    mymapname:
      map-store:
        enabled: true
        class-name: com.hazelcast.mapstore.GenericMapStore <1>
        properties:
            external-data-store-ref: my-mysql-database <2>
----
--
Java::
+
--
[source,java]
----
MapConfig mapConfig = new MapConfig("myMapName");
MapStoreConfig mapStoreConfig = new MapStoreConfig();
mapStoreConfig.setClassName("com.hazelcast.mapstore.GenericMapStore"); <1>
mapStoreConfig.setProperty("external-data-store-ref", "my-mysql-database"); <2>
mapConfig.setMapStoreConfig(mapStoreConfig);
instance().getConfig().addMapConfig(mapConfig);
----
--
====

<1> The xref:configuration-guide.adoc#class-name[class name] of the generic MapStore that's built into Hazelcast. This implementation reads from the external data store configuration to create a <<mapping, SQL mapping>>.
<2> The name of your external data store configuration.

[[mapping]]
== SQL Mapping for the Generic MapStore

When you configure a map with the generic MapStore, Hazelcast creates a xref:sql:mapping-to-jdbc.adoc[SQL mapping with the JDBC connector]. The name of the mapping is the same name as your map prefixed with `__map-store.`. This mapping is used to read data from the data store or write data to the data store and it is removed whenever the configured map is removed. You can also configure this SQL mapping, using <<external-data-store-ref, configuration properties>>.

== Configuration Properties for the Generic MapStore

These configuration properties allow you to configure the generic MapStore and its SQL mapping.

TIP: As well as these properties, you can also configure xref:configuration-guide.adoc[general MapStore settings].

.Generic MapStore configuration options
[cols="1a,1a,1m,2a",options="header"]
|===
|Option|Description|Default|Example

|[[external-data-store-ref]]`external-data-store-ref` (required)
|The name of the configured external
data store to use to set up a mapping. Use this property when you have an xref:external-data-stores:external-data-stores.adoc[existing connection] to an external data store.

a|`''` (empty)
|

[tabs] 
==== 
XML:: 
+ 
--
[source,xml]
----
<hazelcast>
  <map name="myMapName">
    <map-store enabled="true">
      <class-name>com.hazelcast.mapstore.GenericMapStore</class-name>
      <properties>
          <property name="external-data-store-ref">my-mysql-database</property>
      </properties>
    </map-store>
</hazelcast>
----
--
YAML:: 
+ 
--
[source,yaml]
----
hazelcast:
  map:
    mymapname:
      map-store:
        enabled: true
        class-name: com.hazelcast.mapstore.GenericMapStore
        properties:
            external-data-store-ref: my-mysql-database
----
--
Java:: 
+ 
--
[source,java]
----
MapConfig mapConfig = new MapConfig("myMapName");

MapStoreConfig mapStoreConfig = new MapStoreConfig();
mapStoreConfig.setClassName("com.hazelcast.mapstore.GenericMapStore");
mapStoreConfig.setProperty("external-data-store-ref", "my-mysql-database");

mapConfig.setMapStoreConfig(mapStoreConfig);
----
--
====

|[[table-name]]`table-name`
|Name of the table to read from.

a|The name of the map.
|

[tabs] 
==== 
XML:: 
+ 
--
[source,xml]
----
<hazelcast>
  <map name="myMapName">
    <map-store enabled="true">
      <class-name>com.hazelcast.mapstore.GenericMapStore</class-name>
      <properties>
          <property name="external-data-store-ref">my-mysql-database</property>
          <property name="table-name">test</property>
      </properties>
    </map-store>
</hazelcast>
----
--
YAML:: 
+ 
--
[source,yaml]
----
hazelcast:
  map:
    mymapname:
      map-store:
        enabled: true
        class-name: com.hazelcast.mapstore.GenericMapStore
        properties:
            external-data-store-ref: my-mysql-database
            table-name: test
----
--
Java:: 
+ 
--
[source,java]
----
MapConfig mapConfig = new MapConfig("myMapName");

MapStoreConfig mapStoreConfig = new MapStoreConfig();
mapStoreConfig.setClassName("com.hazelcast.mapstore.GenericMapStore");
mapStoreConfig.setProperty("external-data-store-ref", "my-mysql-database");
mapStoreConfig.setProperty("table-name", "test");

mapConfig.setMapStoreConfig(mapStoreConfig);
----
--
====

|[[mapping-type]]`mapping-type`
|SQL connector to use for the mapping.

a|The SQL connector is derived from the external data store in the configuration.
|

[tabs] 
==== 
XML:: 
+ 
--
[source,xml]
----
<hazelcast>
  <map name="myMapName">
    <map-store enabled="true">
      <class-name>com.hazelcast.mapstore.GenericMapStore</class-name>
      <properties>
          <property name="external-data-store-ref">my-mysql-database</property>
          <property name="mapping-type">JDBC</property>
      </properties>
    </map-store>
</hazelcast>
----
--
YAML:: 
+ 
--
[source,yaml]
----
hazelcast:
  map:
    mymapname:
      map-store:
        enabled: true
        class-name: com.hazelcast.mapstore.GenericMapStore
        properties:
            external-data-store-ref: my-mysql-database
            mapping-type: JDBC
----
--
Java:: 
+ 
--
[source,java]
----
MapConfig mapConfig = new MapConfig("myMapName");

MapStoreConfig mapStoreConfig = new MapStoreConfig();
mapStoreConfig.setClassName("com.hazelcast.mapstore.GenericMapStore");
mapStoreConfig.setProperty("external-data-store-ref", "my-mysql-database");
mapStoreConfig.setProperty("mapping-type", "JDBC");

mapConfig.setMapStoreConfig(mapStoreConfig);
----
--
====

|[[id-column]]`id-column`
|Name of the column that contains the primary key.

|id
|

[tabs] 
==== 
XML:: 
+ 
--
[source,xml]
----
<hazelcast>
  <map name="myMapName">
    <map-store enabled="true">
      <class-name>com.hazelcast.mapstore.GenericMapStore</class-name>
      <properties>
          <property name="external-data-store-ref">my-mysql-database</property>
          <property name="id-column">id</property>
      </properties>
    </map-store>
</hazelcast>
----
--
YAML:: 
+ 
--
[source,yaml]
----
hazelcast:
  map:
    mymapname:
      map-store:
        enabled: true
        class-name: com.hazelcast.mapstore.GenericMapStore
        properties:
            external-data-store-ref: my-mysql-database
            id-column: id
----
--
Java:: 
+ 
--
[source,java]
----
MapConfig mapConfig = new MapConfig("myMapName");

MapStoreConfig mapStoreConfig = new MapStoreConfig();
mapStoreConfig.setClassName("com.hazelcast.mapstore.GenericMapStore");
mapStoreConfig.setProperty("external-data-store-ref", "my-mysql-database");
mapStoreConfig.setProperty("id-column", "id");

mapConfig.setMapStoreConfig(mapStoreConfig);
----
--
====

|[[columns]]`columns`
|Names of the columns to map. This value must include a subset of columns in
the table. Missing columns must have a default value defined.

|
|

[tabs] 
==== 
XML:: 
+ 
--
[source,xml]
----
<hazelcast>
  <map name="myMapName">
    <map-store enabled="true">
      <class-name>com.hazelcast.mapstore.GenericMapStore</class-name>
      <properties>
          <property name="external-data-store-ref">my-mysql-database</property>
          <property name="columns">name</property>
      </properties>
    </map-store>
</hazelcast>
----
--
YAML:: 
+ 
--
[source,yaml]
----
hazelcast:
  map:
    mymapname:
      map-store:
        enabled: true
        class-name: com.hazelcast.mapstore.GenericMapStore
        properties:
            external-data-store-ref: my-mysql-database
            columns: name
----
--
Java:: 
+ 
--
[source,java]
----
MapConfig mapConfig = new MapConfig("myMapName");

MapStoreConfig mapStoreConfig = new MapStoreConfig();
mapStoreConfig.setClassName("com.hazelcast.mapstore.GenericMapStore");
mapStoreConfig.setProperty("external-data-store-ref", "my-mysql-database");
mapStoreConfig.setProperty("columns", "name");

mapConfig.setMapStoreConfig(mapStoreConfig);
----
--
====

|===


== Related Resources

- To monitor MapStores for each loaded entry, use the `EntryLoadedListener` interface. See the xref:events:object-events.adoc#listening-for-map-events[Listening for Map Events section] to learn how you can catch entry-based events.

- xref:mapstore-triggers.adoc[].

== Next Steps

See the MapStore xref:configuration-guide.adoc[configuration guide] for details about configuration options, including caching behaviors.
