= Cluster Events
[[cluster-events]]

[[listening-for-member-events]]
== Listening for Member Events

The Membership Listener interface has methods that are invoked
for the following events:

* `memberAdded`: A new member is added to the cluster.
* `memberRemoved`: An existing member leaves the cluster.

To write a Membership Listener class, you implement the MembershipListener
interface and its methods.

The following is an example Membership Listener class.

[source,java]
----
include::ROOT:example$/distributedevents/ClusterMembershipListener.java[tag=cml]
----

When a respective event is fired, the membership listener outputs the
addresses of the members that joined and left, and also which attribute
changed on which member.

[[registering-membership-listeners]]
=== Registering Membership Listeners

After you create your class, you can configure your cluster to include the
membership listener. Below is an example using the method `addMembershipListener`.

[source,java]
----
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
hazelcastInstance.getCluster().addMembershipListener( new ClusterMembershipListener() );
----

With the above approach, there is the possibility of missing events
between the creation of the instance and registering the listener.
To overcome this race condition, Hazelcast allows you to register
listeners in the configuration. You can register listeners using declarative,
programmatic, or Spring configuration, as shown below.

The following is an example programmatic configuration.

[source,java]
----
Config config = new Config();
config.addListenerConfig(
new ListenerConfig( "com.yourpackage.ClusterMembershipListener" ) );
----

The following is an example of the equivalent declarative configuration.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <listeners>
        <listener>
            com.yourpackage.ClusterMembershipListener
        </listener>
    </listeners>
    ...
</hazelcast>
----
--

YAML::
+
--
[source,yaml]
----
hazelcast:
  listeners:
    - com.yourpackage.ClusterMembershipListener
----
--

Spring::
+
[source,xml]
----
<hz:listeners>
    <hz:listener class-name="com.yourpackage.ClusterMembershipListener"/>
    <hz:listener implementation="MembershipListener"/>
</hz:listeners>
----
====

[[listening-for-distributed-object-events]]
== Listening for Distributed Object Events

The Distributed Object Listener methods `distributedObjectCreated` and
`distributedObjectDestroyed` are invoked when a distributed object is
created and destroyed throughout the cluster. To write a Distributed Object
Listener class, you implement the DistributedObjectListener interface and its methods.

The following is an example Distributed Object Listener class.

[source,java]
----
include::ROOT:example$/distributedevents/ExampleDistObjListener.java[tag=distobjlistener]
----

When a respective event is fired, the distributed object listener
outputs the event type, the object name and a service name
(for example, for a Map object the service name is `"hz:impl:mapService"`).

[[registering-distributed-object-listeners]]
=== Registering Distributed Object Listeners

After you create your class, you can configure your cluster to
include distributed object listeners. Below is an example using
the method `addDistributedObjectListener`. You can also see this
portion in the above class creation.

[source,java]
----
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
ExampleDistObjListener example = new ExampleDistObjListener();

hazelcastInstance.addDistributedObjectListener( example );
----

With the above approach, there is the possibility of missing events
between the creation of the instance and registering the listener.
To overcome this race condition, Hazelcast allows you to register
the listeners in the configuration. You can register listeners using
declarative, programmatic, or Spring configuration, as shown below.

The following is an example programmatic configuration.

[source,java]
----
config.addListenerConfig(
new ListenerConfig( "com.yourpackage.ExampleDistObjListener" ) );
----


The following is an example of the equivalent declarative configuration.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <listeners>
        <listener>
            com.yourpackage.ExampleDistObjListener
        </listener>
    </listeners>
    ...
</hazelcast>
----
--

YAML::
+
--
[source,yaml]
----
hazelcast:
  listeners:
    - com.yourpackage.ExampleDistObjListener
----
--

Spring::
+
[source,xml]
----
<hz:listeners>
    <hz:listener class-name="com.yourpackage.ExampleDistObjListener"/>
    <hz:listener implementation="DistributedObjectListener"/>
</hz:listeners>
----
====

[[listening-for-migration-events]]
== Listening for Migration Events

The Migration Listener interface has methods that are invoked
for the following events:

* `migrationStarted`: The migration starts. A migration consists of a
group of replica migrations which are planned together. The `MigrationState`
parameter of the  `migrationStarted` method shows information about
the migration: start time of the process, number of the planned migrations, etc.
* `migrationFinished`: The migration finishes. `MigrationState` parameter
shows the result of the migration: number of the completed migrations,
number of the remaining migrations, total elapsed time, etc.
* `replicaMigrationCompleted`: A partition replica migration starts.
Method's parameter, `ReplicaMigrationEvent`, shows information about
a replica migration: partition ID, replica index, source and destination
members of the migration and elapsed time for this replica migration.
Also it shows the progress of the overall migration: number of the completed
and remaining replica migrations and total elapsed time.
* `replicaMigrationFailed`: A partition replica migration fails.
The `MigrationEvent` parameter shows the information about this replica migration
and overall migration similar to the `migrationCompleted` method.

To write a Migration Listener class, you implement the `MigrationListener`
interface and its methods.

The following is an example Migration Listener class.

[source,java]
----
include::ROOT:example$/distributedevents/ClusterMigrationListener.java[tag=clstrmigrationlistener]
----

=== Registering Migration Listeners

After you create your class, you can configure your cluster to include
migration listeners. Below is an example using the method `addMigrationListener`.

[source,java]
----
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();

PartitionService partitionService = hazelcastInstance.getPartitionService();
partitionService.addMigrationListener( new ClusterMigrationListener() );
----

With the above approach, there is the possibility of missing events
between the creation of the instance and registering the listener.
To overcome this race condition, Hazelcast allows you to register
the listeners in the configuration. You can register listeners using
declarative, programmatic, or Spring configuration, as shown below.

The following is an example programmatic configuration.

[source,java]
----
config.addListenerConfig(
new ListenerConfig( "com.yourpackage.ClusterMigrationListener" ) );
----

The following is an example of the equivalent declarative configuration.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <listeners>
        <listener>
            com.yourpackage.ClusterMigrationListener
        </listener>
    </listeners>
    ...
</hazelcast>
----
--

YAML::
+
--
[source,yaml]
----
hazelcast:
  listeners:
    - com.yourpackage.ClusterMigrationListener
----
--

Spring::
+
[source,xml]
----
<hz:listeners>
    <hz:listener class-name="com.yourpackage.ClusterMigrationListener"/>
    <hz:listener implementation="MigrationListener"/>
</hz:listeners>
----
====

[[listening-for-partition-lost-events]]
== Listening for Partition Lost Events

Hazelcast provides fault-tolerance by keeping multiple copies of your data.
For each partition, one of your cluster members becomes the owner and
some of the other members become replica members, based on your configuration.
Nevertheless, data loss may occur if a few members crash simultaneously.

Let's consider the following example with three members: N1, N2, N3 for
a given partition-0. N1 is owner of partition-0. N2 and N3 are the first
and second replicas respectively. If N1 and N2 crash simultaneously,
partition-0 loses its data that is configured with less than two backups.
For instance, if we configure a map with one backup, that map loses its
data in partition-0 since both owner and first replica of partition-0 have
crashed. However, if we configure our map with two backups, it does not
lose any data since a copy of partition-0's data for the given map
also resides in N3.

The Partition Lost Listener notifies for possible data loss occurrences
with the information of how many replicas are lost for a partition. It
listens to `PartitionLostEvent` instances. Partition lost events are
dispatched per partition.

Partition loss detection is done after a member crash is detected by the
other members and the crashed member is removed from the cluster.
Please note that false-positive `PartitionLostEvent` instances may be
fired on the network split errors.

=== Writing a Partition Lost Listener Class

To write a Partition Lost Listener, you implement the PartitionLostListener
interface and its `partitionLost` method, which is invoked when a partition
loses its owner and all backups.

The following is an example Partition Lost Listener class.

[source,java]
----
public class ConsoleLoggingPartitionLostListener implements PartitionLostListener {
    @Override
    public void partitionLost(PartitionLostEvent event) {
        System.out.println(event);
    }
}
----

When a `PartitionLostEvent` is fired, the partition lost listener given
above outputs the partition ID, the replica index that is lost and the
member that has detected the partition loss. The following is an example output.

```
com.hazelcast.partition.PartitionLostEvent{partitionId=242, lostBackupCount=0,
eventSource=Address[192.168.2.49]:5701}
```

=== Registering Partition Lost Listeners

After you create your class, you can configure your cluster programmatically
or declaratively to include the partition lost listener. Below is an example
of its programmatic configuration.

[source,java]
----
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
hazelcastInstance.getPartitionService().addPartitionLostListener( new ConsoleLoggingPartitionLostListener() );
----

The following is an example of the equivalent declarative configuration.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <listeners>
        <listener>
            com.yourpackage.ConsoleLoggingPartitionLostListener
        </listener>
    </listeners>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  listeners:
    - com.yourpackage.ConsoleLoggingPartitionLostListener
----
====

[[listening-for-lifecycle-events]]
== Listening for Lifecycle Events

The Lifecycle Listener notifies for the following events:

* `STARTING`: A member is starting.
* `STARTED`: A member started.
* `SHUTTING_DOWN`: A member is shutting down.
* `SHUTDOWN`: A member's shutdown has completed.
* `MERGING`: A member is merging with the cluster.
* `MERGED`: A member's merge operation has completed.
* `CLIENT_CONNECTED`: A Hazelcast Client connected to the cluster.
* `CLIENT_DISCONNECTED`: A Hazelcast Client disconnected from the cluster.

The following is an example Lifecycle Listener class.

[source,java]
----
public class NodeLifecycleListener implements LifecycleListener {
     @Override
     public void stateChanged(LifecycleEvent event) {
         System.err.println(event);
     }
}
----

This listener is local to an individual member. It notifies the
application that uses Hazelcast about the events mentioned above
for a particular member.

=== Registering Lifecycle Listeners

After you create your class, you can configure your cluster to
include lifecycle listeners. Below is an example using the method
`addLifecycleListener`.

[source,java]
----
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
hazelcastInstance.getLifecycleService().addLifecycleListener( new NodeLifecycleListener() );
----

With the above approach, there is the possibility of missing events
between the creation of the instance and registering the listener.
To overcome this race condition, Hazelcast allows you to register
the listeners in the configuration. You can register listeners using
declarative, programmatic, or Spring configuration, as shown below.

The following is an example programmatic configuration.

[source,java]
----
config.addListenerConfig(
    new ListenerConfig( "com.yourpackage.NodeLifecycleListener" ) );
----

The following is an example of the equivalent declarative configuration.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <listeners>
        <listener>
            com.yourpackage.NodeLifecycleListener
        </listener>
    </listeners>
    ...
</hazelcast>
----
--

YAML::
+
--
[source,yaml]
----
hazelcast:
  listeners:
    - com.yourpackage.NodeLifecycleListener
----
--

Spring::
+
[source,xml]
----
<hz:listeners>
    <hz:listener class-name="com.yourpackage.NodeLifecycleListener"/>
    <hz:listener implementation="LifecycleListener"/>
</hz:listeners>
----
====

[[listening-for-clients]]
== Listening for Clients

The client listener is used by the Hazelcast cluster members.
It notifies the cluster member when a client is connected to or
disconnected from it, i.e., the clients fire an event from only one member
they are connected to. Other cluster members do not fire a "client is connected"
or "client is disconnected" event.

To write a client listener class, you implement the `ClientListener`
interface and its methods `clientConnected` and `clientDisconnected`,
which are invoked when a client is connected to or disconnected from the
cluster. You can add your client listener as shown below.

[source,java]
----
hazelcastInstance.getClientService().addClientListener(new ExampleClientListener());
----

The following is the equivalent declarative configuration.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <listeners>
        <listener>
            com.yourpackage.ExampleClientListener
        </listener>
    </listeners>
    ...
</hazelcast>
----
--

YAML::
+
--
[source,yaml]
----
hazelcast:
  listeners:
    - com.yourpackage.ExampleClientListener
----
--

Spring::
+
[source,xml]
----
<hz:listeners>
    <hz:listener class-name="com.yourpackage.ExampleClientListener"/>
    <hz:listener implementation="com.yourpackage.ExampleClientListener"/>
</hz:listeners>
----
====

NOTE: You can also add event listeners to a Hazelcast client. See the
xref:clients:java.adoc#configuring-client-listeners[Client Listenerconfig section] for the
related information.