= CP Subsystem Unsafe Mode

When CP Subsystem is not enabled, that means
`CPSubsystemConfig.getCPMemberCount()` is `0`, CP data structures operate in
_the unsafe mode_. In this mode, they use Hazelcast's partitioning and lazy
replication mechanisms instead of CP Subsystem's consensus mechanism. For more
information about the lazy replication mechanism of Hazelcast, see
the xref:consistency-and-replication:consistency.adoc[Consistency and Replication Model chapter].

_The unsafe mode_ provides weaker consistency guarantees compared to when CP
Subsystem is enabled. For example, when you increment an `IAtomicLong` or
acquire a `FencedLock`, just before crash of a member, even though you receive
a success response, the write operation (increment of `IAtomicLong` or acquire
of `FencedLock`) can be lost (which cannot happen when CP Subsystem is enabled).
For this reason, _the unsafe mode_ is not recommended for use-cases requiring
strong consistency. It is more suitable for development or testing. You should
take this limitation into consideration if you use CP Subsystem in production
with _the unsafe mode_.

NOTE: CP Subsystem Management APIs are not available in _the unsafe mode_.

NOTE: In _the unsafe mode_, split-brain protection is not supported.