= Data Migration Tool
:description: You can use the Data Migration Tool (DMT) to migrate your data from version 4.x or 5.x Open Source and Enterprise Edition Hazelcast clusters when upgrading to Enterprise edition version 5.3.x or later, or moving to the latest {hazelcast-cloud} release. The DMT can also be used for infrastructure consolidation or separation with selective migration of application data between clusters.

{description} 

TIP: If you want to avoid downtime, use an in-place rolling upgrade instead of the DMT tool. For further information on upgrading without interrupting the operation of the cluster, see the xref:maintain-cluster:rolling-upgrade.adoc[Rolling Upgrades] topic.

When using the DMT, bear the following in mind:

* *General:*

** You can run only one migration at a time
** Any empty data structures are not migrated

* *Source Cluster:*

** The source cluster must be running and populated with required data
** The application must be using the source cluster successfully before migration
** Before starting the migration, remember to shutdown any applications that are using the source cluster

* *Target Cluster:*

** The target cluster must be set up
+
Any populated data structures that already exist on the target cluster are not migrated; however, if the existing data structure is empty, it is migrated.

** The target cluster must be running on either Enterprise Edition, version 5.3.2 or later, or {hazelcast-cloud}
+
NOTE: {hazelcast-cloud} Trial and {hazelcast-cloud} Standard have a limit of 14GB of primary data. If you require more, you must use {hazelcast-cloud} Dedicated. For further information on the available {hazelcast-cloud} editions, refer to the xref:cloud:ROOT:overview.adoc[Hazelcast {hazelcast-cloud}, window=_blank] documentation.

* *Migration Cluster:*

** You must specify at least one data structure name in the migration configuration file
** All data structures specified in the migration configuration must exist in the source cluster

== When to Use the DMT

The DMT is typically used to migrate:

* From an Open Source cluster to an Enterprise Edition cluster
* From an earlier version of Enterprise Edition to a newer version. Such a migration can move directly between specified versions, even if several minor versions exist between them
* From an on-premise cluster to a self-managed Enterprise Edition cluster in the cloud
* From an on-premise cluster to a {hazelcast-cloud} cluster
* Specific application data from one cluster to another due to infrastructure changes

TIP: You cannot use the DMT to upgrade, or to migrate data from, IMDG 3.12.x. If you are upgrading from IMDG 3.12.x, see the xref:upgrading-from-imdg-3.adoc[Upgrading from IMDG 3.12.x] topic. If migrating data from IMDG 3.12.x, see the xref:migration-tool-imdg.adoc[Migrating Data from IMDG 3.12.x] topic. 

== Next Steps

Use a Development cluster to walk through a migration before migrating your Production clusters, as described in the xref:migrate:dmt-dev-test.adoc[] topic.

Prepare for and run your migration using the DMT, as described in the xref:migrate:dmt-migration.adoc[] section.

Discover the available DMT commands and their format in the xref:migrate:dmt-command-reference.adoc[].