= Using the Data Migration Tool
:description: You can use the Data Migration Tool (DMT) to migrate your data from version 4.x or 5.x Open Source and Enterprise Edition Hazelcast clusters when upgrading to 5.3.x versions of Enterprise Edition, or moving to the latest {hazelcast-cloud} release.

{description} 

NOTE: The DMT migrates your data for maps and replicated maps only. Metadata is not migrated.

The DMT can be run on Mac, Linux, and Windows Operating Systems.

== Get the DMT

You can download the DMT from https://viridian.hazelcast.com/[Hazelcast {hazelcast-cloud}^] or the https://hazelcast.com/[Hazelcast web site^].

Once downloaded, extract the DMT package to a location in your folder structure. The DMT package includes the following:

* The DMT
* A custom Hazelcast distribution that creates a migration cluster as a _hazelcast/_ folder and runs the data migration service
* Example configuration files
* Example connection configuration file, which is used to connect to the migration client

== Before You Begin

Ensure that you have installed the following:

* https://docs.docker.com/get-docker/[Docker^]
* https://docs.hazelcast.com/clc/latest/install-clc[Hazelcast Command-Line Client (CLC)^]

When using the DMT, bear the following in mind:

* You can run only one migration at a time
* The target cluster must be on 5.3.x Enterprise Edition or the latest {hazelcast-cloud} release

NOTE: {hazelcast-cloud} Trial and {hazelcast-cloud} Standard have a limit of 14GB of primal data. If you require more, you must use {hazelcast-cloud} Dedicated. For further information on the available {hazelcast-cloud} editions, refer to the https://docs.hazelcast.com/cloud/overview[Hazelcast {hazelcast-cloud}^] documentation.

* You must specify at least one data structure name in the migration configuration file
* All data structures specified in the migration configuration must exist in the source cluster
* Any data structures that already exist on the target cluster are not migrated
* Any empty data structures are not migrated

== Migrate Your Data

To migrate your data, you must complete the following steps:

. xref:migrate:data-migration-tool.adoc#start-the-source-cluster[Start the source cluster]
+
The source cluster is your existing cluster, the one that you want to migrate.
+
NOTE: Hazelcast recommends that the source cluster is put in a `PASSIVE` state before you start the migration. For information on changing the state, see xref:maintain-cluster:cluster-member-states.adoc#changing-a-clusters-state[Changing a Cluster's State]. 
+
If necessary, you can add data to the source cluster before continuing. For example, this can be done when testing a migration using a Development cluster. For further information on doing this, see the xref:migrate:data-migration-tool.adoc#add-data-to-cluster[Add Data to Cluster] section.
+ 
You must also update the configuration for the source cluster and related data structures. For further information on doing this, see the xref:migrate:data-migration-tool.adoc#update-the-configuration[Update the configuration] section.

. xref:migrate:data-migration-tool.adoc#check-the-target-cluster[Check the target cluster]
+
The target cluster is the new cluster to which you want to migrate the source cluster.

. xref:migrate:data-migration-tool.adoc#start-the-migration-cluster[Start the migration cluster]
+
The _hazelcast/_ folder used as a migration cluster.

. xref:migrate:data-migration-tool.adoc#run-the-migration[Run the Migration]

. xref:migrate:data-migration-tool.adoc#verify-the-migrated-data[Verify the migrated data]

NOTE: If you are using the DMT to test a migration, use a Development cluster when following the steps. 

==== Limited Migration Cluster License

A 10-node limited license is included for use with your migration cluster. 

This license is valid for 60 days following download and can be used only for data migration and trial purposes. 

If migrating to a {hazelcast-cloud} cluster, or an Enterprise Edition cluster that uses a TLS connection, security is enforced.

The license terms are available in the _enterprise-license.txt_ file located in the _licenses_ folder of the extracted DMT package.

=== Start the Source Cluster

You can start your source cluster in either of the following ways:

* xref:migrate:data-migration-tool.adoc#using-docker[Using Docker]. This is the recommended method
* Downloading the version package, for the examples in the sections below we use https://hazelcast.com/open-source-projects/downloads/archives/#hazelcast-imdg[Hazelcast IMDG version 4.2.7], and follow the IMDG https://docs.hazelcast.com/imdg/4.2/getting-started[Quickstart]

==== Using Docker

To start your source cluster using Docker, you need the following information:

* The IP Address on which to start the cluster. This will be your internal Docker IP address
* The port to use. This will be your internal Docker port
* The version of Hazelcast

NOTE: Ensure that the IP address you use for Docker is different to that used by any running processes on your local machine, such as the source cluster. In the sections below, we use `127.0.0.1:5701` for the source cluster and `172.12.0.1:5701` for the Docker container.

The command has the following format:

====
docker run -p <ip_address>:<port_range_start>:<port_range_end> -e HZ_CLUSTERNAME=source hazelcast/hazelcast:<source_version>
====

NOTE: The `-p` option in the above command maps the container's port to the host machine. This ensures that your Docker instance, which is running in a virtual network, is accessible to your local processes. The option is required because the migration and target clusters, CLC, and DMT run locally on your computer outside the Docker environment.

For example, to start a version 4.2.7 source cluster on IP address 127.0.0.1 and port 5701, enter the following command in a terminal:

====
docker run -p 127.0.0.1:5701:5701 -e HZ_CLUSTERNAME=source hazelcast/hazelcast:4.2.7
====

==== Add Data to Cluster

To access the cluster and populate it with data - for example, because you are using the DMT to test a migration of a Development cluster - you can do either of the following: 
 
* Use the _source.yaml_ configuration file, included in the _migration_config_ folder of the DMT download package

* Write data to memory as described in the xref:getting-started:get-started-binary.adoc#step-3-write-data-to-memory[Step 3. Write Data to Memory] section of this documentation

The _source.yaml_ file contains the following:

[source,yaml]
====
cluster:
  name: "source"
  address: "127.0.0.1:5701"
====

NOTE: If you have not installed the Hazelcast CLC, do this now. For further information on installing the CLC, refer to the https://docs.hazelcast.com/clc/latest/install-clc[Hazelcast Command-Line Client^] documentation.

To make sure that you can add an entry to the source cluster, enter the following command in a terminal:

[source,shell]
----
clc -c source.yaml map --name my-map set key-1 value-1
----

If an error relating to CLC being unable to connect to your source cluster is returned, confirm the following:

* The port mapping is correct
* The source cluster container is running
* The configuration in your _source.yaml_ file is correct

If no errors are returned, you can populate the source cluster with 1000 entries using the following script:

[tabs] 
==== 
macOS and Linux:: 
+ 
-- 
[source,shell]
----
for i in {1..1000}; do clc -c source.yaml map --name my-map set key-$i value-$i --quiet; done && echo OK
----
--

Windows::
+
[source,shell]
----
for /l %x in (1, 1, 1000) do clc -c source.yaml map --name my-map set key-%x value-%x --quiet
----
====

==== Update the Configuration

You must update the following configuration:

* The cluster information
* The data structure information

To update the cluster information, complete the following steps:

. Navigate to the folder in which you extracted the DMT package
. Open the _migration_config/source/hazelcast.yaml_ file in your favorite editor
. Update the `cluster-name` field to match the name of your source cluster
. Update the `cluster-members` field to match the addresses of the cluster members
. Save the file

To update the data structure information, complete the following steps:

. Navigate to the folder in which you extracted the DMT package
. Open the _migration_config/data/imaps.yaml_ and/or the _migration_config/data/imaps.yaml_ file in your favorite editor
. Update the file content to match the names of your maps
+
NOTE: If you have multiple data structures, use a new line for each map name.

. Save the file

=== Check the Target Cluster

Ensure that the target cluster is running on one of the following:

* Enterprise Edition version 5.3.2 or later 
* {hazelcast-cloud}

=== Start the Migration Cluster

To start the migration cluster, complete the following steps:

. Open a terminal
. Navigate to the folder in which you extracted the DMT package
. Enter the following command:
+
====
HZ_NETWORK_PORT_PORT=5702 HZ_CLUSTERNAME=migration ./bin/hz start
====

If the specified port is available, the cluster starts on that port. Otherwise, the cluster selects a different port. You can confirm the port used by the cluster in the logs displayed in your terminal.

You can find the _migration.yaml_ configuration folder in the _migration_config_ folder of the DMT download package. If your logs show that the cluster starts on a different port to that specified in this file, you must update the `address` field to match the port number used.

DMT uses this configuration file to connect to the migration cluster when running the migration.

NOTE: The _migration.yaml_ file uses the same configuration options as the Hazelcast CLC. For further information on the options, refer to the https://docs.hazelcast.com/clc/latest/clc-config[Hazelcast CLC documentation^].

=== Run the Migration

Before running the migration, you need the following information:

* Your Operating System
* Your processor architecture
* The binary that is suitable for your machine

You can find DMT binaries, in the format `dmt_[platform]_arch]`, in the _bin_ folder of the extracted DMT package. Use the ``arm64`` binary for ARM, and the `amd64` binary for Intel.

To run the migration, complete the following steps:

. Open a terminal
. Navigate to the folder containing the extracted DMT package
. Enter the following command:
+
[source,shell]
----
./bin/dmt_[platform]_[arch] --config migration.yaml start migration_config --yes
----

NOTE: On MacOS, you might need to allow the `dmt*` binary to run. If the command is rejected, go to the *Privacy & Security* settings on your device and update them to allow the binary. After updating the settings, retry the command, and select *Open* when prompted.

You can use the https://docs.hazelcast.com/management-center/latest/getting-started/overviewHazelcast[Management Center^], or the DMT `status` command to track the migration. For further information on the available DMT commands, see the xref:migrate:dmt-command-reference.adoc[DMT Command Reference].

=== Verify the Migrated Data

You can verify the size of the map in the target cluster in the following ways:

* Use the Hazelcast Management Center
* Use Hazelcast CLC 

To use Hazelcast CLC to verify the migrated map size, enter the following command in your terminal:

[source,shell]
----
clc -c target.yaml map size --name my-map
----

The output is similar to the following

[source,shell]
----
1000
OK
----

You can also check a random value from the data we populated in the xref:migrate:data-migration-tool.adoc#add-data-to-cluster[Add Data to Cluster] section above using the following command:

[source,shell]
----
clc -c target.yaml map get key-42 --name my-map
----

The output is similar to the following:

[source,shell]
----
value-42
OK
----