= Extending the Source Cluster
:description: Migration of ReplicatedMap metadata and/or CP structures requires new functionality to be available at the source cluster side. You can extend your source cluster using the extension jar in the DMT package using following the information in this page.

{description}

== Introduction

The extension jar is a jar file found inside _extension_ folder in the extracted DMT package. It contains additional functionalities for your source Hazelcast cluster.

* The extension jar is compatible with 4.x and 5.x versions of Hazelcast. 3.x versions are not supported.
* You can use the extension jar with open source or enterprise Hazelcast versions.

== When to Use the Extension Jar

Depending on which data structures you want to migrate, you may or may not need to use the extension jar. 

The extension jar includes the following functionality:

. List CP structures
. Return ReplicatedMap data + metadata (time to live, creation time and so on). Your source cluster already has functionality to return ReplicatedMap data. The extension jar provides metadata read functionality.

Therefore, you need the extension jar if one of the following is true:

* You want to migrate ReplicatedMap metadata and your source cluster version is not newer than "5.3.7". (This API is added to Hazelcast in "5.3.7".)
* You want to migrate CP structures (IAtomicLong, IAtomicReference, ICountdownLatch) and your source cluster is not newer than "5.4.0". (This API is added to Hazelcast in "5.4.0".) so if your source cluster is newer than "5.4.0", you don't need the extension jar.


== How to Use the Extension Jar

You can extend your source cluster by gracefully shutting down and restarting your source cluster members one by one as described in xref:maintain-cluster:shutdown.adoc#graceful-shutdown[Graceful Shutdown, window=_blank] documentation.
