= Run the Migration
:description: You are now ready to run the migration.

{description}

TIP: If you want to avoid downtime, use an in-place rolling upgrade instead of the DMT tool. For further information on upgrading without interrupting the operation of the cluster, see the xref:maintain-cluster:rolling-upgrades.adoc[Rolling Upgrades] topic.

Make sure you have everything you need before you start, as detailed in the xref:migrate:dmt-run.adoc#before-you-begin[] section below.

== Before You Begin

If you haven't already done so, disconnect all client applications from the source cluster.

Hazelcast also recommends that the source cluster is put in a `PASSIVE` state before you start the migration, as described in the  xref:maintain-cluster:cluster-member-states#changing-a-clusters-state.adoc[Changing a Cluster's State] topic. If you do not do this, the DMT might not migrate data that changed during the migration.

Ensure that you have installed the https://docs.hazelcast.com/clc/latest/install-clc[Hazelcast Command-Line Client (CLC)^].

If using a Development cluster, or you use Docker on your Production cluster, install https://docs.docker.com/get-docker/[Docker^].

Before running the migration, you need the following information:

* Your Operating System
* Your processor architecture
* The binary that is suitable for your machine
+
You can find DMT binaries in the _bin_ folder of the extracted DMT package. The binaries are in the format `dmt_[platform]_[arch]`.  Use the ``arm64`` binary for ARM processors, such as Mac M1 or AWS Graviton. Use the `amd64` binary for Intel and AMD processors.

== Start the Migration

To run the migration, complete the following steps:

. Open a terminal
. Navigate to the folder containing the extracted DMT package
. Enter the following command:
+
[source,shell]
----
./bin/dmt_[platform]_[arch] --config migration.yaml start migration_config --yes --log.path migration.log
----

[NOTE]
====
. `--log.path migration.log` specifies that the migration logs are saved to the _migration.log_ file on completion of the migration. For further information on viewing the migration details, see the xref:migrate:data-migration-tool.adoc#view-result[View Migration Results]
. The DMT will attempt to connect to the migration cluster indefinitely. This means that it can appear to hang if unable to connect. To avoid this, you can set a timeout for the connection attempt using the `--timeout` flag.  For further information on the `--timeout` flag, refer to the https://docs.hazelcast.com/clc/5.3.5/configuration#clc-configuration-with-command-line-parameters[CLC Configuration with Command-line Parameters^] section of the Hazelcast CLC documentation. 
. On MacOS, you might need to allow the `dmt*` binary to run. If the command is rejected, go to the *Privacy & Security* settings on your device and update them to allow the binary. After updating the settings, retry the command, and select *Open* when prompted
====

== Track the Migration

You can use the DMT `status` command to track the migration. 

For further information on the available DMT commands, see the xref:migrate:dmt-command-reference.adoc[DMT Command Reference].
