= Extending the Source Cluster
:description: To migrate ReplicatedMap metadata and/or CP data structures, you must add the extension JAR provided in the DMT package to the class path in your source cluster. 

{description}


The extension JAR is located at _extension/hazelcast-data-migration-extension-{version}.jar_ in the extracted DMT package. This file is only required when you want to migrate ReplicatedMap metadata and/or CP data structures as described in <<when-to-use,When to Use the Extension JAR>>.

* The extension JAR can only be used with 4.x and 5.x versions of Hazelcast. Earlier versions of Hazelcast are not supported.
* You can use the extension JAR with both Enterprise and Open Source versions.

[when-to-use]
== When to Use the Extension JAR

Depending on which data structures you want to migrate, you may not need the extension jar. 

The extension jar includes the following functionality:

. Lists CP data structures
. Reads ReplicatedMap data and metadata (such as time to live and creation time). Your source cluster can migrate ReplicatedMap data without the extension JAR, which adds the ability to read metadata.

Therefore, you need the extension jar if one of the following is true:

* You want to migrate ReplicatedMap metadata and your source cluster version is not newer than "5.3.7". (This API is added to Hazelcast in "5.3.7".)
* You want to migrate CP structures (IAtomicLong, IAtomicReference, ICountdownLatch) and your source cluster is not newer than "5.4.0". (This API is added to Hazelcast in "5.4.0".) so if your source cluster is newer than "5.4.0", you don't need the extension jar.

WARNING: Using the extension jar with a Hazelcast versions that already have the API in the extension jar can cause a class mismatch and thus failures in migration. Therefore, don't use the extension jar if your source cluster is newer than 5.3.7 (or 5.4.0 for CP case).

== How to Use the Extension Jar



To use the extension JAR, complete the following steps for each member in your cluster:

. Gracefully shutdown the member, as described in xref:maintain-cluster:shutdown.adoc#graceful-shutdown[Graceful Shutdown].
+
Once the graceful shutdown has completed, the cluster contains one less member but no data loss occurs.
. Add the extension JAR to the class path of the JVM. 
+
You can use the _user-lib_ folder in your Hazelcast distribution to do this, as described in xref:clusters:deploying-code-from-clients.adoc#adding-user-library-to-classpath[Deploying User Code from Clients].
. Restart the member.
