= View Migration Details
:description: Once the migration completes, you can view the details of the migration in a report, DMT log file, or the results IMap created on the target cluster.

{description}

The details of the migration are recorded as follows:

* Migration report
+
For further information on the migration report, see the xref:migrate:dmt-view-details.adoc#migration-report-format[] section below.

* DMT log file
+
This is the file specified in the `--log.path` flag of the `start` command.
+
If the flag is not used, the file is saved to the location set in the `CLC_HOME` environment variable. If this environment variable is not set, the default location is the _~/.hazelcast_ folder.
+
NOTE: Logging uses the same environment variables as Hazelcast CLC. For further information on environment variables, refer to the https://docs.hazelcast.com/clc/latest/environment-variables[Environment Variables^] section of the Hazelcast CLC documentation.
+
The DMT log file includes migration member logs and other DMT logs.
+
The migration member logs are in the format `[(migration_id)_(member uuid)] (member log)`.

* `__datamigration_results` IMap
+
This is created on the target cluster.
+
The keys are UUID4 string format migration IDs, and the values are `HazelcastJsonValue` serialization interfaces that correspond to migration statuses. A migration status represents the details of the completed migration, and can be provided when contacting Hazelcast Support to help us in our investigations into your issue.
+
The migration report is also included as a field.

== Migration Report Format

The migration report is a plain text file. This file is written to the directory used when running the `dmt` command, and is named _migration$$_$$report$$_$$[migration_id].txt_.

The migration report contains the following information:

* Timestamp for the start of the migration
* The status of each data structure migration
* Timestamp for the end of the migration