= Configure Connections
:description: The migration cluster acts a client for both source and target clusters. You must configure the connections to allow communication between the migration cluster and both the source and target clusters. 

{description}

If the connections are not correctly configured, the migration fails.

== Source Cluster Connection

To complete the configuration, you need the following information from your source cluster:

* The cluster name
* The cluster member addresses
* The data structures to migrate

=== Update Cluster Information

To update the cluster information, complete the following steps:

. Navigate to the folder containing the extracted DMT package
. Open the _migration_config/source/hazelcast-client.yaml_ file in your favorite editor
+
NOTE: The _hazelcast-client.yaml_ file is a Hazelcast client configuration file, which can include any supported configuration.
+
. Update the `cluster-name` field to match the name of your source cluster
. Update the `cluster-members` field to match the addresses of the cluster members
. Save the file

=== Update Data Structures

To update the data structure information, complete the following steps:

. Navigate to the folder containing the extracted DMT package
. Navigate to the _migration_config_ folder
. Open the text file for the data structure in your favorite editor; for example, to update your map information, open the _imap_names.txt_ file
. Update the file content to match the names of the data structures to migrate
+
If you have multiple data structures use a new line for each name, or use wildcards to select multiple data structures using a single entry. For further information on using wildcards, see the xref:configuration:using-wildcards.adoc[Using Wildcards] topic.

. Save the files

The data structure configuration options are described in the following table:

[%header,cols="1,2"]
|===
|Option |Description

|`"matchHidden"`
|Defines whether to include data structures with names that start with a double underscore ($$__$$) in the migration when a wildcard (`*`) is included in the migration configuration. For example, Hazelcast uses some internal maps with names starting with $$__$$ such as $$__$$sql.catalog.
By default, this is set to `"false"`, which means that maps starting with $$__$$ are not migrated.
Valid values are `"true"` and `"false"`

|===


==== ReplicatedMap Metadata Migration

By default, Replicated Map metadata is migrated. However, for some versions you must add the provided extension JAR to your class path and restart the cluster before starting the migration to migrate Replicated map metadata. For further information on when you need to use the extension JAR and how to use it, see the xref:migrate:dmt-source-cluster-extension.adoc[] topic.

If you want to disable migration of Replicated map metadata, open the _migration_config/migration_config.yaml_ file in your favorite editor and complete the following steps:

. Set `migrateReplicatedMapMetadata` to `false`
. Save the file

==== CP Data Structures

NOTE: For some versions you must add the provided extension JAR to your class path and restart the cluster before starting the migration to migrate CP data structures. For further information on when you need to use the extension JAR and how to use it, see the xref:migrate:dmt-source-cluster-extension.adoc[] topic.

You can migrate the following CP data structures:

* xref:data-structures:iatomiclong.adoc[]
* xref:data-structures:iatomicreference.adoc[]
* xref:data-structures:icountdownlatch.adoc[]

If a CP data structure has no data, it is not migrated. For example, where the `set()` method has not been called on an existing `AtomicReference`. This is because such data structures are created lazily and do not exist in the cluster until used. This avoids the creation of a server-side resource with null data.

You can update the following files with a list of the CP structures to migrate:

** _migration_config/data/iatomic_long_names.txt_
** _migration_config/data/iatomic_reference_names.txt_
** _migration_config/data/icount_down_latch_names.txt_

To configure the migration of CP data structures, you must update the _migration_config.yaml_ file located in the _migration_config_ folder.

== Target Cluster Connection

Ensure that the target cluster is running on one of the following:

* If you don't want to migrate ReplicatedMap metadata, Enterprise Edition version 5.3.2 or later. You can disable migration of Replicated map metadata as described in xref:migrate:dmt-connection-config.adoc#replicatedmap-metadata-migration[ReplicatedMap Metadata Migration]
* If you want to migrate ReplicatedMap metadata, Enterprise Edition version 5.3.8 or later
* {hazelcast-cloud}

To complete the configuration, you need the following information from your target cluster:

* The cluster name
* The IP address or cloud configuration
* If required, the SSL keystore and truststore

=== Update Connection Configuration

To update the target connection configuration, complete the following steps:

. Navigate to the folder containing the extracted DMT package
. Open the _migration_config/target/hazelcast-client.yaml_ file in your favorite editor
+
NOTE: The _hazelcast-client.yaml_ file is a Hazelcast client configuration file, which can include any supported configuration.
+
. Update the `cluster-name` field to match the name of your source cluster
. Update the `network` section as follows:
+
* For an on-premise target cluster, update the `cluster-members` field to match the addresses of the cluster members
* For a cloud target cluster, including a {hazelcast-cloud} cluster, update the network information 
+
For a public cloud cluster, refer to the documentation for the cloud provider for the required network details. 
+
For {hazelcast-cloud}, you must update the network section as follows:
+
----
hazelcast-client:
  ...
  network:
    hazelcast-cloud:
      enabled: true
      discovery-token: <token>
----
+
For further information on finding the discovery token in {hazelcast-cloud}, refer to the xref:cloud:ROOT:connect-to-cluster.adoc[Connecting to Viridian Cloud Clusters, window=_blank] topic of the Hazelcast {hazelcast-cloud} documentation.

. If required, add the `ssl` information. The format is as follows:
+
----
hazelcast-client:
  ...
  network:
  ...
    ssl:
      enabled: true
      properties:
        keyStore: client.keystore
        keyStorePassword: abc123
        trustStore: client.truststore
        trustStorePassword: abc123
----
+
NOTE: The `keyStore` and `trustStore` values identify the files containing your key and certificate. These files must be located in the same folder as your _hazelcast-client.yaml_ file.


. Save the file

NOTE: For further information on the `ssl` properties and their values, refer to the xref:cloud:ROOT:connect-to-cluster#advanced[Using Advanced Setup, window=_blank] section in the Hazelcast {hazelcast-cloud} documentation.

=== Example Cloud Target Connection

In the example connection configuration below, we do the following:

* Add the name of our target cluster
* Enable Hazelcast {hazelcast-cloud}, and add our cluster's discovery token
* Enable SSL and add the keystore and truststore credentials

The file content for this cloud-based target cluster is as follows:

----
hazelcast-client:
  cluster-name: xyz
  network:
    hazelcast-cloud:
      enabled: true
      discovery-token: tokentoken
    ssl:
      enabled: true
      properties:
        keyStore: client.keystore
        keyStorePassword: abc123
        trustStore: client.truststore
        trustStorePassword: abc123
----
