= Extending the Source Cluster
:description: To migrate ReplicatedMap metadata and/or CP data structures, you must add the extension JAR provided in the DMT package to the class path in your source cluster. 

{description}


The extension JAR is located at _extension/hazelcast-data-migration-extension-{version}.jar_ in the extracted DMT package. This file is only required when you want to migrate ReplicatedMap metadata and/or CP data structures as described in <<when-to-use,When to Use the Extension JAR>>.

* The extension JAR can only be used with 4.x and 5.x versions of Hazelcast. Earlier versions of Hazelcast are not supported.
* You can use the extension JAR with both Enterprise and Open Source versions.

[when-to-use]
== When to Use the Extension JAR

You can migrate most structures without adding the extension JAR. It is required only if you want to migrate ReplicatedMap metadata and/or CP data structures.

WARNING: If your source cluster is newer than 5.3.7, you must not use the extension JAR since the APIs in the extension JAR already exists. If you use the extension JAR with a version of Hazelcast that includes the API that replaces the extension JAR, class mismatches and migration failure can occur.

The extension JAR does the following:

. Lists CP data structures
. Reads ReplicatedMap data and metadata (such as time to live and creation time). Your source cluster can migrate ReplicatedMap data without the extension JAR, which adds the ability to read metadata.

== How to Use the Extension Jar

To use the extension JAR, complete the following steps for each member in your cluster:

. Gracefully shutdown the member, as described in xref:maintain-cluster:shutdown.adoc#graceful-shutdown[Graceful Shutdown].
+
Once the graceful shutdown has completed, the cluster contains one less member but no data loss occurs.
. Add the extension JAR to the class path of the JVM. 
+
You can use the _user-lib_ folder in your Hazelcast distribution to do this, as described in xref:clusters:deploying-code-from-clients.adoc#adding-user-library-to-classpath[Deploying User Code from Clients].
. Restart the member.
