= Extending the Source Cluster
:description: To migrate ReplicatedMap metadata and/or CP data structures, you must add the extension JAR provided in the DMT package to the class path in your source cluster. 

{description}

== Introduction

The extension jar is a file named as _hazelcast-data-migration-extension-{version}.jar_ found inside the _extension_ folder in the extracted DMT package. It contains additional functionalities for your source Hazelcast cluster.

* The extension jar is compatible with 4.x and 5.x versions of Hazelcast. 3.x versions are not supported.
* You can use the extension jar with open source or enterprise Hazelcast versions.

== When to Use the Extension Jar

Depending on which data structures you want to migrate, you may not need the extension jar. 

The extension jar includes the following functionality:

. List CP structures
. Read ReplicatedMap data + metadata (time to live, creation time and so on). Your source cluster already has functionality to return ReplicatedMap data. The extension jar provides metadata read functionality.

Therefore, you need the extension jar if one of the following is true:

* You want to migrate ReplicatedMap metadata and your source cluster version is not newer than "5.3.7". (This API is added to Hazelcast in "5.3.7".)
* You want to migrate CP structures (IAtomicLong, IAtomicReference, ICountdownLatch) and your source cluster is not newer than "5.4.0". (This API is added to Hazelcast in "5.4.0".) so if your source cluster is newer than "5.4.0", you don't need the extension jar.

WARNING: Using the extension jar with a Hazelcast versions that already have the API in the extension jar can cause a class mismatch and thus failures in migration. Therefore, don't use the extension jar if your source cluster is newer than 5.3.7 (or 5.4.0 for CP case).

== How to Use the Extension Jar

You can extend your source cluster by gracefully shutting down your cluster members one by one as described in xref:maintain-cluster:shutdown.adoc#graceful-shutdown[Graceful Shutdown, window=_blank] documentation.


For each member in your cluster:

. Gracefully shutdown the member. 
. After graceful shutdown, you will have one less member without any data loss. Add the extension jar to the class path of the JVM. You can use the _user-lib_ folder in your Hazelcast distribution explained xref:clusters:deploying-code-from-clients.adoc#adding-user-library-to-classpath[here, window=_blank].
. Restart the member.
