= Upgrading from Jet
:description: This guide covers the most important changes that we made to the Hazelcast engine in this version and how you can migrate existing jobs over from Jet clusters.

{description}

This guide is not an overview of the new features in Hazelcast {page-component-version}. This release includes other enhancements that don't need any special attention during an upgrade. For a complete list of changes, see the xref:ROOT:release-notes.adoc[release notes].

== Before you Upgrade

If you are using Jet Enterprise version 3.x or 4.x, you can export the state of your existing jobs and continue running them on the upgraded cluster. See <<migrating-data-from-jet-clusters, Migrating Data from Jet Clusters>> on this page.

== Migrating Job Snapshots from Jet Clusters

[blue]*Hazelcast Enterprise Feature*

You can migrate job snapshots from Jet clusters only if the Jet clusters are running version 3.x or 4.x.

. Suspend any running jobs.
. Export a snapshot of your jobs.
. Perform a rolling upgrade.
. Resume the suspended jobs after the rolling upgrade is completed.

See the following topics for help completing these steps:

* xref:pipelines:job-management.adoc#suspending-and-resuming-jobs[Suspending and Resuming Jobs]
* xref:pipelines:job-update.adoc#exporting-a-snapshot[Exporting a Snapshot]
* xref:maintain-cluster:rolling-upgrades.adoc[Rolling Upgrades]

== Entry Points

== Configuration

Removed the following properties that were used in the former Jet product, since it is now part of Hazelcast 5.0:

jet.home

jet.imdg.version.mismatch.check.disabled

The properties provided in former JetProperties are now merged into ClusterProperty. Also added the hazelcast prefix to the former Jet property names, e.g., jet.job.scan.period has become hazelcast.jet.job.scan.period and the former one is deprecated.

== Distributions

Hazelcast distribution is now available in two versions: full and slim. While the full one includes Hazelcast and all of its modules along with SQL, Jet engine extensions and Management Center, the slim one only includes the Hazelcast runtime, default configurations and scripts. See here for details. #18990, #18989

Consolidated the scripts delivered with the former IMDG and Jet distributions. See the Changes in Distribution Packaging section. #18999

The former hazelcast-sql, hazelcast-sql-core and hazelcast-jet-sql Maven modules in the distributions have been merged into a single hazelcast-sql module as a part of the Hazelcast 5.0 distribution. #18584

Removed the jackson-core dependency from pom.xml since it was breaking the extensions that depend on jackson. #18665

Moved the former Hazelcast Jet code samples into the Hazelcast code samples repository.