= Upgrade a cluster to {enterprise-product-name}
:description: You can upgrade your Open Source cluster to an Enterprise cluster using an in-place rolling restart to change each member in turn.

{description}

This approach ensures that you can move your cluster without interruption to the service. 
Similar to the rolling upgrade process, a rolling restart allows you to move one member at a time.

To use a rolling restart to upgrade your cluster to {enterprise-product-name}, the codebase of your {open-source-product-name} cluster must match the target {enterprise-product-name} release. 

For example, you can use a rolling restart to upgrade your cluster from {open-source-product-name} 5.5 to {enterprise-product-name} 5.5. However, you cannot use a rolling restart to move to {enterprise-product-name} 5.5 from an earlier {open-source-product-name} release, such as 5.3. To move from an earlier {open-source-product-name} release, you must migrate your {open-source-product-name} data and make any other associated updates, then set-up {enterprise-product-name}. You might find the Data Migration Tool (DMT) suitable for migrating your data -- see xref:migrate:data-migration-tool.adoc[].

== Best practices

Before starting a rolling restart, consider the following best practices:

* Back up your IMap and ReplicatedMap data structures using your usual method. This is not essential, but it is recommended.
* Ensure that the version of JDK meets the minimum required for the target {enterprise-product-name} release.
* Plan sufficient time for the rolling restart to complete, and remember that the member cannot change during the move.

== Perform a rolling restart

Before starting, ensure you have your {enterprise-product-name} license key ready to add to the member configuration. See xref:deploy:enterprise-licenses.adoc[].

To move your {open-source-product-name} cluster to {enterprise-product-name}, complete the following steps:

. Gracefully shut down the first member:
+
[tabs]
====
CLI::
+
IMPORTANT: This command shuts down all running members on the local machine.
+
--
[source,bash]
----
hz-stop
----
--

Management Center::
+
--
Go to *Members*, select the member's row in the table and select *Shutdown*.
--

Docker::
+
--
[source,bash]
----
docker stop <CONTAINER_NAME>
----
--
====

. Wait until all partition migrations are completed. You can monitor the progress of migrations on the xref:{page-latest-supported-mc}@management-center:clusters:dashboard.adoc[cluster dashboard] in Management Center.

. Upgrade the member's codebase to match the {enterprise-product-name} version and configure your {enterprise-product-name} license key.

. Start a new member and wait until it joins the {enterprise-product-name} cluster.
+
[tabs]
====
CLI::
+
--
[source,bash]
----
hz start
----
--

Docker::
+
--
[source,bash]
----
docker start <CONTAINER_NAME>
----
--
====

. Repeat this process for each member in the {open-source-product-name} cluster.

When all members on the {open-source-product-name} cluster have been moved to the {enterprise-product-name} cluster, you can start configuring the 
{enterprise-product-name} features that you want to use. See xref:getting-started:editions.adoc[].
