= ALTER JOB
:description: The ALTER JOB statement can supend, resume, or restart a job that is running on a cluster.

The `ALTER JOB` statement can supend, resume, or restart a job that is running on a cluster.

== Syntax Summary

This code block is a quick reference with all the <<parameters, parameters>> that you can use with the `ALTER JOB` statement.

See some <<examples, practical examples>>.

[source,sql]
----
ALTER JOB job_name { SUSPEND | RESUME | RESTART }
----

== Parameters

The `ALTER JOB` statement accepts the following parameters.

The `job_name` parameter is required.

[cols="1a,2a,1a"]
|===
|Parameter | Description | Example

|job_name
|The name of the job to suspend, resume, or restart.
|

|SUSPEND
|Suspend the job. For details, see the API reference for the link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/jet/Job.html#suspend()[`suspend()`] method.
|

|RESUME
|Resume a suspended job. For details, see the API reference for the link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/jet/Job.html#resume()[`resume()`] method.
|

|RESTART
|Suspends and resumes the job. For details, see the API reference for the link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/jet/Job.html#restart()[`restart()`] method.
|

|===

== Examples

This section lists some example SQL queries that show you how to use the `ALTER JOB` statement.

=== Suspend and Resume a Job

You may want to suspend a job to perform maintenance on a source or a sink without disrupting the job.

[source,sql]
----
ALTER JOB track_trades SUSPEND
----

When maintenance is finished, you can resume the job to restart it.

[source,sql]
----
ALTER JOB track_trades RESUME
----

=== Restart a Job

You may want to restart a job if you want to distribute it over some new members in your cluster and auto-scaling is disabled.

[source,sql]
----
ALTER JOB track_trades RESTART
----


