= Connecting to the SQL Service
:description: You can connect to the SQL service of a Hazelcast member using a shell, a client API, or Management Center.

You can connect to the SQL service of a Hazelcast member using one of the following options:

- <<sql-shell, SQL shell>> or xref:{page-latest-supported-mc}@management-center:ROOT:sql-browser.adoc[Management Center]: For fast prototyping.

- link:https://github.com/hazelcast/hazelcast-jdbc/blob/main/README.md[JDBC driver] or the link:https://docs.hazelcast.org/docs/{page-latest-supported-java-client}/javadoc/com/hazelcast/sql/SqlService.html[Java client]: For Java applications.

- link:http://hazelcast.github.io/hazelcast-nodejs-client/api/{page-latest-supported-nodejs-client}/docs/interfaces/sql_sqlservice.sqlservice.html[Node.js client].
+
WARNING: This client does not yet support `DATE`, `TIMESTAMP`, or `TIMESTAMP WITH TIME ZONE` xref:sql:data-types.adoc[data types].

- link:https://hazelcast.readthedocs.io/en/v{page-latest-supported-python-client}/api/sql.html[Python client].
+
WARNING: This client does not yet support `DATE`, `TIMESTAMP`, or `TIMESTAMP WITH TIME ZONE` xref:sql:data-types.adoc[data types].

NOTE: You cannot run SQL queries on xref:ROOT:glossary.adoc#lite-member[lite members]. This limitation will be removed in future releases.

== Using the SQL Shell

The easiest way to run SQL queries on a cluster is to connect to the SQL shell.

To connect to the SQL shell, run the `hz-cli sql` command of your member's built-in CLI.

[tabs]
====
Binary::
+
--
.Mac and Linux
[source,shell]
----
bin/hz-cli sql
----

.Windows
[source,shell]
----
bin/hz-cli.bat sql
----
--
Docker::
+
--
Replace the `$LOCAL_IP` placeholder with your member's local IP address.

[source,shell,subs="attributes+"]
----
docker run --network hazelcast-network -it --rm hazelcast/hazelcast:{page-component-version} hz-cli --targets hello-world@$LOCAL_IP sql
----

The `--targets` parameter tells the SQL shell to connect to the member at the given IP address in a cluster called `hello-world`.
--
====