= SQL Connectors
:description: SQL connectors are extensions that allow you to communicate with external systems such as databases, using SQL. These connectors are configured to read and write data in the most efficient way for their respective system.

{description}

To use a connector, you must use the xref:create-mapping.adoc[`CREATE MAPPING` statement].

[cols="1m,1a"]
|===
|Connector | Usage

|xref:kafka-connector.adoc[Apache Kafka]
|Read from and write to Kafka topics.

|xref:file-connector.adoc[File]
|Read from a local or remote file.

|xref:imap-connector.adoc[IMap]
|Read from and write to an IMap.

|===

== Installing Connectors

All connectors are available in the full distribution of Hazelcast.

If you're using the slim distribution, you must add connectors to your classpath before you can use them.

Each connector's reference page lists the information you need to add them to your classpath.

== SQL Isolation Levels

SQL isolation levels define the locking and row versioning behavior of an SQL or DML statement.

The isolation level for each mapping is defined by the connector type and in some cases can be tuned in the connector's options.

However, in general, connectors use the Read Committed isolation level because it allows you to read different versions of a single row while executing a single query.

This isolation level is ideal for streaming queries where you want to see the current version of the data, not the version from the time when the query was started. For example, a streaming query such as joining a table to a stream may run for months. In this case, the Read Committed isolation level allows you to see the current data in the table and not an old version of it from when the query started.