= CREATE VIEW
:description: The CREATE VIEW statement creates a virtual table based on the result set of an SQL query. Views can be reused in other queries.
:page-beta: true

The `CREATE VIEW` statement creates a virtual table based on the result set of an SQL query. Views can be aliased and reused in other queries.

== Syntax Summary

This code block is a quick reference with all the <<parameters, parameters>> that you can use with the `CREATE VIEW` statement.

See some <<examples, practical examples>>.

[source,sql]
----
CREATE [ OR REPLACE ] VIEW [ IF NOT EXISTS ] name AS query
----

== Parameters

The `CREATE VIEW` statement accepts the following parameters.

You must provide the following:

- `name`
- `query`

[cols="1m,2a"]
|===
|Parameter | Description

|`IF NOT EXISTS`
|Create a new view only if a view of the same name does not already exist (recommended).

|`OR REPLACE`
|Overwrite an existing view of the same name.

|`name`
|Name of the view. This name must be unique.

|`query`
|A `SELECT` statement. If the table in the `query` parameter does not exist at the time the view is created, this statement will fail.

|===

== Dependency Management

All views depend on other views or mappings. As a result, if you change a mapping that a view depends on, you will invalidate that view. For example, if you drop a column from a mapping that the view `v` depends on, the command will succeed. However, subsequent
queries such as `SELECT * FROM v` will fail because the column is missing.

The command to drop a column from the mapping succeeds because the `query` parameter in the view isn't validated until the next time it is used.

== Information Schema Views

The `information_schema.views` view provides a view into the engine metadata for the user. View
columns are in
`information_schema.columns` table.

== Permissions

In Hazelcast Enterprise, you can grant or deny permission for certain clients to use this statement.

See xref:security:native-client-security.adoc#sql-permission[SQL Permissions].

== Examples

This section lists some example SQL queries that show you how to use the `CREATE VIEW` statement.

```sql
CREATE VIEW topPerformingEmployees  
AS   
SELECT FirstName, LastName
FROM employees   
WHERE performance > 70 ;
```