= CREATE MAPPING
:description: pass:q[The CREATE MAPPING statement creates a table that stores essential metadata about a source's data model, data connection or connection parameters, and serialization formats so that the SQL service can connect to the data source and query it.]

{description}

== Syntax Summary

This code block is a quick reference with all the <<parameters, parameters>> that you can use with the `CREATE MAPPING` statement.

See some <<examples, practical examples>>.

[source,sql]
----
CREATE [OR REPLACE] MAPPING [IF NOT EXISTS] mapping_name
[EXTERNAL NAME external_name]
[ ( column_name column_type [EXTERNAL NAME external_column_name] [, ...] ) ]
{TYPE type_identifier | DATA CONNECTION data_connection_name [OBJECT TYPE resource_type]}
[ OPTIONS ( 'option_name' = 'option_value' [, ...] ) ]
----

== Parameters

The `CREATE MAPPING` statement accepts the following parameters.

You must provide the following:

- `mapping_name`
- `type_identifier` or `data_connection_name`

[cols="1a,2a,3a"]
|===
|Parameter | Description | Example

|`OR REPLACE`
|Overwrite an existing mapping of the same name, if it exists.
|
[source,sql]
----
CREATE OR REPLACE MAPPING myMap
TYPE IMap
OPTIONS (
    'keyFormat'='varchar',
    'valueFormat'='int');
----

|`IF NOT EXISTS`
|Create a new mapping only if a mapping of the same name does not already exist.
|
[source,sql]
----
CREATE MAPPING IF NOT EXISTS myMap
TYPE IMap
OPTIONS (
    'keyFormat'='varchar',
    'valueFormat'='int');
----

|`mapping_name`
|Name of the mapping, which you can use to query the data.
|
[source,sql]
----
CREATE MAPPING myMappingName
TYPE IMap
OPTIONS (
    'keyFormat'='varchar',
    'valueFormat'='int');
----

|`external_name`
|An optional name that identifies the object or resource in the external system for which the mapping is created. For example, for a Kafka connector, the identifier is the topic name. For a JDBC connector, the identifier may be the name of a table, view, or other relation. By default, this parameter is equal to the mapping name.
|

|`column_name`, `column_type`
|The name and data type of the column.
|
[source,sql]
----
CREATE MAPPING myMap (
    name VARCHAR,
    id INT
)
TYPE IMap
OPTIONS (
    'keyFormat'='varchar',
    'valueFormat'='json-flat');
----

|`external_column_name`
|An optional name of a column. If omitted, Hazelcast assumes this name is equal to the `column_name` parameter. For key-value connectors (Kafka, IMap), the key's and value's fields are prefixed by `__key` and `this`.
|

|`type_identifier`
|The connector to use to map the data. For example, if you use the `IMap` type, data is mapped to a Hazelcast map.
|
[source,sql]
----
CREATE MAPPING myMap
TYPE IMap
OPTIONS (
    'keyFormat'='varchar',
    'valueFormat'='int');
----

|`data_connection_name`
|An existing data connection that is used to connect to the external system. 
|
[source,sql]
----
CREATE MAPPING my_transactions_topic
DATA CONNECTION myKafkaConnection
OPTIONS (
    'keyFormat' = 'bigint',
    'valueFormat' = 'json-flat');
----

|`resource_type`
|An optional name of the type of resource in the external system. For a JDBC connector, the resource may be a table, view, or other data structure. For a Kafka connector, the resource is a topic.
|
[source,sql]
----
CREATE MAPPING my_transactions_topic (
    __key BIGINT
    transactionType VARCHAR,
    amount INT)
DATA CONNECTION myKafkaConnection
OBJECT TYPE topic
OPTIONS (
    'keyFormat' = 'bigint',
    'valueFormat' = 'json-flat');
----

|`'option_name'`, `'option_value'`
|Data connection or connector parameters. Check the xref:integrate:connectors.adoc[reference page] for your connector to find out what values you can use. These parameters must be enclosed in single quotes (a SQL `VARCHAR` literal).
|
```sql
CREATE MAPPING my_topic(
    __key BIGINT,
    ticker VARCHAR,
    amount INT)
TYPE Kafka
OPTIONS (
    'keyFormat' = 'bigint',
    'valueFormat' = 'json-flat',
    'bootstrap.servers' = '127.0.0.1:9092');
```

|===

== Permissions
[.enterprise]*{enterprise-product-name}*

If xref:security:enabling-jaas.adoc[security] is enabled, you can grant or deny permission for certain clients to use this statement. See xref:security:native-client-security.adoc#sql-permission[SQL Permissions].

== Auto-resolving Columns and Options

Some connectors can resolve the column names and values of an object either by using the options you provide or by sampling a random record in the input. For example, if you give Hazelcast the name of a map that contains Java objects, Hazelcast will resolve the columns by reflecting that class.

If the connector fails to resolve the columns, the statement will fail.

== Examples

This section lists some example SQL queries that show you how to use the `CREATE MAPPING` statement.

=== Create a Mapping to a Map

See xref:sql:mapping-to-maps.adoc[].

=== Create a Mapping to a Kafka Topic

See xref:sql:mapping-to-kafka.adoc[].

=== Create a Mapping to a File

See xref:sql:mapping-to-a-file-system.adoc[].

=== Create a Mapping to a Database

See xref:sql:mapping-to-jdbc.adoc[].

=== Change a Mapping

If you want to overwrite an existing mapping, use the `CREATE OR REPLACE MAPPING` statement.

include::partial$warnings.adoc[tag=changing-or-removing-a-mapping]

[source,sql]
----
CREATE OR REPLACE MAPPING myMap TYPE IMap OPTIONS ('keyFormat'='varchar','valueFormat'='int');
----

