= CREATE OR REPLACE SNAPSHOT (Enterprise only)
:description: The CREATE OR REPLACE SNAPSHOT statement creates a named snapshot that you can use to start other jobs or keep as a backup.

The `CREATE OR REPLACE SNAPSHOT` statement creates a named xref:ROOT:glossary.adoc#snapshot[snapshot] that you can use to start other jobs or keep as a backup.

NOTE: After you create a snapshot, the job will continue running. If you want to cancel the job after creating a snapshot, use the xref:drop-job.adoc[`DROP JOB WITH SNAPSHOT` statement].

== Syntax Summary

This code block is a quick reference with all the <<parameters, parameters>> that you can use with the `CREATE OR REPLACE SNAPSHOT` statement.

TIP: For some practical examples, see << examples, Code Examples>>.

[source,sql]
----
CREATE OR REPLACE SNAPSHOT snapshot_name FOR JOB job_name
----

== Parameters

The `CREATE OR REPLACE SNAPSHOT` statement accepts the following parameters.

All of these parameters are required.


[cols="1a,2a,1a"]
|===
|Parameter | Description | Example

|snapshot_name
|Name the snapshot. If the snapshot already exists, it is overwritten.
|<<create-a-snapshot, Create a Snapshot>>

|job_name
|Define the job for which to create the snapshot.
|<<create-a-snapshot, Create a Snapshot>>

|===

== Examples

This section lists some example SQL queries that show you how to use the `CREATE OR REPLACE SNAPSHOT` statement.

=== Create a Snapshot

[source,sql]
----
CREATE OR REPLACE SNAPSHOT track_trades_snapshot FOR JOB track_trades;
----

