= DELETE
:description: The DELETE statement deletes map entries that match the condition in a given WHERE clause.

The `DELETE` statement deletes map entries that match the condition in a given `WHERE` clause.

NOTE: This statement is not atomic and deletions are never rolled back. If this statement is canceled for any reason, some values that match the condition may be deleted and some may remain.

== Syntax Summary

This code block is a quick reference with all the <<parameters, parameters>> that you can use with the `DELETE` statement.

See some <<examples, practical examples>>.

[source,sql]
----
DELETE FROM table_name [  [ AS ] alias  ]
[ WHERE condition ]
----

== Parameters

The `DELETE` statement accepts the following parameters.

You must provide an `expression` parameter and a `from_item` parameter.

[cols="1a,2a,1a"]
|===
|Parameter | Description | Example

| `WHERE condition`
|An optional clause that, if given, indicates the conditions that rows must satisfy to be selected. `condition` is an expression that is evaluated for each row. If the expression is `true`, the row is selected. This expression is evaluated before grouping.
|<<filter-rows-by-condition, Filter rows by condition>>

|===

== Examples

This section lists some example SQL queries that show you how to use the `DELETE` statement.

=== Delete Entries by Keys or Values

You can delete map entries by key or value.

For example, in a map that contains `Employee` objects as values with the following structure:

[cols="1,1"]
|===
| Name
| Type

|`startDate`
|`integer`

|`amount`
|`integer`

|`title`
|`string`

|`department`
|`string`
|===

You can delete the entries of the `Employee.age` field where the age is less than 18:

[source,sql]
----
DELETE FROM employees WHERE age < 18;
----

Whether you can access nested fields like this in objects depends on how your map entries are serialized:

- For Java objects (xref:serialization:implementing-java-serializable.adoc[`Serializable`], xref:serialization:implementing-dataserializable.adoc[`DataSerializable`], xref:serialization:implementing-java-serializable.adoc#identifieddataserializable[`IdentifiedDataSerializable`]), you must xref:clusters:deploying-code-on-member.adoc[add the object's class to the classpath of the member] you are sending the query to.

- For xref:serialization:implementing-portable-serialization.adoc[`Portable`] / xref:serialization:compact-serialization.adoc[`Compact(BETA)`] objects, you do not need to add the object's class to the classpath of the member, unless you want to use parameterized queries to compare one object against another.
