= DROP JOB
:description: The DROP JOB statement cancels a job and gives you the option to create a named snapshot from it.

The `DROP JOB` statement cancels a job and gives you the option to create a named xref:ROOT:glossary.adoc#snapshot[snapshot] from it.

== Syntax Summary

This code block is a quick reference with all the <<parameters, parameters>> that you can use with the `DROP JOB` statement.

TIP: For some practical examples, see <<examples, Code Examples>>.

[source,sql]
----
DROP JOB [IF EXISTS] job_name [WITH SNAPSHOT snapshot_name]
----

== Parameters

The `DROP JOB` statement accepts the following parameters.

The `job_name` parameter is required.

[cols="1a,2a,1a"]
|===
|Parameter | Description | Example

|IF EXISTS
|Fail silently if the job either does not exist or is no longer running.
|<<delete-a-job, Delete a Job>>

|job_name
|The name of the job to delete.
|<<delete-a-job, Delete a Job>>

|WITH SNAPSHOT
|Create a named snapshot of the job before canceling it (Enterprise only).
|<<delete-a-job, Delete a Job>>

|===

== Examples

This section lists some example SQL queries that show you how to use the `DROP JOB` statement.

=== Delete a Job

[source,sql]
----
DROP JOB IF EXISTS track_trades WITH SNAPSHOT track_trades_snapshot;
----



