= DROP MAPPING
:description: The DROP MAPPING statement removes a mapping from the public schema.

The `DROP MAPPING` statement removes a mapping from the `public` schema.

== Syntax Summary

This code block is a quick reference with all the <<parameters, parameters>> that you can use with the `DROP MAPPING` statement.

See some <<examples, practical examples>>.

[source,sql]
----
DROP MAPPING [IF EXISTS] mapping_name
----

== Parameters

The `DROP MAPPING` statement accepts the following parameters.

[cols="1a,2a,1a"]
|===
|Parameter | Description | Example

|`IF EXISTS`
|Fail silently if the mapping does not exist.
|<<delete-a-mapping, Delete a Mapping>>

|`mapping_name` (required)
|The name of the mapping to delete.
|<<delete-a-mapping, Delete a Mapping>>

|===

== Permissions
[.enterprise]*Enterprise*

If xref:security:enabling-jaas.adoc[security] is enabled, you can grant or deny permission for certain clients to use this statement. See xref:security:native-client-security.adoc#sql-permission[SQL Permissions].

== Examples

This section lists some example SQL queries that show you how to use the `DROP MAPPING` statement.

=== Delete a Mapping

[source,sql]
----
DROP MAPPING IF EXISTS myMap;
----
