= EXPLAIN
:description: The EXPLAIN statement returns the execution plan for a given statement, without executing it.
:page-beta: true

The `EXPLAIN` statement returns the execution plan for a given statement, without executing it. You can use this statement to debug long-running queries and learn how to optimize them.

== Syntax Summary

This code block is a quick reference for the `EXPLAIN` statement.

See some <<examples, practical examples>>.

[source,sql]
----
EXPLAIN statement
----

== Parameters

All statements can be used as parameters to the `EXPLAIN` statement.

== Optimizing Queries

Scanning an entire table is the slowest way to access data. You can find out if your queries are performing full table scans, using the `EXPLAIN` statement.

If your queries are performing full table scans, you should create indexes that contain at least one of the columns that the query is filtering in its `WHERE` clause. See xref:create-index.adoc[].

== Examples

This section lists some example SQL queries that show you how to use the `EXPLAIN` statement.

=== Full table scans

[source,sql]
----
EXPLAIN SELECT * FROM cities WHERE countries = 'United Kingdom';
----

```
+--------------------+
|rel                 |
+--------------------+
|FullScanPhysicalRel…|
+--------------------+
```
