= Finding Existing Mappings
:description: You can find out information about existing mappings such as column names and their SQL data types.

{description}

== Before you Begin

[cols="1a,1a"]
|===
|Prerequisites|Useful resources

|A Hazelcast cluster in client/server mode.
|xref:getting-started:get-started-binary.adoc[Start a Local Cluster].

|Enable the Jet engine.
|The Jet engine is needed to run SQL queries. For information about how to enable the Jet engine, see xref:pipelines:job-security.adoc[].

|An understanding of mappings.
|xref:sql-overview.adoc[]
|===

== Find a Mapping

. Create a mapping to a map called `myMappingName`.
+
[source,sql]
----
CREATE MAPPING myMappingName
TYPE IMap
OPTIONS ('keyFormat'='varchar','valueFormat'='int');
----

. Get the name of your mapping.
+
[source,sql]
----
SHOW MAPPINGS;
----
+
You should see the name of the mapping.
+
```
+--------------------+
|name                |
+--------------------+
|myMappingName       |
+--------------------+
```

. Get more information about the mapping.
+
[source,sql]
----
SELECT * FROM information_schema.mappings
WHERE table_name = 'myMappingName';
----
+
The name of the mapping is stored in the `table_name` column. And, all tables are part of the `hazelcast` table catalog in the `public` schema.

. Get information about the column names and the columns' SQL data types.
+
[source,sql]
----
SELECT * FROM information_schema.columns
WHERE table_name = 'myMappingName';
----

== Next Steps

See the xref:sql-statements.adoc#ddl-statements[SQL statements] that you can use to manage your mappings.