= Mapping to JDBC
:description: To query external JDBC data stores, you can create a mapping to them with the JDBC connector.
:page-beta: true

{description}

== What is the JDBC Connector

The JDBC connector allows you to connect to any database that supports the JDBC interface.

== Installing the Connector

The JDBC connector is included in the full and slim distributions of Hazelcast.

== Permissions
[.enterprise]*Enterprise*

If xref:security:enabling-jaas.adoc[security] is enabled, your clients may need permissions to use this connector. For details, see xref:pipelines:job-security.adoc[].

== Before you Begin

Before you can create a mapping to an external data store, you must have the following:

- A JDBC driver that's compatible with your data store. This driver must be on the classpath of your cluster members:
** The full distribution of Hazelcast comes with a JDBC driver for MySQL and PostgreSQL data stores.
** The slim distribution of Hazelcast does not come with a JDBC driver.
- A xref:external-data-stores:external-data-stores.adoc[data store connection] that's configured on all cluster members.

== Creating a JDBC Mapping

Use the `CREATE MAPPING` statement to tell the JDBC connector the name of your data store configuration.

For example, consider that you already have a connection configured to a MySQL database.

```yaml
external-data-store:
  mysql-database: <3>
    class-name: com.hazelcast.datastore.JdbcDataStoreFactory
    properties:
      jdbcUrl: jdbc:mysql://dummy:3306
      username: xyz
      password: xyz
    shared: true
```

You then create the following `people` table in the MySQL database:

```sql
CREATE TABLE people (id INT PRIMARY KEY, name VARCHAR(100))
```

Your mapping must contain explicit column names that match the data types in the database.

```sql
CREATE MAPPING people (
  <1>
  id INT, 
  name VARCHAR 
) 
TYPE JDBC <2>
OPTIONS ( 
  'externalDataStoreRef'='mysql-database' <3>
)
```

<1> The columns are mapped to the data in the external data store.
<2> The name of the connector.
<3> The name of the external data store configuration on your members.