= Mapping to JDBC
:description: To query external JDBC data stores, you can create a mapping to them with the JDBC connector.
:page-beta: false

{description}

== What is the JDBC Connector

The JDBC connector allows you to connect to any database that supports the JDBC interface.

== Supported Databases

The JDBC connector supports the following database management systems:

- MySQL
- PostgreSQL
- Microsoft SQL Server
- Oracle


== Supported SQL Statements

The JDBC connector supports only the following statements:

- xref:select.adoc[`SELECT`]
- xref:sink-into.adoc[`INSERT INTO`]
- xref:update.adoc[`UPDATE`]
- xref:delete.adoc[`DELETE`]





== Installing the Connector

The JDBC connector is included in the full and slim distributions of Hazelcast.

== Permissions
[.enterprise]*Enterprise*

The JDBC connector does not yet support permissions.

== Before you Begin

Before you can create a mapping to an external data store, you must have the following:

- A JDBC driver that's compatible with your data store. This driver must be on the classpath of your cluster members:
** The full distribution of  Hazelcast Enterprise comes with a JDBC driver for PostgreSQL data stores only.
** The slim distribution of Hazelcast does not come with a JDBC driver.
** The full distribution of Hazelcast Open Source comes with a JDBC driver for MySQL and PostgreSQL data stores.
- A xref:external-data-stores:external-data-stores.adoc[data store connection] that's configured on all cluster members.
- Create the database that you'll use as your external data store.

== Creating a JDBC Mapping

The following example creates a mapping to a MySQL database.

In the MySQL database, create a `people` table.

```sql
CREATE TABLE people (id INT PRIMARY KEY, name VARCHAR(100))
```

Use the `CREATE MAPPING` statement to tell the JDBC connector the name of your data store configuration.

```yaml
external-data-store:
  mysql-database: <1>
    class-name: com.hazelcast.datastore.JdbcDataStoreFactory
    properties:
      jdbcUrl: jdbc:mysql://dummy:3306
      username: xyz
      password: xyz
    shared: true
```
<1> Configuration details for a MySQL database.

Create the mapping.

```sql
CREATE MAPPING people
TYPE JDBC <1>
OPTIONS ( 
  'externalDataStoreRef'='mysql-database' <2>
)
```

<1> The name of the connector.
<2> The name of the external data store configuration on your members.

== Data Type Mapping Between Hazelcast and MSSQL
Hazelcast supports a subset of SQL data types. The following MSSQL types are mapped to the respective Hazelcast SQL type:


[cols="1,1"]
|===
| MSSQL Type| Hazelcast SQL Type

|`varchar`
|`VARCHAR`

|`tinyint`
|`TINYINT`

|`smallint`
|`SMALLINT`

|`int`
|`INTEGER`

|`bigint`
|`BIGINT`

|`decimal`
|`DECIMAL`

|`real`
|`REAL`

|`float`
|`DOUBLE`

|`date`
|`DATE`

|`time`
|`TIME`

|`datetime`
|`TIMESTAMP`

|`datetimeoffset`
|`TIMESTAMP WITH TIME ZONE`

|`numeric`
|`DECIMAL`

|`char`
|`VARCHAR`

|`text`
|`VARCHAR`

|===

== Data Type Mapping Between Hazelcast and Oracle
The following Oracle types are mapped to the respective Hazelcast SQL type.
`NUMBER(p,s)` represents a NUMBER type with a decimal precision of `p` and a scale of `s` that is greater than 0. `NUMBER(p)` has a scale of 0.


[cols="1,1"]
|===
| Oracle Type| Hazelcast SQL Type

|`VARCHAR2`
|`VARCHAR`

|`from NUMBER(1) to NUMBER(4) inclusive`
|`SMALLINT`

|`from NUMBER(5) to NUMBER(9) inclusive`
|`INTEGER`

|`from NUMBER(10) to NUMBER(18) inclusive`
|`BIGINT`

|`NUMBER(p,s) where "s" is 0 and "p" is bigger than 18 or "s+p" is bigger than 15`
|`DECIMAL`

|`NUMBER(p,s) where "s+p" is smaller than 8`
|`REAL`

|`NUMBER(p,s) where "s+p" is smaller than 16`
|`DOUBLE`

|`DATE`
|`DATE`

|`TIMESTAMP`
|`TIMESTAMP`

|`TIMESTAMP WITH TIME ZONE`
|`TIMESTAMP WITH TIME ZONE`

|===
