= Querying Maps with SQL
:description: You can use SQL to run optimized distributed queries on the keys and values of maps in a local cluster.
:page-aliases: query:querying-maps-sql.adoc

{description}

== Querying Primitive Entries

A map entry consists of a key and a value. You can query the key through the `__key` alias and the value through the `this` alias.

For example, if you have an map named `capital_cities`, you can query that map, using the following `SELECT` statement.

[source,sql]
----
SELECT * FROM capital_cities;
----

```
+--------------------+------------+
|     __key          |    this    |
+--------------------+------------+
|        1           |   Tokyo    |
+--------------------+------------+
```

The `this` alias is returned by a query only if the value does not contain an object. For example, if the `capital_cities` value was a serialized object that had a `name` and a `country` field, the query result would include those fields as columns and exclude the `this` column.

```
+--------------------+------------+--------------+
|     __key          |    name    |   country    |
+--------------------+------------+--------------+
|        1           |   Tokyo    |    Japan     |
+--------------------+------------+--------------+
```

== Querying Objects in Map Entries

If you store objects in a map, you can query the objects' top-level fields only if they are serialized using one of the following options:

- xref:serialization:implementing-java-serializable.adoc[`Serializable`] - xref:serialization:implementing-dataserializable.adoc[`DataSerializable`], and xref:serialization:implementing-dataserializable.adoc#identifieddataserializable[`IdentifiedDataSerializable`].
+
Only public fields and getters are available. A public field is available with its exact name. A getter is available with the JavaBean naming conventions.
- xref:serialization:implementing-portable-serialization.adoc[`Portable`].
+
Only the fields that are written in the `Portable.writePortable()` method are available, using their exact names.
- JSON.

NOTE: You cannot query nested object fields using SQL.

Consider a map that stores `Employee` objects as values with `name` and `age` fields:

```java
IMap<Long, Employee>
```

The SQL service has access to
the `Employee` object's fields.

[cols="1,1"]
|===
| Name
| Type

|`name`
|`VARCHAR`

|`age`
|`integer`
|===

Together with the key, you may query those fields.

[source,sql]
----
SELECT __key, this, name, age FROM employee
----

If both the key and value have fields with the same name, you may only query the key's field and not the value's field.

== Querying Enums

An enum is a user-defined type, which is mapped to the xref:data-types.adoc[`OBJECT` type] in SQL.

If you use the Java client, you can use the following options to query enums:

- xref:parameterized-queries.adoc[Use a parameterized query].
- Create getter/setter methods that use the enum's ordinal or name.

For example, consider a map whose values are `Employee` objects with the following fields.

[cols="1,1"]
|===
| Name
| Type

|`name`
|`String`

|`age`
|`Int`

|`status`
|`EmployeeStatus`
|===

And the `status` field is an enum called `EmployeeStatus`.

```java
public enum EmployeeStatus {
  PENDING,
  ACTIVE,
  VACATION,
  DELETED;
}
```

To query employees who have a `VACATION` status, you could do either of the following:

- Define a getter method that returns the string representation of the enum.
+
```java
public enum EmployeeStatus {
  PENDING,
  ACTIVE,
  VACATION,
  DELETED;

  public String getEmployeeStatusString() {
    return EmployeeStatus != null ? EmployeeStatus.name() : null;
  }

  public void setEmployeeStatusString(String newValue) {
    EmployeeStatus = newValue == null ? null : EmployeeStatus.valueOf(newValue);
  }
}
```
+
```sql
SELECT * FROM employees 
WHERE getEmployeeStatusString='VACATION';
```

- Use a parameterized query with the Java client.
+
```java
sql.execute("SELECT * FROM employees WHERE employee.status = ?", EmployeeStatus.VACATION);
```

== Running Streaming Queries on Maps

At the moment, you cannot run streaming queries on maps with SQL.

Until this feature is available, use the Jet API to run streaming queries on maps. For a tutorial, see xref:pipelines:stream-imap.adoc[].

== Learn More

Learn the details of all the available xref:sql:sql-statements.adoc[SQL statements].

See more examples of the xref:sql:select.adoc[`SELECT` statement].



