= Querying Streams in SQL
:description: You can query streams, using standard SQL as well as some non-standard SQL for features such as windowed aggregations. 
:page-beta: true

Stream processing is a programming paradigm for performing computations over events as they arrive. These events are never-ending, which is why they often described as _unbounded_. 

{description}

== Context

This guide explains how to query streams, using the following `trades` data as an example:

[cols="1m,1m"]
|===
|Field|Data type

|trade_amount
|BIGINT

|trade_ticker
|VARCHAR

|price
|DECIMAL

|trade_time
|TIMESTAMP
|===

== Creating a Mapping to a Streaming Source

To allow Hazelcast to read data from a streaming source, you need to create a mapping to it. For example, the mapping for the `trades` topic may look like the following:

```sql
CREATE OR REPLACE MAPPING trades (
  trade_amount BIGINT,
  trade_ticker VARCHAR,
  price DECIMAL,
  trade_time TIMESTAMP)
TYPE Kafka
OPTIONS (
  'valueFormat' = 'json-flat',
  'bootstrap.servers' = 'kafka:9092'
);
```

NOTE: At the moment, the only supported streaming source for SQL is Kafka.

For details about creating a mapping to Kafka, see xref:mapping-to-kafka.adoc[].

== Basic Continuous Queries on a Stream

You can query streams like you would for any batch source. The main difference between streaming and batch queries is that when you query a streaming source, Hazelcast creates a job in the background, which continues to run until you cancel it or the client disconnects.

For example, you can monitor the whole `trades` stream:

```sql
SELECT * FROM trades;
```

This query starts a job that monitors the `trades` stream for new events and executes the query on new ones.

The output contains all trades since the query was first executed. If no trades have yet been made, the output will be empty:

```
+------------+------------+-----+----------+
|trade_amount|trade_ticker|price|trade_time|
+------------+------------+-----+----------+
```

You can also use other clauses such as the `WHERE` clause to filter the output of the stream:

```sql
SELECT * FROM trades
WHERE price > 10;
```

== Managing Streaming Queries

Hazelcast converts streaming queries into jobs, which are executed by the Jet engine. Streaming queries continue to run until the client disconnects or you explicitly cancel the job.

If the client stops receiving results, but doesn't disconnect, Hazelcast keeps a batch of those results in memory, using backpressure. See xref:architecture:distributed-computing.adoc#backpressure[Backpressure].

You can manage streaming queries, using SQL statements. For example, you may want to show all running queries, cancel a query, or alter a query. See xref:pipelines:job-management.adoc[].

== Windowed Aggregations on Streams

An aggregate function performs computations over a set of values and returns a single value. For example, the `COUNT()` function returns the number of rows in a table. However, streams are unbounded, making it impossible to count all the rows because they are continuously being appended.

To use aggregate functions over a stream, you need a way to order related values and group them into _windows_. A common way to order streams is in relation to time, since one event happens after another. However, in theory, streams can be ordered by any value. For example, you might want to perform some computations over all trades that happened in the past minute.

```sql
SELECT window_start, window_end, COUNT(*) AS total_trades <1>
FROM TABLE(TUMBLE(
  TABLE(trades_ordered), <2>
  DESCRIPTOR(trade_time), <3>
  INTERVAL '1' MINUTE)) <4>
GROUP BY 1,2; <5>
```

<1> Get a count of all trades that happened in the window.
<2> Use a <<creating-watermarks, watermark>> to drop any late events.
<3> Use the timestamp in the `trade_time` column to define the window size.
<4> Set the size of the tumbling window to one minute.
<5> Group results in the same window, using the `window_start` and `window_end` columns.

When new results are available for each one-minute window, they are returned:

```
+-------------------+-------------------+--------------------+
|window_start       |window_end         |        total_trades|
+-------------------+-------------------+--------------------+
|2022-01-04T00:00   |2022-01-04T00:01   |                  45|
```

=== Creating Watermarks

Hazelcast can't emit the result of a windowed aggregation until it has received all the events belonging to the
window. But streams are infinite, so to tell Hazelcast how long to wait, you must define a watermark.

Watermarks tell Hazelcast how long to wait by defining how much time is allowed between each event. This time is called the _maximum event lag_. Any event that is later than the maximum event lag is dropped.

NOTE: Time is measured by the timestamps in the events, rather than the current time on a system clock.

To impose order over streams, you can use the `IMPOSE_ORDER()` function to create a watermark. The `IMPOSE_ORDER()` function is a stateful function whose state is scoped for the duration of the query. This function injects watermarks that lag a fixed amount behind the maximum value of the field observed since the query start.

```sql
SELECT *
FROM TABLE(IMPOSE_ORDER(
  TABLE(trades), <1>
  DESCRIPTOR(trade_time), <2>
  INTERVAL '0.5' SECONDS) <3>
);
```

<1> The table that contains the event payload, including the timestamp.
<2> A pointer to the column that contains the timestamp for the watermark.
<3> The maximum event lag. Any events that are later than this lag are dropped. For example, an event with a timestamp of `yyyy-mm-dd 23:59:59.5` is added to the window. If another event is processed with a timestamp that's 0.5 seconds or more older, such as ``yyyy-mm-dd 23:59:58.9`, that event is dropped because it is too old.

If an event is later than the defined maximum event lag, that event is dropped and an entry like the following is added to the log:

```
 Late event dropped. currentWatermark=Watermark{ts=23:03:00.000}
```

For better readability, it's useful to create a view for the watermark like so:

```sql
CREATE VIEW trades_ordered AS
  SELECT *
  FROM TABLE(IMPOSE_ORDER(
    TABLE(trades),
    DESCRIPTOR(trade_time),
    INTERVAL '0.5' SECONDS)
  );
```

For a conceptual introduction to watermarks and windowing, see xref:pipelines:event-time.adoc[].