= SQL Overview
:description: You can use SQL to query data in maps, Kafka topics, or a variety of file systems. Results can be sent directly to the client or inserted into maps or Kafka topics. For streaming queries, you can submit them to a cluster as jobs to run in the background.
:page-aliases: query:sql-overview.adoc

{description}

== Supported Queries

You can run the following queries with SQL.

TIP: For a hands-on introduction to SQL, see xref:get-started-sql.adoc[].

[cols="a,a,a"]
|===

|Query|Description|Tutorial

|Ad-hoc queries, also known as point queries or online transactional processing (OLTP) queries.
|Retrieve a small subset of data quickly.
|xref:get-started-sql.adoc#ad-hoc[]

|Batch queries, also known as online analytical processing (OLAP) queries.
|Query large datasets either in one or multiple systems and/or run aggregations on them to get deeper insights.
|xref:get-started-sql.adoc#batch[]

|Streaming queries, also known as continuous queries.
|Keep an open connection to a streaming data source and run a continuous query to get near real-time updates.
|xref:learn-sql.adoc[]

|Federated queries 
|Query different datasets such as Kafka topics and Hazelcast maps, using a single query. Normally, querying in SQL is database or dataset-specific. However, with <<mappings, mappings>>, you can pull information from different sources and present a more complete picture of the data.
|xref:get-started-sql-files.adoc[]

|===

== Mappings

To connect to data sources and query them as if they were tables, the SQL service uses a concept called _mappings_.

Mappings store essential metadata about the source's data model, data access patterns, and serialization formats so that the SQL service can connect to the data source and query it.

You can create mappings for the following data sources by using the xref:create-mapping.adoc[`CREATE MAPPING` statement]:

- xref:mapping-to-a-file-system.adoc[Hazelcast maps]
- xref:mapping-to-kafka.adoc[Kafka topics]
- xref:mapping-to-maps.adoc[File systems]

== Case Sensitivity

Mapping names and field names are case-sensitive.

For example, you can access an `employee` map
as `employee` but not as `Employee`.

== Limitations

SQL has the following limitations:

- The only supported Hazelcast data structure is map.
+
You cannot query other data structures such as replicated maps.
- No support for the `CREATE INDEX` statement.
+
To create indexes for maps in Hazelcast, see xref:query:indexing-maps.adoc[]
- No support for the `JSON` type.
+
You can't use functions such as `JSON_VALUE` or `JSON_QUERY`.
- Limited support for joins.
+
See xref:sql:select.adoc#join-tables[Join Tables].
- No support for window functions.
+
You cannot group or aggregate results in streaming queries.

== Supported Statements

Hazelcast supports a subset of standard ANSI SQL statements as well as some custom ones for creating jobs, mappings, and streaming queries.

For a list of supported statements, see xref:sql:sql-statements.adoc[].

== How Hazelcast Executes SQL Statements

When an SQL statement is submitted for execution, the SQL service parses and
optimizes it using link:https://calcite.apache.org/[Apache Calcite]. The result is an executable plan in the form of a Jet graph that
is cached and reused by subsequent executions of the same statement.

For details about how the Jet engine models data into graphs, see xref:architecture:distributed-computing.adoc[].

== Next Steps

- xref:get-started-sql.adoc[].
- xref:learn-sql.adoc[].
- xref:get-started-sql-files.adoc[].

Explore the xref:sql:select.adoc[SQL reference docs].
