= SQL Overview
:description: You can use SQL to query data in maps, Kafka topics, or a variety of file systems. Results can be sent directly to the client or inserted into maps or Kafka topics. For streaming queries, you can submit them to a cluster as jobs to run in the background.
:page-aliases: query:sql-overview.adoc

{description}

== Supported Queries

You can run the following queries with SQL.

TIP: For a hands-on introduction to SQL, see xref:get-started-sql.adoc[].

[cols="a,a,a"]
|===

|Query|Description|Tutorial

|Ad-hoc queries
|Query large datasets either in one or multiple systems and/or run aggregations on them to get deeper insights.
|xref:get-started-sql.adoc[]

|Streaming queries, also known as continuous queries.
|Keep an open connection to a streaming data source and run a continuous query to get near real-time updates.
|xref:learn-sql.adoc[]

|Federated queries 
|Query different datasets such as Kafka topics and Hazelcast maps, using a single query. Normally, querying in SQL is database or dataset-specific. However, with <<mappings, mappings>>, you can pull information from different sources to present a more complete picture.
|xref:get-started-sql-files.adoc[]

|===

== Mappings

To connect to data sources and query them as if they were tables, the SQL service uses a concept called _mappings_.

Mappings store essential metadata about the source's data model, data access patterns, and serialization formats so that the SQL service can connect to the data source and query it.

You can create mappings for the following data sources by using the xref:create-mapping.adoc[`CREATE MAPPING` statement]:

- xref:mapping-to-maps.adoc[Hazelcast maps]
- xref:mapping-to-kafka.adoc[Kafka topics]
- xref:mapping-to-a-file-system.adoc[File systems]

== Case Sensitivity

Mapping names and field names are case-sensitive.

For example, you can access an `employee` map
as `employee` but not as `Employee`.

== Limitations

SQL has the following limitations. We plan to remove these limitations in future releases.

- The only supported Hazelcast data structure is map.
+
You cannot query other data structures such as replicated maps.
- Although you can create bitmap indexes in SQL, SQL queries do not leverage those indexes to improve query performance.
- You cannot join results from two streaming sources.
+
See xref:sql:select.adoc#join-tables[Join Tables].

== Supported Statements

Hazelcast supports a subset of standard ANSI SQL statements as well as some custom ones for creating jobs, mappings, and streaming queries.

For a list of supported statements, see xref:sql:sql-statements.adoc[].

== How Hazelcast Executes SQL Statements

When a SQL statement is submitted for execution, the SQL service parses and
optimizes it using link:https://calcite.apache.org/[Apache Calcite]. The result is an executable plan in the form of a Jet graph that
is cached and reused by subsequent executions of the same statement.

For details about how the Jet engine models data into graphs, see xref:architecture:distributed-computing.adoc[].

== Next Steps

- xref:get-started-sql.adoc[].
- xref:learn-sql.adoc[].
- xref:get-started-sql-files.adoc[].

Explore the xref:sql:select.adoc[SQL reference docs].
