= SQL
:description: You can use SQL to query data in maps, Kafka topics, or a variety of file systems. Results can be sent directly to the client or inserted into maps or Kafka topics.
:page-aliases: query:sql-overview.adoc, sql:connecting-to-sql.adoc

{description}

TIP: For a hands-on introduction to SQL, see xref:get-started-sql.adoc[].

== Before you Begin

To use the SQL service, the Jet engine must be enabled on the cluster. For information about how to enable the Jet engine, see xref:pipelines:job-security.adoc[].

== Connecting to the SQL Service

You can connect to the SQL service of a Hazelcast member using one of the following options:

- <<using-the-sql-shell, SQL shell>> or xref:{page-latest-supported-mc}@management-center:ROOT:sql-browser.adoc[Management Center]: For fast prototyping.

- link:https://github.com/hazelcast/hazelcast-jdbc/blob/main/README.md[JDBC driver] or the link:https://docs.hazelcast.org/docs/{page-latest-supported-java-client}/javadoc/com/hazelcast/sql/SqlService.html[Java client]: For Java applications.

- link:http://hazelcast.github.io/hazelcast-nodejs-client/api/{page-latest-supported-nodejs-client}/docs/modules/sql_SqlService.html[Node.js client].

- link:https://hazelcast.readthedocs.io/en/v{page-latest-supported-python-client}/api/sql.html[Python client].

- link:https://pkg.go.dev/github.com/hazelcast/hazelcast-go-client#hdr-Running_SQL_Queries[Go client].

- link:http://hazelcast.github.io/hazelcast-csharp-client/{page-latest-supported-csharp-client}/doc/sql.html[C# client].

NOTE: You cannot run SQL queries on xref:ROOT:glossary.adoc#lite-member[lite members]. This limitation will be removed in future releases.

=== Using the SQL Shell

The easiest way to run SQL queries on a cluster is to connect to the SQL shell.

To connect to the SQL shell, run the `hz-cli sql` command of your member's built-in CLI.

[tabs]
====
Binary::
+
--
.Mac and Linux
[source,shell]
----
bin/hz-cli sql
----

.Windows
[source,shell]
----
bin\hz-cli.bat sql
----
--
Docker::
+
--
Replace the `<cluster-name>` placeholder with the name of your cluster and the `<address>` placeholder with your member's IP address.

[source,shell,subs="attributes+"]
----
docker run --network hazelcast-network -it --rm hazelcast/hazelcast:{full-version} hz-cli --targets <cluster-name>@<address> sql
----
--
====

== Mappings

Before you can query data in SQL, you need to create a _mapping_ to the data source. Mappings store essential metadata about the source's data model, data access patterns, and serialization formats so that the SQL service can connect to the data source and query it.

Currently, you can create mappings for the following data sources:

- xref:mapping-to-maps.adoc[Hazelcast maps]
- xref:mapping-to-kafka.adoc[Kafka topics]
- xref:mapping-to-a-file-system.adoc[File systems]

== Case Sensitivity

Mapping names and field names are case-sensitive.

For example, you can access an `employee` map
as `employee` but not as `Employee`.

Keywords or built-in function names are case-insensitive.

== Permissions and Security
[.enterprise]*Enterprise*

If xref:security:enabling-jaas.adoc[security] is enabled, you can set xref:security:native-client-security.adoc[permissions] for the following:

- xref:security:native-client-security.adoc#connector-permission[Connectors] (mappings)
- Some xref:security:native-client-security.adoc#sql-permission[SQL statements]

NOTE: When you run a query, Hazelcast runs it as a job. As a result, clients with the `read` permission for jobs can see the SQL query text and the arguments. See xref:security:native-client-security.adoc#job-permission[Job Permissions].

== Supported Statements

Hazelcast supports a subset of standard ANSI SQL statements as well as some custom ones for creating jobs, mappings, and streaming queries.

For a list of supported statements, see xref:sql:sql-statements.adoc[].

== Limitations

SQL has the following limitations. We plan to remove these limitations in future releases.

- The only supported Hazelcast data structure is map.
+
You cannot query other data structures such as replicated maps.
- Although you can xref:create-index.adoc[create bitmap indexes] in SQL, SQL queries do not leverage those indexes to improve query performance.
- You cannot join results from two streaming sources.
+
See xref:sql:select.adoc#join-tables[Join Tables].
- You cannot run SQL queries on lite members. This limitation will be removed in future releases.
- You cannot xref:storage:persistence.adoc[persist] SQL metadata on disk. This means that when a cluster restarts, it does not retain any SQL mappings or views that you have created.

== SQL Jobs

When a SQL statement is submitted for execution, the SQL service parses and
optimizes it. The result is an execution plan in the form of a job that
is cached and reused by subsequent executions of the same statement.

For details about how Hazelcast models and executes jobs, see xref:architecture:distributed-computing.adoc[].

== Next Steps

- xref:get-started-sql.adoc[].
- xref:learn-sql.adoc[].
- xref:get-started-sql-files.adoc[].

Explore the xref:sql:select.adoc[SQL reference docs].
