= Troubleshooting SQL
:description: This topic provides solutions to some common errors in SQL queries.
:toclevels: 3

{description}

== Mapping Errors

This section provides troubleshooting for the `CREATE MAPPING` statement.

=== Reading Parquet files is not supported in local filesystem mode

You cannot create mappings to local files in the parquet format.

To read from local files in the parquet format, you can use the Java link:https://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/jet/pipeline/file/FileSourceBuilder.html[`FileSourceBuilder` API] with the `useHadoopforLocalFiles` method. See the xref:integrate:file-connector.adoc#usehadoopforlocalfiles[unified file connector documentation] for examples.

=== Could not find ReadFileFnProvider

Hazelcast cannot read the file format that you're trying to map to. This error could be thrown because you are using the slim distribution of Hazelcast Platform, which doesn't come with the ability to read the file format by default.

Use the xref:getting-started:editions.adoc[full distribution] of Hazelcast Platform or find the missing module and add it to your cluster members' classpaths.

=== No suitable FileSourceFactory found

Hazelcast cannot read from the specified file system.

To read from some file systems, you must add additional modules to your cluster members' classpaths. See xref:sql:mapping-to-a-file-system.adoc#supported-file-systems[Supported file systems].

=== java.net.UnknownHostException: path

Your mapping contains an invalid URL.

Make sure that all your URLs are resolvable.

== JSON Errors

This section provides troubleshooting for using JSON in SQL.

=== JSON_QUERY evaluated to multiple values

The JsonPath is matching multiple values, which results in invalid JSON.

If the JsonPath expression can match multiple values in some edge cases, add a wrapper, such as the xref:sql:functions-and-operators.adoc#json_query[`WITH CONDITIONAL ARRAY WRAPPER`] clause, to wrap the matches in an array.

=== jsonpath.InvalidPathException

The JsonPath in your query is invalid.

Check the xref:working-with-json.adoc#jsonpath-syntax[supported JsonPath syntax].

== Out Of Memory Errors

If you find that your queries lead to out of memory exceptions (OOME), consider decreasing the value of the Jet engine's xref:configuration:jet-configuration.adoc#list-of-configuration-options[maxProcessorAccumulatedRecords option], or reduce the number of concurrently running queries.