= Troubleshooting SQL
:description: This topic provides solutions to common errors in SQL queries.

{description}

== JSON_QUERY evaluated to multiple values

If you see this error, the JsonPath is matching multiple values, which results in invalid JSON. If you expect multiple values to be returned from the JsonPath expression, you should add a wrapper, such as the `WITH CONDITIONAL ARRAY WRAPPER` clause, to wrap the matches in an array.

See the xref:sql:functions-and-operators.adoc#json_query[`JSON_QUERY` reference].

== jsonpath.InvalidPathException

If you see this error, the JsonPath in your query is invalid.

Check the xref:working-with-json.adoc#jsonpath-syntax[supported JsonPath syntax].

== Out Of Memory Errors

If you find that your queries lead to out of memory exceptions (OOME), consider decreasing the value of the Jet engine's xref:configuration:jet-configuration.adoc#list-of-configuration-options[maxProcessorAccumulatedRecords option], or reduce the number of concurrently running queries.