= Working with JSON Data in SQL
:description: In Hazelcast, the SQL service supports ways of working with JSON data: `json-flat`, which does not allow you to query nested keys/values and `json`, which supports nested queries and JSON functions.

JSON is a semi-structured data type used for holding JSON (JavaScript Object Notation) data. In Hazelcast, the SQL service supports the following ways of working with JSON data:

- `json`: Maps JSON data to a single column of `JSON` type where you can use <<jsonpath, JsonPath>> syntax to query and filter it, including nested levels.
- `json-flat`: Maps JSON top-level fields to columns with non-JSON types where you can query only top-level keys.

== JSON

The `JSON` data type comes with full support for querying JSON in maps and Kafka topics.

NOTE: The JSON data type is currently not supported for xref:mapping-to-a-file-system.adoc[file mappings]. Files support the <<json-flat, `JSON-FLAT` data type>>.

=== Mapping to the `JSON` Type

You can map JSON data to a single column, by creating a mapping to one of the following data sources:

- xref:mapping-to-maps.adoc[Map]
- xref:mapping-to-kafka.adoc[Kafka]

For example, to map the JSON data type to a value in a map:

```sql
CREATE MAPPING countries
TYPE IMap OPTIONS('keyFormat'='int', 'valueFormat'='json');
```

This statement creates a mapping to a map with two columns where the key is an `INTEGER` and the value is `JSON`:

- `__key`: A key as an integer
- `this`: JSON data

=== Creating JSON Data

You can create new JSON data using a JSON-formatted string, or using one of the following JSON functions:

- xref:functions-and-operators.adoc#json-functions[JSON_ARRAY]
- xref:functions-and-operators.adoc#json-functions[JSON_OBJECT]

.Example JSON-formatted string
====
```json
'{"country": "United Kingdom", "cities": [{"city": "London"}]}'
```
====


.Example JSON function
====
```sql
INSERT INTO countries VALUES (1, JSON_OBJECT('country':'United Kingdom', 'cities': JSON_ARRAY(JSON_OBJECT('city':'London'))))
```
====

=== Querying JSON

To query and/or filter JSON, use the <<jsonpath, JsonPath>> syntax in the following JSON functions:

- xref:functions-and-operators.adoc#json-functions[JSON_QUERY]
- xref:functions-and-operators.adoc#json-functions[JSON_VALUE]

`JSON_QUERY` returns a JSON value, while `JSON_VALUE` returns non-JSON value, a `VARCHAR` by default. If you use the functions to extract a string field, `JSON_VALUE` will return the value directly, while `JSON_QUERY` will return it in quotes and with special characters escaped, i.e. JSON-formatted. `JSON_VALUE` can't be used to extract arrays or objects.

JsonPath is a query language for JSON. The JsonPath format starts with a dollar (`$`) operator that refers to the root level of the JSON. From there, you can add other operators to traverse the data and filter the results.

For example, consider the following JSON data:

```json
{
  "countries": [
    {
      "country":"United Kingdom",
      "cities": [{"city": "London"}]
    },
    {
      "country":"France",
      "cities": [{"city": "Lyon"}]
    },
    {
      "country":"Turkey",
      "cities": [{"city": "Istanbul"}]
    }
  ]
}
```

The following examples show you how to use JsonPath to query this document.

[cols="50%a,50%a"]
|===
|JsonPath|Result

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$')
   FROM countries;
----
|
Returns the whole document.
[source,json]
----
{"countries":[{"country":"United Kingdom","cities":[{"city":"London"}]},{"country":"France","cities":[{"city":"Lyon"}]},{"country":"Turkey","cities":[{"city":"Istanbul"}]}]}
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$..cities' WITH WRAPPER)
   FROM countries;
----
|
Returns the `cities` property at any depth.
[source,json]
----
[{"city": "London"},{"city": "Lyon"},{"city": "Istanbul"}]
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries.*' WITH WRAPPER)
   FROM countries;
----
|
Returns all fields of `countries` in an array. `countries` property must be in the root object.
[source,json]
----
["United Kingdom",{"city": "London"},"France",{"city": "Lyon"},"Turkey",{"city": "Istanbul"}]
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries..city' WITH WRAPPER)
   FROM countries;
----
|
From `countries` property in the root document, find `city` property anywhere under it. Return as array.
[source,json]
----
["London","Lyon","Istanbul"]
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries[2]')
   FROM countries;
----
|
Return the 3rd element of `countries` array.
[source,json]
----
{"country":"Turkey","cities":[{"city":"Istanbul"}]}
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries[0,2]' WITH WRAPPER)
   FROM countries;
----
|
Returns 1st and 3rd elements of `countries` array.
[source,json]
----
[{"country":"United Kingdom","cities":[{"city":"London"}]},{"country":"Turkey","cities":[{"city":"Istanbul"}]}]]
----
|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries[0 to 2]' WITH WRAPPER)
   FROM countries;
----
|
Returns 1st to 3rd elements of `countries` array (range end is inclusive).
[source,json]
----
[{"country":"United Kingdom","cities":[{"city":"London"}]},{"country":"France","cities":[{"city":"Lyon"}]},{"country":"Turkey","cities":[{"city":"Istanbul"}]}]
----

|
### this one doesn't work ###

[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries[*]?(@..city=="London"')
   FROM countries;
----
|
From `countries` array returns those elements, which have `city` property at any depth equal to `London`.
[source,json]
----
{"country":"United Kingdom","cities":[{"city":"London"}]}
----

|===

If the JsonPath does not match a value, `NULL` is returned.

[[jsonpath-synax]]
=== Supported JsonPath Operators

These are the supported operators from the JsonPath standard.

[cols="20%m,80%a"]
|===
|Operator|	Description

|$
|Root

|*
|Wildcard

|.<name>
|Child property

|..
|Child property at any level deeper

|['<name>' (, '<name>')]
|List of child properties

|[<number> (, <number>)]
|List of array indexes

|[<number> *to* <number>]
|Array range

|?(<expression>)
|Filter expression

|@
|Current node in filter expression
|===

== JSON-FLAT

The `json-flat` format comes with partial support for querying JSON in maps, Kafka topics, and files.

=== Mapping to the `JSON-FLAT` Type

You can map JSON data to a multiple columns, by creating a mapping to one of the following data sources:

- xref:mapping-to-maps.adoc[Map]
- xref:mapping-to-kafka.adoc[Kafka]
- xref:mapping-to-a-file-system.adoc[File]

For example, consider the following JSON data:

```json
{
  "countries": "United Kingdom",
  "cities": "London"
}
```

To map the JSON data using the `json-flat` format in a map, you need to provide the JSON keys as column names:

```sql
CREATE MAPPING cities (
__key INT,
countries VARCHAR,
cities VARCHAR)
type IMap OPTIONS('keyFormat'='int', 'valueFormat'='json-flat');
```

This statement creates a mapping to a map that expects three columns:

- `__key`: A key as an integer
- `countries`: A string
- `cities`: A string

```SQL
INSERT INTO cities VALUES
(1, 'United Kingdom','London');
```

=== Querying `json-flat`

To query the JSON values, select the column names.

```sql
SELECT cities AS City, countries AS Country
FROM cities;
```

```
+--------------------+--------------------+
|City                |Country             |
+--------------------+--------------------+
|London              |United Kingdom      |
+--------------------+--------------------+
```

== JSON Type Conversion

SQL integer and floating-point types are converted into JSON
numbers. The `DECIMAL` type and all temporal types are converted
into JSON strings.

[cols="m,m"]
|===
| JSON type | SQL Type

|BOOLEAN
|BOOLEAN

|NUMBER
|DOUBLE

INTEGER

REAL

BIGINT

SMALLINT

TINYINT

|STRING
|VARCHAR

DECIMAL

DATE

TIME

TIMESTAMP

TIMESTAMP WITH TIME ZONE

OBJECT

|===