= Working with JSON Data in SQL
:description: In Hazelcast, the SQL service supports two data types for JSON data: JSON-FLAT, which does not allow you to query nested keys/values and JSON, which supports nested queries and JSON functions.
:page-beta: true

JSON is a semi-structured data type used for holding JSON (JavaScript Object Notation) data. In Hazelcast, the SQL service supports the following data types for JSON data:

- `JSON`: Allows you to map JSON data to a single column and use <<jsonpath, JsonPath>> syntax to query and filter it, including nested levels.
- `JSON-FLAT`: Allows you to map JSON data to columns and query only top-level keys/values.

== JSON

The `JSON` data type comes with full support for querying JSON in maps and Kafka topics.

NOTE: The JSON data type is not supported for xref:mapping-to-files.adoc[file mappings]. Files support the <<json-flat, `JSON-FLAT` data type>>.

=== Mapping to the `JSON` Type

You can map JSON data to a single column, by creating a mapping to one of the following data sources:

- xref:mapping-to-maps.adoc[Map]
- xref:mapping-to-kafka.adoc[Kafka]

For example, to map the JSON data type to a value in a map:

```sql
CREATE MAPPING countries
type IMap OPTIONS('keyFormat'='int', 'valueFormat'='json');
```

This statement creates a mapping to a map with two columns where the key is an `INTEGER` and the value is `JSON`:

- `__key`: A key as an integer
- `this`: JSON data

=== Adding JSON to a Table

You can add new JSON data to a table, using a JSON-formatted string, a `HazelcastJsonValue` object, or one of the following JSON functions:

- xref:functions-and-operators.adoc#json-functions[JSON_ARRAY]
- xref:functions-and-operators.adoc#json-functions[JSON_OBJECT]

.Example JSON-formatted string
[%collapsible]
====
```json
'{"country": "United Kingdom", "cities": [{"city": "London"}]}'
```
====

.Example HazelcastJsonValue
[%collapsible]
====
```java
hzInstance.getSql().execute("INSERT INTO countries VALUES (?, ?)", 1L, new HazelcastJsonValue(someJsonStringWithCountries));
```
====

.Example JSON function
[%collapsible]
====
```sql
INSERT INTO countries VALUES (1, JSON_OBJECT('country':'United Kingdom', 'cities': JSON_ARRAY(JSON_OBJECT('city':'London'))))
```
====

=== Querying JSON

To query and/or filter JSON, use the <<jsonpath, JsonPath>> syntax in the following JSON functions:

- xref:functions-and-operators.adoc#json-functions[JSON_QUERY]
- xref:functions-and-operators.adoc#json-functions[JSON_VALUE]

JsonPath is a query language for JSON. The JsonPath format starts with a dollar (`$`) operator that refers to the root level of the JSON. From there, you can add other operators to traverse the data and filter the results.

For example, consider the following JSON data:

```json
"countries": [
  {
  "country":"United Kingdom",
  "cities": [{"city": "London"}]
  },
  {
  "country":"France",
  "cities": [{"city": "Lyon"}]
  },
  {
  "country":"Turkey",
  "cities": [{"city": "Istanbul"}]
  }
]
```

The following examples show you how to use JsonPath to query this dataset.

[cols="20%a,80%a"]
|===
|JsonPath|Result

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$')
   FROM countries;
----
|
[source,json]
----
{"countries":[{"country":"United Kingdom","cities":[{"city":"London"}]},{"country":"France","cities":[{"city":"Lyon"}]},{"country":"Turkey","cities":[{"city":"Istanbul"}]}]}
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$..cities' WITH WRAPPER)
   FROM countries;
----
|
[source,json]
----
[{"city": "London"},{"city": "Lyon"},{"city": "Istanbul"}]
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries.*' WITH WRAPPER)
   FROM countries;
----
|
[source,json]
----
["United Kingdom",{"city": "London"},"France",{"city": "Lyon"},"Turkey",{"city": "Istanbul"}]
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries..cities' WITH WRAPPER)
   FROM countries;
----
|
[source,json]
----
["London","Lyon","Istanbul"]
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries[2]')
   FROM countries;
----
|
[source,json]
----
{"country":"Turkey","cities":[{"city":"Istanbul"}]}
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries[0,1]')
   FROM countries;
----
|
[source,json]
----
[{"country":"United Kingdom","cities":[{"city":"London"}]},{"country":"France","cities":[{"city":"Lyon"}]}]
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries[*]?(@..city=="United Kingdom"')
   FROM countries;
----
|
[source,json]
----
[{"country":"United Kingdom","cities":[{"city":"London"}]}]
----

|===

If the JsonPath does not match a value, `NULL` is returned.

[[jsonpath-synax]]
=== Supported JsonPath Operators

These are the supported operators from the JsonPath standard.

[cols="20%m,80%a"]
|===
|Operator|	Description

|$
|Root

|@
|Current node

|*
|Wildcard

|..
|Recursive descent

|.<name>
|Child

|['<name>' (, '<name>')]
|Children

|[<number> (, <number>)]
|Indexes

|?(<expression>)
|Filter expression
|===

== JSON-FLAT

The `JSON-FLAT` data type comes with partial support for querying JSON in maps, Kafka topics, and files.

=== Mapping to the `JSON-FLAT` Type

You can map JSON data to a multiple columns, by creating a mapping to one of the following data sources:

- xref:mapping-to-maps.adoc[Map]
- xref:mapping-to-kafka.adoc[Kafka]
- xref:mapping-to-files.adoc[File]

For example, consider the following JSON data:

```json
"countries": "United Kingdom",
"cities": "London"
```

To map the `JSON-FLAT` data to a value in a map, you need to provide the JSON keys as column names:

```sql
CREATE MAPPING cities (
__key INT,
countries VARCHAR,
cities VARCHAR)
type IMap OPTIONS('keyFormat'='int', 'valueFormat'='json-flat');
```

This statement creates a mapping to a map that expects three columns:

- `__key`: A key as an integer
- `countries`: A string
- `cities`: A string

```SQL
INSERT INTO cities VALUES
(1, 'United Kingdom','London');
```

=== Querying `JSON-FLAT`

To query the JSON values, select the column names.

```sql
SELECT cities AS City, countries AS Country
FROM cities;
```

```
+--------------------+--------------------+
|City                |Country             |
+--------------------+--------------------+
|London              |United Kingdom      |
+--------------------+--------------------+
```

== JSON Type Conversion

SQL integer and floating-point types are converted into JSON
numbers. The `DECIMAL` type and all temporal types are converted
into JSON strings.

[cols="m,m"]
|===
| JSON type | SQL Type

|BOOLEAN
|BOOLEAN

|NUMBER
|DOUBLE

INTEGER

REAL

BIGINT

SMALLINT

TINYINT

|STRING
|VARCHAR

DECIMAL

DATE

TIME

TIMESTAMP

TIMESTAMP WITH TIME ZONE



a|All other types
| OBJECT

|===