= Working with JSON Data in SQL
:description: In Hazelcast, the SQL service supports two data types for JSON data: JSON-FLAT, which does not allow you to query nested keys/values and JSON, which supports nested queries and JSON functions.
:page-beta: true

JSON is a semi-structured data type used for holding JSON (JavaScript Object Notation) data. In Hazelcast, the SQL service supports the following data types for JSON data:

- `JSON`: Allows you to map JSON data to a single column and use <<jsonpath, JsonPath>> syntax to query and filter it, including nested levels.
- `JSON-FLAT`: Allows you to map JSON data to columns and query only top-level keys/values.

== JSON

The `JSON` data type comes with full support for querying JSON in maps, Kafka topics, and files.

To query JSON data, you can use the following built-in functions that allow you read JSON values from a column:

- xref:functions-and-operators.adoc#json-functions[JSON_QUERY]
- xref:functions-and-operators.adoc#json-functions[JSON_VALUE]
- xref:functions-and-operators.adoc#json-functions[JSON_ARRAY]
- xref:functions-and-operators.adoc#json-functions[JSON_OBJECT]

With the `JSON` data type, you can map JSON data to a single column, using the xref:create-mapping.adoc[`CREATE MAPPING` statement].

=== Context

For example, consider the following JSON data:

```json
"countries": [
  {
  "country":"United Kingdom",
  "cities": [{"city": "London"}]
  },
  {
  "country":"France",
  "cities": [{"city": "Lyon"}]
  },
  {
  "country":"Turkey",
  "cities": [{"city": "Istanbul"}]
  }
]
```

To map the JSON data type to a value in a map:

```sql
CREATE MAPPING countries
type IMap OPTIONS('keyFormat'='int', 'valueFormat'='json');
```

This statement creates a mapping to a map with two columns where the key is an `INTEGER` and the value is `JSON`:

- `__key`: A key as an integer
- `this`: JSON data

The JSON data can be a JSON parameter, a JSON-formatted string, or a `HazelcastJsonValue` object.

.Example JSON-formatted string
```json
'{"country": "United Kingdom", "cities": [{"city": "London"}]}'
```

.Example JSON parameter
```sql
INSERT INTO countries VALUES (1, JSON_OBJECT('country':'United Kingdom', 'cities': JSON_ARRAY(JSON_OBJECT('city':'London'))))
```

.Example HazelcastJsonValue
```java
hzInstance.getSql().execute("INSERT INTO countries VALUES (?, ?)", 1L, new HazelcastJsonValue(someJsonStringWithCountries));
```

To query and/or filter JSON, use the <<jsonpath, JsonPath>> syntax in the built-in JSON functions.

=== JsonPath

JsonPath is a query language for JSON.

Some JSON functions require JsonPath as a  parameter, which identifies the values that you want to query.

The JsonPath format starts with a dollar (`$`) operator that refers to the root level of the JSON. From there, you can add other operators to traverse the data and filter the results.

[cols="20%a,80%a"]
|===
|JsonPath|Result

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$')
   FROM countries;
----
|
[source,json]
----
{"countries":[{"country":"United Kingdom","cities":[{"city":"London"}]},{"country":"France","cities":[{"city":"Lyon"}]},{"country":"Turkey","cities":[{"city":"Istanbul"}]}]}
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$..cities' WITH WRAPPER)
   FROM countries;
----
|
[source,json]
----
[{"city": "London"},{"city": "Lyon"},{"city": "Istanbul"}]
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries.*' WITH WRAPPER)
   FROM countries;
----
|
[source,json]
----
["United Kingdom",{"city": "London"},"France",{"city": "Lyon"},"Turkey",{"city": "Istanbul"}]
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries..cities' WITH WRAPPER)
   FROM countries;
----
|
[source,json]
----
["London","Lyon","Istanbul"]
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries[2]')
   FROM countries;
----
|
[source,json]
----
{"country":"Turkey","cities":[{"city":"Istanbul"}]}
----

|
[source,sql]
----
SELECT
   JSON_QUERY(this, '$.countries[0,1]')
   FROM countries;
----
|
[source,json]
----
[{"country":"United Kingdom","cities":[{"city":"London"}]},{"country":"France","cities":[{"city":"Lyon"}]}]
----

|===

If the JsonPath does not match a value, `NULL` is returned.

If the JsonPath is invalid, the following exception is thrown: `com.hazelcast.com.jayway.jsonpath.InvalidPathException`.

=== Supported JsonPath Operators

These are the supported operators from the JsonPath standard.

[cols="20%m,80%a"]
|===
|Operator|	Description

|$
|Root

|@
|Current node

|*
|Wildcard

|..
|Recursive descent

|.<name>
|Child

|['<name>' (, '<name>')]
|Children

|[<number> (, <number>)]
|Indexes

|?(<expression>)
|Filter expression
|===

== JSON-FLAT

The `JSON-FLAT` data type comes with partial support for querying JSON.

This data type allows you to map JSON data to columns and only query top-level keys/values.

For example, consider the following JSON data:

```json
"countries": "United Kingdom",
"cities": "London"
```

To map the JSON data to a value in a map:

```sql
CREATE MAPPING cities (
__key INT,
countries VARCHAR,
cities VARCHAR)
type IMap OPTIONS('keyFormat'='int', 'valueFormat'='json-flat');
```

This statement creates a mapping to a map that expects three columns:

- `__key`: A key as an integer
- `countries`: A string
- `cities`: A string

```SQL
INSERT INTO cities VALUES
(1, 'United Kingdom','London');
```

To query the JSON value, select the column names.

```sql
SELECT cities AS City, countries AS Country
FROM cities;
```

```
+--------------------+--------------------+
|City                |Country             |
+--------------------+--------------------+
|London              |United Kingdom      |
+--------------------+--------------------+
```