= Network Partitioning

== Split-Brain Syndrome

In general, network partitioning is a network failure that causes
the members to split into multiple groups such that
a member in a group cannot communicate with members in other groups.
In a partition scenario, all sides of the original cluster operate independently
assuming members in other sides are failed. Network partitioning is also called as _Split-Brain Syndrome_.

Even though this communication failure is called as _network partitioning_,
in practice a process or an entire OS that's suspending/pausing very long can cause
communication interruptions. If these interruptions take long enough time to
assume that the other side is crashed, the cluster splits into
multiple partitions and they start operating independently.
That's why any communication failure/interruption long enough can be
classified as network partitioning.

Moreover, communication failures don't have to be symmetrical.
A network failure can interrupt only one side of the channel or
a suspended process/member may not even observe the rest as crashed.
That kind of network partitioning can be called as _partial network partitioning_.
See xref:partial-network-partitions.adoc[Partial Network Partitions section] for more info.