= Get Started with SQL Queries
:description: In this tutorial, you learn the basics of querying in SQL by using the interactive SQL shell on your Hazelcast member to query a CSV file.

{description}

== Before You Begin

To complete this tutorial, you need the following:

[cols="1a,1a"]
|===
|Prerequisites|Useful resources

|A Hazelcast cluster and an instance of Management Center running on your local network 
|xref:getting-started:get-started-binary.adoc[Start a Local Cluster]
|===

[.interactive-button]
xref:interactive-sql.adoc[Try the interactive example,window=_blank]

== Query Static Data

Using SQL, you can load static data from sources such as files and maps so you can tranform and analyze it.

In this step, you create a static file, load that data into Hazelcast, and query it from an SQL shell.

. Create a file named `likes.csv`.

. Add the following data to your file.
+
[source,shell]
----
id,name,likes
1,Jerry,13
2,Greg,108
3,Mary,73
4,Jerry,88
----
+
This example file contains a record of the number of likes each person has.

. Connect to the SQL shell on your cluster member.
+
[tabs]
====
Binary::
+
--
.Mac and Linux
[source,shell]
----
bin/hazelcast sql
----

.Windows
[source,shell]
----
bin/hazelcast.bat sql
----
--
Docker::
+
--
Replace the `$LOCAL_IP` placeholder with your member's local IP address.

[source,shell,subs="attributes+"]
----
docker run --network hazelcast-network -it --rm hazelcast/hazelcast:{page-component-version} hazelcast --targets hello-world@$LOCAL_IP sql
----

The `--targets` parameter tells the SQL shell to connect to the member at the given IP address in a cluster called `hello-world`.

TIP: Make sure you mount the `likes.csv` file on the container that's running your member.
--
====

. Use a xref:sql:create-mapping.adoc[`CREATE MAPPING` statement] to give Hazelcast access to the data in the `likes.csv` file.
+
[source,sql]
----
CREATE MAPPING csv_likes (id INT, name VARCHAR, likes INT)
TYPE File
OPTIONS ('format'='csv',
    'path'='/absolute/path/to/current/folder', 'glob'='likes.csv');
----
+
TIP: Make sure you replace the `path` option with the absolute path to your `.csv` file.
+
NOTE: The SQL service does not have a native storage system. Instead it uses external mappings to access various resources as if they were tables.

. Use a xref:sql:select.adoc[`SELECT` statement] to query all the data in the `likes.csv` file.
+
[source,sql]
----
SELECT * FROM csv_likes;
----
+
You should see the following:
+
[source,shell]
----
+------------+--------------------+------------+
|          id|name                |       likes|
+------------+--------------------+------------+
|           1|Jerry               |          13|
|           2|Greg                |         108|
|           3|Mary                |          73|
|           4|Jerry               |          88|
+------------+--------------------+------------+
----

. Use the `SUM()` function to aggregate the total number of likes for each person and group the results by name.
+
[source,sql]
----
SELECT name, sum(likes) AS total_likes FROM csv_likes GROUP BY name;
----
+  
You should see the following:
+
```
+--------------------+--------------------+
|name                |         total_likes|
+--------------------+--------------------+
|Greg                |                 108|
|Jerry               |                 101|
|Mary                |                  73|
+--------------------+--------------------+
```
+
The results do not include a rows for each Jerry because the `GROUP BY` statement groups the results by name.

. Create a mapping to a new table called `dislikes`.
+
[source,sql]
----
CREATE MAPPING dislikes (
name VARCHAR,
dislikes INT
) TYPE IMap OPTIONS ('keyFormat'='int', 'valueFormat'='json');
----
+
This table is mapped to a distributed map in Hazelcast where the key is an integer and the value is an object that's serialized to JSON.

. Use `SINK INTO` statements to add some data to the map.
+
[source,sql]
----
SINK INTO dislikes VALUES(1, 'Greg', 1);
SINK INTO dislikes VALUES(2, 'Jerry', 0);
SINK INTO dislikes VALUES(3, 'Mary', 5);
SINK INTO dislikes VALUES(4, 'Jerry', 0);
----

. Use the xref:sql:select.adoc#join-tables[`JOIN` clause] to merge results from the `likes` and `dislikes` tables so you can see who has the most likes and dislikes.
+
[source,sql]
---- 
SELECT csv_likes.name, csv_likes.likes, dislikes.dislikes
FROM csv_likes
JOIN dislikes
ON csv_likes.id = dislikes.__key;
----
+
```
+--------------------+------------+------------+
|name                |       likes|    dislikes|
+--------------------+------------+------------+
|Jerry               |          13|           0|
|Greg                |         108|           5|
|Mary                |          73|           5|
|Jerry               |          88|          20|
+--------------------+------------+------------+
```

. Use the `ORDER BY` clause to order the results by name and use the `LIMIT` clause to limit them so that only the first two are displayed.

[source,sql]
----
SELECT csv_likes.name, csv_likes.likes, dislikes.dislikes
FROM csv_likes
JOIN dislikes
ON csv_likes.id = dislikes.__key
ORDER BY csv_likes.name
LIMIT 2;
----

== Next Steps

Learn how to xref:querying-maps-sql.adoc[query maps with SQL].

See more examples of the xref:sql:select.adoc[`SELECT` statement].