= Running Distributed Queries
:description: Explore the tools that Hazelcast offers for running distributed queries.
:page-aliases: distributed-query.adoc

{description}

== What is a Distributed Query?

In a distributed system such as Hazelcast, data is partitioned across different members in the cluster. As a result, to query that data you have two options:

. Request all data from members and iterate over it locally until you find what you're looking for.
. Build a distributed query that each member can run so that you receive only the data you want.

Distributed queries allow you to request filtered data from members or external data sources without having to receive it all and iterate over it locally.

== Available Tools

Hazelcast offers the following tools for running distributed queries, depending on your use case:

- xref:sql-overview.adoc[SQL]: Use SQL syntax to query your cluster for data in map entries or query external systems such as Apache Kafka.

- xref:predicate-overview.adoc[Predicates API]: Use a client API to query your cluster for data in map entries. 

[cols="h,a,a"]
.Comparison of SQL and the Predicates API
|===
| |SQL|Predicates API

|Can query data in external sources
|Yes
|No

|Can query nested object fields
|No
|Yes

|Can query JSON data in map entries
|Yes
|Yes

|Supported Hazelcast clients
|
Java

Node.js

Python


|All clients
|===

== Related Resources

To learn more about SQL in Hazelcast, see the following resources:

- xref:sql-overview.adoc[]
- xref:get-started-sql.adoc[]

To learn more about the Predicates API, see the following resources:

- xref:predicate-overview.adoc[]
- xref:querying-maps-predicates.adoc[]


