= Cluster and Member States
[[managing-cluster-and-member-states]]
:description: By changing the state of a cluster, you can grant or restrict cluster operations such as migrations as well as change the behavior of those operations.

{description}

== Changing a Cluster's State

To change a cluster's state, you can use the https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/cluster/Cluster.html[`changeClusterState()`method] or use xref:{page-latest-supported-mc}@management-center:monitor-imdg:cluster-administration.adoc#cluster-state[Management Center].

NOTE: You cannot change a cluster's state to anything other than `ACTIVE` when members are moving data among each other.

The following snippet from the `Cluster` interface shows
the methods used to manage your cluster's states.

[source,java]
----
public interface Cluster {
    ClusterState getClusterState();
    void changeClusterState(ClusterState newState);
    void changeClusterState(ClusterState newState, TransactionOptions transactionOptions);
    void shutdown();
    void shutdown(TransactionOptions transactionOptions);
}
----

== Cluster States

By default, all clusters are in an `ACTIVE` state. In this state, the cluster operates without restrictions.

In all other states, the cluster *cannot move data among other members* such as in the following circumstances:

- Repartitioning data in the cluster
- Creating backup replicas of partitions
- Running Jobs that use partitioned data

As a result, you cannot change a cluster's state to anything other than `ACTIVE` when members are moving data among each other.

Where cluster states differ is in what other restrictions are applied to the cluster.

.Differences among cluster states
[cols="1m,1a,3a,2a"]
|===
|State|New members can join|Restrictions|Use case

|ACTIVE
|Yes ✅ 
|None
|Normal cluster operation

|NO_MIGRATION
|Yes ✅ 	
|Data cannot be moved among cluster members.
|Adding multiple new members to the cluster without triggering repartitioning after each member joins.

|FROZEN
|No ❌
|
Data cannot be moved among cluster members.

Backup partitions cannot be promoted to primary. If a member leaves the cluster, the partitions owned by that member are unavailable until it rejoins or the cluster is put back into an `ACTIVE` state.
|Performing maintenance on a cluster without triggering repartitioning.

|PASSIVE
|No ❌
|
Data cannot be moved among cluster members.

The cluster *allows only the following*:

- Replication operations (keeping backups partitions in sync with the primary partitions)
- Read-only operations such as `map.get()` and `cache.get()` methods
- Cluster heartbeat tasks
|Used internally during graceful cluster-wide shutdowns.

|IN_TRANSITION
|No ❌
|Repartitioning and replication tasks are paused until the state is changed.
|Used internally as a temporary state.

NOTE: When an error is thrown during a state transition, that error is propagated immediately. Hazelcast does not try to transition the cluster state again.

|===

== Member States

Individual members can be in the following states:

* `ACTIVE`: Members are in this state when the state of a cluster is `ACTIVE` or `FROZEN`.
* `PASSIVE`: Members transition to this state in the following circumstances:
** During a graceful shutdown. When the graceful shutdown process is completed, the member's state changes to `SHUT_DOWN`.
** When the cluster's state is manually changed to `PASSIVE`.
* `SHUT_DOWN`: Members transition to this state when they are shut down. Members in this state reject all operations and invocations and cannot be restarted.