= Dynamic Configuration using the REST API
:description: This tutorial introduces you to dynamic configuration via the REST API

:page-enterprise: true

{description}

== Before You Begin

To complete this tutorial, you need the following:

[cols="1a,1a"]
|===
|Prerequisites|Useful resources

|Make sure you've already completed either the Docker or Java "Getting Started" guides
|xref:#TODO()

|===

== Add a Data Structure Configuration Dynamically

== Step 1. Add the new configuration using the `/hazelcast/rest/api/v1/config/update` endpoint

To update the configuration, send a POST request including the new data structure config in the request body as YAML/XML.

[tabs]
====
cURL with XML::
+
--
[source,shell]
----
curl -X POST \
'http://localhost:8443/hazelcast/rest/api/v1/cluster/config/update' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer '"$JWT_TOKEN"'' \ <1>
-d '<hazelcast xmlns="http://www.hazelcast.com/schema/config">
    <map name="my-map">
        <in-memory-format>BINARY</in-memory-format>
        <statistics-enabled>true</statistics-enabled>
        <backup-count>2</backup-count>
    </map>
</hazelcast>'
----
--

cURL with YAML::
+
[source,shell]
----
curl -X 'POST' \
  'http://localhost:8443/hazelcast/rest/api/v1/cluster/config/update' \
  -H 'Authorization: Bearer '"$JWT_TOKEN"'' \ <1>
  -H 'Content-Type: application/json' \
  -d 'hazelcast:
  map:
    my-map:
      in-memory-format: BINARY
      statistics-enabled: true
      backup-count: 2'
----

Using Swagger UI::
+
- Open the Swagger UI at http://localhost:8443/swagger-ui/index.html.
- Navigate to the `/cluster/config/update` endpoint under the *Cluster Controller* section.
- *Note:* Make sure that you have saved the authorization token from the http://todo.when.ready.provide.link[previous steps]
- Click the `Try it out` button.
- Set the request body as follows (either YAML or XML can be used):
+
[source,yaml]
----
hazelcast:
  map:
    my-map:
      in-memory-format: BINARY
      statistics-enabled: true
      backup-count: 2
----
+
- Click the `Execute` button.
====
<1> Set the JWT_TOKEN as environment variable or replace it with you token directly in the command.

Here is the expected response body:
[source,json]
----
{
  "addedConfigs": [
    {
      "sectionName": "map",
      "configName": "my-map"
    }
  ],
  "ignoredConfigs": []
}
----

== Step 2. Create a Map with the New Configuration

Access the `/map/{mapName}/{key}` POST endpoint to create the map and put an entry:

[tabs]
====
Using cURL::
+
--
[source,shell]
----
curl -X 'POST' \
  'http://localhost:8443/hazelcast/rest/api/v1/map/my-map/1' \
  -H 'Authorization: Bearer '"$JWT_TOKEN"'' \
  -H 'Content-Type: text/plain' \
  -d 'my-value'
----
--

Using Swagger UI::
+
- Open the Swagger UI at http://localhost:8443/swagger-ui/index.html.
- Navigate to the `/map/{mapName}/{key}` POST endpoint under the *Data Controller* section.
- Click the `Try it out` button.
- Enter `my-map` and `1` in the 'mapName' and `key` fields respectively:
- Enter the value in the request body section
+
[source,txt]
----
my-value
----
- Click the `Execute` button.
====

This action will create the map named `my-map` which matches the dynamically added config from the previous step.

You can use https://docs.hazelcast.com/management-center/latest/data-structures/map[Management Center] to verify that the map was successfully created with the expected configuration properties.

=== Step 3 (Optional). Dynamically Add a New Map by Reloading the Configuration from Disk

Modify the declarative configuration file to add a new map config and reload it using the `/cluster/config/reload` endpoint. For this tutorial our config is located at `~/config`

[tabs]
====
Using cURL::
+
--
[source,shell]
----
curl -X 'POST' \
  'http://localhost:8443/hazelcast/rest/api/v1/cluster/config/reload' \
  -H 'Authorization: Bearer '"$JWT_TOKEN"''
----
--

Using Swagger UI::
+
- Open the Swagger UI at http://localhost:8443/swagger-ui/index.html.
- Navigate to the `/map/{mapName}/{key}` POST endpoint under the *Config Controller* section.
- Click the `Try it out` button.
- Click the `Execute` button
====

== Next Steps

If you're interested in learning more about the topics introduced in this tutorial, see: 

* xref:enterprise-rest-api.adoc#dynamic-configuration-update-rest-endpoint[REST Dynamic Configuration]
* xref:configuration:dynamic-config.adoc[Dynamic Configuration for Members]
