= Persistence Configuration Options
:description: To use Persistence, you must first enable it using the global configuration options. Then, you can choose to fine-tune the configuration as well as configure persistence for specific maps, JCache data structures, or all job snapshots.

To use Persistence, you must first enable it using the <<global-persistence-configuration, global options>>. Then, you can choose to fine-tune the configuration as well as configure persistence for <<data-structure-persistence-configuration, specific map or JCache data structures>> or all <<job-snapshot-configuration, job snapshots>>.

== Global Persistence Configuration

Use the following options to configure Persistence on your members.

=== `persistence.enabled`

Enables Persistence on the member.

Default: `false`

=== `persistence.base-dir`

The parent folder where persisted data
is stored.

Default: `persistence`

This folder is created automatically if it does not exist.

If more than one member shares this parent folder, each member stores its own unique folder inside it. This is especially useful for cloud
environments where the members generally use a shared filesystem.

When a member starts, it tries to acquire ownership of the
first available folder inside the parent folder. If the parent folder
is empty or if all folders are already acquired by other members, then it creates its own new folder.

=== `persistence.backup-dir`

The folder in which backup snapshots of data
(hot backups) are stored. See xref:backing-up-persistence.adoc[].

Default: ''

If this element is not defined,
hot backup is disabled. If a folder is defined which does not exist, it is created during
the first backup. To avoid clashing data on multiple backups, each backup has a unique
sequence ID which determines the name of the folder which contains all data for that backup.
This unique folder is created as a subfolder of the configured `backup-dir`.

=== `persistence.parallelism`

Number of I/O threads that are started concurrently for reading from and writing to files in the persistence store.

Default: `1`

This is a good default in most but not
all cases. You should measure the raw I/O throughput of your infrastructure and
test with different values of parallelism. In some cases such as dedicated
hardware, higher parallelism can yield more throughput. In other
cases, such as running on EC2, a higher parallelism can yield diminishing returns with more thread
scheduling, more contention on I/O, and less efficient garbage collection.

=== `persistence.validation-timeout-seconds`

Validation timeout for the Persistence process
when validating the cluster members expected to join and the partition table on the whole cluster.

=== `persistence.data-load-timeout-seconds`

Data load timeout for the Persistence process.
All members in the cluster should finish restoring their local data before this timeout.

=== `persistence.cluster-data-recovery-policy`

Specifies the data recovery policy that is
respected during the Persistence cluster start.

Default: `FULL_RECOVERY_ONLY`

Valid values are:

* `FULL_RECOVERY_ONLY`: Starts the cluster only when all expected members
are present and correct. Otherwise, it fails.
* `PARTIAL_RECOVERY_MOST_RECENT`: Starts the cluster with the members which have most up-to-date partition table and successfully restored their data. All other members leave the cluster and force start themselves. If no member restores its data successfully, cluster start fails.
* `PARTIAL_RECOVERY_MOST_COMPLETE`: Starts the cluster with the largest group of members which have the same partition table version and successfully restored their data. All other members leave the cluster and force start themselves. If no member restores its data successfully, cluster start fails.

=== `persistence.auto-remove-stale-data`

Enables a joining member to automatically remove its persistence store if the cluster's master member considers the peristed data to be stale. See xref:recover-single-member.adoc[].

Default: `false`

NOTE: A joining member that crashes while in an `ACTIVE` state will generally not consider its data stale. Instead, the member will reload its data from disk and then synchronize it with other cluster members as needed. Only in some exceptional circumstances will the master member consider the joining member's data stale.

=== `persistence.encryption-at-rest`

Enables encryption of data in the persistence store.
See xref:encryption-at-rest.adoc[] for more information.

Default: disabled

== Data Structure Persistence Configuration

Use the following options to configure Persistence for map and JCache data structures.

=== `persistence.enabled`

Enabled the
Persistence feature for the related data structure.

Default: `false`

=== `persistence.fsync`

Guarantees that data is persisted to the disk
device when a write operation returns successful response to the caller.

Default: `false`

By default, data is persisted to the disk device
eventually, instead of on every disk write. This generally provides a better performance.

=== `merkle-tree`

Allows restarting members to synchronize their persisted map or JCache data faster with the rest of the cluster.

Default: disabled

While this option is not unique to persistence (map Merkle trees are also used for WAN delta synchronization), we strongly recommended enabling it for each map or JCache data structure that you want to persist on disk.

See xref:recover-single-member.adoc#synchronizing-data-faster[Synchronizing Data Faster] for more information.

== Job Snapshot Configuration

Use the following options to configure Persistence for jobs.

=== `jet.instance.lossless-cluster-restart`

Whether to save job snapshot data to disk.

Default: `false`

For lossless restart to work the cluster must be xref:maintain-cluster:shutdown.adoc#graceful-shutdown[shut down gracefully].
When members are shutdown one by one in a rapid succession, Hazelcast triggers
an automatic rebalancing process where backup partitions are promoted
and new backups are created for each member. This may result in
out-of-memory errors or data loss.

Because data is saved locally on each member, all
members must be present after a restart for Hazelcast to be able to reload
the data.

=== Persistence Configuration Examples

The following are example configuration settings for a map instance, a JCache instance, and the Jet engine.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <persistence enabled="true">
      <base-dir>/mnt/persistence</base-dir>
      <backup-dir>/mnt/hot-backup</backup-dir>
      <validation-timeout-seconds>120</validation-timeout-seconds>
      <data-load-timeout-seconds>900</data-load-timeout-seconds>
      <cluster-data-recovery-policy>FULL_RECOVERY_ONLY</cluster-data-recovery-policy>
    </persistence>
    ...
    <map name="test-map">
      <merkle-tree enabled="true" >
        <depth>12</depth>
      </merkle-tree>
      <persistence enabled="true">
        <fsync>false</fsync>
      </persistence>
    </map>
    ...
    <cache name="test-cache">
      <merkle-tree enabled="true" >
        <depth>12</depth>
      </merkle-tree>
      <persistence enabled="true">
          <fsync>false</fsync>
      </persistence>
    </cache>
    ...
    <jet>
      <instance>
        <lossless-restart-enabled>true</lossless-restart-enabled>
      </instance>
    </jet>
    ...
</hazelcast>
----
--

YAML::
+
--
[source,yaml]
----
hazelcast:
  persistence:
    enabled: true
    base-dir: /mnt/persistence
    backup-dir: /mnt/hot-backup
    validation-timeout-seconds: 120
    data-load-timeout-seconds: 900
    cluster-data-recovery-policy: FULL_RECOVERY_ONLY
  map:
    test-map:
      merkle-tree:
        enabled: true
        depth: 12
      persistence:
        enabled: true
        fsync: false
  cache:
    test-cache:
      merkle-tree:
        enabled: true
        depth: 12
      persistence:
        enabled: true
        fsync: false
  jet:
    instance:
      lossless-restart-enabled: true
----
--
Java::
+
--
[source,java]
----
include::ROOT:example$/storage/SampleHotRestartConfiguration.java[tag=hrconf]
----
--
====