= Copying Persisted Data onto other Members
:description: When you persist data on disk, you may want to copy that data onto another cluster to perform testing, QA, or reproduce an issue on production data.
:page-enterprise: true

{description}

To copy persisted data onto other members, you have two options:

- xref:maintain-cluster:shutdown.adoc[Shut down the cluster] and copy the files onto a new cluster.
- xref:backing-up-persistence.adoc[Create backups of the files] and copy those onto the new cluster while the cluster is still running (recommended).

The server onto which you copy files (in the directory configured in the xref:configuring-persistence.adoc#base-dir[`base-dir` setting]) can have a different IP address and/or different number of CPU cores to the original server without affecting performance. This flexibility provides the following abilities:

* Replacing one or more faulty servers with the new ones easily without
touching remaining cluster.
* Using Persistence on the cloud environments easily. Sometimes cloud providers
do not preserve the IP addresses on restart or after shutdown. Also it is
possible to startup the whole cluster on a different set of machines.
* Copying production data to the test environment so that a more functional
test cluster can be set up.

