= Persistence Overview
:description: Allow individual members and whole clusters to recover faster by persisting map entries, JCache data, and streaming job snapshots on disk. Members can use persisted data to recover from a planned shutdown (including rolling upgrades), a sudden cluster-wide crash, or a single member failure.

[blue]*Hazelcast Enterprise Feature*

{description}

== Why Persist Data

Data in Hazelcast is usually stored in-memory (RAM) so that it's faster to access. However, data in RAM is volatile, meaning that when one or more members shut down, their data is lost.

When you persist data on disk, members can load it upon a restart and continue to operate as usual.

Clusters can use persisted data to recover from the following scenarios:

- **Planned cluster-wide shutdown**: A whole cluster is xref:maintain-cluster:shutdown.adoc[shut down] and restarted with the same configuration, state, and data as before the restart.
** Rolling restart: The cluster is restarted member by member for scenarios such as installing an operating system patch or new hardware.
- **Unplanned cluster-wide crash**: A cluster is restarted after all its members crashed at the same time due an event such as a power outage.
- **A single member restart**: A single member is restarted for whatever reason.

== What you can Persist

You can save the contents of map or JCache xref:data-structures:distributed-data-structures.adoc[data structures] to disk as well as any xref:pipelines:configuring-jobs.adoc#setting-a-processing-guarantee-for-streaming-jobs[streaming job snapshots].

== Limitations

In some cases, specifically when a
cluster crashes while it has an ongoing partition migration process, currently it is
not possible to restore persisted data.

== Terminology

[cols="a,a"]
|===
|Term| Definition

|persistence store
|The name of the files that contain persisted data.

|===