= Triggering a Partial-Start
:description: To recover a cluster that has Persistence enabled after a cluster-wide restart, you can force a cluster to start without some members when one or more of them fail.
:page-enterprise: true

To recover a cluster that has xref:persistence.adoc[Persistence] enabled after a cluster-wide restart, you can force a cluster to start without some members when one or more of them fail.

== Before you Begin

You should trigger a partial-start only if your cluster has Persistence enabled and it is configured to use one of the `PARTIAL` policies. See xref:configuring-persistence.adoc#policy[Choosing a Cluster Recovery Policy].

== Using Management Center

See the xref:{page-latest-supported-mc}@management-center:clusters:triggering-partial-start.adoc[Management Center docs].

== Using the REST API

See the xref:maintain-cluster:rest-api.adoc#managing-clusters-state[REST API docs].

include::clients:partial$rest-deprecation.adoc[]

== Using Cluster Management Scripts

See the xref:management:cluster-utilities.adoc#example-usages-for-cluster-sh[Cluster management scripts].