= Triggering a Force-Start 
:description: To recover a cluster that has Persistence enabled after a cluster-wide restart, you can force a cluster to delete their persistence stores when one or more members fail to restart.
:page-enterprise: true

To recover a cluster that has xref:persistence.adoc[Persistence] enabled after a cluster-wide restart, you can force a cluster to delete their persistence stores when one or more members fail to restart.

== Before you Begin

You should trigger a force-start only if your cluster has Persistence enabled and it is configured to use the `FULL_RECOVERY_ONLY` policy. See xref:configuring-persistence.adoc#policy[Choosing a Cluster Recovery Policy].

WARNING: Force-start deletes all data in your cluster members' persistence stores.

== Using Management Center

See the xref:{page-latest-supported-mc}@management-center:clusters:triggering-force-start.adoc[Management Center docs].

== Using the REST API

See the xref:maintain-cluster:rest-api.adoc#managing-clusters-state[REST API docs].

include::clients:partial$rest-deprecation.adoc[]

== Using Cluster Management Scripts

See the xref:management:cluster-utilities.adoc#example-usages-for-cluster-sh[Cluster management scripts].




