= 5.0.3 Release Notes
:description: These release notes list any new features, enhancements, and fixes that were made between version 5.0.2 and 5.0.3 of Hazelcast Platform.

{description}

For information about upgrading from previous IMDG and Jet
releases, see the xref:migrate:upgrade.adoc[Upgrading to Hazelcast Platform section].

To learn about the changes in previous IMDG and Jet releases, see https://docs.hazelcast.org/docs/rn/[IMDG release notes] and
https://jet-start.sh/blog/[Jet release notes].

The numbers in the square brackets refer to the issues in Hazelcast's GitHub repositories.

== Enhancements

* Hazelcast command line interface is now available within the Hazelcast distribution package;
previously it needed to be installed separately. https://github.com/hazelcast/hazelcast/pull/20812[#20812]
* Enabled XXE (XML External Entity Reference) protection for `XMLInputFactory`. The related issue was reported
through the https://huntr.dev/bounties/d63972a2-b910-480a-a86b-d1f75d24d563/. https://github.com/hazelcast/hazelcast/pull/20941[#20941]

== Fixes

* [.enterprise]*Enterprise* Fixed an issue where a Hazelcast Enterprise member could not start when there is a custom serializer
and the `allow-override-default-serializers` configuration is enabled. #4879
* Fixed a data race in `SingleProtocolEncoder`; while one method of this interface is called from the input thread,
another one is called from the output thread which was causing the race. https://github.com/hazelcast/hazelcast/pull/20993[#20993]
* Fixed a potential deadlock during partition migrations and inability to make progress while performing graceful shutdown with persistence enabled. https://github.com/hazelcast/hazelcast/pull/20884[#20884]
* Fixed an issue where the `hz-start.bat` command was not working with Java 8 in the Windows operating system. https://github.com/hazelcast/hazelcast/pull/20811[#20811]
* Fixed an issue where the Operation Profiler of diagnostic utility was showing incorrect
latency distributions. https://github.com/hazelcast/hazelcast/pull/20722[#20722]
* Fixed an issue where a Hazelcast client was failing to connect to a cluster if it does not
know the hostname of a cluster member. https://github.com/hazelcast/hazelcast/pull/20630[#20630]
* Fixed the mapping issue of Hazelcast Map fields in SQL; when the value object contains a
public getter of `java.util.Map`, the `CREATE MAPPING` statement was failing. https://github.com/hazelcast/hazelcast/pull/20256[#20256]
* [.enterprise]*Enterprise* Fixed an issue where the memory cost statistics for a High-Density Memory Store backed map
were being calculated incorrectly when you perform key based evictions and then load all the keys. #4647