= 5.1.2 Release Notes

== Fixes

* Fixed an issue where a cluster could not be formed when security is enabled, various client permissions are set, and multiple members
are started simultaneously.
https://github.com/hazelcast/hazelcast/pull/21510[#21510]
* Fixed an issue where a cluster was unresponsive when you perform a health check to see the members are in the safe state;
cluster members were hanging in the `REPLICA_NOT_SYNC` state during such health checks.
https://github.com/hazelcast/hazelcast/pull/21208[#21208]
* Fixed an issue where the list of members in the cluster was reset to an empty list when the UUID of a cluster changes after its restart:
this was causing startup failures since Hazelcast could not manage the events due to the empty member list after a restart.
https://github.com/hazelcast/hazelcast/pull/21178[#21178]
* Fixed an issue where the statistics like puts and removals were not increasing when these operations are executed through Transactional interface.
https://github.com/hazelcast/hazelcast/pull/21107[#21107]
* Fixed a data race in `SingleProtocolEncoder`; while one method of this interface is called from the input thread,
another one is called from the output thread which was causing the race.
https://github.com/hazelcast/hazelcast/pull/20994[#20994]
* Fixed an issue where the automatic module name in `hazelcast-5.x.jar` could not be detected using Gradle. The reason was
`/META-INF/MANIFEST.MF` not being the first or second entry in the JAR file; now this manifest file is the second entry.
https://github.com/hazelcast/hazelcast/pull/20976[#20976]
