= 5.2 Release Notes

== New Features

* **???**: ???. See xref:???.adoc[???].

== Enhancements

=== SQL Engine

???

=== Distribution

* Upgraded the Kafka client library to the version 2.8.1.
https://github.com/hazelcast/hazelcast/pull/20938[#20938]

=== Cloud Discovery Plugins

???

=== Serialization

* Hazelcast now does not allow to create SQL mappings containing the compact format, when the compact serialization is not enabled, and
provides a meaningful error; previously this situation was producing confusing errors.
https://github.com/hazelcast/hazelcast/pull/20998[#20998]

=== Data Structures

???

=== Configuration

???

=== Logging

???

=== Management Center

???

=== Licensing

???

=== Other Enhancements

???

== Fixes

* Fixed a data race in `SingleProtocolEncoder`; while one method of this interface is called from the input thread,
another one is called from the output thread which was causing the race.
https://github.com/hazelcast/hazelcast/pull/20991[#20991]
* Fixed an issue where the automatic module name in `hazelcast-5.x.jar` could not be detected using Gradle. The reason was
`/META-INF/MANIFEST.MF` not being the first or second entry in the JAR file; now this manifest file is the second entry.
https://github.com/hazelcast/hazelcast/pull/20969[#20969]

== Removed/Deprecated Features

???


== Contributors

We would like to thank the contributors from our open source community
who worked on this release:

* https://github.com/dreis2211[Christoph Dreis]
