= 5.2 Release Notes

== New Features

* **???**: ???. See xref:???.adoc[???].

== Enhancements

=== SQL Engine

* Added support of the following statements, operators, and functions:
** `Calc` operator to merge `Project` and `Filter`.
** ???
https://github.com/hazelcast/hazelcast/issues/17058[#17058],


=== Distribution

* Upgraded the Kafka client library to the version 2.8.1.
https://github.com/hazelcast/hazelcast/pull/20938[#20938]

=== Cloud Discovery Plugins

???

=== Serialization

* Hazelcast now does not allow to create SQL mappings containing the compact format, when the compact serialization is not enabled, and
provides a meaningful error; previously this situation was producing confusing errors.
https://github.com/hazelcast/hazelcast/pull/20998[#20998]

=== Data Structures

???

=== Configuration

???

=== Logging

???

=== Management Center

???

=== Licensing

???

=== Other Enhancements

* While https://github.com/hazelcast/hazelcast#building-from-source[building Hazelcast] from the source,
you can now use the boolean `hazelcast.disable.docker.tests` property to ignore the tests that require Docker
to run (by setting it to `false`).
https://github.com/hazelcast/hazelcast/pull/21087[#21087]

== Fixes

* Fixed an issue where a set time-to-live (TTL) duration for an entry was ignoring the split seconds.
For example, when you set TTL as 1 seconds and put an entry at 01:01:5.99 AM , then the entry was already
expired when you want to get this entry at 01:01:6.01 AM (should have been expired at 01:01:6.99 AM).
https://github.com/hazelcast/hazelcast/pull/21018[#21018] 
* Fixed a data race in `SingleProtocolEncoder`; while one method of this interface is called from the input thread,
another one is called from the output thread which was causing the race.
https://github.com/hazelcast/hazelcast/pull/20991[#20991]
* Fixed an issue where the automatic module name in `hazelcast-5.x.jar` could not be detected using Gradle. The reason was
`/META-INF/MANIFEST.MF` not being the first or second entry in the JAR file; now this manifest file is the second entry.
https://github.com/hazelcast/hazelcast/pull/20969[#20969]
* Fixed an issue where the list of members in the cluster was reset to an empty list when the UUID of a cluster changes after its restart:
this was causing startup failures since Hazelcast could not manage the events due to the empty member list after a restart.
https://github.com/hazelcast/hazelcast/pull/20818[#20818]
* Fixed an issue where `JSON_QUERY` with expression filter in SQL was not producing a result when the data source contains internal array(s).
https://github.com/hazelcast/hazelcast/issues/20761[#20761]

== Removed/Deprecated Features

???


== Contributors

We would like to thank the contributors from our open source community
who worked on this release:

* https://github.com/dreis2211[Christoph Dreis]
