= 5.0.1

Hazelcast Platform is a major release which unifies
the former Hazelcast IMDG and Jet products in a
single solution. The changes are summarized below.

For information about upgrading from previous IMDG and Jet
releases, see the xref:migrate:upgrade.adoc[Upgrading to Hazelcast Platform section].

To learn about the changes in previous IMDG and Jet releases, see https://docs.hazelcast.org/docs/rn/[IMDG release notes] and
https://jet-start.sh/blog/[Jet release notes].

== New Features

???

== Enhancements

???

== Fixes

* Fixed an issue where the command `hz-stop --help` was not displaying the help but executing
the `hz-stop` command.
https://github.com/hazelcast/hazelcast/issues/19726[#19726]
* Hazelcast's memcached implementation was interpreting the number values and parameters
for `incr` and `decr` wrongly (numbers were being converted into byte arrays instead of decimals).
This has been fixed by making these commands' implementations strictly follow the
memcached protocol specification.
https://github.com/hazelcast/hazelcast/pull/19677[#19677]
* Fixed an issue where the `totalPublishes` statistics for the Reliable Topic data structure
were always generated as `0`.
https://github.com/hazelcast/hazelcast/pull/19651[#19651]
* When you both enable the persistence and automatic removal of stale data in the configuration,
member startup failures were occurring. This has been fixed by adding the `auto-remove-stale-data`
element to the configuration schema.
https://github.com/hazelcast/hazelcast/issues/19373[#19373]

== Removed/Deprecated Features

???

== Contributors

We would like to thank the contributors from our open source community
who worked on this release:

* https://github.com/Chelsea31[Chelsea31]
