= 5.0.1 Release Notes

Hazelcast Platform is a major release which unifies
the former Hazelcast IMDG and Jet products in a
single solution. The changes are summarized below.

For information about upgrading from previous IMDG and Jet
releases, see the xref:migrate:upgrade.adoc[Upgrading to Hazelcast Platform section].

To learn about the changes in previous IMDG and Jet releases, see https://docs.hazelcast.org/docs/rn/[IMDG release notes] and
https://jet-start.sh/blog/[Jet release notes].

== Enhancements

* Updated Avro dependency version to 1.11.0 and AWS SDK to 1.12.120 in Hazelcast's root `pom.xml`.
https://github.com/hazelcast/hazelcast/pull/20008[#20008], https://github.com/hazelcast/hazelcast/pull/20007[#20007]
* Introduced a system property for allowing you to audit that all the Hazelcast instances
running in your environment have the instance tracking file name set correctly in the configuration.
See the note in xref:maintain-cluster:monitoring#instance-tracking[Instance Tracking].
https://github.com/hazelcast/hazelcast/pull/19930[#19930]

== Fixes

* Fixed an issue where the `hazelcast.yaml` file was ignored when it is the only configuration file present in the
Hazelcast setup; during startup it was looking only for the `hazelcast.xml` file and producing an error message saying that
the configuration does not exist even though there is the `yaml` configuration file. Now it automatically uses `hazelcast.yaml`
when `hazelcast.xml` is not available.
https://github.com/hazelcast/hazelcast/pull/20004[#20004]
* Fixed an issue where the Hazelcast command line interfaces commands were outputting incorrect command names
when you want to see their usages using the `--help` argument. For example, the command `hz-start --help` was outputting
the following:
+
[source,shell]
----
Usage: hazelcast-start [-d]
  -d, --daemon   Starts Hazelcast in daemon mode
----
+
instead of the following:
+
[source,shell]
----
Usage: hz-start [-d]
  -d, --daemon   Starts Hazelcast in daemon mode
----
+
https://github.com/hazelcast/hazelcast/pull/20002[#20002]
* Hazelcast was executing cluster wide operations when you query the state of a member using the health
check endpoint - it was causing to kill all the members in a cluster; this issue has been fixed.
https://github.com/hazelcast/hazelcast/pull/19905[#19905]
* Fixed an issue where there were mismatching map configurations when phone home is enabled.
https://github.com/hazelcast/hazelcast/pull/19900[#19900]
* Fixed an issue where the command `hz-stop --help` was not displaying the help but executing
the `hz-stop` command.
https://github.com/hazelcast/hazelcast/issues/19726[#19726]
* Hazelcast's memcached implementation was interpreting the number values and parameters
for `incr` and `decr` wrongly (numbers were being converted into byte arrays instead of decimals).
This has been fixed by making these commands' implementations strictly follow the
memcached protocol specification.
https://github.com/hazelcast/hazelcast/pull/19677[#19677]
* Fixed an issue where the `totalPublishes` statistics for the Reliable Topic data structure
were always generated as `0`.
https://github.com/hazelcast/hazelcast/pull/19651[#19651]
* When you both enable the persistence and automatic removal of stale data in the configuration,
member startup failures were occurring. This has been fixed by adding the `auto-remove-stale-data`
element to the configuration schema.
https://github.com/hazelcast/hazelcast/issues/19373[#19373]

== Contributors

We would like to thank the contributors from our open source community
who worked on this release:

* https://github.com/Chelsea31[Chelsea31]