= Release Notes

Hazelcast 5.0 is a major release which unifies
the former Hazelcast IMDG and Jet products in a
single solution. The changes are summarized below.

For information on upgrading from previous IMDG and Jet
releases, see the xref:migrate:upgrade.adoc[Upgrading to Hazelcast 5.0 section].

To learn about the changes in previous IMDG and Jet releases, see https://docs.hazelcast.org/docs/rn/[IMDG release notes] and
https://jet-start.sh/blog/[Jet release notes].

== New Features

== Breaking Changes

* Since the `HOST` and `RACK` metadata were deprecated in the previous Hazelcast
release, these information are removed from the `ZONE_AWARE` partition grouping
configuration.
https://github.com/hazelcast/hazelcast/pull/18780[#18780]
* Since DAG printing was not reflecting the real queue size, the `DAG.toDotString(int defaultParallelism)` method
signature is changed as `DAG.toDotString(int defaultLocalParallelism, int defaultQueueSize)`. You, now, need to supply the
queue size that will be shown if it is not overriden on the edge.
https://github.com/hazelcast/hazelcast/pull/18475[#18475]

== Enhancements

* Standardized the `TIME` and `TIMESTAMP` temporal formats for the
SQL engine: You can now use `TIME` without leading zeroes and `TIMESTAMP`
with space instead of the `T` symbol.
https://github.com/hazelcast/hazelcast/pull/18881[#18881]
* Implemented a basic memory management for the SQL engine
so that number of records accumulated by it can be limited
to avoid out of memory failures. You can use the `max-processor-accumulated-records`
configuration element for this purpose.
https://github.com/hazelcast/hazelcast/pull/18671[#18671]
* Removed the `jackson-core` dependency from `pom.xml` since it was
breaking the extensions that depend on `jackson`.
https://github.com/hazelcast/hazelcast/pull/18665[#18665]
* Added a configuration option to enable/disable resource uploading for
Jet engine jobs. See xref:configuration:jet-configuration.adoc#enabling-resource-uploading[here] for details.
* The log message for infinite cluster connection timeout is clearer now.
Previously, it was represented as the value of `Long.MAX_VALUE`.
https://github.com/hazelcast/hazelcast/pull/18642[#18642]
* Introduced a new mechanism in the background expiration tasks;
now a thread local array controls the allocations for these tasks otherwise
which may cause increased garbage collection pressure and CPU usage spikes when
you use aggressive expiration configurations, e.g., low time-to-live values.
https://github.com/hazelcast/hazelcast/pull/18633[#18633]
* Added support of dynamic parameters for the SQL engine and file table functions.
https://github.com/hazelcast/hazelcast/pull/18613[#18613],
https://github.com/hazelcast/hazelcast/pull/18522[#18522]
* Introduced `QueryDataType.MAP` and `QueryDataTypeFamily.MAP` to support map operand checks
for file table functions.
https://github.com/hazelcast/hazelcast/pull/18602[#18602]
* Added support of `EXTRACT(field FROM source)` for the SQL engine.
The function computes date parts from the source field. The supported types for `source` argument are as follow:
** Date
** Time
** Timestamp
** Timestamp With Time Zone
+
https://github.com/hazelcast/hazelcast/pull/18570[#18570]
* Added support of the `DELETE` function for the SQL engine
to remove entries from maps.
https://github.com/hazelcast/hazelcast/pull/18569[#18569]
* The license key is, now, not shown while starting a member on Docker with overriding configurations.
https://github.com/hazelcast/hazelcast/pull/18568[#18568]
* Limited the number of parallel partition reads (to a fixed value of five)
for maps and caches to prevent out of memory failures.
https://github.com/hazelcast/hazelcast/pull/18663[#18663],
https://github.com/hazelcast/hazelcast/pull/18499[#18499]
* Added support of the `LIMIT <n>` and `ORDER BY` clauses for the streaming engine.
https://github.com/hazelcast/hazelcast/pull/18479[#18479]
* Implemented the following functions for the SQL engine:
** `REPLACE`
** `ATAN2`
** `POWER`
** `SQUARE`
** `SQRT`
** `CBRT`
** `POSITION`
** `COALESCE`
** `NULLIF`
+
https://github.com/hazelcast/hazelcast/pull/18510[#18510],
https://github.com/hazelcast/hazelcast/pull/18487[#18487],
https://github.com/hazelcast/hazelcast/pull/18450[#18450],
https://github.com/hazelcast/hazelcast/pull/18424[#18424],
https://github.com/hazelcast/hazelcast/pull/18405[#18405]
* Added support of plan caching for Jet engine based queries.
https://github.com/hazelcast/hazelcast/pull/18446[#18446]
* Added support of plus and minus operations for interval types (date, time, etc.) for
the SQL engine.
https://github.com/hazelcast/hazelcast/pull/18390[#18390]
* Added support of various new `Portable` types for the SQL engine.
https://github.com/hazelcast/hazelcast/issues/18115[#18115]
* Added a comprehensive documentation for metrics produced by Hazelcast.
See https://docs.hazelcast.com/imdg/5.0/list-of-hazelcast-metrics.html[here]
for the full list of metrics with their descriptions.
https://github.com/hazelcast/hazelcast/issues/17880[#17880]
* Improved the speed of connection by a member when it joins the cluster, by
removing the unnecessary `sleep` statements in the code.
https://github.com/hazelcast/hazelcast/pull/17428[#17428]
* Added support of `IN`, `BETWEEN`, and `CASE` operators for the SQL queries.
https://github.com/hazelcast/hazelcast/pull/18483[#18483],
https://github.com/hazelcast/hazelcast/pull/18422[#18422],
https://github.com/hazelcast/hazelcast/pull/18067[#18067]

== Fixes

* Fixed a regression issue where a job using map reader/writer could not be completed
when the target map has a configured Near Cache.
https://github.com/hazelcast/hazelcast/pull/18696[#18696]
* Fixed a reconnection flood when members are separated by a proxy: When a member is disconnected
from the cluster, the alive cluster members still try to reconnect to it if the dying member
connection is not closed explicitly. In the cases where the connection is explicitly closed with a cause
(such as `Connection reset by peer` or `Remote socket closed!`), a new connection was being established
if the member is placed behind a proxy. This scenario was end causing opening and closing connections continuously.
This issue has been fixed.
https://github.com/hazelcast/hazelcast/pull/18673[#18673]
* Fixed an issue where the multicast discovery was not working between the members
when the loopback mode is enabled.
https://github.com/hazelcast/hazelcast/pull/18669[#18669]
* The `HazelcastInstance.shutdown()` method now gracefully terminate Jet engine jobs, too.
After the merge of IMDG and Jet, it was failing.
https://github.com/hazelcast/hazelcast/issues/18625[#18625]
* Replicated Map does not fail to publish events anymore, from an entry listener with a predicate
which has an attribute path.
https://github.com/hazelcast/hazelcast/pull/18623[#18623]
* Fixed a possible performance regression by not starting the cooperative threads
until a job is submitted; otherwise the Jet engine was consuming system resources.
https://github.com/hazelcast/hazelcast/pull/18574[#18574]
* Fixed an issue where running SQL statements was fetching results incorrectly
(from an unexpected mapping) when there are different user-provided schemas for
data structures and mappings.
https://github.com/hazelcast/hazelcast/issues/18428[#18428]
* Fixed an issue where there might be continuous reconnection attempts by the
cluster members to a failed member, even its connection is explicitly closed
and when Hazelcast is placed behind a proxy.
https://github.com/hazelcast/hazelcast/issues/18320[#18320]
* Hazelcast now properly works on hosts with multiple NICs.
https://github.com/hazelcast/hazelcast/issues/17834[#17834]

== Removed/Deprecated Features

* Former `Jet`, `JetInstance` and `JetCacheManager` classes have been deprecated.
See xref:migrate:upgrade.adoc#depreciation-of-the-jet-and-jetinstance-classes[here]
for details.
* Former Hazelcast Jet's `bootstrappedInstance()` has been deprecated. Instead, you can use `Hazelcast.bootstrappedInstance()`.
See xref:migrate:upgrade.adoc#depreciation-of-the-jet-and-jetinstance-classes[here] for details.

== Contributors

We would like to thank the contributors from our open source community
who worked on this release:

* https://github.com/lprimak[Lenny Primak]