= Release Notes

Hazelcast Platform is a major release which unifies
the former Hazelcast IMDG and Jet products in a
single solution. The changes are summarized below.

For information about upgrading from previous IMDG and Jet
releases, see the xref:migrate:upgrade.adoc[Upgrading to Hazelcast Platform section].

To learn about the changes in previous IMDG and Jet releases, see https://docs.hazelcast.org/docs/rn/[IMDG release notes] and
https://jet-start.sh/blog/[Jet release notes].

== New Features

* **???**: ???
See the xref:???:???.adoc[??? section].
https://github.com/hazelcast/hazelcast/pull/???[#???],

== Breaking Changes

=== API Changes

???

=== Configuration Changes

???

== Enhancements

=== SQL Engine

* Added `JSON` as a supported type for the SQL engine with functions like `JSON_QUERY` and `JSON_VALUE`;
they return a JSON object/array and a primitive value, respectively.
https://github.com/hazelcast/hazelcast/pull/19303[#19303]

=== Cloud Discovery Plugins

* Added `EndpointSlices` support for the Kubernetes discovery plugin; now the `EndpointSlices` API usage is default,
and the old `Endpoints` API is not used as a fallback if `EndpointSlices` are not available.
https://github.com/hazelcast/hazelcast/pull/19643[#19643]

=== Serialization

* Introduced the `FieldKind` class to get the field types for portable and compact serializations;
previously it was `FieldType`.
https://github.com/hazelcast/hazelcast/pull/19517[#19517]

=== Other Enhancements

* Since the name of Hot Restart Persistence feature changed to Persistence, the prefix for its
metrics also has been changed from "hot-restart" to "persistence".
https://github.com/hazelcast/hazelcast/pull/19543[#19543]
* Improved the speed of connection by a member when it joins the cluster, by removing the unnecessary
sleep statements in the code.
https://github.com/hazelcast/hazelcast/pull/18932[#18932]

== Fixes

* Fixed an issue where some Spring XML configuration elements having values as property placeholders
were not working when Hazelcast is upgraded to a newer version.
https://github.com/hazelcast/hazelcast/pull/19629[#19629]
* Fixed an issue where the `totalPublishes` statistics for the Reliable Topic data structure
were always generated as `0`.
https://github.com/hazelcast/hazelcast/issues/19555[#19555]
* Fixed an issue where the serialization was failing when the object has enum fields, or it is an enum itself.
https://github.com/hazelcast/hazelcast/issues/19314[#19314]

== Removed/Deprecated Features

* ???

== Contributors

We would like to thank the contributors from our open source community
who worked on this release:

* https://github.com/lprimak[Lenny Primak]
