= Release Notes

Hazelcast 5.0 is a major release which unifies
the former Hazelcast IMDG and Jet products in a
single solution. The changes are summarized below.

For information on upgrading from previous IMDG and Jet
releases, see the xref:migrate:upgrade.adoc[Upgrading to Hazelcast 5.0 section].

To learn about the changes in previous IMDG and Jet releases, see https://docs.hazelcast.org/docs/rn/[IMDG release notes] and
https://jet-start.sh/blog/[Jet release notes].

== New Features

== Breaking Changes

* Since the `HOST` and `RACK` metadata were deprecated in the previous Hazelcast
release, these information are removed from the `ZONE_AWARE` partition grouping
configuration.
https://github.com/hazelcast/hazelcast/pull/18780[#18780] 

== Enhancements

* Standardized the `TIME` and `TIMESTAMP` temporal formats for the
SQL engine: You can now use `TIME` without leading zeroes and `TIMESTAMP`
with space instead of the `T` symbol.
https://github.com/hazelcast/hazelcast/pull/18881[#18881]
* Implemented a basic memory management for the SQL engine
so that number of records accumulated by it can be limited
to avoid out of memory failures.
https://github.com/hazelcast/hazelcast/pull/18671[#18671]
* Added support of various new `Portable` types for the SQL engine.
https://github.com/hazelcast/hazelcast/issues/18115[#18115]
* Added a comprehensive documentation for metrics produced by Hazelcast.
See https://docs.hazelcast.com/imdg/5.0/list-of-hazelcast-metrics.html[here]
for the full list of metrics with their descriptions.
https://github.com/hazelcast/hazelcast/issues/17880[#17880]
* Added support of `IN`, `BETWEEN`, and `CASE` operators for the SQL queries.
https://github.com/hazelcast/hazelcast/issues/17329[#17329],
https://github.com/hazelcast/hazelcast/issues/17303[#17303]

== Fixes

* The `HazelcastInstance.shutdown()` method now gracefully terminate Jet engine jobs, too.
After the merge of IMDG and Jet, it was failing.
https://github.com/hazelcast/hazelcast/issues/18625[#18625]
* Replicated Map does not fail to publish events anymore, from an entry listener with a predicate
which has an attribute path.
https://github.com/hazelcast/hazelcast/pull/18623[#18623]
* Fixed an issue where there might be continuous reconnection attempts by the
cluster members to a failed member, even its connection is explicitly closed
and when Hazelcast is placed behind a proxy.
https://github.com/hazelcast/hazelcast/issues/18320[#18320]
* Hazelcast now properly works on hosts with multiple NICs.
https://github.com/hazelcast/hazelcast/issues/17834[#17834]