= Tiered Storage
:description: Hazelcast’s Tiered Storage feature offers an extension to Hazelcast Map which allows you to store map data both in the memory and on the disk.
:page-beta: true
:page-enterprise: true

NOTE: The Tiered Storage feature is in BETA state; it is not recommended to use in production environments.

NOTE: The Tiered Storage feature is available to our customers who already have a Hazelcast Enterprise license.

{description}

You can use Tiered Storage as a persistent key-value store with additional guarantees
including lesser Hazelcast members for large maps (cost efficiency) or size-comfortable SQL operations.
For example, when you do table joins in SQL, the intermediate result may become too large to fit in the memory;
with Tiered Storage this is not an issue. As another example, if you have a map having 1 TB of data, you may
be needing around 10 Hazelcast members if all data is kept in the memory; with Tiered Storage, you would need
one or two members depending on your cluster’s availability needs.

Tiered Storage uses

* an in-memory index to allow faster access to map entries
* a special memory manager, i.e., HybridLog, to decide which entries to store in the memory tier or disk tier -
if a map entry is not accessed for some time, it gets flushed to the disk; if it is a frequently accessed data, it stays in the memory.
Note that an entry cannot be available in both tiers.

For now, Tiered Storage supports the local machine’s disk as the storage device. It will also support
additional systems such as Amazon S3 and Google Blobstore in the future releases, so that
when the local disk is filled up, you will be able to flush data to, for example, Amazon S3.

== Configuring Tiered Storage

Configuration for Tiered Storage includes setting the device (local disk) parameters for the Hazelcast member
and providing Tiered Storage details for the map.

[tabs] 
==== 
YAML:: 
+ 
-- 
[source,yaml]
----
hazelcast:
  local-device:
    my-disk:
      base-dir: "tiered-store"
      block-size: 4096
      read-io-thread-count: 16
      write-io-thread-count: 4
  map:
    my-map:
      in-memory-format: NATIVE
      tiered-store:
        enabled: true
        memory-tier:
          capacity: "256 MB"
        disk-tier:
          enabled: true
          device-name: "my-disk"
----
--

XML::
+
[source,xml]
----
<hazelcast>
    <local-device name="my-disk">
        <base-dir>tiered-store</base-dir>
        <block-size>4096</block-size>
        <read-io-thread-count>16</read-io-thread-count>
        <write-io-thread-count>4</write-io-thread-count>
    </local-device>
    <map name="my-map">
        <in-memory-format>NATIVE</in-memory-format>
        <tiered-store enabled="true">
            <memory-tier>
                <capacity>256 MB</capacity>
            </memory-tier>
            <disk-tier enabled="true" device-name="my-disk"/>
        </tiered-store>
    </map>
</hazelcast>
----
====


Parameters of the device (disk) are set under the `local-device` parent configuration element:

* `my-disk`: Name of the disk; “my-disk” in this example.
* `base-dir`: Name of the directory where the data on disk is stored.
* `block-size`: Allocated size of the device’s IO (read/write), in bytes; refers to the minimum size to request IO.
* `read/write-io-thread-count`: Number of threads for read/write operations from/to disk.

Parameters of the Tiered Storage for a map are set in `tiered-store` under the `map` parent configuration element:

* Tiered Storage is disabled by default; set the `enabled` parameter of `tiered-store` to `true` to start using it.
* You can set the capacity of the memory in which the frequently accessed data will be stored using
the `memory-tier` -> `capacity` parameter. This parameter cannot be set to `0`.
* Under `disk-tier`, you decide whether to use the device (disk) as storage using the `enabled` parameter,
and provide the device name of the disk that you set under the `local-device` configuration.

NOTE: The in-memory format for the map having Tiered Storage enabled should be `NATIVE`. 
