= What's New in Hazelcast Platform
:description: Here are the highlights of what's new and improved in Hazelcast Platform 5.6.
[[whats-new]]

{description}

== Dynamic Diagnostic Logging available in BETA

Platform 5.6 introduces dynamic diagnostic logging, which enables you to toggle diagnostic logging without requiring cluster restarts. Previously, if you wanted to enable or disable diagnostic logging, you had to restart cluster members, which was not ideal for production systems and could lead to disruption or delays. You can now also use an auto-shutoff timer to terminate diagnostic logging, which helps minimise any ongoing impact on performance.

With the release of Hazelcast Platform 5.6, and associated updates for Management Center and Platform Operator, you can now control diagnostic logging via a number of methods.

With Management Center 5.9 you can view the current state of diagnostic logging, toggle the service on and off, set the auto-disable timer, and control the log output location. These controls are also available via the Management Center REST interface. For more information, see Management Center documentation.

With Platform Operator for Kubernetes 5.16, you have full control over all diagnostic logging parameters without needing to restart cluster members. You can update the Hazelcast Custom Resource Definition (CRD) and Operator will apply the changes to your cluster without requiring any member restarts, which means you have an auditable, version-controlled and automated way to manage diagnostics in complex cloud-native environments.

For more information, see xref:cp-subsystem:cp-subsystem.adoc[].

== CP Snapshot Chunking 
[.enterprise]*Enterprise* 

With the introduction of snapshot chunking in 5.6, the CP Subsystem now benefits from enhanced stability and performance due to incremental snapshot transfers that prevent potential memory overloads, reduce network congestion, and enable more reliable synchronization. Previously, the snapshots were sent as a single monolithic message, which could cause network congestion and lengthy synchronization times, which could impact network stability and performance, particularly in topologies with very large clusters or geographically distributed desployments with significant network latency. Instead, the cluster leader now breaks the large snapshot into smaller, fixed-size "chunks" before transmission. 

With the following additional improvements, the Enterprise-only CP Subsystem is now more efficient and performant than ever before:

* Optimized snapshot serialization: redundant serialization steps have been eliminated, resulting in much faster snapshot operations.
* Improved resource listing: avoids unnecessary snapshot creation when listing resources, reducing data overheads and improving responsiveness.
* Enhanced failure response handling: the `AppendFailureResponse` message now includes the `followerNextIndex` field, enabling leaders to identify the next expected follower index in constant O(1) time instead of linear O(n), boosting synchronization efficiency.
* Clearer leadership exception messages: improved error messages related to leadership and cluster state issues, such as `NotLeaderException`, provide better clarity, aiding diagnostics and troubleshooting.
* Reduced log noise: frequent log messages related to `CPGroupDestroyedException` are now suppressed to reduce log flooding, making logs easier to manage and analyze.

These new features and enhancements strengthen the use of Hazelcast Platform as a flexible real-time data platform capable of delivering both the low-latency performance of AP data structures (IMap) and the consistency guarantees of distributed data structures. 

For more information, see xref:cp-subsystem:cp-subsystem.adoc[].

== Release Notes

For detailed release notes for {enterprise-product-name} and {open-source-product-name} that include new features and enhancements, breaking changes, deprecations and other fixes, see xref:release-notes:releases.adoc[Release Notes].

To evaluate Hazelcast {enterprise-product-name} features, you can https://hazelcast.com/trial-request/?utm_source=docs-website[request a trial license key].

== Management Center 5.9

== Hazelcast Operator for Kubernetes 5.16

== Hazelcast CLC