= What's New in Hazelcast Platform
:description: Here are the highlights of what's new and improved in Hazelcast Platform 5.6, including Management Center and Platform Operator for Kubernetes updates.
[[whats-new]]

{description}

== Dynamic diagnostic logging available in beta

Platform 5.6 introduces dynamic diagnostic logging, which enables you to toggle diagnostic logging without requiring cluster restarts. Previously, if you wanted to enable or disable diagnostic logging, you had to restart cluster members, which was not ideal for production systems and could lead to disruption or delays. You can now also use an auto-shutoff timer to terminate diagnostic logging, which helps minimize any ongoing impact on performance.

With the release of Hazelcast Platform 5.6, and associated updates for Management Center and Platform Operator, you can now control diagnostic logging via a number of methods.

With Management Center 5.9 you can view the current state of diagnostic logging, toggle the service on and off, set the auto-disable timer, and control the log output location. These controls are also available via the Management Center REST interface.

With Platform Operator for Kubernetes 5.16, you have full control over all diagnostic logging parameters without needing to restart cluster members. You can update the Hazelcast Custom Resource Definition (CRD) and Operator will apply the changes to your cluster without requiring any member restarts, which means you have a version-controlled and automated way to manage diagnostics in complex cloud-native environments.

For more information, see xref:maintain-cluster:monitoring.adoc#diagnostics[Diagnostics].

== CP snapshot chunking provides enhanced stability and performance
[.enterprise]*Enterprise* 

With the introduction of snapshot chunking in 5.6, the CP Subsystem now benefits from enhanced stability and performance due to incremental snapshot chunk transfers that prevent potential memory overloads, reduce network congestion, and enable more reliable synchronization. Previously, the snapshots were sent as a single monolithic message, which could cause network congestion and lengthy synchronization times. 

With the following additional improvements, the Enterprise-only CP Subsystem is now more efficient and performant than ever before:

* Optimized snapshot serialization: redundant serialization steps have been eliminated, resulting in much faster snapshot operations.
* Improved resource listing: avoids unnecessary snapshot creation when listing resources, reducing data overheads and improving responsiveness.
* Enhanced failure response handling: the `AppendFailureResponse` message now includes the `followerNextIndex` field, enabling leaders to identify the next expected follower index more efficiently.
* Clearer leadership exception messages: improved error messages related to leadership and cluster state issues, such as `NotLeaderException`, provide better clarity, aiding diagnostics and troubleshooting.
* Reduced log noise: frequent log messages related to `CPGroupDestroyedException` are now suppressed to reduce log flooding, making logs easier to manage and analyze.

For more information, see xref:cp-subsystem:cp-subsystem.adoc[].

== Vector search faster and more accurate (beta)
[.enterprise]*Enterprise* 

This release adds a number of important vector search changes that improve performance, fault tolerance, and observability. Similarity searches are faster and more accurate, with greater control over search settings to improve result quality. Support has been added for fault tolerance and split-brain protection, making vector search more robust. New performance metrics and enhanced error messaging also improve monitoring and diagnostics. Core components have been upgraded for greater stability and speed, and protection against data conflicts has been enhanced with flexible merge options.

While still in beta, vector search now offers more scalable and performant similarity retrieval capabilities, which enables advanced AI and machine learning workloads, such as semantic search, fraud detection, and contextual data queries. For more information, see xref:release-notes:enterprise.adoc#5-6-0[Enterprise 5.6.0 Release Notes].

== Hazelcast Platform Release Notes

For detailed release notes for {enterprise-product-name} and {open-source-product-name} that include new features and enhancements, breaking changes, deprecations and other fixes, see xref:release-notes:releases.adoc[Release Notes].

To evaluate Hazelcast {enterprise-product-name} features, you can https://hazelcast.com/trial-request/?utm_source=docs-website[request a trial license key].

== Management Center 5.9

Management Center 5.9 adds corresponding support for diagnostic logging, as well as various metrics improvements and CVE fixes.

For more information, see xref:{page-latest-supported-mc}@management-center:release-notes:releases.adoc[Management Center 5.9 Release Notes].

== Hazelcast Platform Operator for Kubernetes 5.16

Alongside this Hazelcast Platform release, Platform Operator 5.16 adds support for diagnostic logging, OpenShift S3 locations, and Red Hat Container Registry certification.

For more information, see Operator 5.16 Release Notes.
