= What's New in Hazelcast Platform 5.4
:description: Here are the highlights of what's new and improved in Hazelcast Platform 5.4.
[[whats-new]]

{description}

== Tiered Storage now Generally Available [.enterprise]*Enterprise* 

Tiered Storage ensures that high-hit data remains in fast memory and low-hit data is stored on cheaper disks. We are delighted to confirm this functionality is now generally available as an Enterprise feature. 

Tiered Storage uses an in-memory index to provide faster access to map entries. A dedicated memory manager decides which entries to store in the memory tier and which to store in the disk tier. If a map entry is not accessed for some time, it is flushed to disk; if a map is frequently accessed, it stays in memory. Similar to a _spill to disk_ technology, Tiered Storage allows the cluster to hold more data than the total available RAM.

For more information on how to enable and configure this feature, see xref:tiered-storage:overview.adoc[].

== Use CPMap for Mission-Critical Workflows [.enterprise]*Enterprise* 

A new CPMap data structure is the latest addition to our xref:cp-subsystem:cp-subsystem.adoc[CP Subsystem]. Unlike traditional maps built for availability (AP), CPMap guarantees data consistency even during network partitions, ensuring that every member within the cluster sees the same data. CPMaps are ideal for storing sensitive information or managing mission-critical workflows.

The CP Subsystem is the Hazelcast component that builds a strongly consistent layer for a set of distributed data structures. As well as network partitions, the CP Subsystem withstands server and client failures. xref:management-center:cp-subsystem:dashboard.adoc[Hazelcast Management Center] allows you to inspect the CP Subsystem as a whole – for individual data record access, you can use the Hazelcast Command Line Client (CLC).

For more information on how to use this new data structure, see xref:data-structures:cpmap.adoc[].

== Thread-Per-Core (TPC) now Generally Available [.enterprise]*Enterprise* 

Enable Thread-Per-Core (TPC) on both clients and cluster members to improve system performance, especially in environments where the number of CPU cores on your machines does not match the recommended hardware. TPC is an alternative to traditional Staged Event-Driven Architecture (SEDA) that supports easier scaling based on the number of available cores.

For more information on how to enable and configure TPC, see xref:cluster-performance:thread-per-core-tpc.adoc[].

== Compute Isolation with User Code Namespaces [.enterprise]*Enterprise* 

User Code Namespaces provide a container for Java classpath resources such as user code, and accompanying artifacts such as property files. This allows you to effectively manage access to resources in different namespaces through either static or dynamic configuration. This is an Enterprise feature that extends and replaces the now deprecated xref:clusters:legacy-ucd.adoc[User Code Deployment] functionality.

For more information on how to enable and configure User Code Namespaces, or migrate from User Code Deployment, see xref:clusters:user-code-namespaces.adoc[].

== Connector Updates

**Kafka Connect source connector** is now generally available, which means that the Kafka Connect source can now scale across the whole cluster instead of on a single member. See xref:integrate:kafka-connect-connectors.adoc#parallelism-and-reconfigurations[Parallelism].

**Mongo SQL Connector (SQL over MongoDB)** is now generally available. An important addition to the connector is the security support; you can secure your data connection with TLS when creating MongoDB mappings over SQL. See xref:sql:mapping-to-mongo.adoc[].

**JDBC SQL Connector (SQL over JDBC)** is now generally available. In addition to MySQL and PostgreSQL, JDBC SQL connector now also supports Oracle and Microsoft SQL Server databases. See xref:sql:mapping-to-jdbc.adoc#data-type-mapping-between-hazelcast-and-mssql[JDBC Connector] to learn how data types in these two databases are mapped to Hazelcast.

== Release Notes

For detailed release notes that include new features and enhancements, breaking changes, deprecations and other fixes, see xref:release-notes:5-4-0.adoc[].

== Hazelcast Command Line Client (CLC)

You can use the Hazelcast Command Line Client (CLC) to connect to, and interact with, clusters on Hazelcast Platform and Hazelcast Cloud directly from the command line or through scripts.

You can now import a subset of the Java client configuration. You can also now define custom template actions using advanced scripts, and add a success note when a project is created successfully.

For detailed release notes that include new features and fixes, see Hazelcast CLC xref:clc:release-notes-5.3.7.adoc[].