= Deploying on Kubernetes
:description: Discover ways to deploy Hazelcast clusters in Kubernetes environments.
:page-aliases: deploy:deploying-in-kubernetes.adoc

[[deploying-in-kubernetes]]

{description}

== Quickstart

[tabs]
====

Hazelcast Platform Operator::
+

--
[source, bash]
----
helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com/
helm repo update
helm install operator hazelcast/hazelcast-platform-operator --set installCRDs=true
cat << EOF | kubectl apply -f -
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
EOF
----
--

Helm::
+
--
[source, bash]
----
helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com/
helm repo update
helm install hazelcast hazelcast/hazelcast
----
--

Kubectl::
+

--
[source, bash]
----
kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast-kubernetes/master/rbac.yaml

kubectl run hazelcast-0 --image=hazelcast/hazelcast:{full-version} -l "role=hazelcast"
kubectl run hazelcast-1 --image=hazelcast/hazelcast:{full-version} -l "role=hazelcast"
kubectl run hazelcast-2 --image=hazelcast/hazelcast:{full-version} -l "role=hazelcast"

kubectl create service clusterip hz-hazelcast --tcp=5701 -o yaml --dry-run=client | kubectl set selector --local -f - "role=hazelcast" -o yaml | kubectl create -f -
----
--

====

NOTE: For production-grade Kubernetes deployment, use Hazelcast Platform Operator or Helm chart.

== Hazelcast Platform Operator for Kubernetes/OpenShift

Kubernetes Operators are software extensions to Kubernetes which help you create and manage your applications. Hazelcast Platform Operator automates common management tasks such as configuring, creating, and scaling Hazelcast clusters on Kubernetes and Red Hat OpenShift. By taking care of manual deployment and life-cycle management, Hazelcast Platform Operator makes it simpler to work with Hazelcast clusters.

See the https://docs.hazelcast.com/operator/latest/[Hazelcast Platform Operator Documentation] for more information and find details about deploying a Hazelcast cluster in Kubernetes and also connecting clients outside Kubernetes.

== Helm Chart

https://helm.sh/[Helm^] is a package manager for Kubernetes. Hazelcast is distributed in a form of Helm Charts:

* https://github.com/hazelcast/charts/tree/master/stable/hazelcast[hazelcast/hazelcast^]
* https://github.com/hazelcast/charts/tree/master/stable/hazelcast-enterprise[hazelcast/hazelcast-enterprise^]
* https://github.com/hazelcast/charts/tree/master/stable/hazelcast-platform-operator[hazelcast/hazelcast-platform-operator^]

See the xref:kubernetes:helm-hazelcast-chart.adoc[Hazelcast Helm Charts documentation] for more details.

== Guides

Explore some step-by-step guides about how to use Hazelcast in Kubernetes.

=== Getting Started

* link:https://guides.hazelcast.org/kubernetes/[Deploy Hazelcast Cluster on Kubernetes]

=== Hazelcast Platform Operator

* link:https://docs.hazelcast.com/tutorials/hazelcast-platform-operator-expose-externally[Connect to Hazelcast from Outside Kubernetes]
* link:https://docs.hazelcast.com/tutorials/hazelcast-platform-operator-external-backup-restore[Restore a Cluster from Cloud Storage]
* link:https://docs.hazelcast.com/tutorials/hazelcast-platform-operator-wan-replication[Replicate Data between Two Hazelcast Clusters]
* link:https://docs.hazelcast.com/tutorials/hazelcast-platform-operator-map-store-mongodb-atlas[Configure MongoDB Atlas as an External Data Store for the Cluster]

=== Hazelcast Features

* link:https://guides.hazelcast.org/kubernetes-external-client/[Connect External Hazelcast Client to Kubernetes]
* link:https://guides.hazelcast.org/kubernetes-hpa/[Deploy Hazelcast Cluster with Kubernetes HPA]
* link:https://guides.hazelcast.org/kubernetes-ssl/[Enable SSL between Hazelcast Members and Clients on Kubernetes]
* link:https://guides.hazelcast.org/kubernetes-wan/[Use Hazelcast WAN Replication on Kubernetes]

=== Embedded and Sidecar Topologies

* link:https://guides.hazelcast.org/kubernetes-embedded/[Deploy Hazelcast Applications on Kubernetes]
* link:https://guides.hazelcast.org/kubernetes-sidecar/[Use Hazelcast as Sidecar Container]

=== Service Meshes

* link:https://guides.hazelcast.org/istio/[Use Hazelcast with Istio Environment]
* link:https://guides.hazelcast.org/linkerd/[Use Hazelcast with Linkerd Environment]
