= Adding custom JAR files to the Platform/Management Center Classpath

NOTE: We highly recommend you to use Hazelcast Platform Operator's xref:operator:ROOT:user-code-deployment.adoc[User Code Deployment] feature if you need to add custom jar to your Hazelcast members.

If you'd like to add custom JAR files to the Platform/Management Center, you can extend the Hazelcast/Management Center base image and provide your configuration file or/and custom JARs.
To do that, you need to create a new `Dockerfile` and build it with `docker build` command.

In the `Dockerfile` example below, we are creating a new image based on the Hazelcast image and adding a custom JAR
from our host to the container, which will be used with Hazelcast when the container runs.


[source,dockerfile]
----
FROM hazelcast/hazelcast:$HAZELCAST_VERSION

# Adding custom JARs to the classpath
ADD custom-library.jar ${HZ_HOME}
----

Build and push the image to your own Docker registry.

[source,bash]
----
docker build -t example/hazelcast .
docker push example/hazelcast
----

You can configure your Helm chart to use the custom image you have built in your `values.yaml`.

[source,yaml]
----
image:
  # repository is the Hazelcast image name
  repository: example/hazelcast
----
