= Helm Upgrade Guide

Before upgrade, we recommend you to check link:https://docs.hazelcast.com/hazelcast/5.3/maintain-cluster/rolling-upgrades#hazelcast-members-compatibility-guarantees[Hazelcast's Compatibility Guarantees].

If you are not using hotRestart (aka persistence) feature and Management Center's persistence feature, tests cannot cover every scenario, but no problems expected during upgrade.

`helm upgrade` command does not allow modifications to `spec.volumeClaimTemplates` property in stateful sets that prevents upgrade which can be seen in link:https://github.com/helm/charts/issues/7803[this helm issue]. Because of this issue, we have some upgrade limitations related to Management Center's persistence and hotRestart/persistence that uses volumeClaimTemplates internally. This guide informs you about possible upgrade scenarios.

We recommend to disable Management Center before upgrade, and re-enable it after upgrade. You should follow the steps outlined below:

Step 1: Export values of existing installation:

[source,bash]
----
helm get values <installation-name> > values.yaml
----

Step 2: Disable Management Center:

[source,bash]
----
helm upgrade <installation-name> hazelcast/hazelcast-enterprise -f values.yaml --version <installed-version> --set mancenter.enabled=false
----

Step 3: Delete persistent volume of the deleted Management Center:

[source,bash]
----
kubectl get pvc -o name | grep "mancenter" | xargs -n 1 kubectl delete
----

Step 4: Upgrade your installation without disabling Management Center:

[source,bash]
----
helm upgrade hz hazelcast/hazelcast-enterprise -f values.yaml --version <new-version>
----


The following solutions upgrade solutions cover scenarios for persistence/hotRestart enabled installations:

== Upgrading from Hazelcast Version 4.x to 5.x

Hazelcast rolling update supports upgrading from 4.2 to 5.0. You can check link:https://docs.hazelcast.com/hazelcast/5.3/maintain-cluster/rolling-upgrades#hazelcast-members-compatibility-guarantees[Hazelcast's Compatibility Guarantees] for more information.

=== Upgrading from Helm Chart < 3.11 Installations

These versions do not support rolling upgrade, so we propose you to check Alternative Solutions section.

=== Upgrading from Helm Chart 3.11 Installations

3.11 and 5.3.9 are recent versions that upgrade problems are fixed, so that they are compatible. If you are using 3.11, we recommend upgrading to 5.3.9:

[source,bash]
----
helm get values > values.yaml
helm upgrade hz hazelcast/hazelcast-enterprise --version 5.3.9 -f values.yaml
----

== Upgrading from Hazelcast Version 5.x to 5.x

We support Hazelcast rolling upgrade and chart upgrade from 5.4.7 to 5.9.2. However, in 5.8.0, there is a breaking change: `hot-restart-persistence` is renamed to `persistence`. Following steps should be applied:

Step 1: Export values of existing installation

[source,bash]
----
helm get values <installation-name> > values.yaml
----

Step 2: Modify existing values

- `hot-restart-persistence` should be replaced with `persistence` in Hazelcast configuration. See: link:https://docs.hazelcast.com/hazelcast/5.2/storage/configuring-persistence[Configuring Persistence].
- `hotRestart` field in `values.yaml` should be replaced with `persistence`. See: link:https://docs.hazelcast.com/hazelcast/5.3/kubernetes/helm-hazelcast-enterprise-chart#5-8-0[Notable Changes in Helm Chart]

Step 3: Upgrade using corrected values

[source,bash]
----
helm upgrade hz hazelcast/hazelcast-enterprise --version 5.8.0 -f values.yaml
----

If you are using versions other than in these ranges, please check the next section.

== Alternative Solutions

=== Solution 1: Persistence-based Solution

WARNING: This solution does not support rolling update.

Step 1: Export values of existing installation:

[source,bash]
----
helm get values <installation-name> > values.yaml
----

Step 2: Uninstall existing cluster:

[source,bash]
----
helm uninstall <installation-name>
----

Step 3: Install cluster with the same name using newer helm chart version. It is a must to use the same name to volumes to be attached correctly.

[source,bash]
----
helm install <installation-name> --version <newer-version> -f values.yaml
----

=== Solution 2: Upgrading without Changing the Helm Chart Version

This solution supports rolling update, but as it is not possible to use new charts' features, it is less recommended.

Following scenario is an example for this solution:

Assuming Hazelcast version 5.0.0 is already deployed to a cluster using Helm chart version 5.2.0 and the desired Hazelcast version is 5.3.6. As mentioned at the beginning of this document, Hazelcast supports upgrade by increasing single minor version. So, as current cluster's version is 5.0.0, following steps should be applied:

Step 1: Upgrade Hazelcast Version to 5.1.1 without when helm chart version is fixed.

[source,bash]
----
helm upgrade --reuse-values hz hazelcast/hazelcast-enterprise --set image.tag=5.1.1 --version 5.2.0
----

Step 2: Upgrade Hazelcast Version to 5.2.1 without when helm chart version is fixed.

[source,bash]
----
helm upgrade --reuse-values hz hazelcast/hazelcast-enterprise --set image.tag=5.2.1 --version 5.2.0
----

Step 3: Upgrade Hazelcast Version to 5.3.6 without when helm chart version is fixed.

[source,bash]
----
helm upgrade --reuse-values hz hazelcast/hazelcast-enterprise --set image.tag=5.3.6 --version 5.2.0
----
