= 5.0.5
:description: These release notes list any new features, enhancements, and fixes that were made between version 5.0.4 and 5.0.5 of Hazelcast Platform.

{description}

== Enhancements

* Updated the version of `jackson-core` dependency to `2.15.2`.
https://github.com/hazelcast/hazelcast/pull/24733[#24733]
* Updated the versions of Snappy and Netty dependencies to `1.1.10.1` and `4.1.94.Final`, respectively.
https://github.com/hazelcast/hazelcast/pull/24886[#24886],
https://github.com/hazelcast/hazelcast/pull/24864[#24864],
* Added support of IMDSv2 for Hazelcast’s AWS Discovery plugin.
https://github.com/hazelcast/hazelcast/pull/23606[#23606]

== Fixes

* Fixed an issue where a member with persistence can be restarted even though the persistence file structure is not valid (e.g., the persistence directory does not contain the required files). #5878
* Fixed an issue where Hazelcast was sending empty map interceptor information to the members which are newly joined to the cluster; it was causing eager map initializations.
https://github.com/hazelcast/hazelcast/pull/24667[#24667]
* Fixed an issue where `lastAccessTime` and `expirationTime` were not updated when an entry is accessed via `executeOnEntries`.
https://github.com/hazelcast/hazelcast/pull/24010[#24010]
* Fixed a parsing issue in JSON arrays when using predicate queries; it was causing the JSON query results to be varied according to the property order.
https://github.com/hazelcast/hazelcast/pull/23451[#23451]

== Contributors

We would like to thank the contributors from our open source community who worked on this release:

* https://github.com/azotcsit[Aleksei Zotov]