= 5.0.4
:description: These release notes list any new features, enhancements, and fixes that were made between version 5.0.3 and 5.0.4 of Hazelcast Platform.

{description}

== Enhancements

* You can now provide comma-separated lists to give multiple labels for the Kubernetes Discovery Plugin configurations service-label-name, service-label-value, pod-label-name, and pod-label-value. https://github.com/hazelcast/hazelcast/pull/22402[#22402]
* Improved connection handling.
https://github.com/hazelcast/hazelcast/pull/21642[#21642]
* Upgraded the versions of Hadoop dependencies from 3.3.1 to 3.3.3.
https://github.com/hazelcast/hazelcast/pull/21530[#21530]
* Removed the hazelcast-jet-cdc-mysql module from the Hazelcast Platform Enterprise distributions due to licensing. You need to manually download this module if you have the Enterprise edition. See Capture Changes from MySQL for details. #5313

== Fixes

* Fixed an issue where replication over WAN was failing on the source cluster members, when there are multiple batch publishers configured in a single WAN replication.
https://github.com/hazelcast/hazelcast/pull/22499[#22499]
* Fixed an issue where the cluster was failing to operate since the indexes on backup partitions were removed by `map.ClearBackupOperation`.
https://github.com/hazelcast/hazelcast/pull/22423[#22423]
* Fixed an issue where metadata information such as TTL and maximum idle time were not being replicated via WAN replication.
https://github.com/hazelcast/hazelcast/pull/22337[#22337]
* Fixed an issue where the list of members in the cluster was reset to an empty list when the UUID of a cluster changes after its restart: this was causing startup failures since Hazelcast could not manage the events due to the empty member list after a restart.
https://github.com/hazelcast/hazelcast/pull/21179[#21179]
