= 5.1.6 Release Notes

== Enhancements

* Updated the `parquet` dependency to 1.13.0.
https://github.com/hazelcast/hazelcast/pull/24469[#24469]
* Hazelcast was sending requests to Kubernetes API when deploying an application with embedded Hazelcast and `service-dns` (DNS lookup mode) specified to a Kubernetes cluster.
This was causing the requests to be unsuccessful and the application not to start. This mechanism has been improved by creating Kubernetes client only for the DNS lookup mode.
https://github.com/hazelcast/hazelcast/pull/24044[#24044]
* Updated the `everit-json-schema` dependency to 1.14.2.
https://github.com/hazelcast/hazelcast/pull/23971[#23971]
* When advanced networking is enabled, the Kubernetes discovery plugin might have been discovering several endpoints (per each port)
for each member's pod. The discovery plugin now matches only the private IP per endpoint, ignoring the port values.
https://github.com/hazelcast/hazelcast/pull/23932[#23932]
* Introduced the `hazelcast.discovery.public.address.fallback` property to enable smart client
connectivity to Hazelcast clusters deployed on Kubernetes, and having advanced network configuration enabled.
https://github.com/hazelcast/hazelcast/pull/23921[#23921]

== Fixes

* Fixed an issue where `lastAccessTime` and `expirationTime` was not updated when an entry is accessed via `executeOnEntries`.
https://github.com/hazelcast/hazelcast/pull/24011[#24011]