= 5.1.7 Release Notes

== Enhancements

* Added support of IMDSv2 for Hazelcast’s AWS Discovery plugin.
https://github.com/hazelcast/hazelcast/pull/23594[#23594]
* Updated the version of jackson-core dependency to 2.15.2.
https://github.com/hazelcast/hazelcast/pull/24731[#24731]

== Fixes

* Fixed an issue where Hazelcast was sending empty map interceptor information to the members which are newly joined to the cluster;
it was causing eager map initializations.
https://github.com/hazelcast/hazelcast/pull/24668[#24668]
* Fixed various issues in Health Monitor including incorrect metric names.
https://github.com/hazelcast/hazelcast/pull/24633[#24633]
* Fixed an issue where the REST calls were failing for Hazelcast clusters with TLS v1.3 configured, and deployed on Kubernetes.
https://github.com/hazelcast/hazelcast/pull/24625[#24625]
* Fixed a parsing issue in JSON arrays when using predicate queries; it was causing the JSON query results to be varied according to the property order.
https://github.com/hazelcast/hazelcast/pull/23452[#23452]

== Contributors

We would like to thank the contributors from our open source community who worked on this release:

* https://github.com/azotcsit[Aleksei Zotov]