= 5.2.1 Release Notes

== Enhancements

* Enhanced the experience of using Hazelcast with persistence under Kubernetes by removing requirements for manual interventions.
Previously, when there is a restart on such a cluster, the cluster states were needed to be changed manually. For some cases, this might have led to data loss.
Now, the shutdown process is automated. See xref:deploy:configuring-kubernetes.adoc#running-hazelcast-enterprise-with-persistence-under-kubernetes[Configuring Kubernetes] for details. #5382
* Added the support of discovering ECS and EC2 members on AWS. See xref:deploy:deploying-on-aws.adoc[Deploying a Cluster on Amazon AWS].
https://github.com/hazelcast/hazelcast/pull/22590[#22590]

== Fixes

* Fixed an issue where replication over WAN was failing on the source cluster members, when there are multiple batch publishers configured in a single WAN replication. #5376
* Fixed an issue where the members were crashing while they are loading data into the `NATIVE` memory and using JSON or Kryo serialization. #5385
* Fixed a memory leak due to incomplete clean-up of backup replica sync operations.
https://github.com/hazelcast/hazelcast/pull/22756[#22756]
* Fixed an issue where a map was loading old values with `map.set()` when map store offloading is enabled.
https://github.com/hazelcast/hazelcast/pull/22603[#22603]
* Fixed an issue where the map entries recovered from persistence were not expiring after their time-to-live durations.
https://github.com/hazelcast/hazelcast/pull/22557[#22557]
* Fixed an issue where external data store configurations could not be added dynamically.
https://github.com/hazelcast/hazelcast/pull/22464[#22464]
