= 5.2.5 Release Notes

== Enhancements

* Improved the permission checks in the file connectors by adding a method that returns the permissions required to resolve field names.
https://github.com/hazelcast/hazelcast/pull/25674[#25674]
* Updated the versions of following dependencies:
** Snappy to 1.1.10.5
** gRPC to 1.59
** Netty to 4.1.100.Final
** Elasticsearch to 7.17.13
** Everit JSON Schema to 1.14.3
+
https://github.com/hazelcast/hazelcast/pull/24866[#24866],
https://github.com/hazelcast/hazelcast/pull/25820[#25820],
https://github.com/hazelcast/hazelcast/pull/25708[#25708],
https://github.com/hazelcast/hazelcast/pull/25729[#25729],
https://github.com/hazelcast/hazelcast/pull/25775[#25775]

== Fixes

* Fixed an issue where the entry listeners for Replicated Maps were checking the Map permissions instead of the Replicated Map permissions.
https://github.com/hazelcast/hazelcast/pull/25971[#25971]
* Fixed an issue where the map entries' metadata, such as time-to-live and expiration, was not replicated correctly over WAN after updating existing entries.
https://github.com/hazelcast/hazelcast/pull/25506[#25506]
* Fixed an issue where there was a difference between the elapsed clock time and elapsed total time when listening to migration events.
https://github.com/hazelcast/hazelcast/pull/25066[#25066]
* Fixed an issue where the member list was not updated after a cluster failover scenario.
https://github.com/hazelcast/hazelcast/pull/24944[#24944]
* Renamed the service port for Hazelcast clusters deployed in Kubernetes environments to hazelcast. The previous name, `hazelcast-service-port`, caused member auto-discovery for embedded deployments to fail.
https://github.com/hazelcast/hazelcast/pull/24841[#24841]
* Fixed an issue where Hazelcast was sending empty map interceptor information to the members that are newly joined to the cluster; it was causing eager map initializations.
https://github.com/hazelcast/hazelcast/pull/24669[#24669]

== Removed/Deprecated Features

* Removed the evaluation tool (for trying out Platform 5.x features for IMDG 3.x users) and the relevant IMDG 3.x JAR libraries from Hazelcast Platform distributions.
https://github.com/hazelcast/hazelcast/pull/25697[#25697]

== Contributors

We would like to thank the contributors from our open source community
who worked on this release:

* https://github.com/azotcsit[Aleksei Zotov]
