= 5.2.4 Release Notes

== Enhancements

* Updated the version of `jackson-core` dependency to 2.15.2.
https://github.com/hazelcast/hazelcast/pull/24730[#24730]
* Hazelcast was sending requests to Kubernetes API when deploying an application with embedded Hazelcast and `service-dns` (DNS lookup mode) specified to a Kubernetes cluster. This was causing the requests to be unsuccessful and the application not to start. This mechanism has been improved by creating Kubernetes client only for the DNS lookup mode.
https://github.com/hazelcast/hazelcast/pull/24045[#24045]

== Fixes 

* Fixed an issue where a member with persistence can be restarted even though the persistence file structure is not valid (e.g., the persistence directory does not contain the required files). #5876
* Fixed an issue where some of the members in a Hazelcast cluster deployed on Kubernetes (as a statefulset) shut down with an exception in a delayed manner.
https://github.com/hazelcast/hazelcast/pull/24709[#24709]
* Fixed an issue where Jet job snapshots could be prematurely deleted after a restart of a cluster, having lossless restart enabled.
https://github.com/hazelcast/hazelcast/pull/24576[#24576]
* Fixed an issue where the SELECT COUNT(DISTINCT COLUMN) query for maps was producing incorrect results.
https://github.com/hazelcast/hazelcast/pull/24490[#24490]
* Fixed various issues in xref:maintain-cluster:monitoring.adoc#health-monitor[Health Monitor] including incorrect metric names.
https://github.com/hazelcast/hazelcast/pull/24634[#24634]
* Fixed an issue where the REST calls were failing for Hazelcast clusters with TLS v1.3 configured, and deployed on Kubernetes.
https://github.com/hazelcast/hazelcast/pull/24624[#24624]
* Fixed an issue where SQL statements were failing when a class (to determine the fields of a key/value pair) no longer exists but the mapping is still valid.
https://github.com/hazelcast/hazelcast/pull/24043[#24043]
* Fixed an issue where `lastAccessTime` and `expirationTime` was not updated when an entry is accessed via `executeOnEntries`.
https://github.com/hazelcast/hazelcast/pull/24012[#24012]
