= 5.2.3 Release Notes

== Enhancements

* When advanced networking is enabled, the Kubernetes discovery plugin might have been discovering several endpoints (per each port)
for each member's pod. The discovery plugin now matches only the private IP per endpoint, ignoring the port values.
https://github.com/hazelcast/hazelcast/pull/23931[#23931]
* Introduced the `hazelcast.discovery.public.address.fallback` property to enable smart client
connectivity to Hazelcast clusters deployed on Kubernetes, and having advanced network configuration enabled.
https://github.com/hazelcast/hazelcast/pull/23920[#23920]

== Fixes

* Fixed an issue where a ECS Fargate cluster was failing to start due to the `Failed to configure discovery strategies` error.
https://github.com/hazelcast/hazelcast/pull/23939[#23939]
* Fixed an issue where the Hazelcast configuration was modified by the Jet engine, if the wildcard configuration is used and Jet is enabled; meaning the configurations
made by the user was not being reflected.
https://github.com/hazelcast/hazelcast/pull/23877[#23877]
* Fixed an issue where Debezium connector for MongoDB could not keep the connection after some time.
https://github.com/hazelcast/hazelcast/pull/23690[#23690]
