= 5.3.0 Release Notes

== New Features


== Breaking Changes


== Enhancements

=== Cloud

* Added the support of discovering ECS and EC2 members on AWS. See xref:deploy:deploying-on-aws.adoc[Deploying a Cluster on Amazon AWS].
https://github.com/hazelcast/hazelcast/pull/22411[#22411]
* Enhanced the experience of using Hazelcast with persistence under Kubernetes by removing requirements for manual interventions. Previously, when there is a restart on such a cluster, the cluster states were needed to be changed manually. For some cases, this might have led to data loss. Now, the shutdown process is automated. See xref:deploy:configuring-kubernetes.adoc#running-hazelcast-enterprise-with-persistence-under-kubernetes[Configuring Kubernetes] for details.
https://github.com/hazelcast/hazelcast/pull/21844[#21844]

=== SQL Engine

* Implemented `JSON=VARCHAR` comparison.
https://github.com/hazelcast/hazelcast/pull/22746[#22746]

=== Other Enhancements

* Upgraded Apache Calcite to 1.32.0.
https://github.com/hazelcast/hazelcast/pull/22849[#22849]
* Added flock to guard all pip executions.
https://github.com/hazelcast/hazelcast/pull/22829[#22829]
* Introduced clearer exception messages for Generic MapStore, instead of `UndefinedErrorCodeException`.
https://github.com/hazelcast/hazelcast/pull/22765[#22765]

== Fixes

* Fixed an issue where the beginning time of a job was being recorded after the job is submitted, which was causing a race condition.
https://github.com/hazelcast/hazelcast/pull/23065[#23065]
* Fixed a memory leak due to incomplete clean-up of backup replica sync operations.
https://github.com/hazelcast/hazelcast/pull/22769[#22769]
* Fixed an issue where a map was loading old values with map.set() when map store offloading is enabled.
https://github.com/hazelcast/hazelcast/pull/22602[#22602]
* Fixed an issue where a CP Subsystem object could be destroyed without a permission even the object has security and permission configurations enabled.
https://github.com/hazelcast/hazelcast/pull/22475[#22475]
* Fixed an issue where external data store configurations could not be added dynamically.
https://github.com/hazelcast/hazelcast/pull/22450[#22450]
* Fixed an issue where replication over WAN was failing on the source cluster members, when there are multiple batch publishers configured in a single WAN replication.
https://github.com/hazelcast/hazelcast/pull/22437[#22437]
* Fixed an issue where the map entries recovered from persistence were not expiring after their time-to-live durations.
https://github.com/hazelcast/hazelcast/pull/22279[#22279]

== Removed/Deprecated Features

== Contributors

