= 5.3.3 Release Notes

== Enhancements

* Changed the exception type from `CancellationException` to `CancellationByUserException` in case the user cancels a job before it is initialized.
https://github.com/hazelcast/hazelcast/pull/25452[#25452]
* Updated the gRPC dependency version to 1.57.0.
https://github.com/hazelcast/hazelcast/pull/25430[#25430]
* Renamed the service port for Hazelcast clusters deployed in Kubernetes environments as `hazelcast`.
Previously, the name was `hazelcast-service-port` causing the member auto-discovery (for embedded deployments) to fail.
https://github.com/hazelcast/hazelcast/pull/24834[#24834]

== Fixes

* Fixed an issue where the map entries' metadata, such as time-to-live and expiration, was not replicated correctly over WAN after updating existing entries.
https://github.com/hazelcast/hazelcast/pull/25505[#25505]
* Fixed an issue where the member list was not updated after a cluster failover scenario.
https://github.com/hazelcast/hazelcast/pull/25504[#25504]
* Fixed a memory leak issue happening in Hazelcast members and clients while destroying fenced locks.
https://github.com/hazelcast/hazelcast/pull/25421[#25421]
