= 5.3.0 Release Notes

== New Features

* xref:???.adoc#???[*???*]: ???.


== Breaking Changes

* Changed the default cloud coordinator URL from `coordinator.hazelcast.cloud` to `api.viridian.hazelcast.com`.
The default configuration now connects to https://viridian.hazelcast.com/sign-in?next=/[Hazelcast Viridian^] instead of Hazelcast Cloud.
If you want to continue accessing your Hazelcast Cloud clusters, you need to set the `hazelcast.client.cloud.url` property to `https://coordinator.hazelcast.cloud` in your configuration.
https://github.com/hazelcast/hazelcast/pull/23290[#23290]

== Enhancements

=== Performance

???

=== Cloud

* Added support of link:https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-machine-images-support-instance-metadata-service-version-2-default/#:~:text=Posted%20On%3A%20Oct%203%2C%202022,depth%20against%20unauthorized%20metadata%20access.[IMDSv2^] for Hazelcast's AWS Discovery plugin.
https://github.com/hazelcast/hazelcast/pull/23545[#23545]
* Enhanced the handling of errors coming from the Kubernetes API:
** Not detecting the intent correctly whenever the cluster is shutdown, so the cluster was not restarted successfully.
** Extensive amount of Kubernetes API calls were being logged when Automatic State Management feature is enabled.
+
https://github.com/hazelcast/hazelcast/pull/23538[#23538]
* Added the support of discovering ECS and EC2 members on AWS. See xref:deploy:deploying-on-aws.adoc[Deploying a Cluster on Amazon AWS].
https://github.com/hazelcast/hazelcast/pull/22411[#22411]
* [.enterprise]*Enterprise* Enhanced the experience of using Hazelcast with persistence under Kubernetes by removing requirements for manual interventions. Previously, when there is a restart on such a cluster, the cluster states were needed to be changed manually. For some cases, this might have led to data loss. Now, the shutdown process is automated. See xref:deploy:configuring-kubernetes.adoc#running-hazelcast-enterprise-with-persistence-under-kubernetes[Configuring Kubernetes] for details.
https://github.com/hazelcast/hazelcast/pull/21844[#21844]

=== Distribution

* Shaded dependencies for Hazelcast Platform have been combined in a dedicated package (`com.hazelcast.shaded`).
https://github.com/hazelcast/hazelcast/pull/23124[#23124]

=== SQL Engine

* Improved the nested loop joins algorithm by making the `CreateDagVisitor` interface generic.
https://github.com/hazelcast/hazelcast/pull/23368[#23368]
* Implemented the `TO_CHAR` function which is capable of formatting dates, timestamps, and numbers.
https://github.com/hazelcast/hazelcast/pull/22529[#22529]
* Implemented `JSON=VARCHAR` comparison.
https://github.com/hazelcast/hazelcast/pull/22746[#22746]

=== Jet Engine

* Added new messages (`uploadJobMetaData` and `uploadJobMultipart`) to the binary client protocol to be able to
execute non-Java codes for streaming data pipelines, i.e., to submit Jet jobs.
https://github.com/hazelcast/hazelcast/pull/23212[#23212]
* Updated the https://docs.hazelcast.org/docs/{page-latest-supported-java-client}/javadoc/com/hazelcast/jet/Job.html#isUserCancelled--[job API] to add the ability
to distinguish the user-cancelled jobs from the failed ones.
https://github.com/hazelcast/hazelcast/pull/22924[#22924]
* Added `flock` to guard all the concurrent `pip` executions (upgrading `pip` and `protobuf` versions) in the Jet-to-Python script.
https://github.com/hazelcast/hazelcast/pull/22829[#22829]

=== Security

* Added the TLS configuration property `keyMaterialDuration` which allows using a configurable timeout for caching keyStores and trustStores.
See xref:security:tls-configuration.adoc[TLS Configuration] for the details on how to configure this property.
https://github.com/hazelcast/hazelcast/pull/23307[#23307]

=== Serialization

* Hazelcast now allows serializing unsupported types via xref:serialization:compact-serialization.adoc#using-compact-serialization-with-zero-configuration[zero-configuration]
provided that there is an explicit serializer implemented for the unsupported type.
https://github.com/hazelcast/hazelcast/pull/23449[#23449]
* Setting a generic record now fails if the value is not of the same type of generic record.
https://github.com/hazelcast/hazelcast/pull/23522[#23522]
* Introduced clearer exception messages for Generic MapStore, instead of `UndefinedErrorCodeException`.
https://github.com/hazelcast/hazelcast/pull/22765[#22765]

=== WAN Replication

* Added the REST endpoint `/hazelcast/rest/wan/sync/progress` which allows tracking the WAN synchronization progress.
https://github.com/hazelcast/hazelcast/pull/22958[#22958]

=== Tiered Storage

=== Connectors

* Jet engine's connector for MongoDB is now a part of the Hazelcast Platform distribution.
https://github.com/hazelcast/hazelcast/pull/22565[#22565]

=== Metrics

* Added a new tag to the CP Subsystem metrics to display the client names for CP sessions on Hazelcast Management Center.
https://github.com/hazelcast/hazelcast/pull/23387[#23387]
* Added entry eviction and expiration counts to local map statistics and metrics.
https://github.com/hazelcast/hazelcast/pull/23318[#23318]

=== Other Enhancements

* Added the ability to test whether the connection with a JDBC data store is valid (`testConnection` method for `JdbcDataStoreFactory`).
https://github.com/hazelcast/hazelcast/pull/23405[#23405]
* Upgraded Apache Calcite to 1.32.0.
https://github.com/hazelcast/hazelcast/pull/22849[#22849]

== Fixes

* Fixed an issue where the unordered `mapUsingServiceAsync` was losing items when there are no watermarks.
https://github.com/hazelcast/hazelcast/pull/23271[#23271]
* Fixed an issue where disabling metrics and JMX on a Hazelcast client was failing the members to start.
https://github.com/hazelcast/hazelcast/pull/23360[#23360]
* Fixed an issue where a JDBC related exception message was mentioning data source reference instead of the table name.
https://github.com/hazelcast/hazelcast/pull/23122[#23122]
* Fixed an issue where the beginning time of a job was being recorded after the job is submitted, which was causing a race condition.
https://github.com/hazelcast/hazelcast/pull/23065[#23065]
* Fixed an issue where the `hz-cli` shell script was failing to run in bash on Windows systems since it uses a colon-separated `CLASSPATH`
where each path is a Linux-style path. However, Java on Windows expects a semicolon-separated `CLASSPATH` where each path is a Windows-style path.
As a consequence, the `hz-cli` could not be used from bash on Windows.
https://github.com/hazelcast/hazelcast/pull/22884[#22884]
* Fixed a memory leak due to incomplete clean-up of backup replica sync operations.
https://github.com/hazelcast/hazelcast/pull/22769[#22769]
* Fixed an issue where a map was loading old values with map.set() when map store offloading is enabled.
https://github.com/hazelcast/hazelcast/pull/22602[#22602]
* Fixed an issue where a CP Subsystem object could be destroyed without a permission even the object has security and permission configurations enabled.
https://github.com/hazelcast/hazelcast/pull/22475[#22475]
* Fixed an issue where external data store configurations could not be added dynamically.
https://github.com/hazelcast/hazelcast/pull/22450[#22450]
* Fixed an issue where replication over WAN was failing on the source cluster members, when there are multiple batch publishers configured in a single WAN replication.
https://github.com/hazelcast/hazelcast/pull/22437[#22437]
* Fixed an issue where the map entries recovered from persistence were not expiring after their time-to-live durations.
https://github.com/hazelcast/hazelcast/pull/22279[#22279]

== Known Issues

???

== Contributors

We would like to thank the contributors from our open source community
who worked on this release:

* https://github.com/???[???]

