= 5.3.2 Release Notes

== Enhancements

* Added the ability to replicate eviction events over WAN. See xref:wan:tuning.adoc#replicating-imap-icache-evictions[Replicating Map/Cache Evictions].
https://github.com/hazelcast/hazelcast/pull/25039[#25039]
* Updated the Janino dependency version to 3.1.10.
https://github.com/hazelcast/hazelcast/pull/25094[#25094]

== Fixes 

* Fixed an issue where not all the events were replicated over WAN when one of the target endpoints is down. #6249
* Fixed an issue where the `getDistributedObjects()` was returning inconsistent results when multiple members are simultaneously joining to the cluster.
https://github.com/hazelcast/hazelcast/pull/25153[#25153] 
* Fixed an issue where the Hot Restart procedure was failing on Hazelcast Viridian, when the cluster is in the `FROZEN` state.
https://github.com/hazelcast/hazelcast/pull/25081[#25081] 
* Fixed an issue where the retry mechanism for the communications between CP group members and CP leader was not working, due to incorrect backoff timeout behavior.
https://github.com/hazelcast/hazelcast/pull/25074[#25074] 

