= 5.3.2 Release Notes

== Enhancements

* Updated the Janino dependency version to 3.1.10.
https://github.com/hazelcast/hazelcast/pull/25094[#25094]

== Fixes 

* Fixed an issue where not all the events were replicated over WAN when one of the target endpoints is down. #6249
* Renamed the service port for Hazelcast clusters deployed in Kubernetes environments as `hazelcast`.
Previously, the name was `hazelcast-service-port` causing the member auto-discovery (for embedded deployments) to fail.
https://github.com/hazelcast/hazelcast/pull/25228[#25228]
* Fixed an issue where the `getDistributedObjects()` was returning inconsistent results when multiple members are simultaneously joining to the cluster.
https://github.com/hazelcast/hazelcast/pull/25153[#25153] 
* Fixed an issue where the Hot Restart procedure was failing on Hazelcast Viridian, when the cluster is in the `FROZEN` state.
https://github.com/hazelcast/hazelcast/pull/25081[#25081] 
* Fixed an issue where the retry mechanism for the communications between CP leader and followers was generating too many retries, due to incorrect backoff timeout reset behavior.
https://github.com/hazelcast/hazelcast/pull/25074[#25074] 

