= 5.3.0 Release Notes

WARNING: The minimal supported Java version is 11 starting with this release of Hazelcast Platform.

== New Features

* **xref:integrate:kafka-connect-connectors.adoc[Connector for Kafka Connect source (BETA)]**: Import data from an external system directly into a Hazelcast data pipeline
without the need of a Kafka cluster.
* **xref:integrate:mongodb-connector.adoc[Connector for MongoDB (BETA)]**: Read and write from/to MongoDB via this connector and execute SQL queries on Mongo collections directly from Hazelcast.
* **https://github.com/hazelcast/hazelcast/blob/master/docs/design/sql/16-partition-aware-client.md[Partition-Aware SQL Client]**: Send the SQL commands only to the members having the relevant data, which reduces the network hops and improves the query performances.
* **xref:sql:create-data-connection.adoc[Data Connection Support via SQL]**: Data connections and mappings using them can be managed using SQL commands.

== Breaking Changes

* Renamed the `DataLinkFactory` interface as `DataConnection`.
https://github.com/hazelcast/hazelcast/pull/24224[#24224]
* Removed the `TO_ROW` function as it is obsolete, you can use `CAST (udtObj AS JSON)` instead.
https://github.com/hazelcast/hazelcast/pull/23808[#23808]
* SQL mappings for internal maps (`__sql.catalog` and `__jet.*`) cannot be created anymore.
https://github.com/hazelcast/hazelcast/pull/24282[#24282]
* Changed the default cloud coordinator URL from `coordinator.hazelcast.cloud` to `api.viridian.hazelcast.com`.
The default configuration now connects to https://viridian.hazelcast.com/sign-in?next=/[Hazelcast Viridian Cloud^] instead of Hazelcast Cloud.
If you want to continue accessing your Hazelcast Cloud clusters, you need to set the `hazelcast.client.cloud.url` property to `https://coordinator.hazelcast.cloud` in your configuration.
https://github.com/hazelcast/hazelcast/pull/23290[#23290]

== Enhancements

=== Cloud

* Hazelcast was sending requests to Kubernetes API when deploying an application with embedded Hazelcast and `service-dns` (DNS lookup mode) specified to a Kubernetes cluster.
This was causing the requests to be unsuccessful and the application not to start. This mechanism has been improved by creating Kubernetes client only for the DNS lookup mode.
https://github.com/hazelcast/hazelcast/pull/23883[#23883]
* When advanced networking is enabled, the Kubernetes discovery plugin might have been discovering several endpoints (per each port)
for each member's pod. The discovery plugin now matches only the private IP per endpoint, ignoring the port values.
https://github.com/hazelcast/hazelcast/pull/23766[#23766]
* Added support of link:https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-machine-images-support-instance-metadata-service-version-2-default/#:~:text=Posted%20On%3A%20Oct%203%2C%202022,depth%20against%20unauthorized%20metadata%20access.[IMDSv2^] for Hazelcast's AWS Discovery plugin.
https://github.com/hazelcast/hazelcast/pull/23545[#23545]
* Added the support of discovering ECS and EC2 members on AWS. See xref:deploy:deploying-on-aws.adoc[Deploying a Cluster on Amazon AWS].
https://github.com/hazelcast/hazelcast/pull/22411[#22411]
* [.enterprise]*Enterprise* Enhanced the experience of using Hazelcast with persistence under Kubernetes by removing requirements for manual interventions. Previously, when there is a restart on such a cluster, the cluster states were needed to be changed manually. For some cases, this might have led to data loss. Now, the shutdown process is automated. See xref:kubernetes:kubernetes-auto-discovery.adoc#running-hazelcast-enterprise-with-persistence-under-kubernetes[Configuring Kubernetes] for details.
https://github.com/hazelcast/hazelcast/pull/21844[#21844]

=== Storage

* Added support of generating suggested Data Definition Language (DDL) for a map with High-Density Memory Store and having no indexes.
https://github.com/hazelcast/hazelcast/pull/24054[#24054]
* Disk tier option of Tiered Storage is now disabled by default.
https://github.com/hazelcast/hazelcast/pull/23747[#23747]

NOTE: Tiered Storage feature is still in BETA stage.

=== Distribution

* Hazelcast no longer depends on JRuby; the JRuby `ScriptFactory` dependency must be explicitly added to the application.
https://github.com/hazelcast/hazelcast/pull/23355[#23355]
* Added the Kafka Connect extension to the distribution.
https://github.com/hazelcast/hazelcast/pull/23312[#23312]
* Shaded dependencies for Hazelcast Platform have been combined in a dedicated package (`com.hazelcast.shaded`).
https://github.com/hazelcast/hazelcast/pull/23124[#23124]

=== Networking

* Added socket options for per-socket keep-alive configuration: `keep-count`, `keep-idle-seconds`, and `keep-interval-seconds`.
You can set these options using either the advanced network configurations or Hazelcast system properties.
See xref:clusters:network-configuration.adoc#configuring-tcp-keep-alive[Configuring TCP Keep-Alive].
https://github.com/hazelcast/hazelcast/pull/23816[#23816], https://github.com/hazelcast/hazelcast/pull/24050[#24050]

=== SQL Engine

* The `CREATE MAPPING` statement for Compact Serialization now supports nullable primitives.
https://github.com/hazelcast/hazelcast/pull/24300[#24300]
* Added support of fault tolerance and processing guarantees for stream-to-stream JOINs.
https://github.com/hazelcast/hazelcast/pull/22979[#22979], https://github.com/hazelcast/hazelcast/pull/23462[#23462]
* Implemented the `GET_DDL` function.
https://github.com/hazelcast/hazelcast/pull/23595[#23595]
* Implemented the `SHOW DATA CONNECTIONS` and `SHOW RESOURCES` statements to show the connections and resources created by the `CREATE CONNECTIONS` statement.
https://github.com/hazelcast/hazelcast/pull/24028[#24028], https://github.com/hazelcast/hazelcast/pull/23844[#23844]
* Added support of providing declarative partitioning strategies based on attributes. These attributes represent specific partition keys for a map.
You can also configure this strategy dynamically.
https://github.com/hazelcast/hazelcast/pull/23535[#23535], https://github.com/hazelcast/hazelcast/pull/23954[#23954]
* Added `attributes` and `user_defined_types` tables to `information_schema`.
https://github.com/hazelcast/hazelcast/pull/23267[#23267]
* Made all streaming SQL jobs to be suspending on failure.
https://github.com/hazelcast/hazelcast/pull/23178[#23178]
* Implemented the `TO_CHAR` function which is capable of formatting dates, timestamps, and numbers.
https://github.com/hazelcast/hazelcast/pull/22529[#22529]
* Implemented `JSON=VARCHAR` comparison.
https://github.com/hazelcast/hazelcast/pull/22746[#22746]
* [.enterprise]*Enterprise* Added support of configuring SQL Catalog persistence.
https://github.com/hazelcast/hazelcast/pull/24383[#24383]

=== Jet Engine

* Added support of modifying the job configuration of suspended jobs so that jobs can run without overflow failures by adding more resources.
https://github.com/hazelcast/hazelcast/pull/23862[#23862]
* Each Jet engine job was creating a client for connecting to the remote cluster, resulting in an excessive number of clients.
This has been fixed by introducing a single data connection which can be reused for all job instances.
https://github.com/hazelcast/hazelcast/pull/23472[#23472], https://github.com/hazelcast/hazelcast/pull/23849[#23849]
* Added MongoDB read (source) and write (sink) processors.
https://github.com/hazelcast/hazelcast/pull/23348[#23348]
* Introduced `JobStatusListener` as an alternative to repeatedly retrieve a job status via the `Job.getStatus()` method.
https://github.com/hazelcast/hazelcast/pull/23193[#23193]
* Updated the https://docs.hazelcast.org/docs/{page-latest-supported-java-client}/javadoc/com/hazelcast/jet/Job.html#isUserCancelled--[job API] to add the ability
to distinguish the user-cancelled jobs from the failed ones.
https://github.com/hazelcast/hazelcast/pull/22924[#22924]
* Added `flock` to guard all the concurrent `pip` executions (upgrading `pip` and `protobuf` versions) in the Jet-to-Python script.
https://github.com/hazelcast/hazelcast/pull/22829[#22829]

=== Security

* [.enterprise]*Enterprise* Added the TLS configuration property `keyMaterialDuration` which allows using a configurable timeout for caching keyStores and trustStores.
See xref:security:tls-configuration.adoc[TLS Configuration] for the details on how to configure this property.
https://github.com/hazelcast/hazelcast/pull/23307[#23307]

=== Serialization

* Hazelcast now allows serializing unsupported types via xref:serialization:compact-serialization.adoc#using-compact-serialization-with-zero-configuration[zero-configuration]
provided that there is an explicit serializer implemented for the unsupported type.
https://github.com/hazelcast/hazelcast/pull/23449[#23449]
* Setting a generic record now fails if the value is not of the same type of generic record.
https://github.com/hazelcast/hazelcast/pull/23522[#23522]
* Introduced clearer exception messages for Generic MapStore, instead of `UndefinedErrorCodeException`.
https://github.com/hazelcast/hazelcast/pull/22765[#22765]

=== WAN Replication

* Added the REST endpoint `/hazelcast/rest/wan/sync/progress` which allows tracking the WAN synchronization progress.
https://github.com/hazelcast/hazelcast/pull/22958[#22958]

=== Connectors

* Added support of predicates in DML (Data Manipulation Language) in JDBC SQL connector.
https://github.com/hazelcast/hazelcast/pull/24521[#24521]
* Added the ability to provide host, username, password, and authDB when connecting to a MongoDB, as an alternative to specifying a connection string.
https://github.com/hazelcast/hazelcast/pull/24238[#24238]
* Added the ability to create a mapping with a MongoDB data connections that provides unbounded (streaming) results.
https://github.com/hazelcast/hazelcast/pull/24356[#24356]
* Added compound identifier for the `externalName()` method.
https://github.com/hazelcast/hazelcast/pull/23772[#23772]
* Added an option for the MongoDB source to perform reading with a single processor instance. Usually distributing the operations is a best practice; however,
the `$function` aggregation method is not supported by the Atlas Serverless instances. In this case, this newly introduced option can be used to to query such instances in one processor. See the option's https://github.com/hazelcast/hazelcast/blob/master/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/mongodb/Options.java#L77[documentation]. 
https://github.com/hazelcast/hazelcast/pull/24198/files[#24198]
* Added additional permission checks to JDBC connectors (source and sink). The previous checks in some cases used only the `jdbc:` name in `ConnectorPermission`.
The newly introduced checks get the JDBC URL from existing connection metadata and check if the permission is granted. If want to grant a `ConnectorPermission`
to all JDBC URLs, you may use wildcards, e.g., `jdbc:*`.
https://github.com/hazelcast/hazelcast/pull/23716[#23716]
* Added `DataConnection` for Kafka consumers and producers, and for MongoDB
https://github.com/hazelcast/hazelcast/pull/23886[#23886], https://github.com/hazelcast/hazelcast/pull/23837[#23837]
* Jet engine's connector for MongoDB is now a part of the Hazelcast Platform distribution.
https://github.com/hazelcast/hazelcast/pull/22565[#22565]
* Introduced a way to control the initial partitions offsets when consuming records from Kafka via the Jet engine: by passing an additional topics configuration object that contains definitions of initial offsets for specific partitions.
https://github.com/hazelcast/hazelcast/pull/21546[#21546]

=== Metrics

* Added name of the job to the xref:ROOT:list-of-metrics.adoc#jet-engine-job-specific-metrics[job specific metrics].
https://github.com/hazelcast/hazelcast/pull/23744[#23744]
* Added Tiered Storage compactor metrics to be exposed by the tools and interfaces such as Management Center, JMX, and diagnostics.
https://github.com/hazelcast/hazelcast/pull/23643[#23643]
* Added a new tag to the CP Subsystem metrics to display the client names for CP sessions on Hazelcast Management Center.
https://github.com/hazelcast/hazelcast/pull/23387[#23387]
* Added entry eviction and expiration counts to local map statistics and metrics.
https://github.com/hazelcast/hazelcast/pull/23318[#23318]

=== Other Enhancements

* _External Data Store_ references have been renamed as _Data Connections. This includes the renaming of the `external-data-store` configuration element as `data-connection`.
https://github.com/hazelcast/hazelcast/pull/24224[#24224]
* Added the ability to test whether the connection with a JDBC data link is valid (`testConnection` method for `JdbcDataConnection`).
https://github.com/hazelcast/hazelcast/pull/23405[#23405]
* Upgraded Apache Calcite to 1.32.0.
https://github.com/hazelcast/hazelcast/pull/22849[#22849]

== Fixes

* [.enterprise]*Enterprise* Fixed an issue where a member with persistence can be restarted even though the persistence file structure is not valid (e.g., the persistence directory does not contain the required files). #5861
* [.enterprise]*Enterprise* Fixed an issue where multiple Hazelcast members were able to use the same base directory for Tiered Storage, causing crashes. #5770
* [.enterprise]*Enterprise* Fixed an issue where the members were crashing while they are loading data into the NATIVE memory and using JSON or Kryo serialization. #5384
* [.enterprise]*Enterprise* Fixed an issue where Jet job snapshots could be prematurely deleted after a restart of a cluster, having lossless restart enabled.
https://github.com/hazelcast/hazelcast/pull/24576[#24576]
* Fixed an issue where `map.clear()` was timing out when the map is configured with a generic map store.
https://github.com/hazelcast/hazelcast/pull/24534[#24534] 
* Fixed an issue where the `SELECT COUNT(DISTINCT COLUMN)` query for maps was producing incorrect results.
https://github.com/hazelcast/hazelcast/pull/24464[#24464]
* Fixed an issue where there was a memory leak when Jet engine metrics are enabled.
https://github.com/hazelcast/hazelcast/issues/23492[#23492]
* Fixed an issue where the `DELETE FROM` or `UPDATE` functions, when used with fully-qualified names, was failing in a JDBC table.
https://github.com/hazelcast/hazelcast/issues/23476[#23476]
* Fixed an issue where SQL statements were failing when a class (to determine the fields of a key/value pair) no longer exists but the mapping is still valid.
https://github.com/hazelcast/hazelcast/pull/24003[#24003]
* Fixed an issue where `lastAccessTime` and `expirationTime` was not updated when an entry is accessed via `executeOnEntries`.
https://github.com/hazelcast/hazelcast/pull/23926[#23926]
* Fixed an issue where the Hazelcast configuration was modified by the Jet engine, if the wildcard configuration is used and Jet is enabled; meaning the configurations
made by the user was not being reflected.
https://github.com/hazelcast/hazelcast/pull/23848[#23848]
* Fixed an issue where Hazelcast was failing to connect to a database when using Debezium, and the key of a record is null.
https://github.com/hazelcast/hazelcast/pull/23768[#23768]
* Fixed an issue where the `SELECT` query was returning duplicated rows for the mappings in AWS S3 bucket.
https://github.com/hazelcast/hazelcast/pull/23723[#23723]
* Enabled smart client connectivity to Hazelcast clusters deployed on Kubernetes, when advanced network configuration is enabled.
https://github.com/hazelcast/hazelcast/pull/23707[#23707]
* Fixed an issue where Debezium connector for MongoDB could not keep the connection after some time.
https://github.com/hazelcast/hazelcast/pull/23689[#23689]
* Enhanced the handling of errors coming from the Kubernetes API:
** Not detecting the intent correctly whenever the cluster is shutdown, so the cluster was not restarted successfully.
** Extensive amount of Kubernetes API calls were being logged when Automatic State Management feature is enabled.
+
https://github.com/hazelcast/hazelcast/pull/23538[#23538]
* Fixed an issue where Hazelcast transaction manager was timing out before the timeout value set for the transaction commit.
https://github.com/hazelcast/hazelcast/pull/23471[#23471]
* Fixed an issue where the unordered `mapUsingServiceAsync` was losing items when there are no watermarks.
https://github.com/hazelcast/hazelcast/pull/23271[#23271]
* Fixed an issue where the state of a job was being corrupted if a member is forcefully shut down and the job is restarted from snapshot.
https://github.com/hazelcast/hazelcast/pull/23201[#23201]
* Fixed an issue where disabling metrics and JMX on a Hazelcast client was failing the members to start.
https://github.com/hazelcast/hazelcast/pull/23360[#23360]
* Fixed an issue where a JDBC related exception message was mentioning data source reference instead of the table name.
https://github.com/hazelcast/hazelcast/pull/23122[#23122]
* Fixed an issue where the beginning time of a job was being recorded after the job is submitted, which was causing a race condition.
https://github.com/hazelcast/hazelcast/pull/23065[#23065]
* Fixed an issue where the `hz-cli` shell script was failing to run in bash on Windows systems since it uses a colon-separated `CLASSPATH`
where each path is a Linux-style path. However, Java on Windows expects a semicolon-separated `CLASSPATH` where each path is a Windows-style path.
As a consequence, the `hz-cli` could not be used from bash on Windows.
https://github.com/hazelcast/hazelcast/pull/22884[#22884]
* Fixed a memory leak due to incomplete clean-up of backup replica sync operations.
https://github.com/hazelcast/hazelcast/pull/22769[#22769]
* Fixed an issue where a map was loading old values with map.set() when map store offloading is enabled.
https://github.com/hazelcast/hazelcast/pull/22602[#22602]
* Fixed an issue where a CP Subsystem object could be destroyed without a permission even the object has security and permission configurations enabled.
https://github.com/hazelcast/hazelcast/pull/22475[#22475]
* Fixed an issue where external data store configurations could not be added dynamically.
https://github.com/hazelcast/hazelcast/pull/22450[#22450]
* Fixed an issue where replication over WAN was failing on the source cluster members, when there are multiple batch publishers configured in a single WAN replication.
https://github.com/hazelcast/hazelcast/pull/22437[#22437]
* Fixed an issue where creating a JDBC SQL mapping without specifying the columns was causing the column order to be reversed compared to that in the remote source table (affecting statements such as `SELECT * FROM ...` and `INSERT INTO <mapping> VALUES`.
https://github.com/hazelcast/hazelcast/pull/22410[#22410]
* Fixed an issue where the map entries recovered from persistence were not expiring after their time-to-live durations.
https://github.com/hazelcast/hazelcast/pull/22279[#22279]
* Fixed an issue where Hazelcast members in a Spring Boot application could not establish a connection to each other when deployed
in Kubernetes cluster with Istio Envoy Proxy enabled.
https://github.com/hazelcast/hazelcast/issues/22256[#22256]
* Eliminated the usage of `ForkJoinPool#commonPool` for internal Hazelcast code, improving stability and avoiding potential deadlocks.
https://github.com/hazelcast/hazelcast/issues/18190[#18190]

== Upcoming Deprecations

* Hazelcast will end support for Elasticsearch 6 in the upcoming release (5.4). This will affect you if you are using the xref:integrate:elasticsearch-connector.adoc#installing-the-connector[version 6 module of the Elasticsearch connector].

* Hazelcast will deprecate transactions in the upcoming release (5.4). An improved version of this feature is under consideration. If you are already using transactions, get in touch and share your use case. Your feedback will help us to develop a solution that meets your needs.

== Contributors

We would like to thank the contributors from our open source community
who worked on this release:

* https://github.com/ivyanni[Ilia Vianni]
* https://github.com/xitep[Xitep]
* https://github.com/agrawalprakash[Agrawal Prakash]
* https://github.com/dbaltor[Denis Baltor]
* https://github.com/debanjanc01[Debanjan Choudhury]
* https://github.com/Nikhil2508[Nikhil Umraliya]
* https://github.com/erdinctaskin[Erdinc Taskin]
* https://github.com/TureBentzin[Ture Bentzin]
* https://github.com/jxblum[John Blum]
* https://github.com/anestoruk[Andrzej Nestoruk]
