= 5.4.0-BETA-2 Release Notes

CAUTION: Starting with this release of Hazelcast Platform, the minimum supported Java version is 17.

== New Features

* **User Code Namespaces**: Enable deployment, undeployment and redeployment of your custom classes.
* [.enterprise]*Enterprise* **CPMap**:  Added CPMap as a minimal key-value CP data structure. See xref:data-structures:cpmap.adoc[CPMap documentation].
https://github.com/hazelcast/hazelcast/pull/25802[#25802]

== Breaking Changes

* The `MergingValue` interface within the SPI package now requires the `getDeserializedValue()` method to be defined within implementations, replacing the `getValue()` definition.
https://github.com/hazelcast/hazelcast/pull/25942[#25942]
* Serialized forms of the following have been changed:
** `FunctionEx.compose`, `FunctionEx.andThen`, `BiFunctionEx.andThen`, `ConsumerEx.andThen`: Any Jet pipeline using these methods (directly or indirectly, such as `AggregateOperation.andThen`) has to be redeployed from the updated client.
** `peekInputP`, `peekOutputP`, `peekSnapshotP` with the `SupplierEx`: Any Jet pipeline using these processors has to be redeployed from the updated client. These are only for diagnostics and available only in the core API.
+
Due to the above changes, Jet jobs may fail to work properly in the clusters with mixed forms (before and after this change). The changes may also affect the jobs where processor fusing is performed.
+
https://github.com/hazelcast/hazelcast/pull/25966[#25966]
* Moved the MongoDB connector to the extensions module, that is, its classes and related dependencies relocated;
if you are using Maven to install the connector, you must add `<classifier>jar-with-dependencies</classifier>` to your `pom.xml`.
Also removed the permissions for MongoDB connector.
https://github.com/hazelcast/hazelcast/pull/25744[#25744], https://github.com/hazelcast/hazelcast/pull/25701[#25701]
* Changed the return values for `getMethodName()` of the following message task classes:
** `MapFetchKeysMessageTask`: `iterator` -> `SecurityInterceptorConstants.ITERATOR_FETCH_KEYS`
** `MapFetchWithQueryMessageTask.`: `iterator` -> `SecurityInterceptorConstants.ITERATOR_FETCH_WITH_QUERY`
** `MapProjectionWithPredicateMessageTask`: `projectWithPredicate` -> `SecurityInterceptorConstants.PROJECT`
** `ScheduledExecutorGetAllScheduledMessageTask`: `getAllScheduled` -> `SecurityInterceptorConstants.GET_ALL_SCHEDULED_FUTURES`
** `ScheduledExecutorSubmitToPartitionMessageTask`: `submitToPartition` -> `SecurityInterceptorConstants.SCHEDULE_ON_PARTITION`
** `ScheduledExecutorSubmitToTargetMessageTask`: `submitToAddress` -> `SecurityInterceptorConstants.SCHEDULE_ON_MEMBER`
** `ScheduledExecutorTaskGetResultFromPartitionMessageTask`: `getResultTimeout` -> `SecurityInterceptorConstants.GET_RESULT`
** `ScheduledExecutorTaskGetResultFromTargetMessageTask`: `getResultTimeout` -> `SecurityInterceptorConstants.GET_RESULT`
** `SetGetAllMessageTask`: `iterator` -> `SecurityInterceptorConstants.GET_ALL`
** `TransactionalListAddMessageTask`: `set` -> `SecurityInterceptorConstants.ADD`
** `TransactionalMultiMapRemoveEntryMessageTask`: `removeEntry` -> `SecurityInterceptorConstants.REMOVE`
+
https://github.com/hazelcast/hazelcast/pull/25020[#25020]
* Renamed the service port for Hazelcast clusters deployed in Kubernetes environments to `hazelcast`.
The previous name, `hazelcast-service-port`, caused member auto-discovery for embedded deployments to fail.
https://github.com/hazelcast/hazelcast/pull/24834[#24834], https://github.com/hazelcast/hazelcast/issues/24705[#24705], https://github.com/hazelcast/hazelcast/issues/24688[#24688]
* Fixed an issue where Hazelcast was not fast-failing when a member is started with a blank public address. This has been fixed by introducing a configuration validation
that might break any existing, but invalid, configuration.
https://github.com/hazelcast/hazelcast/pull/24729[#24729]

== Enhancements

=== SQL/Jet Engine

* Removed the beta annotations from the data connection classes.
https://github.com/hazelcast/hazelcast/pull/26000[#26000]
* Replaced the user-defined types (UDTs) feature flag with the cyclic UDT feature flag, to prevent querying such type data.
https://github.com/hazelcast/hazelcast/pull/25977[#25977]
* Added support for loading and storing a single column as the value using the `GenericMapStore`.
https://github.com/hazelcast/hazelcast/pull/25878[#25878]
* Each Jet engine job was creating a client for connecting to the remote cluster, resulting in an excessive number of clients. This has been fixed by introducing a single data connection which can be reused for all job instances.
https://github.com/hazelcast/hazelcast/pull/25754[#25754], https://github.com/hazelcast/hazelcast/pull/25731[#25731]
* Added support of resolving fields from Avro schemas in Kafka mappings.
https://github.com/hazelcast/hazelcast/pull/25935[#25935]
* Changed the exception type from `CancellationException` to `CancellationByUserException` when the user cancels a job before it is initialized.
https://github.com/hazelcast/hazelcast/pull/25383[#25383]
* Added nested field support for Avro serialization format.
https://github.com/hazelcast/hazelcast/pull/25269[#25269]
* Removed the redundant sort and merge operations in sorted index scans, for the computations where the index order is not needed, for example, aggregations.
https://github.com/hazelcast/hazelcast/pull/25180[#25180]
* Updated the data comparator to improve the performance of sorted index operations.
https://github.com/hazelcast/hazelcast/pull/25196[#25196]
* Added support for partition pruning for the `__key` filters.
https://github.com/hazelcast/hazelcast/pull/25105[25105]
* Added support for partitioned edges in Jet engine's partition pruning.
https://github.com/hazelcast/hazelcast/pull/25062[#25062]
* Added a new mechanism to compute the required partitions to be scanned, if attribute partitioning strategy is applied.
https://github.com/hazelcast/hazelcast/pull/25006[#25006]
* Added the condition type to the `EXPLAIN PLAN` statement outputs for all physical joins.
https://github.com/hazelcast/hazelcast/pull/24899[#24899]
* Added support for nullable types when reading Avro files.
https://github.com/hazelcast/hazelcast/pull/24840[#24840]
* Added the ability to pass parameters for JDBC configuration, such as the fetch size for large tables.
https://github.com/hazelcast/hazelcast/pull/24835[#24835]
* Added support for partition pruning for SQL queries that have trivial filter predicates.
https://github.com/hazelcast/hazelcast/pull/24813[#24813]
* Reflected the https://blogs.oracle.com/javamagazine/post/transition-from-java-ee-to-jakarta-ee[change^] of `javax.jms` to `jakarta.jms` in Hazelcast distributions.
https://github.com/hazelcast/hazelcast/pull/24804[#24804]
* Added support for member pruning for Platform jobs to optimize a job's performance by picking up only the members required for the job.
https://github.com/hazelcast/hazelcast/pull/24689[#24689]
* Added the `stream()` method to the SQL service to return the stream of result rows.
https://github.com/hazelcast/hazelcast/pull/24525[#24525]
* Boxing of partitionId is now avoided in the `getPartitionAssignment()` method when the partition pruning is not used. #486
* Added the ability to limit the creation of objects through reflection. #296
* Added the ability to use reusable processor meta supplier for `forceTotalParallelismOne ()` on random members without permissions. #227
* Added a comparator for the High-Density Memory Store's index entries. Previously, on-heap entries comparators were used which causes incorrect query outputs. #52


=== Connectors

* Implemented a new SQL mapping option to define the preferred local parallelism for connectors that support configuring it. Currently, only the Kafka connector supports this.
See xref:sql:mapping-to-kafka.adoc#creating-a-kafka-mapping[Creating a Kafka Mapping] for example configurations.
https://github.com/hazelcast/hazelcast/pull/26194[#26194]
* Removed the beta annotations from the MongoDB classes.
https://github.com/hazelcast/hazelcast/pull/25743[#25743]
* Added TLS support for MongoDB data connections.
https://github.com/hazelcast/hazelcast/pull/25301[#25301]
* Added support Oracle databases support by the JDBC SQL connector.
https://github.com/hazelcast/hazelcast/pull/25255[#25255]
* Added support for inline Avro schemas for Kafka mappings.
https://github.com/hazelcast/hazelcast/pull/25207[#25207]
* Added support for `DataSerializable` serialization to Mongo connector.
https://github.com/hazelcast/hazelcast/pull/25197[#25197]
* Check for existing resources for Mongo connector is now done only once; previously, it was performed on every processor.
https://github.com/hazelcast/hazelcast/pull/24953[#24953]
* Hazelcast JDBC connector now supports Microsoft SQL server.
https://github.com/hazelcast/hazelcast/pull/25071[#25071]
* Added the ability to configure the pool size of a MongoDB data connection. See xref:sql:mapping-to-mongo.adoc#creating-a-mongodb-mapping[Creating a MongoDB Mapping].
https://github.com/hazelcast/hazelcast/pull/25027[#25027]

=== Data Structures

* Added support of specifying the maximum size of a CPMap.
https://github.com/hazelcast/hazelcast/pull/25881[#25881]
* Added Java client support for CPMap.
https://github.com/hazelcast/hazelcast/pull/25877[#25877]
* Added check for negative positions on the collections' `getItemAtPositionOrNull()` method.
https://github.com/hazelcast/hazelcast/pull/25672[#25672]
* Introduced a cluster state check to improve the removal of expired map/cache entries from the cluster.
The removal operation is no longer executed if the cluster is in passive state.
https://github.com/hazelcast/hazelcast/pull/24808[#24808]
* Added the `IMap.localValues()` and `IMap.localValues(Predicate)` methods for a faster access to locally owned values in maps.
https://github.com/hazelcast/hazelcast/pull/24673[#24763]
* Added the `deleteAsync()` for maps to asynchronously remove a provided map entry key.
https://github.com/hazelcast/hazelcast/pull/23509[#23509]
* Fixed the Javadoc for caches where it was referring incorrectly to statistics instead of management, for the `setManagementEnabled()` method.
https://github.com/hazelcast/hazelcast/pull/22575[#22575]
* Added the `getCPGroupIds()` method to the CP Subsystem API to allow listing all data structures within a CP group. #591
* The "last update time" record of the map entries recovered from the disk persistence is not used anymore when calculating the entries' expiration times. #233
* [.enterprise]*Enterprise* Added the ability to check whether the `ADVANCED_CP` feature is present in the Hazelcast Platform Enterprise license, to enable CPMap. #157

=== WAN Replication

* Improved dead connection handling for WAN replication static IP discovery, by introducing health check to the discovery strategy.
https://github.com/hazelcast/hazelcast/pull/25364[#25364]
* Added support for the dynamic adding of WAN replication configurations using Java API.
https://github.com/hazelcast/hazelcast/pull/25118[#25118]
* Added support for evicting map and cache entries through WAN replication by introducing two new properties. When enabled, WAN replication
events are fired when values are evicted from the map and cache objects. See xref:wan:tuning.adoc#replicating-imap-icache-evictions[Replicating `IMap`/`ICache` Evictions].
https://github.com/hazelcast/hazelcast/pull/24941[#24941]

=== Security

* Added the ability to check map permissions before suggesting a schema; if a client has permission to read a map then a suggestion with schema is sent, otherwise a warning is produced saying no
permissions to read maps has been set.
https://github.com/hazelcast/hazelcast/pull/26058[#26058]
* Updated permission checks in `CacheCreateConfig` and `GetSemaphoreType` tasks.
https://github.com/hazelcast/hazelcast/pull/25529[#25529]
* Improved the permission checks in the file connectors by adding a method that returns the permissions required to resolve field names.
https://github.com/hazelcast/hazelcast/pull/25348[#25348]
* Added support for permission subtraction (deny permissions) in client connections. See xref:security:native-client-security.adoc#deny-permissions[Deny Permissions].
https://github.com/hazelcast/hazelcast/pull/25154[#25154]

=== Storage

* Improved the hit/miss cache statistics counter performance.
https://github.com/hazelcast/hazelcast/pull/25146[#25146]
* Tiered Store can now be used for map loaders.
https://github.com/hazelcast/hazelcast/pull/24827[#24827]
* Added the ability to persist namespaces for Hot Restart. #402

=== Networking

* Added the ability to evaluate priorities while picking member addresses; when interfaces are not configured, the first possible IP address is no longer used. Instead, all addresses are evaluated and the one with the highest priority (IPv6 address) is selected.
https://github.com/hazelcast/hazelcast/pull/25305[#25305]
* Added the `demoteLocalDataMember()` method to convert members holding data to lite members, enabling a cluster to be alive while there is no data in it.
https://github.com/hazelcast/hazelcast/pull/24617[#24617]
* Improved the duration of joins by the clients to the cluster; the clients can now join instantaneously without waiting by internally delaying the migrations asynchronously.
https://github.com/hazelcast/hazelcast/pull/17582[#17582]

=== Serialization

* Added the ability to use consistent serialization service for `ByKey` plans.
https://github.com/hazelcast/hazelcast/pull/25631[#25631]
* Serialization service is not created anymore for light jobs as it creates overhead and generates garbage. #235, #449

=== Cloud

* Enhanced the warning message shown in the cases of incorrect configurations when deploying a Hazelcast client on Amazon EKS.
https://github.com/hazelcast/hazelcast/pull/25568[#25568]
* Added the ability to retry DNS resolutions for the Kubernetes discovery plugin. #445

=== Metrics and Logs

* Disabled the log4j2 shutdown hook for cleaner shutdown logs after a Hazelcast Platform cluster deployed on Kubernetes is shutdown.
https://github.com/hazelcast/hazelcast/pull/26006[#26006]
* Enabled faster execution times and more efficient garbage collection by making method probes to use `MethodHandle` instead of reflections.
https://github.com/hazelcast/hazelcast/pull/25279[#25279]
* Improved the naming convention for CP Session, Lock, and Persistence metrics.
https://github.com/hazelcast/hazelcast/pull/24843[#24843], https://github.com/hazelcast/hazelcast/pull/24836[#24836]
* Added `status` and `userCancelled` flags to job metrics.
https://github.com/hazelcast/hazelcast/pull/24716[#24716]
* Removed the stack trace for WAN connection exception since its content was the same as the exception log itself. #578
* Added the ability to collect job execution metrics only from the members which run the job. #194

=== Events and Listeners

* Added the `onCancel()` method to the reliable message listener to trigger a notification when the listener is cancelled for any reason. #286

=== REST API

* Added the new `RestConfig` tag under the server `Config`; it allows configuration of the new REST API server. #508
# Added the health check endpoints for the new REST API; these include state of the members and cluster, and the member count. #192

=== Distribution

* Improved the binary scripts of Hazelcast Platform for Windows operating systems.
** `common.bat` has been updated to not include excessive spaces in parameters.
** `hz-cli.bat` and `hz-start.bat` have been updated to reference the `common.bat` script with correct paths.
** `hz-start.bat` has been updated to remove double quote expansion for `CLASSPATH`.
+
#165
* Updated the versions of following dependencies:
** Snappy to 1.1.10.5
** Netty to 4.1.99.Final
** Jackson to 2.14.2
** Avro to 1.11.3
+
https://github.com/hazelcast/hazelcast/pull/24863[#25607],
https://github.com/hazelcast/hazelcast/pull/25555[#25555],
https://github.com/hazelcast/hazelcast/pull/25576[#25576],
https://github.com/hazelcast/hazelcast/issues/22407[#22407]
* Upgraded the Hazelcast Platform's `pom.xml` to use JDK 17, as it requires at minimum JDK 17. #436
* Updated the copyright year to 2024 in the codebase. #396

=== Licensing

* License keys are now masked in the license expiration notifications.
https://github.com/hazelcast/hazelcast/pull/24800[#24800]

== Fixes

* Fixed an issue where sending internal Debezium messages was causing failures when connecting to databases.
https://github.com/hazelcast/hazelcast/pull/26027[#26027]
* Fixed an issue where the entry listeners for Replicated Maps was checking the Map permissions instead of the Replicated Map ones.
https://github.com/hazelcast/hazelcast/pull/25965[#25965]
* Fixed an issue where the queries with indexes were producing duplicate results or failing.
https://github.com/hazelcast/hazelcast/pull/25527[#25527]
* Fixed an issue where the map entries' metadata, such as time-to-live and expiration, was not replicated correctly over WAN after updating existing entries.
https://github.com/hazelcast/hazelcast/pull/25481[#25481]
* Fixed an issue where the loading of compact-serialized generic records by the complex classloaders, such as `JetClassLoader`) were likely to cause deadlocks.
https://github.com/hazelcast/hazelcast/pull/25379[#25379]
* Fixed a memory leak issue happening in Hazelcast members and clients while destroying fenced locks.
https://github.com/hazelcast/hazelcast/pull/25353[#25353]
* Fixed an issue where the sorted index scans were hanging or producing duplicate values when there are many entries with the same key.
https://github.com/hazelcast/hazelcast/pull/25328[#25328]
* Fixed an issue where setting indexes in a different order, while dynamically adding a map configuration, was failing.
https://github.com/hazelcast/hazelcast/pull/25234[#25234]
* Fixed an issue where the diagnostic tool was showing the suggestion of enabling it, even it is already enabled.
https://github.com/hazelcast/hazelcast/pull/25220[#25220]
* Fixed an issue where clearing an inexistent map was resulting in an exception.
https://github.com/hazelcast/hazelcast/pull/25202[#25202]
* Fixed an issue where the mechanism to retrieve partitioning strategy on a client was ignoring to check the provided Hazelcast cluster properties.
https://github.com/hazelcast/hazelcast/pull/25162[#25162]
* Fixed an issue where `ClientConfigXmlGenerator` didn't have the support for `hazelcast-cloud` configuration.
https://github.com/hazelcast/hazelcast/pull/25155[#25155]
* Fixed an issue where the cache provider was not able to read the YAML configurations.
https://github.com/hazelcast/hazelcast/pull/25137[#25137]
* Fixed an issue where the `getDistributedObjects()` was returning inconsistent results when multiple members are simultaneously joining to the cluster.
https://github.com/hazelcast/hazelcast/pull/25114[#25114]
* Fixed an issue where zero-config compact serialization was not working on the objects that have a field of type `java.util.UUID`.
https://github.com/hazelcast/hazelcast/pull/25073[#25073]
* Fixed an issue where the retry mechanism for the communications between CP leader and followers was generating too many retries, due to incorrect backoff timeout reset behavior.
https://github.com/hazelcast/hazelcast/pull/25055[#25055]
* Fixed an issue where there was a difference between the elapsed clock time and elapsed total time when listening to migration events.
https://github.com/hazelcast/hazelcast/pull/25028[#25028]
* Fixed an issue where the transaction in the Kafka producer was not committed when a batch job is finished.
https://github.com/hazelcast/hazelcast/pull/25024[#25024]
* Fixed an issue where data events were being fired through WAN replication after a split-brain, even there were no changes in data.
https://github.com/hazelcast/hazelcast/pull/24928[#24928]
* Fixed an issue where the lite members were not reporting statistics for map operations.
https://github.com/hazelcast/hazelcast/pull/24871[#24871]
* Fixed an issue where the blacklisting was being ignored after a split-brain happens.
https://github.com/hazelcast/hazelcast/pull/24830[#24830]
* Fixed an issue where the Kinesis sink might loose data, when retrying on failures, during a terminal snapshot.
https://github.com/hazelcast/hazelcast/pull/24779[#24779]
* Fixed an issue where the member list was not updated after a cluster failover scenario.
https://github.com/hazelcast/hazelcast/pull/24745[#24745]
* Fixed an issue where the batches produced for write-behind queues were not having the expected size of entries.
 https://github.com/hazelcast/hazelcast/issues/24763[#24763]
* Fixed an issue where the fused Jet vertex was ignoring the configured local parallelism and using the default parallelism instead.
https://github.com/hazelcast/hazelcast/issues/24683[#24683]
* Fixed an issue where Hazelcast was sending empty map interceptor information to the members which are newly joined to the cluster; it was causing eager map initializations.
https://github.com/hazelcast/hazelcast/pull/24639[#24639]
* Fixed an issue where the REST calls were failing for Hazelcast clusters with TLS v1.3 configured, and deployed on Kubernetes.
https://github.com/hazelcast/hazelcast/pull/24616[#24616]
* Fixed an issue where the predicates did not have managed context injection when the predicate is local or not serialized.
https://github.com/hazelcast/hazelcast/pull/24463[#24463]
* Fixed an issue where the results of the stream-to-stream join could not be inserted into the remote table connected via JDBC, causing an exception.
https://github.com/hazelcast/hazelcast/issues/22459[#22459]
* Fixed an issue when querying JSON, elements that appear after an element containing nested JSON was not appearing in the query results. #570
* Fixed an issue where data was lost from the ICache data structure with `NATIVE` entries in a split-brain scenario. #480
* Fixed an issue where the `ANALYZE INSERT INTO` SQL statement did not generate metrics. #444
* [.enterprise]*Enterprise* Fixed an issue where the map entries with time-to-live values were being removed as soon as the cluster with persistence enabled is restarted. #233
* Fixed an issue where map entries' metadata were replicated incorrectly over WAN after a merge, causing deserialization of values. #225
* Fixed an issue where the process of retrieving metrics for job executions was entering into an infinite loop, when a job execution is completed on a member but continues on the other members.
With this fix, only the members on which the jobs have not been completed are queried for metrics; for completed jobs, the metrics are already retrieved from the completed jobs context. #194
* Fixed an issue where the attribute partitioning strategy was not working with Compact and Portable classes. #127

== Removed/Deprecated Features

* The connector for Elasticsearch 6 is removed, as the Elasticsearch 6 module is removed from Hazelcast distributions.
https://github.com/hazelcast/hazelcast/pull/24734[#24734]
* The evaluation tool for IMDG 3.x users (Hazelcast 3 Connector) is removed. In the upcoming releases, a new tooling for migrating data from 3.x versions will be introduced.
https://github.com/hazelcast/hazelcast/pull/25051[#25051]
* Transactions are deprecated, will be removed as of Hazelcast Platform version 7.0.
** Only maintenance support will be provided for transactions.
** Transactions will no longer be actively developed.
** Issues arising from new or existing implementations of transactions will no longer be supported.
+
In the meantime, if you are already using transactions and want to discuss alternatives, please get in touch with xref:getting-started:support.adoc[Hazelcast Support].
* Portable Serialization is deprecated. We recommend you to use Compact Serialization as Portable Serialization will be removed as of Hazelcast Platform version 7.0.
* The user code deployment API is deprecated, and will be removed in Hazelcast Platform version 6.0. #223

== Contributors

We would like to thank the contributors from our open source community
who worked on this release:

* https://github.com/hhromic[Hugo Hromic]
* https://github.com/aditya-32[Aditya Ranjan Barik]
* https://github.com/azotcsit[Aleksei Zotov]
* https://github.com/LarsKrogJensen[LarsKorgJensen]
* https://github.com/vladykin[Alexey Vladykin]
* https://github.com/lprimak[Lenny Primak]
* https://github.com/lfgcampos[Lucas Campos]
* https://github.com/tommyk-gears[Tommy Karlsson]
* https://github.com/vinicius-colutti[Vinicius Colutti]
* https://github.com/lukasblu[Lukas Blunschi]