= 5.4.0 Release Notes

WARNING: The minimal supported Java version is 11 starting with this release of Hazelcast Platform.

== New Features

* **xref:???.adoc[???]**: ???

== Breaking Changes

* Renamed the service port for Hazelcast clusters deployed in Kubernetes environments as `hazelcast`.
Previously, the name was `hazelcast-service-port` causing the member auto-discovery (for embedded deployments) to fail.
https://github.com/hazelcast/hazelcast/pull/24834[#24834], https://github.com/hazelcast/hazelcast/issues/24705[#24705], https://github.com/hazelcast/hazelcast/issues/24688[#24688]
* The connector for Elasticsearch 6 does not exist anymore since the Elastichsearch 6 module has been removed from the Hazelcast distributions.
https://github.com/hazelcast/hazelcast/pull/24734[#24734]
* Fixed an issue where Hazelcast was not fast-failing when a member is started with a blank public address. This has been fixed by introducing a configuration validation
which may break the existing invalid configurations.
https://github.com/hazelcast/hazelcast/pull/24729[#24729]

== Enhancements

=== Cloud

* ???
* [.enterprise]*Enterprise* ???

=== Storage

* ???

=== Distribution

* ???

=== Networking

* ???

=== SQL/Jet Engine

* Added the ability to pass parameters for JDBC configuration, such as the fetch size for large tables.
https://github.com/hazelcast/hazelcast/pull/24835[#24835]
* Introduced member pruning for Platform jobs to optimize a job's performance by picking up only the members required for the job.
https://github.com/hazelcast/hazelcast/pull/24689[#24689]
* Added the `stream()` method to the SQL service to return the stream of result rows.
https://github.com/hazelcast/hazelcast/pull/24525[#24525]

=== Security

* ???

=== Serialization

* ???

=== WAN Replication

* ???

=== Connectors

* ???

=== Metrics

* ???

=== Licensing

* License keys are now being masked in the license expiration notifications.
https://github.com/hazelcast/hazelcast/pull/24800[#24800]

=== Other Enhancements

* Updated the versions of Snappy, Netty and Jackson dependencies to `1.1.10.1`, `4.1.94.Final` and `2.14.2`, respectively.
https://github.com/hazelcast/hazelcast/pull/24863[#24863], https://github.com/hazelcast/hazelcast/pull/24885[#24885], https://github.com/hazelcast/hazelcast/issues/22407[#22407]
* Introduced a cluster state check to improve the removal of expired map/cache entries from the cluster.
The removal operation now is not being executed if the cluster is in passive state.
https://github.com/hazelcast/hazelcast/pull/24808[#24808]

== Fixes

* Fixed an issue where the lite members were not reporting statistics for map operations.
https://github.com/hazelcast/hazelcast/pull/24871[#24871]
* Fixed an issue where the blacklisting was being ignored after a split-brain happens.
https://github.com/hazelcast/hazelcast/pull/24830[#24830]
* Fixed an issue where the member list was not updated after a cluster failover scenario.
https://github.com/hazelcast/hazelcast/pull/24745[#24745]
* Fixed an issue where the batches produced for write-behind queues were not having the expected size of entries.
 https://github.com/hazelcast/hazelcast/issues/24763[#24763]
* Fixed an issue where the fused Jet vertex was ignoring the configured local parallelism and using the default parallelism instead.
https://github.com/hazelcast/hazelcast/issues/24683[#24683]
* Fixed an issue where Hazelcast was sending empty map interceptor information to the members which are newly joined to the cluster; it was causing eager map initializations.
https://github.com/hazelcast/hazelcast/pull/24639[#24639]
* Fixed an issue where the REST calls were failing for Hazelcast clusters with TLS v1.3 configured, and deployed on Kubernetes.
https://github.com/hazelcast/hazelcast/pull/24616[#24616]
* Fixed an issue where the predicates did not have managed context injection when the predicate is local or not serialized.
https://github.com/hazelcast/hazelcast/pull/24463[#24463]
* Fixed an issue where the results of the stream-to-stream join could not be inserted into the remote table connected via JDBC, causing an exception.
https://github.com/hazelcast/hazelcast/issues/22459[#22459]

== Removed/Deprecated Features

* ???

== Upcoming Deprecations

???

== Contributors

We would like to thank the contributors from our open source community
who worked on this release:

* https://github.com/aditya-32[Aditya Ranjan Barik]
* https://github.com/azotcsit[Aleksei Zotov]
