= 5.5.0 Release Notes


== New Features

* **xref:???[???]**: 

== Breaking Changes

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

== Enhancements

=== Cloud

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

=== Storage

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

=== Distribution

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

=== Networking

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

=== SQL Engine

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

=== Jet Engine

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

=== Security

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

=== Serialization

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

=== WAN Replication

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

=== Connectors

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

=== Metrics

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

== Fixes

* Fixed an issue where the `AddIndexBackupOperation` operation was not allowed in the cluster when it is in the passive state. [#1076]
* Fixed an issue where the deferred post-join operations were not executed when a member joins an active cluster and the cluster is forced to restart. [#1037]
* Eliminated the possibility of data loss when partition migrations and replications overlap. [#992]

== Removed/Deprecated Features

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

== Upcoming Deprecations

* ???
https://github.com/hazelcast/hazelcast/pull/???[#???]

== Contributors

We would like to thank the contributors from our open source community
who worked on this release:

* https://github.com/???[???]
