= 5.5.1 Release notes
:description: These release notes list any new features, enhancements, fixes, and breaking changes implemented between version 5.5.0 and version 5.5.1 of Hazelcast Platform.

{description}

This is a maintenance release for {enterprise-product-name}. 

For help downloading Hazelcast {enterprise-product-name}, see xref:getting-started:install-enterprise.adoc[] or https://hazelcast.com/trial-request/?utm_source=docs-website[request a trial license key].

== Known issues
* There is currently a known issue that has potential for causing a memory leak in Vector collections in some scenarios (AI-133). For more info, including a workaround, see xref:data-structures:vector-collections.adoc#known-issue[Vector Collection Known Issue].

== Fixes
* Fix partition table snapshot selection when partitions not distributed correctly after all members restarted and persistence is enabled (SUP-538)
* Fix some invocations not de-registered due to invocation method (SUP-543)
* Fix `ClassCastException` when Offloadable EntryProcessor used with Interceptor (SUP-551)
* Fix HD memory exception with Thread-Per-Core (TPC) (SUP-502)
* Disable TPC if `ALL_MEMBERS` routing is not configured (HZG-69)
