= 5.5.2 Release Notes
:description: These release notes list any new features, enhancements, fixes, and breaking changes implemented between version 5.5.2 and version 5.5.3 of Hazelcast Platform.

{description}

This is a maintenance release for {Enterprise Edition}. 

For help downloading Hazelcast {enterprise-product-name}, see xref:getting-started:install-hazelcast.adoc[] or https://hazelcast.com/trial-request/?utm_source=docs-website[request a trial license key].

== Enhancements
* CP: Enhance error message that the client receives when the CP system is reset (SUP-117)
* Set license.extractor.version to 7.0.2 (SUP-667)
* Add IPv6 support for the AWS discovery for the client (SUP-653)

For more details on new features, see xref:ROOT:whats-new.adoc[What's new in 5.5].

== Known issues
* There is currently a known issue that has potential for causing a memory leak in Vector collections in some scenarios (AI-133). For more info, including a workaround, see xref:data-structures:vector-collections.adoc#known-issue[Vector Collection Known Issue].

== Fixes

* Fix task config publishing in Kafka Connect
* Fix UCN + Object format migration
* 14775: IllegalStateException - NodeEngine context is not available for Namespaces in Hazelcast 5.5.0 (SUP-572)

== Security

* Security Fix for CVE-2023-45676
We have resolved https://github.com/advisories/GHSA-gcg6-xv4f-f749[CVE-2023-45676], a vulnerability related to improper authorization checks in certain scenarios. This issue could potentially allow attackers to bypass expected permission restrictions.

// new sections we could consider including

// == Dependency changes
// == Version changes
// == Downloads
// == Resolved issues
// could combine with Fixes or explain context of SUP #s. Are SUPs private only to raiser? List multiples if several customers raise same issue? DO we ever get fixes without issues, SUP or otherwise?