= Providing XA Transactions

[NOTE]
.Transactions Support 5.3 onwards 
====
An improved version of transactions is in development, and will be available in an upcoming release (5.5).

* For new transaction implementations, Hazelcast recommends waiting for the 5.5 release.
* For existing implementations, support will continue until the release of 5.5.
====

XA describes the interface between the global transaction manager and the
local resource manager. XA allows multiple resources (such as databases,
application servers, message queues and transactional caches) to be accessed
within the same transaction, thereby preserving the ACID properties across
applications. XA uses a two-phase commit to ensure that all resources either
commit or rollback any particular transaction consistently (all do the same).

When you implement the `XAResource` interface, Hazelcast provides XA transactions.
You can obtain the `HazelcastXAResource` instance via the `HazelcastInstance getXAResource`
method. You can see the HazelcastXAResource API
https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/transaction/HazelcastXAResource.html[here^].

Below is example code that uses JTA API for transaction management.

[source,java]
----
include::ROOT:example$/transactions/XATransaction.java[tag=xa]
----
