= Providing XA Transactions

[CAUTION]
.Deprecation Notice for Transactions
====
Hazelcast will deprecate transactions in the upcoming release (5.4). An improved version of this feature is under consideration. If you are already using transactions, get in touch and share your use case. Your feedback will help us to develop a solution that meets your needs.
====

XA describes the interface between the global transaction manager and the
local resource manager. XA allows multiple resources (such as databases,
application servers, message queues and transactional caches) to be accessed
within the same transaction, thereby preserving the ACID properties across
applications. XA uses a two-phase commit to ensure that all resources either
commit or rollback any particular transaction consistently (all do the same).

When you implement the `XAResource` interface, Hazelcast provides XA transactions.
You can obtain the `HazelcastXAResource` instance via the `HazelcastInstance getXAResource`
method. You can see the HazelcastXAResource API
https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/transaction/HazelcastXAResource.html[here^].

Below is example code that uses JTA API for transaction management.

[source,java]
----
include::ROOT:example$/transactions/XATransaction.java[tag=xa]
----
