= Implementing HazelcastInstanceAware

You can implement the `HazelcastInstanceAware` interface to access
distributed objects for cases where an object is deserialized and needs access to HazelcastInstance.

Let's implement it for the `Employee` class mentioned in the
xref:custom-serialization.adoc[Custom Serialization section].

[source,java]
----
include::ROOT:example$/serialization/PersonAwr.java[tag=personawr]
----

After deserialization, the object is checked to see if it implements
`HazelcastInstanceAware` and the method `setHazelcastInstance` is called.
Notice the `hazelcastInstance` is `transient`. This is because this field should not be serialized.

It may be a good practice to inject a HazelcastInstance into a domain object,
e.g., `Employee` in the above example, when used together with `Runnable`/`Callable` implementations.
These runnables/callables are executed by `IExecutorService` which sends them to another machine.
And after a task is deserialized, run/call method implementations need to access HazelcastInstance.

We recommend you only set the HazelcastInstance field while using
`setHazelcastInstance` method and you not execute operations on the HazelcastInstance.
The reason is that when HazelcastInstance is injected for a `HazelcastInstanceAware` implementation,
it may not be up and running at the injection time.