= Serialization Interface Types

For complex objects, use the following interfaces for serialization and deserialization:

* `java.io.Serializable`: See the xref:implementing-java-serializable.adoc[Implementing Java Serializable and Externalizable section].
* `java.io.Externalizable`: See the xref:implementing-java-serializable.adoc#implementing-java-externalizable[Implementing Java Externalizable section].
* `com.hazelcast.nio.serialization.DataSerializable`: See the xref:implementing-dataserializable.adoc[Implementing DataSerializable section].
* `com.hazelcast.nio.serialization.IdentifiedDataSerializable`: See the xref:implementing-dataserializable.adoc#identifieddataserializable[IdentifiedDataSerializable section].
* `com.hazelcast.nio.serialization.Portable`: See the xref:implementing-portable-serialization.adoc[Implementing Portable Serialization section].
* Custom Serialization (using xref:custom-serialization.adoc#implementing-streamserializer[StreamSerializer] and xref:custom-serialization.adoc#implementing-bytearrayserializer[ByteArraySerializer]).
* Global Serializer: See the xref:global-serializer.adoc[Global Serializer section] for details.

When Hazelcast serializes an object:

. It first checks whether the object is `null`.
. If the above check fails, then Hazelcast checks if it is an instance of `com.hazelcast.nio.serialization.DataSerializable` or `com.hazelcast.nio.serialization.IdentifiedDataSerializable`.
. If the above check fails, then Hazelcast checks if it is an instance of `com.hazelcast.nio.serialization.Portable`.
. If the above check fails, then Hazelcast checks if it is an instance of one of
the default types (see the xref:serialization.adoc[Serialization chapter introduction] for default types).
. If the above check fails, then Hazelcast looks for a user-specified xref:custom-serialization.adoc[Custom Serializer],
i.e. an implementation of `ByteArraySerializer` or `StreamSerializer`.
Custom serializer is searched using the input Object's Class and its parent class up to Object.
If parent class search fails, all interfaces implemented by the class are also checked (excluding `java.io.Serializable` and `java.io.Externalizable`).
. If the above check fails, then Hazelcast checks if it is an instance of `java.io.Serializable` or
`java.io.Externalizable` and a Global Serializer is not registered with Java Serialization Override feature.
. If the above check fails, Hazelcast uses the registered Global Serializer if one exists.

If all the above checks fail, then serialization fails.
When a class implements multiple interfaces, the above steps are important
to determine the serialization mechanism that Hazelcast uses.
When a class definition is required for any of these serializations, you need to have
all the classes needed by the application on your classpath because Hazelcast does not
download them automatically, unless you are using xref:clusters:deploying-code-on-member.adoc[user code deployment].