= Data Structure Connectors
:description: Data structure connectors allow you to access data stored in Hazelcast data structures. Use these connectors to integrate Hazelcast data structures into your pipelines as sources or sinks.

Hazelcast comes with connectors for the following data structures:

- xref:map-connector.adoc[Map]
- xref:list-connector.adoc[List]
- xref:jcache-connector.adoc[JCache]
- xref:reliable-topic-connector.adoc[Reliable topic]

It's possible to use the data structures that are part of the same Hazelcast
cluster, and share the same memory and computation resources with
running jobs. For a more in-depth discussion on this topic, see
the xref:architecture:in-memory-storage.adoc[].

== Accessing Data Structures on Remote Clusters

With the Jet API, you can also read from or write to data structures from
remote Hazelcast clusters.

NOTE: With SQL, you can only access local maps.

When reading or writing to remote data structures, Hazelcast internally creates a
client using the supplied configuration and will create connections to
the other cluster.

```java
ClientConfig cfg = new ClientConfig();
cfg.setClusterName("cluster-name");
cfg.getNetworkConfig().addAddress("node1.mydomain.com", "node2.mydomain.com");

Pipeline p = Pipeline.create();
p.readFrom(Sources.remoteMap("inputMap", cfg));
...
```

This client uses the embedded Hazelcast version to connect to the
remote cluster. Hazelcast server and client
versions are backward and forward compatible within the same major
version.