= Clients Overview

Hazelcast Platform clients and programming language APIs allow you to extend the benefits of
operational in-memory computing to applications in these languages. These clients and APIs are open source.

Hazelcast has clients in Java, C++, .NET, Node.js, Go, and Python. You can use these clients to communicate with cluster members.

See the following for each client's documentation:

* xref:clients:java.adoc[Java]
* xref:clients:cplusplus.adoc[C++]
* xref:clients:dotnet.adoc[.NET]
* xref:clients:nodejs-quickstart.adoc[Node.js]
* xref:clients:go.adoc[Go]
* xref:clients:python.adoc[Python]

== Client Operation Modes

Hazelcast clients have two operation modes due to the distributed nature of the data and cluster.

**Smart Client**: In the smart mode, the clients connect to each cluster member.
Since each xref:overview:data-partitioning.adoc[data partition] uses the well known and consistent hashing algorithm,
each client can send an operation to the cluster member that owns the partition that holds their data,
which increases the overall throughput and efficiency. Smart mode is the default mode.

**Unisocket Client**: For some cases, the clients can be required to connect to
a single member instead of each member in the cluster. Firewalls, security, or
some custom networking issues can be the reason for these cases.

In the unisocket client mode, the clients only connect to one of the configured addresses.
This single member behaves as a gateway to the other members.
For any operation requested from the client, it redirects the request to the relevant member and
returns the response back to the client returned from that member.

== Maximum Number of Client Connections Per Member

Hundreds or even thousands of clients can be connected to the cluster.
By default, members have `core count * 20` threads that
handle all the requests. For example, if a member has 4 cores, it will have 80 threads available to handle requests.

== Serialization in Client/Server Mode

In xref:overview:topology.adoc[client/server topologies], you can serialize your data
on the client side before sending it to a member. For example, you can serialize data in
JSON and add it to a map. This option is useful if you plan on using Hazelcast to store your
data in binary. Clients can handle serialization without the members needing to know how to do so.

For details about why you need to serialize data and the options for doing so, see xref:serialization:serialization.adoc[Serialization].

== Versioning of Clients

??? https://hazelcast.slack.com/archives/C016TGXPWPJ/p1635786602085100 ???

== Feature Comparison

Not all features are available in all clients.

To find out which features are available in each client,
see the link:https://hazelcast.com/clients/[clients page].

After selecting the language you need, you can find the table showing supported features on the selected language.

== Using Clients with Hazelcast Enterprise 

You do not need to set a license key for your clients for which you want to
use Hazelcast Enterprise features. Hazelcast Enterprise license keys are
required to be set only on the cluster servers.


