= C++ Client
:page-api-reference: http://hazelcast.github.io/hazelcast-cpp-client/{page-latest-supported-cplusplus-client}/index.html
[[c-client]]

You can use the native {cpp} client to connect to Hazelcast cluster members and
perform almost all operations that a member can perform.
Clients differ from members in that clients do not hold data. The {cpp} client is
by default a smart client, i.e., it knows where the data is and asks directly for the correct member.
You can disable this feature (using the `ClientConfig::setSmart` method) if you do not want
the clients to connect to every member.

The features of {cpp} clients are listed below:

* Access to distributed data structures (IMap, IQueue, MultiMap, ITopic, etc.).
* Access to transactional distributed data structures (TransactionalMap, TransactionalQueue, etc.).
* Ability to add cluster listeners to a cluster and entry/item listeners to distributed data structures.
* Distributed synchronization mechanisms with ILock, ISemaphore and ICountDownLatch.

See Hazelcast C++ client's own GitHub https://github.com/hazelcast/hazelcast-cpp-client[repo^]
for information about setting the client up, installing and compiling it,
its serialization support and APIs such as raw pointer and query.
You can also find https://github.com/hazelcast/hazelcast-cpp-client/tree/master/examples[code samples^]
for this client in this repo.