= C++ Client
:page-api-reference: http://hazelcast.github.io/hazelcast-cpp-client/{page-latest-supported-cplusplus-client}/index.html
[[c-client]]

The Hazelcast native {cpp} client is an official library that allows {cpp} applications to connect to and interact with Hazelcast clusters. The key features and benefits include:

* Distributed Data Structures: The client offers access to various distributed data structures such as Map, Queue, Set, List, MultiMap, and RingBuffer. It also gives access to transactional distributed data structures such as transactional_map, transactional_queue, etc.
* Near Cache Support: The Near Cache feature allows frequently read data to be stored for faster read speeds compared to traditional caches
* Enterprise-Level security: the client provides SSL support for enhanced security requirements
* Distributed synchronization: the client offers distributed synchronization mechanisms through the CP Subsystem, including fenced_lock, counting_semaphore and latch
* Smart Client functionality: by default, it operates as a smart client, meaning it knows the data location within the cluster and can directly request the correct member (note that you can disable this feature using the `client_config::set_smart_routing` method if you do not want the clients to connect to every member)
* Listeners: ability to add cluster listeners to a cluster and entry/item listeners to distributed data structures
* Cloud integration: it offers the ability to discover existing Hazelcast clusters in an AWS environment
* Asynchronous operations: the client supports asynchronous execution of tasks in the cluster and non-blocking asynchronous methods for improved performance
* Flexible installation: it can be installed using package managers like Vcpkg or Conan, or built from source using CMake

By using the Hazelcast {cpp} client, developers can build high-performance, distributed applications in {cpp} that leverage Hazelcast's powerful in-memory computing platform.

== Next steps

For the latest {cpp} API documentation, see http://hazelcast.github.io/hazelcast-cpp-client/{page-latest-supported-cplusplus-client}/index.html[Hazelcast {cpp} Client docs].

For information on setting up, installing and compiling the client, and about its serialization, query support and available APIs, see the https://github.com/hazelcast/hazelcast-cpp-client[Hazelcast {cpp} Client GitHub repo]. 
You can also find https://github.com/hazelcast/hazelcast-cpp-client/tree/master/examples[code samples^]
for this client in this repo.
