= {cpp} Client
:page-api-reference: http://hazelcast.github.io/hazelcast-cpp-client/{page-latest-supported-cplusplus-client}/index.html
[[c-client]]

This section provides information about the {cpp} client for Hazelcast, and explains how to get started with the client.

The Hazelcast native {cpp} client is an official library that allows {cpp} applications to connect to and interact with Hazelcast clusters. The key features and benefits include:

* Distributed Data Structures: the client offers access to various distributed data structures such as Map, Queue, Set, List, MultiMap, and RingBuffer. It also gives access to transactional distributed data structures such as transactional_map, transactional_queue, etc.
* Near Cache Support: the Near Cache feature allows frequently read data to be stored for faster read speeds compared to traditional caches
* Enterprise-Level security: the client provides SSL support for enhanced security requirements
* Distributed synchronization: the client offers distributed synchronization mechanisms through the CP Subsystem, including fenced_lock, counting_semaphore and latch
* Smart Client functionality: by default, it operates as a smart client, meaning it knows the data location within the cluster and can directly request the correct member (note that you can disable this feature using the `client_config::set_smart_routing` method if you do not want the clients to connect to every member)
* Listeners: ability to add cluster listeners to a cluster and entry/item listeners to distributed data structures
* Cloud integration: it offers the ability to discover existing Hazelcast clusters in an AWS environment
* Asynchronous operations: the client supports asynchronous execution of tasks in the cluster and non-blocking asynchronous methods for improved performance
* Flexible installation: it can be installed using package managers like Vcpkg or Conan, or built from source using CMake

With the Hazelcast {cpp} client, developers can build high-performance, distributed applications in {cpp} that leverage Hazelcast's powerful in-memory computing platform.

#AUTHORS NOTE—is the following talking about the {cpp} client API or the open client protocol?# 
The client API is fully asynchronous. The API returns `boost::future` API which has the capability of 
https://www.boost.org/doc/libs/1_74_0/doc/html/thread/synchronization.html#thread.synchronization.futures.then[continuations]. To make sure the requested operation is completed in the cluster and committed in the distributed database, you must wait for the result of the future. 

TIP: For the latest {cpp} API documentation, see http://hazelcast.github.io/hazelcast-cpp-client/{page-latest-supported-cplusplus-client}/index.html[Hazelcast {cpp} Client docs].

The {cpp} client uses Hazelcast's https://github.com/hazelcast/hazelcast-client-protocol[Open Client Protocol]. 
This is the client-server protocol that Hazelcast uses to communicate with the clients. 


== Next steps

For information on setting up, installing and compiling the client, and about its serialization, query support and available APIs, see the https://github.com/hazelcast/hazelcast-cpp-client[Hazelcast {cpp} Client GitHub repo]. 
You can also find https://github.com/hazelcast/hazelcast-cpp-client/tree/master/examples[code samples^]
for this client in this repo.

To learn how to get started quickly with the  {cpp} client for Hazelcast, follow our simple tutorial
xref:clients:cpp-client-getting-started.adoc[Get started with {cpp}] 