= {cpp} Client
:page-api-reference: http://hazelcast.github.io/hazelcast-cpp-client/{page-latest-supported-cplusplus-client}/index.html
[[c-client]]

== Overview

This section provides information about the {cpp} client for Hazelcast, and explains how to install and use the client.

TIP: To learn how to get started quickly with the Hazelcast {cpp} client, follow our simple xref:clients:cpp-client-getting-started.adoc[Get started with {cpp}] tutorial.

The Hazelcast native {cpp} client is an official library that allows {cpp} applications to connect to and interact with Hazelcast clusters. With the Hazelcast {cpp} client, developers can build high-performance, distributed applications in {cpp} that leverage Hazelcast's powerful in-memory computing platform.
The key features and benefits include:

* Distributed Data Structures: the client offers access to various distributed data structures such as Map, Queue, Set, List, MultiMap, and RingBuffer. It also gives access to transactional distributed data structures such as transactional_map, transactional_queue, etc.
* Near Cache Support: the Near Cache feature allows frequently read data to be stored for faster read speeds compared to traditional caches
* Enterprise-Level security: the client provides SSL support for enhanced security requirements
* Distributed synchronization: the client offers distributed synchronization mechanisms through the CP Subsystem, including fenced_lock, counting_semaphore and latch
* Smart Client functionality: by default, it operates as a smart client, meaning it knows the data location within the cluster and can directly request the correct member (note that you can disable this feature using the `client_config::set_smart_routing` method if you do not want the clients to connect to every member)
* Listeners: ability to add cluster listeners to a cluster and entry/item listeners to distributed data structures
* Cloud integration: it offers the ability to discover existing Hazelcast clusters in an AWS environment
* Asynchronous operations: the client supports asynchronous execution of tasks in the cluster and non-blocking asynchronous methods for improved performance
* Flexible installation: it can be installed using package managers like Vcpkg or Conan, or built from source using CMake

#AUTHORS NOTE—is the following from the Ref Manual talking about the {cpp} client API or the open client protocol? Do we want to highlight the continuations feature here?# 
The client API is fully asynchronous. The API returns `boost::future` API which has the capability of 
https://www.boost.org/doc/libs/1_74_0/doc/html/thread/synchronization.html#thread.synchronization.futures.then[continuations]. To make sure the requested operation is completed in the cluster and committed in the distributed database, you must wait for the result of the future. 

TIP: For the latest {cpp} API documentation, see http://hazelcast.github.io/hazelcast-cpp-client/{page-latest-supported-cplusplus-client}/index.html[Hazelcast {cpp} Client docs].

The {cpp} client uses Hazelcast's https://github.com/hazelcast/hazelcast-client-protocol[Open Client Protocol]. 
This is the client-server protocol that Hazelcast uses to communicate with the clients. 

== Install the {cpp} client

This section explains how to install the Hazelcast {cpp} client.

=== Vcpkg users
Hazelcast {cpp} client package is available for https://github.com/microsoft/vcpkg[Vcpkg] users. The package name is `hazelcast-cpp-client`.

See https://github.com/microsoft/vcpkg#getting-started[Get started with vcpkg] to learn how to use the Vcpkg package manager with your application. In summary:

If you use Linux or Mac:

```sh
git clone https://github.com/microsoft/vcpkg --branch 2025.02.14
./vcpkg/bootstrap-vcpkg.sh
./vcpkg/vcpkg install "hazelcast-cpp-client[openssl]" --recurse
``` 

If you use Windows:

```bat
git clone https://github.com/microsoft/vcpkg --branch 2025.02.14
.\vcpkg\bootstrap-vcpkg.bat
.\vcpkg\vcpkg install "hazelcast-cpp-client[openssl]:x64-windows" --recurse
``` 
The above code snippet installs `hazelcast-cpp-client` with its `boost` and `openssl` dependencies.

After installation, the library is available to use. For example, if you are using CMake for your builds, you can use the following cmake build command with the `CMAKE_TOOLCHAIN_FILE` cmake option to be the `vcpkg.cmake`.
```bat
cmake -B [build directory] -S . -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake
cmake --build [build directory]
```

=== Conan users
The Hazelcast {cpp} client package is indexed at https://conan.io/center/hazelcast-cpp-client[Conan Center Index]. You can use the https://conan.io/[Conan package manager] to install Hazelcast {cpp} client. The package name is `hazelcast-cpp-client`.

See https://docs.conan.io/en/latest/getting_started.html#an-md5-hash-calculator-using-the-poco-libraries[example instructions] on how to use the Conan package manager with your application. In summary:

- Put the following lines into your `conanfile.txt`:
```
[requires]
hazelcast-cpp-client/5.2.0

[generators]
cmake
```
- Then, execute the following:
```
$ mkdir build && cd build
$ conan install ..
```
This generates the `conanbuildinfo.cmake` file to be included in your CMakeLists.txt. Follow the instructions at the https://docs.conan.io/en/latest/getting_started.html#an-md5-hash-calculator-using-the-poco-libraries[example page] and build your application.

=== Install from source code using CMake
==== Requirements
1. Linux, macOS or Windows
2. A compiler that supports {cpp}11
3. https://cmake.org[CMake] 3.10 or above
4. https://www.boost.org[Boost] 1.71 or above. Minimum boost version is upgraded to 1.73 for Windows due to https://github.com/chriskohlhoff/asio/issues/431[this] bug.
5. https://www.openssl.org[OpenSSL] (optional)

==== Download source code
Go to the https://github.com/hazelcast/hazelcast-cpp-client/releases[releases] page to download the source code for the latest Hazelcast {cpp} client.

The releases page has both `tar.gz` and `zip` archives available. Choose the one that best suits your system.

Follow the instructions for your platform:

==== Linux and MacOS users
To download and extract version 5.2.0 using the **curl** command:
```sh
curl -Lo hazelcast-cpp-client-5.2.0.tar.gz https://github.com/hazelcast/hazelcast-cpp-client/archive/v5.2.0.tar.gz
tar xzf hazelcast-cpp-client-5.2.0.tar.gz
```

Alternatively, clone the repository and checkout a specific version:
```sh
git clone https://github.com/hazelcast/hazelcast-cpp-client.git
cd hazelcast-cpp-client
git checkout v5.2.0
```

Once you are in the source directory of the Hazelcast {cpp} client library, create and change into a new directory:
```sh
cd hazelcast-cpp-client-5.2.0
mkdir build
cd build
```

Run `cmake` (or `cmake3` if you are on CentOS or RHEL) to configure:
```sh
cmake ..
```
See the XREF Advanced installation section below for configuration options.

Run `cmake` again to build and install the library:
```sh
cmake --build . 
sudo cmake --build . --target install
```

You can speed up the build process with parallel threads like 'cmake --build . -j 4'

For information on how to use a different installation location, see XREF Custom install location below.

==== Windows users
Download and extract the release archive from the 
https://github.com/hazelcast/hazelcast-cpp-client/releases[releases] page.

Open a `cmd` window and change into the folder where you extracted the contents of the release archive. Then create and change into a new directory:
```bat
cd hazelcast-cpp-client-5.2.0
mkdir build
cd build
```

Run `cmake` to configure:
```bat
cmake ..
``` 
See the #1135-advanced-installation[advanced installation] section for configuration options.

Build and install:
```bat
cmake --build . --config Release
cmake --build . --target install --config Release
```
The above commands will build and install the library with the `Release` configuration. Make sure you pass the same `--config` option to both commands.

The install command may require administrator privileges depending on your install prefix. See #11351-custom-install-location[this section] for information on how to use a different installation location.

==== Advanced installation

===== Custom install location
The first time you run `cmake`, pass the argument `-DCMAKE_INSTALL_PREFIX=/path/to/install` to configure the installation directory:
```sh
cmake .. -DCMAKE_INSTALL_PREFIX=/path/to/install
```

===== CMake configuration
You can provide additional configuration options using the `-DVARIABLE=VALUE` syntax on the command line. Below are all the supported options:

- `WITH_OPENSSL` : Set to `ON` to build the library with SSL support.
This will require https://www.openssl.org[OpenSSL] to be installed on your system. The default is `OFF`.
- `BUILD_SHARED_LIBS` : Set to `ON` or `OFF` depending on whether you want the shared(ON) or static(OFF) library. The default is `ON`.
- `DISABLE_LOGGING` : Setting this option to `ON` disables logging. The default is `OFF`.

For example, if you want to build the static library with SSL support, use the following command:

```sh
cmake .. -DWITH_OPENSSL=ON -DBUILD_SHARED_LIBS=OFF
```

NOTE: If you want to use the `hazelcast-cpp-client` library with `-DWITH_OPENSSL=ON` option without `find_package()` you must define `HZ_BUILD_WITH_SSL` symbolic constant before including any `hazelcast-cpp-client` header. This symbolic constant can be defined via compiler options or can be passed directly through cmake command as `-DVARIABLE=VALUE` pairs.

For example:
```sh
g++ -DHZ_BUILD_WITH_SSL -DBOOST_CHRONO_DYN_LINK -DBOOST_CHRONO_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DBOOST_THREAD_VERSION=5 -I/var/git/hazelcast-cpp-client/build/include -std=gnu++11 -c main.cpp
```

== Next steps

#AUTHORS NOTE—update depending on what content is included here# 

For information on setting up, installing and compiling the client, and about its serialization, query support and available APIs, see the https://github.com/hazelcast/hazelcast-cpp-client[Hazelcast {cpp} Client GitHub repo]. 
You can also find https://github.com/hazelcast/hazelcast-cpp-client/tree/master/examples[code samples^]
for this client in this repo.

To learn how to get started quickly with the  {cpp} client for Hazelcast, follow our simple tutorial
xref:clients:cpp-client-getting-started.adoc[Get started with {cpp}] 