= C++ Client
:page-api-reference: http://hazelcast.github.io/hazelcast-cpp-client/{page-latest-supported-cplusplus-client}/index.html
[[c-client]]

You can use the native {cpp} client to connect to Hazelcast cluster members and
perform almost all operations that a member can perform.
Clients differ from members in that clients do not hold data. By default, the {cpp} client uses
the `ALL_MEMBERS` cluster routing mode; that is, it knows where the data is and asks directly for the correct member.
If you do not want the clients to connect to every member, you can use the `client_config::cluster-routing` method
to connect to a single member or a subset of the members.

The features of {cpp} clients are listed below:

* Access to distributed data structures (`imap`, `iqueue`, `multi_map`, etc.).
* Access to transactional distributed data structures (`transactional_map`, `transactional_queue`, etc.).
* Ability to add cluster listeners to a cluster and entry/item listeners to distributed data structures.
* Distributed synchronization mechanisms with `fenced_lock`, `counting_semaphore` and `latch`.

See Hazelcast C++ client's own GitHub https://github.com/hazelcast/hazelcast-cpp-client[repo^]
for information on setting the client up, installing and compiling it, its serialization, query support and available APIs.
You can also find https://github.com/hazelcast/hazelcast-cpp-client/tree/master/examples[code samples^]
for this client in this repo.
