= .NET Client
:page-api-reference: http://hazelcast.github.io/hazelcast-csharp-client/{page-latest-supported-csharp-client}/api/index.html
[[net-client]]


The Hazelcast native .NET client is an official library that allows .NET applications to connect to and interact with Hazelcast clusters. The key features and benefits include:

* Distributed Data Structures: It provides access to Hazelcast's distributed data structures such as maps, queues, topics, and more
* SQL Support: The client allows running SQL queries over distributed data
* Near Cache: It supports Near Cache for faster read speeds. Eventual consistency is also supported
* Security Features: The client offers SSL support and Mutual Authentication for enterprise-level security needs
* JSON Object Support: It allows using and querying JSON objects
* Zero Downtime Upgrades: Blue/Green failover for zero downtime during upgrades is supported
* Scalability: The Hazelcast .NET Client is designed to scale up to hundreds of members and thousands of clients, making it suitable for large-scale applications

These features make the Hazelcast .NET Client ideal for .NET applications requiring high-performance, scalable, and distributed data processing capabilities.

== Next steps

For the latest .NET API documentation, see http://hazelcast.github.io/hazelcast-csharp-client/{page-latest-supported-csharp-client}/api/index.html[Hazelcast .NET Client docs].

For more information about configuring, starting, and using the client, see the Hazelcast .NET client GitHub http://hazelcast.github.io/hazelcast-csharp-client/latest/doc/download-install.html[documentation^]. You can also find https://github.com/hazelcast/hazelcast-csharp-client/tree/master/src/Hazelcast.Net.Examples[code samples^]
for the client in this repo.
