= Getting Started with a Hazelcast Client
:description: Hazelcast has clients in Java, .NET, Python, {cpp}, Go, and Node.js. You can use these clients to communicate with cluster members.

{description}

For an overview of available clients, see the xref:client-overview.adoc[Client Overview].   
For documentation and code samples for each client, see the following:

* xref:java.adoc[Java]
* xref:dotnet.adoc[.NET]
* xref:python.adoc[Python]
* xref:cplusplus.adoc[{cpp}]
* xref:go.adoc[Go]
* xref:nodejs.adoc[Node.js]

To learn how to get started quickly with the Hazelcast clients, follow our simple tutorials. These are practical, step-by-step guides to help you get started with using Hazelcast clients in various programming languages. The tutorials are ideal for developers new to Hazelcast, to learn how to integrate Hazelcast's distributed computing capabilities into their applications. These tutorials typically cover the following aspects:

1. Setting up a Hazelcast client.
2. Connecting to a Hazelcast cluster (usually a cloud instance).
3. Performing basic operations like putting data into a distributed map.

See the following:

* xref:clients:java-client-getting-started.adoc[Get started with Java]
* xref:clients:csharp-client-getting-started.adoc[Get started with .NET]
* xref:clients:python-client-getting-started.adoc[Get started with Python]
* xref:clients:cpp-client-getting-started.adoc[Get started with {cpp}]
* xref:clients:go-client-getting-started.adoc[Get started with Go]
* xref:clients:nodejs-client-getting-started.adoc[Get started with Node.js]

Alternatively, you can use xref:memcache.adoc[Memcache] to communicate directly with a Hazelcast cluster, or use the xref:rest.adoc[REST] API for simple operations. 

Additional tools are available to help operate and manage Hazelcast Platform clusters:

* xref:{page-latest-supported-mc}@management-center:getting-started:overview.adoc[Management Center]
* link:https://docs.hazelcast.com/operator/latest/[Platform Operator]
* xref:{page-latest-supported-clc}@clc::overview.adoc[Command Line Client (CLC)]
