= Getting Started with a Hazelcast Client
:description: Hazelcast clients allow you to connect to Hazelcast clusters to request data, listen to events, submit data processing jobs and more.

{description}

Imagine a trading application where all trading data is stored and
managed in a Hazelcast cluster with tens of members. Swing/Web applications
at the traders' desktops can use clients to access and modify the data in the Hazelcast cluster.

To get started with a Hazelcast client, see the following:

* xref:java.adoc[Java]
* xref:cplusplus.adoc[C++]
* xref:dotnet.adoc[.NET]
* xref:memcache.adoc[Memcache]
* xref:rest.adoc[REST]
* xref:nodejs.adoc[Node.js]
* xref:go.adoc[Go]
* xref:python.adoc[Python]

== Feature Comparison for Hazelcast Clients

To find out which features are available for each client, see the https://hazelcast.com/clients/[feature comparison matrix^].

== Maximum Number of Client Connections Per Member

Hundreds or even thousands of clients can be connected to the cluster.
By default, members have `core count * 20` threads that
handle all the requests. For example, if a member has 4 cores, it will have 80 threads available to handle requests.



