= Getting Started with a Hazelcast Client
:description: Hazelcast has clients in Java, C++, .NET, Node.js, Go, Python, and Memcache. You can use these clients to communicate with cluster members.

{description}

For documentation and code samples for each client, see the following:

* xref:java.adoc[Java]
* xref:cplusplus.adoc[C++]
* xref:dotnet.adoc[.NET]
* xref:memcache.adoc[Memcache]
* xref:rest.adoc[REST]
* xref:nodejs.adoc[Node.js]
* xref:go.adoc[Go]
* xref:python.adoc[Python]

== Feature Comparison for Hazelcast Clients

Not all features are available in all clients.

To find out which features are available in each client,
see the link:https://hazelcast.com/clients/[clients page].

After selecting the language you need, you can find the table showing supported features on the selected language.

== Maximum Number of Client Connections Per Member

The maximum recommended number of clients per member is 100.
By default, members have `core count * 20` threads that handle all the requests.
For example, if a member has 4 cores, it will have 80 threads available to handle requests.

== Serialization in Client/Server Mode

In xref:deploy:choosing-a-deployment-option.adoc[client/server topologies], you can serialize your data
on the client side before sending it to a member. For example, you can serialize data in
JSON and add it to a map. This option is useful if you plan on using Hazelcast to store your
data in binary. Clients can handle serialization without the members needing to know how to do so.

For details about why you need to serialize data and the options for doing so, see xref:serialization:serialization.adoc[Serialization].

