= Getting Started with a Hazelcast Client
:description: Hazelcast has clients in Java, .NET, Python, C++, Go, Node.js and Memcache. You can use these clients to communicate with cluster members.

{description}

For an overview of available clients, see the xref:client-overview.adoc[Client Overview].   
For documentation and code samples for each client, see the following:

* xref:java.adoc[Java]
* xref:dotnet.adoc[.NET]
* xref:python.adoc[Python]
* xref:cplusplus.adoc[C++]
* xref:go.adoc[Go]
* xref:nodejs.adoc[Node.js]

To learn how to get started quickly with the Hazelcast clients, follow our simple tutorials. These are practical, step-by-step guides to help you get started with using Hazelcast clients in various programming languages. The tutorials are ideal for developers new to Hazelcast, to learn how to integrate Hazelcast's distributed computing capabilities into their applications. These tutorials typically cover the following aspects:

1. Setting up a Hazelcast client.
2. Connecting to a Hazelcast cluster (usually a cloud instance).
3. Performing basic operations like putting data into a distributed map.

See the following:

* xref:clients:java-client-getting-started.adoc[Get started with Java]
* xref:clients:csharp-client-getting-started.adoc[Get started with .NET]
* xref:clients:python-client-getting-started.adoc[Get started with Python]
* xref:clients:cpp-client-getting-started.adoc[Get started with C++]
* xref:clients:go-client-getting-started.adoc[Get started with Go]
* xref:clients:nodejs-client-getting-started.adoc[Get started with Node.js]

* xref:rest.adoc[REST]

Additional tools are available to help operate and manage Hazelcast Platform clusters:

* xref:ROOT:management-center.adoc[Management Center]
* xref:kubernetes:deploying-in-kubernetes.adoc#hazelcast-platform-operator-for-kubernetesopenshift[Platform Operator]
* xref:clients:clc.adoc[Command Line Client (CLC)]

== Feature Comparison for Hazelcast Clients

Not all features are available in all clients.

To find out which features are available in each client,
see the link:https://hazelcast.com/developers/clients/[clients page].

After selecting the language you need, you can find the table showing supported features on the selected language.

== Maximum Number of Client Connections Per Member

The maximum recommended number of clients per member is 100.
Members use different executors, each with a different thread count, for handling different types of client message tasks:

* Query tasks: `core count` threads
* Blocking tasks: `core count * 20` threads
* All other tasks: `core count` threads

These values, as well as each member's xref:cluster-performance:threading.adoc#io-threading[I/O Thread] counts, need to be taken into consideration when determining the appropriate client connection limits for clusters.

== Serialization in Client/Server Mode

In xref:deploy:choosing-a-deployment-option.adoc[client/server topologies], you can serialize your data
on the client side before sending it to a member. For example, you can serialize data in
JSON and add it to a map. This option is useful if you plan on using Hazelcast to store your
data in binary. Clients can handle serialization without the members needing to know how to do so.

For details about why you need to serialize data and the options for doing so, see xref:serialization:serialization.adoc[Serialization].

