= Configuring for Monitoring

== Enabling Client Metrics

You can monitor the clients using Hazelcast Management Center.
As a prerequisite, you need to enable the client metrics in the Node.js client.
You can configure client metrics with `metrics` client config.

[source,javascript]
----
const cfg = {
    metrics: {
        enabled: true,
        collectionFrequencySeconds: 4 // in seconds, must be positive
    }
};
----

After enabling the client metrics, you can monitor your clients using Hazelcast Management Center. Please refer to the Monitoring Clients section in the Hazelcast Management Center documentation for more information on the client metrics.

== Logging Configuration

By default, Hazelcast Node.js client uses a default logger which logs to the stdout with the `INFO` log level. You can change the log level using the `hazelcast.logging.level` property.

Below is an example of the logging configuration with the `OFF` log level which disables logging.

[source,javascript]
----
const cfg = {
    properties: {
        'hazelcast.logging.level': 'OFF'
    }
};
----

You can also implement a custom logger depending on your needs. Your custom logger must have
log, error, warn, info, debug, trace methods. After implementing it, you can use your custom logger using the `customLogger` config option.

[source,javascript]
----
const winstonAdapter = {
    logger: winston.createLogger({
        level: 'info',
        transports: [
            new winston.transports.Console({
                format: winston.format.simple()
            })
        ]
    }),
    levels: [
        'error',
        'warn',
        'info',
        'debug',
        'silly'
    ],
    log: function (level, objectName, message, furtherInfo) {
        this.logger.log(this.levels[level], objectName + ': ' + message, furtherInfo);
    },
    error: function (objectName, message, furtherInfo) {
        this.log(LogLevel.ERROR, objectName, message, furtherInfo);
    },
    warn: function (objectName, message, furtherInfo) {
        this.log(LogLevel.WARN, objectName, message, furtherInfo);
    },
    info: function (objectName, message, furtherInfo) {
        this.log(LogLevel.INFO, objectName, message, furtherInfo);
    },
    debug: function (objectName, message, furtherInfo) {
        this.log(LogLevel.DEBUG, objectName, message, furtherInfo);
    },
    trace: function (objectName, message, furtherInfo) {
        this.log(LogLevel.TRACE, objectName, message, furtherInfo);
    }
};
const cfg = {
    customLogger: winstonAdapter
};
----