= System Properties

There are some advanced client configuration properties to tune some aspects of the Hazelcast Node.js client.
You can set them as property name and value pairs

You can specify and pass the system properties as follows.

[source,java]
----
const cfg = {
    properties: {
        'hazelcast.client.statistics.enabled': true,
        'hazelcast.client.statistics.period.seconds': 4
    }
};
const client = await Client.newHazelcastClient(cfg);
----

[cols="4,1,1,4a"]

|===
|Property Name
|Default Value
|Type
|Description

|`hazelcast.client.autopipelining.enabled`
|true
|bool
|Turns automated pipelining feature on/off. If your application does only write operations,
like `IMap.set()`, you can try disabling automated pipelining to get a slightly better throughput.

|`hazelcast.client.autopipelining.threshold.bytes`
|65536 (64 KB)
|number
|Coalescing threshold, in bytes, for the internal queue used by the automated pipelining.
Once the total size of operation payloads taken from the queue reaches this value during batch preparation,
these operations are written to the socket. Notice that the automated pipelining still sends operations if their
total size is smaller than the threshold and there are no more operations in the internal queue.

|`hazelcast.client.heartbeat.interval`
|5000
|number
|Frequency of the heartbeat messages sent by the client to members in milliseconds.

|`hazelcast.client.heartbeat.timeout`
|60000
|number
|Timeout for the heartbeat messages sent by the client to members in milliseconds.
If no messages pass between the client and member within the given time via this property, the connection is closed.

|`hazelcast.client.invocation.retry.pause.millisz`
|1000
|number
|Pause time between each retry cycle of an invocation in milliseconds.

|`hazelcast.client.invocation.timeout.millis`
|120000
|number
|Period, in milliseconds, to give up the invocation when a member in the member list is not reachable; member throws an exception or client's heartbeat requests are timed out.

|`hazelcast.client.operation.backup.timeout.millis`
|5000
|number
|If an operation has backups, this property specifies how long (in milliseconds) the invocation waits for
acks from the backup replicas. If acks are not received from some of the backups,
there will not be any rollback on the other successful replicas.

|`hazelcast.client.operation.fail.on.indeterminate.state`
|false
|boolean
|When it is `true`, if an operation has sync backups and acks are not received from backup replicas in time,
or the member which owns primary replica of the target partition leaves the cluster, then the invocation fails.
However, even if the invocation fails, there will not be any rollback on the other successful replicas.

|`hazelcast.client.shuffle.member.list`
|true
|boolean
|The client shuffles the given member list to prevent all the clients to connect to the same member
when this property is true. When it is set to `false`, the client tries to connect to the members in the given order.

|`hazelcast.client.socket.no.delay`
|true
|boolean	
|The `setNoDelay` setting for connections; enables/disables the Nagle algorithm.

|`hazelcast.client.statistics.enabled`
|false
|boolean
|If set to `true`, it enables collecting the client statistics and sending them to the cluster; you can monitor the clients
that are connected to the Hazelcast cluster, using Hazelcast Management Center.

|`hazelcast.client.statistics.period.seconds`
|3
|number
|Period in seconds the client statistics are collected and sent to the cluster.

|`hazelcast.discovery.public.ip.enabled`
|null(detection enabled)
|boolean or null
|When set to `true`, the client assumes that it needs to use public IP addresses reported by the members.
When set to `false`, the client always uses private addresses reported by the members. If it is `null`,
the client tries to infer how the discovery mechanism should be based on the reachability of the members.
This inference is not %100 reliable and may result in false negatives.

|`hazelcast.invalidation.max.tolerated.miss.count`
|10
|number
|If missed invalidation count is bigger than this value,
the relevant cached data in a Near Cache is made unreachable.

|`hazelcast.invalidation.reconciliation.interval.seconds`
|60
|number
|Period of the task that scans cluster members to compare the generated invalidation events with received ones from the client's Near Cache.

|`hazelcast.logging.level`
|INFO
|string
|Logging level; can be `OFF`, `ERROR`, `WARN`, `INFO`, `DEBUG`, `TRACE`.

|===