= Source and Code Samples

See Hazelcast Node.js client's GitHub https://github.com/hazelcast/hazelcast-nodejs-client[repo^]
for the source code and https://github.com/hazelcast/hazelcast-nodejs-client/tree/master/code_samples[code samples^]. This section provides
code snippets to guide you on how you can use a Node.js client with Hazelcast Platform features.

Whenever you want to start a cluster to play with the following code samples, you can simply use Docker:

[source,shell,subs="attributes+"]
----
docker run -p 5701:5701 hazelcast/hazelcast:{full-version}
----

== Data Structures

The Node.js client supports the following Hazelcast distributed data structures:

* Map
* Queue
* Set
* List
* MultiMap
* Replicated Map
* Ringbuffer
* Reliable Topic
* CRDT PN Counter
* Flake Id Generator
* FencedLock (CP Subsystem)
* Semaphore (CP Subsystem)
* AtomicLong (CP Subsystem)
* AtomicReference (CP Subsystem)
* CountDownLatch (CP Subsystem)

See xref:data-structures:distributed-data-structures.adoc[here] if you want to learn more on these data structures.

=== Map

[source,javascript]
----
    const client = await Client.newHazelcastClient();
    const map = await client.getMap('my-distributed-map'); <1>

    await map.put('key', 'value'); <2>
    const value = await map.get('key');
    console.log('Plain value:', value);
    await map.remove('key');

    await map.put('disappearing-key', 'this string will disappear after TTL', 1000); <3>
    let disappearingValue = await map.get('disappearing-key');
    console.log('Disappearing value:', disappearingValue);

    await new Promise((resolve) => setTimeout(resolve, 1000));
    disappearingValue = await map.get('disappearing-key');
    console.log('Disappeared value:', disappearingValue);
----
<1> Creates a map called `my-dsitributed-map`.
<2> Put `key` and `value` as an entry to the map
<3> Put a key and its value as a string which disappears from the terminal after 1000 ms.

=== Others to Come

??? Partition-Aware, Near Cache, Queue, Set, List, etc. ???

== Listeners

???

== Queries

??? SQL, Predicates, Paging Predicates, JSON strings ???

== Computing

??? Entry Processors ???


