= Handling Failures

There are two main failure cases you should be aware of. Below sections explain these, and the configuration options you can use to achieve proper behavior.

== Handling Client Connection Failure

While the client is trying to connect initially to one of the members for the `network.addresses` array,
all the members might not be available. Instead of giving up, throwing an error and stopping the client,
the client retries to connect as configured. This behavior is described in xref:clients:nodejs-connections.adoc#configuring-client-connection-retry[Configuring Client Connection Retry].

The client executes each operation through the already established connection to the cluster.
If this connection(s) disconnects or drops, the client will try to reconnect as configured.

== Handling Retry-able Operation Failure

While sending requests to cluster members, the operations may fail due to various reasons.
Read-only operations are retried by default. If you want to enable retrying for non-read-only operations,
you can set `redoOperation` to true; xref:clients:nodejs-connections.adoc[Configuring Cluster Connections].

You can set a timeout for retrying the operations sent to a member. This can be provided by
using the `hazelcast.client.invocation.timeout.millis` property in the client properties (see xref:clients:nodejs-sys-props.adoc[System Properties] to learn
how you can pass a property).The client will retry an operation within this given period,
of course, if it is a read-only operation or you enabled the redoOperation as stated in the above paragraph.
This timeout value is important when there is a failure resulted by either of the following causes:

* Member throws an exception.
* Connection between the client and member is closed.
* Client’s heartbeat requests are timed out.

When a connection problem occurs, an operation is retried if it is certain that it has not
run on the member yet or if it is idempotent such as a read-only operation, i.e., retrying
does not have a side effect. If it is not certain whether the operation has run on the member,
then the non-idempotent operations are not retried. However, as explained in the first paragraph
of this section, you can force all the client operations to be retried (`redoOperation`)
when there is a connection failure between the client and member. But in this case, you should
know that some operations may run multiple times causing conflicts. For example, assume that your
client sent a `queue.offer` operation to the member and then the connection is lost. Since there will
be no response for this operation, you will not know whether it has run on the member or not.
If you enabled `redoOperation`, it means this operation may run again, which may cause two instances of the same object in the queue.

