= Python Client
:page-api-reference: https://hazelcast.readthedocs.io/en/v{page-latest-supported-python-client}/index.html

== Overview

This section provides information about the Python client for Hazelcast, and explains how to install and use the client.

TIP: To learn how to get started quickly with the Hazelcast Python client, follow our simple xref:clients:python-client-getting-started.adoc[Get started with Python] tutorial.

The Hazelcast native Python client is an official library that allows Python applications to connect to and interact with Hazelcast clusters. It is implemented using the Hazelcast Open Binary Client Protocol. The key features and benefits include:

* Distributed data structures: the client provides access to Hazelcast's distributed data structures such as maps, queues, topics, lists, sets, and more
* SQL support: it offers the ability to query Map data using standard SQL syntax
* JSON object support: it allows using and querying JSON objects 
* Compact serialization: the client supports compact serialization, which provides efficient serialization for objects
* DBAPI support: it implements the DBAPI interface on top of the SQL service, making it compatible with various libraries and tools
* Near cache: the client supports the near cache feature for faster read speeds on frequently accessed data
* Integration with Jupyter Notebook: the client can be used in Jupyter Notebook environments, enabling interactive data analysis and visualization

These features make the Hazelcast Python Client a powerful tool for Python applications requiring distributed computing, in-memory data processing, and real-time analytics capabilities.

TIP: For the latest Python API documentation, see https://hazelcast.readthedocs.io/en/v{page-latest-supported-python-client}/index.html[Hazelcast Python Client docs].

== Install the Python client

(Author's note - continue from here onwards:)

This section explains how to set up a Hazelcast cluster and install the Hazelcast Python client.

=== Set up a Hazelcast cluster

The Hazelcast Python client requires a working Hazelcast cluster to run. The cluster handles storage and manipulation of the user data. Clients are a way to connect to the Hazelcast cluster and access the data.

The quickest way to start a single member cluster for development
purposes is to use our https://hub.docker.com/r/hazelcast/hazelcast/[Docker images].

```bash
docker run -p 5701:5701 hazelcast/hazelcast:5.3.0
```

Alternatively, you can use our https://hazelcast.com/open-source-projects/downloads/[ZIP or TAR distributions].
After downloading, start the Hazelcast member using the ``bin/hz-start`` script.

For more information on setting up a Hazelcast cluster, see the https://hazelcast.readthedocs.io/en/latest/getting_started.html[Python client documntation].

== Install the client

// Author's note - what does the following do? I'm not sure why it's entitled 'client'? 

installs the Hazelcast Python Client library from PyPI (the Python Package Index) onto your system. This library allows your Python applications to connect to and interact with a Hazelcast cluster, enabling you to use distributed data structures and other Hazelcast features in your Python code

```bash
pip install hazelcast-python-client
```

Overview
--------

Usage
~~~~~

.. code:: python

    import hazelcast

    # Connect to Hazelcast cluster.
    client = hazelcast.HazelcastClient()

    # Get or create the "distributed-map" on the cluster.
    distributed_map = client.get_map("distributed-map")

    # Put "key", "value" pair into the "distributed-map" and wait for
    # the request to complete.
    distributed_map.set("key", "value").result()

    # Try to get the value associated with the given key from the cluster
    # and attach a callback to be executed once the response for the
    # get request is received. Note that, the set request above was
    # blocking since it calls ".result()" on the returned Future, whereas
    # the get request below is non-blocking.
    get_future = distributed_map.get("key")
    get_future.add_done_callback(lambda future: print(future.result()))

    # Do other operations. The operations below won't wait for
    # the get request above to complete.

    print("Map size:", distributed_map.size().result())

    # Shutdown the client.
    client.shutdown()


If you are using Hazelcast and the Python client on the same machine,
the default configuration should work out-of-the-box. However,
you may need to configure the client to connect to cluster nodes that
are running on different machines or to customize client properties.

== Configuration

.. code:: python

    import hazelcast

    client = hazelcast.HazelcastClient(
        cluster_name="cluster-name",
        cluster_members=[
            "10.90.0.2:5701",
            "10.90.0.3:5701",
        ],
        lifecycle_listeners=[
            lambda state: print("Lifecycle event >>>", state),
        ]
    )

    print("Connected to cluster")
    client.shutdown()


To learn more about supported configuration options, refer to the documentation <https://hazelcast.readthedocs.io>.

== Get help

You can use the following channels for your questions and development or usage issues:

- GitHub repository <https://github.com/hazelcast/hazelcast-python-client/issues/new>
- Documentation <https://hazelcast.readthedocs.io>
- Slack <https://slack.hazelcast.com>


== Next steps

For more information, see the Hazelcast Python client GitHub https://github.com/hazelcast/hazelcast-python-client[repo^]
and https://github.com/hazelcast/hazelcast-python-client/tree/master/examples[code samples^].
