= IAtomicLong
[[iatomiclong]]

Hazelcast `IAtomicLong` is the distributed implementation of
`java.util.concurrent.atomic.AtomicLong`. It offers most of AtomicLong's operations
such as `get`, `set`, `getAndSet`, `compareAndSet` and `incrementAndGet`.
Since IAtomicLong is a distributed implementation, these operations involve remote
calls and thus their performances differ from AtomicLong.

include::partial$warning-cp-unsafe.adoc[]

The following example code creates an instance, increments it
by a million and prints the count.

[source,java]
----
include::ROOT:example$/dds/iatomiclong/ExampleIAtomicLong.java[tag=ial]
----

When you start other instances with the code above,
you will see the count as *member count* times *a million*.

WARNING: ``IAtomicLong``s are not automatically removed. If an instance is not used anymore, Hazelcast
does not automatically perform garbage collection in it.
This can lead to an `OutOfMemoryError`. If you create ``IAtomicLong``s on the fly,
make sure they are destroyed. See xref:data-structures:distributed-data-structures.adoc#destroying-objects[Destroying Objects]
and xref:data-structures:distributed-data-structures.adoc#cp-data[CP Data Structures].

[[sending-functions-to-iatomiclong]]
== Sending Functions to IAtomicLong

You can send functions to an IAtomicLong. `IFunction` is a Hazelcast owned,
single method interface. The following example `IFunction` implementation
adds two to the original value.

[source,java]
----
include::ROOT:example$/dds/iatomiclong/IAtomicLongExecuteFuncs.java[tag=add2func]
----

[[executing-functions-on-iatomiclong]]
== Executing Functions on IAtomicLong

You can use the following methods to execute functions on IAtomicLong:

* `apply`: Applies the function to the value in IAtomicLong without
changing the actual value and returning the result.
* `alter`: Alters the value stored in the IAtomicLong by applying the function.
It does not send back a result.
* `alterAndGet`: Alters the value stored in the IAtomicLong by applying the function,
storing the result in the IAtomicLong and returning the result.
* `getAndAlter`: Alters the value stored in the IAtomicLong by applying the function
and returning the original value.

The following example includes these methods.

[source,java]
----
include::ROOT:example$/dds/iatomiclong/IAtomicLongExecuteFuncs.java[tag=ialef]
----

The output of the above class when run is as follows:

```
apply.result: 3
apply.value: 1
alter.value: 3
alterAndGet.result: 3
alterAndGet.value: 3
getAndAlter.result: 1
getAndAlter.value: 3
```

[[reasons-to-use-functions-with-iatomic]]
== Reasons to Use Functions with IAtomicLong

The reason for using a function instead of a simple code line like
`atomicLong.set(atomicLong.get() + 2));` is that the IAtomicLong read and write
operations are not atomic. Since `IAtomicLong` is a distributed implementation,
those operations can be remote ones, which may lead to race problems. By using functions,
the data is not pulled into the code, but the code is sent to the data. This makes it more scalable.