= ICountDownLatch
:page-enterprise: true
[[icountdownlatch]]

Hazelcast `ICountDownLatch` is the distributed implementation of
`java.util.concurrent.CountDownLatch`. But unlike Java's implementation,
Hazelcast's `ICountDownLatch` count can be reset after a countdown has finished,
but not during an active count.

include::partial$warning-cp-unsafe.adoc[]

[[gate-keeping-concurrent-activities]]
== Gate-Keeping Concurrent Activities

`ICountDownLatch` is considered to be a gatekeeper for concurrent activities.
It enables the threads to wait for other threads to complete their operations.
The following examples describe the mechanism of `ICountDownLatch`.

Assume that there is a leader process and there are follower processes that will
wait until the leader completes. Here is the leader:

[source,java]
----
include::ROOT:example$/dds/countdownlatch/Leader.java[tag=leader]
----

Since only a single step is needed to be completed as a sample, the above code
initializes the latch with 1. Then, the code sleeps for a while to simulate a
process and starts the countdown. Finally, it clears up the latch. Let's write a follower:

[source,java]
----
include::ROOT:example$/dds/countdownlatch/Follower.java[tag=follower]
----

The follower class above first retrieves `ICountDownLatch` and then calls the `await`
method to enable the thread to listen for the latch. The method `await` has a timeout
value as a parameter. This is useful when the `countDown` method fails. To see `ICountDownLatch`
in action, start the leader first and then start one or more followers. You will see that the
followers wait until the leader completes.

WARNING: ``ICountDownLatch ``s are not automatically removed. If a latch is not used anymore, Hazelcast
does not automatically perform garbage collection in it.
This can lead to an `OutOfMemoryError`. If you create ``ICountDownLatch``s on the fly,
make sure they are destroyed. See xref:data-structures:distributed-data-structures.adoc#destroying-objects[Destroying Objects]
and xref:data-structures:distributed-data-structures.adoc#cp-data[CP Data Structures].
