= Configuring MultiMap
[[configuring-multimap]]

When using MultiMap, the collection type of the values can be either **Set** or **List**.
Configure the collection type with the `valueCollectionType` parameter. If you choose
`Set`, duplicate and null values are not allowed in your collection and ordering is irrelevant.
If you choose `List`, ordering is relevant and your collection can include duplicate but not null values.

You can also enable statistics for your MultiMap with the `statisticsEnabled` parameter.
If you enable `statisticsEnabled`, statistics can be retrieved with `getLocalMultiMapStats()` method.


NOTE: Currently, eviction is not supported for the MultiMap data structure.


The following are the example MultiMap configurations.

**Declarative Configuration:**

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <multimap name="default">
        <backup-count>0</backup-count>
        <async-backup-count>1</async-backup-count>
        <value-collection-type>SET</value-collection-type>
        <entry-listeners>
            <entry-listener include-value="false" local="false" >com.hazelcast.examples.EntryListener</entry-listener>
        </entry-listeners>
        <split-brain-protection-ref>split-brain-protection-name</split-brain-protection-ref>
    </multimap>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  multimap:
    default:
      backup-count: 0
      async-backup-count: 1
      value-collection-type: SET
      entry-listeners:
        - class-name: com.hazelcast.examples.EntryListener
          include-value: false
          local: false
      split-brain-protection-ref: split-brain-protection-name
----

Java::
+
[source,java]
----
include::ROOT:example$/dds/multimap/MultiMapConfiguration.java[tag=mmc]
----
====

The following are the configuration elements and their descriptions:

* `backup-count`: Defines the number of synchronous backups. For example,
if it is set to 1, backup of a partition will be
placed on one other member. If it is 2, it will be placed on two other members.
* `async-backup-count`: The number of asynchronous backups. Behavior is the
same as that of the `backup-count` element.
* `statistics-enabled`: Specifies whether the statistics gathering is enabled for your MultiMap.
If set to `false`, you cannot collect statistics in your implementation
(using `getLocalMultiMapStats()`) and also
xref:{page-latest-supported-mc}@management-center:monitor-imdg:monitor-dds.adoc#monitoring-multimaps[Hazelcast Management Center]
will not show them. Its default value is `true`.
* `value-collection-type`: Type of the value collection. It can be `SET` or `LIST`.
* `entry-listeners`: Lets you add listeners (listener classes) for the map entries.
You can also set the attribute
`include-value` to `true` if you want the item event to contain the entry values.
You can set
`local` to `true` if you want to listen to the entries on the local member.
* `split-brain-protection-ref`: Name of the split-brain protection configuration that you want this MultiMap to use.
See the xref:network-partitioning:split-brain-protection.adoc#split-brain-protection-for-multimap-and-transactionalmultimap[Split-Brain Protection for MultiMap and TransactionalMultiMap section].