= Reliable Topic
[[reliable-topic]]

Reliable Topic uses the same `ITopic` interface
as a regular topic. The main difference is that Reliable Topic
is backed up by the Ringbuffer data structure. The following are the advantages of this approach:

* Events are not lost since the Ringbuffer is configured with one
synchronous backup by default.
* Each Reliable `ITopic` gets its own Ringbuffer; if a topic has a
very fast producer, it will not lead to problems at topics that run at a slower pace.
* Since the event system behind a regular `ITopic` is shared with other
data structures, e.g., collection listeners,
  you can run into isolation problems. This does not happen with the Reliable `ITopic`.

Here is an example for a publisher using Reliable Topic:

[source,java]
----
include::ROOT:example$/dds/reliabletopic/PublisherMember.java[tag=publisher]
----

And the following is an example for the subscriber:

[source,java]
----
include::ROOT:example$/dds/reliabletopic/SubscribedMember.java[tag=sm]
----

When you create a Reliable Topic, Hazelcast automatically creates a
Ringbuffer for it. You may configure this Ringbuffer by adding a Ringbuffer config
with the same name as the Reliable Topic. For instance, if you have a
Reliable Topic with the name "sometopic", you should add a Ringbuffer config
with the name "sometopic" to configure the backing Ringbuffer. Some of the
things that you may configure are the capacity, the time-to-live for the topic
messages, and you can even add a Ringbuffer store which allows you to have a persistent topic.
By default, a Ringbuffer does not have any TTL (time-to-live) and it has a limited
capacity; you may want to change that configuration. The following is an example
configuration for the "sometopic" given above.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <!-- This is the ringbuffer that is used by the 'sometopic' Reliable-topic. As you can see the
         ringbuffer has the same name as the topic. -->
    <ringbuffer name="sometopic">
        <capacity>1000</capacity>
        <time-to-live-seconds>5</time-to-live-seconds>
    </ringbuffer>
    <reliable-topic name="sometopic">
        <topic-overload-policy>BLOCK</topic-overload-policy>
    </reliable-topic>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  ringbuffer:
    sometopic:
      capacity: 1000
      time-to-live-seconds: 5
  reliable-topic:
    sometopic:
      topic-overload-policy: BLOCK
----
====

See the <<configuring-reliable-topic, Configuring Reliable Topic section>>
below for the descriptions of all Reliable Topic configuration elements.

By default, the Reliable `ITopic` uses a shared thread pool. If you need a
better isolation, you can configure a custom executor on the
`ReliableTopicConfig`.

Because the reads on a Ringbuffer are not destructive, batching is easy to apply.
`ITopic` uses read batching and reads
ten items at a time (if available) by default. See xref:data-structures:ringbuffer.adoc#reading-batched-items[Reading Batched Items].
for more information.

[[slow-consumers]]
== Slow Consumers

The Reliable `ITopic` provides control and a way to deal with slow consumers.
It is unwise to keep events for a slow consumer in memory
indefinitely since you do not know when the slow consumer is going to catch up.
You can control the size of the Ringbuffer by using its capacity. For the cases
when a Ringbuffer runs out of its capacity, you can specify the following policies
for the `TopicOverloadPolicy` configuration:

* `DISCARD_OLDEST`: Overwrite the oldest item, even if a TTL is set.
In this case the fast producer supersedes a slow consumer.
* `DISCARD_NEWEST`: Discard the newest item.
* `BLOCK`: Wait until the items are expired in the Ringbuffer.
* `ERROR`: Immediately throw `TopicOverloadException` if there is no space in the Ringbuffer.

[[configuring-reliable-topic]]
== Configuring Reliable Topic

The following are example Reliable Topic configurations.


**Declarative Configuration:**

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <reliable-topic name="default">
        <statistics-enabled>true</statistics-enabled>
        <message-listeners>
            <message-listener>
                ...
            </message-listener>
        </message-listeners>
        <read-batch-size>10</read-batch-size>
        <topic-overload-policy>BLOCK</topic-overload-policy>
    </reliable-topic>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  reliable-topic:
    default:
      statistics-enabled: true
      message-listeners:
        - ...
      read-batch-size: 10
      topic-overload-policy: BLOCK
----
====

**Programmatic Configuration:**

[source,java]
----
Config config = new Config();
ReliableTopicConfig rtConfig = config.getReliableTopicConfig( "default" );
rtConfig.setTopicOverloadPolicy( TopicOverloadPolicy.BLOCK )
    .setReadBatchSize( 10 )
    .setStatisticsEnabled( true );
----

Reliable Topic configuration has the following elements:

* `statistics-enabled`: Specifies whether the statistics gathering is
enabled for your Reliable Topic. If set to `false`, you cannot collect statistics
in your implementation and also
xref:{page-latest-supported-mc}@management-center:monitor-imdg:monitor-dds.adoc#monitoring-reliable-topics[Hazelcast Management Center]
will not show them. Its default value is `true`.
* `message-listener`: Message listener class that listens to the
messages when they are added or removed.
* `read-batch-size`: Minimum number of messages that Reliable Topic
tries to read in batches. Its default value is 10.
* `topic-overload-policy`: Policy to handle an overloaded topic.
Available values are `DISCARD_OLDEST`, `DISCARD_NEWEST`, `BLOCK` and `ERROR`.
Its default value is `BLOCK`. See <<slow-consumers, Slow Consumers>> for definitions of these policies.

[[reliable-message-listener]]
== ReliableMessageListener

ReliableMessageListener is a MessageListener to better integrate with the reliable topic.

If a regular MessageListener is registered on a reliable topic, the message listener works fine, but it can't do much more than listen to messages.
If a ReliableMessageListener is registered on a normal topic, only the MessageListener methods are called.

**Durable Subscription**

The ReliableMessageListener allows you to control where you want to start processing a message when the listener is registered. This makes it possible to create a durable subscription by storing the sequence of the last message and using this sequenceId as the sequenceId to start from.

**Exception handling**

The ReliableMessageListener also gives the ability to deal with exceptions using the `isTerminal(Throwable)` method. This method allows you to control which exceptions should terminate the execution of the listener and cancel it. If a plain MessageListener is used, it won't terminate on exceptions and it will keep on running. But in some cases it is better to stop running.

**Global order**

The ReliableMessageListener will always get all events in order (global order). It will not get duplicates and there will only be gaps (loss of messages) if it is too slow. For more information see `isLossTolerant()`.

**Delivery Guarantees**

Because the ReliableMessageListener controls which item it wants to continue from upon restart, it is very easy to provide an at-least-once or at-most-once delivery guarantee. The storeSequence is always called before a message is processed; so it can be persisted on some non-volatile storage. When the `retrieveInitialSequence()` returns the stored sequence, then an at-least-once delivery is implemented since the same item is now being processed twice. To implement an at-most-once delivery guarantee, add 1 to the stored sequence when the `retrieveInitialSequence()` is called.

**Loss Tolerance**

You can provide the `boolean isLosstolerant()` method return true if this ReliableMessageListener is able to deal with message loss. Even though the reliable topic promises to be reliable, it can be that a MessageListener is too slow. Eventually the message won't be available anymore.

If the ReliableMessageListener is not loss tolerant and the topic detects that there are missing messages, it will terminate the ReliableMessageListener.

**onCancel Callback**

This method is called by Hazelcast when the ReliableMessageListener is cancelled. This can happen when the listener is unregistered or cancelled due to an exception or during shutdown.
