= Set
[[set]]

Hazelcast Set (`ISet`) is a distributed and concurrent implementation of `java.util.Set`.
It has the following features:

* Hazelcast Set does not allow duplicate elements.
* Hazelcast Set does not preserve the order of elements.
* Hazelcast Set is a non-partitioned data structure: all the data that belongs to
a set lives on one single partition in that member.
* Hazelcast Set cannot be scaled beyond the capacity of a single machine.
Since the whole set lives on a single partition, storing a large amount of
data on a single set may cause memory pressure. Therefore, you should use multiple
sets to store a large amount of data. This way, all the sets are spread across the
cluster, sharing the load.
* A backup of Hazelcast Set is stored on a partition of another member in the cluster
so that data is not lost in the event of a primary member failure.
* All items are copied to the local member and iteration occurs locally.
* The equals method implemented in Hazelcast Set uses a serialized byte version of
objects, as opposed to `java.util.HashSet`.

[[getting-a-set-and-putting-items]]
== Getting a Set and Putting Items

Use the ``HazelcastInstance``s `getSet` method to get the Set, then use the `add` method to put items into it.

[source,java]
----
include::ROOT:example$/dds/set/ExampleSet.java[tag=set]
----

Hazelcast Set uses `ItemListener` to listen to events that occur when items are
added to and removed from the Set. See the xref:events:object-events.adoc#listening-for-item-events[Listening for Item Events section]
for information on how to create an item listener class and register it.

[[configuring-set]]
== Configuring Set

The following are the example Hazelcast Set configurations.


**Declarative Configuration:**

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <set name="default">
        <statistics-enabled>false</statistics-enabled>
        <backup-count>1</backup-count>
        <async-backup-count>0</async-backup-count>
        <max-size>10</max-size>
        <item-listeners>
            <item-listener>com.hazelcast.examples.ItemListener</item-listener>
        </item-listeners>
        <split-brain-protection-ref>splitbrainprotection-name</split-brain-protection-ref>
    </set>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  set:
    default:
      statistics-enabled: false
      backup-count: 1
      async-backup-count: 0
      max-size: 10
      item-listeners:
        - class-name: com.hazelcast.examples.ItemListener
      split-brain-protection-ref: splitbrainprotection-name
----
====

**Programmatic Configuration:**

[source,java]
----
include::ROOT:example$/dds/set/SetConfiguration.java[tag=sc]
----

Hazelcast Set configuration has the following elements:

* `statistics-enabled`: True (default) if statistics gathering is
enabled on the Set, false otherwise.
* `backup-count`: Count of synchronous backups. Set is a non-partitioned
data structure, so all entries of a Set reside in one partition. When this
parameter is '1', it means there will be one backup of that Set in another
member in the cluster. When it is '2', two members will have the backup.
* `async-backup-count`: Count of asynchronous backups.
* `max-size`: The maximum number of entries for this Set. It can be any number
between 0 and Integer.MAX_VALUE. Its default value is 0, meaning there is no capacity constraint.
* `item-listeners`: Lets you add listeners (listener classes) for the list items.
You can also set the attributes `include-value` to `true` if you want the item event
to contain the item values. You can set `local` to `true` if you want to listen to
the items on the local member.
* `split-brain-protection-ref`: Name of the split-brain protection configuration that you want this Set to use.
See the <<split-brain-protection-for-iset-and-transactionalset, Split-Brain Protection for ISet and TransactionalSet section>>.

[[split-brain-protection-for-iset-and-transactionalset]]
== Split-Brain Protection for ISet and TransactionalSet

ISet & TransactionalSet can be configured to check for a minimum number of
available members before applying queue operations (see the xref:network-partitioning:split-brain-protection.adoc[Split-Brain Protection section]).
This is a check to avoid performing successful queue operations on all parts of a cluster during a network partition.

The following is a list of methods, grouped by the protection types, that support
split-brain protection checks:

ISet:

* WRITE, READ_WRITE:
** `add`
** `addAll`
** `clear`
** `remove`
** `removeAll`
* READ, READ_WRITE:
** `contains`
** `containsAll`
** `isEmpty`
** `iterator`
** `size`
** `toArray`


TransactionalSet:

* WRITE, READ_WRITE:
** `add`
** `remove`
* READ, READ_WRITE:
** `size`


**Configuring Split-Brain Protection**

Split-brain protection for ISet can be configured programmatically using
the method https://docs.hazelcast.org/docs/{page-component-version}/javadoc/com/hazelcast/config/SetConfig.html[setSplitBrainProtectionName()^],
or declaratively using the element `split-brain-protection-ref`. The following is an example declarative configuration:

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <set name="default">
        <split-brain-protection-ref>splitbrainprotection-name</split-brain-protection-ref>
    </set>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  set:
    default:
      split-brain-protection-ref: splitbrainprotection-name
----
====

The value of `split-brain-protection-ref` should be the split-brain protection configuration name which you
configured under the `split-brain-protection` element as explained in the xref:network-partitioning:split-brain-protection.adoc[Split-Brain Protection section].