= Vector Collection
:page-enterprise: true
:page-beta: true

== Intro

The primary object for interacting with the vector storage is a Vector Collection. This collection holds information about the vectors and associated metadata (user value).

A collection consists of one or more indexes, all sharing a common metadata storage. Each index represents a distinct vector space. Vectors from different indexes are stored independently, and indexes can have different configurations.

Conceptually, a vector collection resembles a key-value store. Here, the key is a user-defined unique identifier, and the value is an object containing metadata (user value) alongside several vectors — one for each index.

Users are permitted to store any necessary value for work as metadata (user value). This can be additional characteristics of the source data or even the source data itself.

== Configuration

Collection configuration can be set dynamically during vector collection creation or statically during cluster configuration. Unlike other data structures, the configuration must be set up before the collection can be used. Below is a table listing all available options:

.Collection configuration options
[cols="1,2,1,1",options="header"]
|===
|Option|Description|Required|Default

|name
|The name of the vector collection.
|`Required`
|null

|indexes
|Information about indexes configuration
|Y
|null
|===

.Index configuration options
[cols="1,2,1,1",options="header"]
|===
|Option|Description|Mandatory|Default

|name
|The name of the vector index.
|`Required` - for single-index vector collections. `Optional` - for multi-index collection
|null

|dimension
|Vectors dimension
|`Required`
|N/A

|metric
|Distance metric used to calculate the distance between two vectors.
See table <<available-metrics, Available distance metrics.>>
|`Required`
|N/A

|max-degree
|The maximum number of neighbors per node is calculated as max-degree * 2
|`Required`
|16

|ef-construction
|The size of the search queue to use when finding nearest neighbors.
|`Required`
|100

|use-deduplication
|The option for vector deduplication.
When disabled, each added vector will be treated as a distinct vector in the index, even if it is identical to an existing one. When deduplication is enabled, the index consumes less space, but the time required to add a vector increases.
|`Required`
|true

|===
[#available-metrics]
.Available distance metrics
[cols="2,2,2",options="header"]
|===
|Name|Description| Score definition

|EUCLIDEAN
|euclidean distance
|1 / (1 + squareDistance(v1, v2))

|COSINE
|cosine of the angle between the vectors
|(1 + cos(v1, v2)) / 2

|DOT
|dot product of the vectors
|(1 + dotProduct(v1, v2)) / 2
|===

NOTE: The recommended method for computing cosine similarity is to normalize all vectors to unit length and utilize the DOT metric instead.


Configuration example:

[tabs]
====
XML::
+
--
[source,xml]
----
<hazelcast>
    <vector-collection name="books">
        <indexes>
            <index name="word2vec-index">
                <dimension>5</dimension>
                <metric>DOT</metric>
            </index>
            <index name="glove-index">
                <dimension>10</dimension>
                <metric>DOT</metric>
                <max-degree>32</max-degree>
                <ef-construction>256</ef-construction>
                <use-deduplication>false</use-deduplication>
            </index>
        </indexes>
    </vector-collection>
</hazelcast>
----
--
YAML::
+
--
[source,yaml]
----
hazelcast:
  vector-collection:
    vector-collection-name:
      indexes:
        - name: word2vec-index
          dimension: 5
          metric: DOT
        - name: glove-index
          dimension: 10
          metric: DOT
          max-degree: 32
          ef-construction: 256
          use-deduplication: false
----
--
Java::
+
--
[source,java]
----
Config config = new Config();
VectorCollectionConfig collectionConfig = new VectorCollectionConfig("books")
    .addVectorIndexConfig(
            new VectorIndexConfig()
                .setName("word2vec-index")
                .setDimension(5)
                .setMetric(Metric.DOT)
    ).addVectorIndexConfig(
            new VectorIndexConfig()
                .setName("glove-index")
                .setDimension(10)
                .setMetric(Metric.DOT)
                .setMaxDegree(32)
                .setEfConstruction(256)
                .setUseDeduplication(false)
    );
config.addVectorCollectionConfig(collectionConfig);
----
--
====

== Create collection

=== Get vector collection
To get the collection, use one of the static methods of `VectorCollection`. Both methods will either create a new vector collection or return an existing one corresponding to the requested name.

* Method `getCollection(HazelcastInstance instance, VectorCollectionConfig collectionConfig)`.
** If a collection with the provided name does not exist, a new collection will be created with the given configuration. If the configuration for the collection already exists, the provided configuration should match the one created earlier; otherwise, an error will be thrown.
** If a collection with the same name and configuration already exists, it will be returned.
** If a collection with the same name but a different configuration exists, an error will be thrown.

[tabs]
====
Java::
+
--
[source,java]
----
VectorCollectionConfig collectionConfig = new VectorCollectionConfig("books")
    .addVectorIndexConfig(
            new VectorIndexConfig()
                .setDimension(5)
                .setMetric(Metric.DOT)
    );
VectorCollection vectorCollection = VectorCollection.getCollection(hazelcastInstance, vectorCollectionConfig);
----
--
====

* Method `getCollection(HazelcastInstance instance, String collectionName)`.
** If a collection with the provided name does not exist, the system will create the collection with the configuration created explicitly during static or dynamic configuration of the cluster. If the configuration does not exist, an error will be thrown.
** If a collection with the provided name exists, it will be returned.

[tabs]
====
Java::
+
--
[source,java]
----
VectorCollection vectorCollection = VectorCollection.getCollection(hazelcastInstance, "books");
----
--
====

== Manage data
All methods of `VectorCollection` that work with collection data are asynchronous. The result is returned as a `CompletionStage`. A collection interacts with entries in the form of documents (`VectorDocument`). Each document comprises a value and one or more vectors associated with that value.

WARNING: When using the asynchronous methods, clients should carefully control the number of requests and their concurrency. A large number of requests can potentially overwhelm both the server and the client by consuming significant heap memory during processing.

=== Create document
To create a document use the static factory methods of `VectorDocument` and `VectorValues` classes.

Example document for single-index vector collection:
[tabs]
====
Java::
+
--
[source,java]
----
VectorDocument<String> document = VectorDocument.of(
        "{'genre': 'novel', 'year': 1976}",
        VectorValues.of(
                new float[]{0.2f, 0.9f, -1.2f, 2.2f,  2.2f,  3.0f}
        )
);
----
--
====

For multi-index collections, specify the names of the indexes to which the vectors belong:
[tabs]
====
Java::
+
--
[source,java]
----
VectorDocument<String> document = VectorDocument.of(
        "{'genre': 'fiction', 'year': 2022}",
        VectorValues.of(
                Map.of(
                        "word2vec-index", new float[] {0.2f, 0.9f, -1.2f, 2.2f,  2.2f,  3.0f},
                        "glove-index", new float[] {2f, 3f, 2f, 10f, -2f}
                )
        )
);
----
--
====


=== Put entries
To put single document to a vector collection, use the method `putAsync`, `putIfAbsent` or `setAsync` of the `VectorCollection` class.
[tabs]
====
Java::
+
--
[source,java]
----
VectorDocument<String> document = VectorDocument.of(
        "{'genre': 'novel', 'year': 1976}",
        VectorValues.of(new float[] {0.2f, 0.9f, -1.2f, 2.2f,  2.2f,  3.0f})
);
CompletionStage<VectorDocument<String>> result = vectorCollection.putAsync("1", document);
----
--
====

To put several documents to a vector collection, use the method `putAllAsync` of the `VectorCollection` class.
[tabs]
====
Java::
+
--
[source,java]
----
VectorDocument<String> document1 = VectorDocument.of("{'genre': 'novel', 'year': 1976}", VectorValues.of(new float[] {1.2f, -0.3f, 2.2f, 0.4f, 0.3f}));
VectorDocument<String> document2 = VectorDocument.of("{'genre': 'fiction', 'year': 2022}", VectorValues.of(new float[] {1.2f, -0.3f, 2.2f, 0.4f, 0.3f}));
CompletionStage<Void> result = vectorCollection.putAllAsync(
        Map.of("1", document1, "2", document2)
);
----
--
====

=== Read entries
To get document from a vector collection, use the method `getAsync` of the `VectorCollection` class.

[tabs]
====
Java::
+
--
[source,java]
----
CompletionStage<VectorDocument<String>> result = vectorCollection.getAsync("1");
----
--
====

=== Update entries
To update single entry in a vector collection, use the method `putAsync` or `setAsync` of the `VectorCollection` class.

[tabs]
====
Java::
+
--
[source,java]
----
VectorDocument<String> document = VectorDocument.of("{'genre': 'fiction', 'year': 2022}", VectorValues.of(new float[] {1.2f, -0.3f, 2.2f, 0.4f, 0.3f}));
CompletionStage<Void> result = vectorCollection.setAsync("1", document);
----
--
====

=== Delete entries
To delete document from a vector collection, use the method `deleteAsync` or `removeAsync` of the `VectorCollection` class.

[tabs]
====
Java::
+
--
[source,java]
----
CompletionStage<Void> resultDelete = vectorCollection.deleteAsync("1");
CompletionStage<VectorDocument<String>> resultRemove = vectorCollection.removeAsync("2");
----
--
====

NOTE: These methods do not delete vectors but mark them as deleted. This may impact search speed and memory usage. To permanently remove vectors from the index, you must run index optimization after deletion. See <<optimize-collection, optimize method>>

== Similarity search

Vector search returns entries with vectors that are most similar to the query vector, based on specified metrics. Any query consists of exactly one vector to search and search options, such as the limit of results to retrieve, etc. For more details about available options, refer to <<similarity-search-options, Similarity search options>>

For similarity search, use the `searchAsync` method of the `VectorCollection`.

In a single index vector collection, specifying the name of the index to search is not required.
However, for a multi-index vector collection, specifying the name of the index to search in is necessary.

Example for single-index vector collection:
[tabs]
====
Java::
+
--
[source,java]
----
CompletionStage<SearchResults<String, String>> results = vectorCollection.searchAsync(
        VectorValues.of(new float[] {0f, 0f, 0.2f, -0.3f, 1.2f}),
        SearchOptions.builder()
            .limit(5)
            .includeVectors()
            .includeValue()
            .build()
);
----
--
====

Example for multi-index vector collection:
[tabs]
====
Java::
+
--
[source,java]
----
CompletionStage<SearchResults<String, String>> results = vectorCollection.searchAsync(
        VectorValues.of("glove-index", new float[] {0f, 0f, 0.2f, -0.3f, 1.2f}),
        SearchOptions.builder()
            .limit(5)
            .includeVectors()
            .includeValue()
            .build()
);
----
--
====

=== Similarity search options
Search parameters are passed as an argument `searchOptions` to the searchAsync method.

.Search options
[cols="1,2,1",options="header"]
|===
|Option|Description|Default

|limit
|How many results should be returned in search result
|`1`

|includeValue
|Include the user value in the search result.
|`N`


|includeVectors
|Include the vectors values in the search result.
|`N`

|hints
|Extra hints for the search.
|`None`

|===


.Available hints
[cols="1,2",options="header"]
|===
|Hint|Description

|`partitionLimit`
|Number of results to fetch from partition.

|`memberLimit`
|Number of results to fetch from member in 2-stage search.

|`singleStage`
|Force use of 1-stage search.

|===

[tabs]
====
Java::
+
--
[source,java]
----
var options = SearchOptions.builder()
                .limit(10)
                .includeValue()
                .includeVectors()
                .hint("partitionLimit", 1)
                .build();
----
--
====

== Manage collection

=== Optimize collection

An optimization operation may be needed in the following cases:

* To permanently delete vectors that were marked for removal.
* After adding a significant number of vectors.
* The collection returns fewer vectors than expected.

WARNING: The optimization operation can be a time-consuming and resource-intensive process, and no mutating operations are allowed during this process.

[tabs]
====
Java::
+
--
[source,java]
----
CompletionStage<Void> result = vectorCollection.optimizeAsync("glove-index");
----
--
====

=== Clear collection
To remove all vectors and values from the vector collection use the method `clearAsync()`.
[tabs]
====
Java::
+
--
[source,java]
----
CompletionStage<Void> result = vectorCollection.clearAsync();
----
--
====

