= Cloud Discovery Plugins
[[hazelcast-cloud-discovery-plugins]]

Hazelcast provides the following plugins that allow Hazelcast cluster members to discover each other on cloud platforms.
These plugins are mainly used for the following reasons:

* To provide dynamic member discovery when you do not want to or you cannot provide a list of static IP
addresses (for member-member discovery, client-member discovery, or WAN replication).
* For resilience against availability zone failures (`ZONE_AWARE` feature).

[[hazelcast-cloud-discovery-plugins-eureka]]
== Hazelcast Eureka

Hazelcast supports using https://github.com/Netflix/eureka[Eureka^] server as the discovery mechanism
with the use of https://github.com/hazelcast/hazelcast-eureka[Hazelcast Eureka Discovery plugin].

You can easily configure your Hazelcast member/client to use Eureka discovery by enabling Eureka in your Hazelcast configuration.

See the
https://github.com/hazelcast/hazelcast-eureka[Hazelcast Eureka Plugin documentation^]
for more details.

[[hazelcast-cloud-discovery-plugins-zookeeper]]
== Hazelcast Zookeeper

Hazelcast supports using https://zookeeper.apache.org/[Zookeeper^] as the discovery mechanism
with the use of https://github.com/hazelcast/hazelcast-zookeeper[Hazelcast Zookeeper Discovery plugin].

You can easily configure your Hazelcast member/client to use Zookeeper discovery by enabling Zookeeper in your Hazelcast configuration.

See the
https://github.com/hazelcast/hazelcast-zookeeper[Hazelcast Zookeeper Plugin documentation^]
for more details.

== Other Discovery Plugins

Apart from the officially maintained plugins listed above, there are a number of community plugins implementing
Hazelcast Discovery SPI:

* https://github.com/bitsofinfo/hazelcast-docker-swarm-discovery-spi[Hazelcast Docker Swarm Discovery Plugin]
* https://github.com/bitsofinfo/hazelcast-consul-discovery-spi[Hazelcast Consul Discovery Plugin]
* https://github.com/bitsofinfo/hazelcast-etcd-discovery-spi[Hazelcast Etcd Discovery Plugin]
* https://github.com/jkutner/hazelcast-heroku-discovery[Hazelcast Heroku Discovery Plugin]