= Cloud Discovery Plugins
[[hazelcast-cloud-discovery-plugins]]

Hazelcast provides the following plugins that allow Hazelcast cluster members to discover each other on the cloud platforms.
They are mainly used for the following reasons:

* provide dynamic member discovery when you do not want to or you cannot provide a list of static IP
addresses (for member-member discovery, client-member discovery, or WAN replication)
* enable resilience to availability zone failures (ZONE_AWARE feature)

[[hazelcast-cloud-discovery-plugins-aws]]
== Hazelcast AWS

Hazelcast provides support for https://aws.amazon.com/[Amazon Web Services], covering the following environments:

* Amazon EC2 discovery with https://github.com/hazelcast/hazelcast-aws[Hazelcast AWS Discovery plugin^]
* Amazon ECS/EC2 discovery with https://github.com/hazelcast/hazelcast-aws[Hazelcast AWS Discovery plugin^]
* Amazon ECS/Fargate with https://github.com/hazelcast/hazelcast-aws[Hazelcast AWS Discovery plugin^]
* Amazon EKS/Fargate with https://github.com/hazelcast/hazelcast-kubernetes[Hazelcast Kubernetes Discovery plugin^]
* Amazon EKS/EC2 with https://github.com/hazelcast/hazelcast-kubernetes[Hazelcast Kubernetes Discovery plugin^]

In all scenarios you can use the `ZONE_AWARE` feature to create partition backups in other Availability Zones (AZ)
and therefore prevent any data loss in case of AZ failures.

You can easily configure your Hazelcast member/client to use EC2/ECS discovery by having the `hazelcast-all`
(or `hazelcast-aws`) JAR on your classpath and enabling AWS in your Hazelcast configuration.

See the
https://github.com/hazelcast/hazelcast-aws[Hazelcast AWS Plugin documentation^]
for more details.

[[hazelcast-cloud-discovery-plugins-azure]]
== Hazelcast Azure

Hazelcast provides support for https://azure.microsoft.com/en-us/[Microsoft Azure^],
covering the following environments:

* Azure Virtual Machines with https://github.com/hazelcast/hazelcast-azure[Hazelcast Azure Discovery plugin^]
* Azure Kubernetes Service (AKS) with https://github.com/hazelcast/hazelcast-kubernetes[Hazelcast Kubernetes Discovery plugin^]

In both scenarios you can use the `ZONE_AWARE` feature to create partition backups in other Availability Zones (AZ)
and therefore prevent any data loss in case of AZ failures.

You can easily configure your Hazelcast member/client to use Azure discovery by having the `hazelcast-all`
(or `hazelcast-azure`) JAR on your classpath and enabling Azure in your Hazelcast configuration.

See the
https://github.com/hazelcast/hazelcast-azure[Hazelcast Azure Plugin documentation^]
for more details.

[[hazelcast-cloud-discovery-plugins-gcp]]
== Hazelcast GCP

Hazelcast provides support for https://cloud.google.com/compute/[Google Compute Engine^],
covering the following environments:

* Compute Engine VM Instances with https://github.com/hazelcast/hazelcast-gcp[Hazelcast GCP Discovery plugin^]
* Google Kubernetes Engine (GKE) with https://github.com/hazelcast/hazelcast-kubernetes[Hazelcast Kubernetes Discovery plugin^]

In both scenarios you can use the `ZONE_AWARE` feature to create partition backups in other Availability Zones (AZ)
and therefore prevent any data loss in case of AZ failures.

You can easily configure your Hazelcast member/client to use GCP discovery by having the `hazelcast-all`
(or `hazelcast-gcp`) JAR on your classpath and enabling GCP in your Hazelcast configuration.

See the
https://github.com/hazelcast/hazelcast-gcp[Hazelcast GCP Plugin documentation^]
for more details.

[[hazelcast-cloud-discovery-plugins-kubernetes]]
== Hazelcast Kubernetes

Hazelcast provides support for all https://kubernetes.io/[Kubernetes^] environments with the use of
https://github.com/hazelcast/hazelcast-kubernetes[Hazelcast Kubernetes Discovery plugin].

We tested Hazelcast in the following environments: GKE, EKS, AKS, OpenShift, IBM Cloud, Minikube.

The plugin supports the `ZONE_AWARE` feature to create partition backups in other Availability Zones (AZ)
and therefore prevent any data loss in case of AZ failures.

You can easily configure your Hazelcast member/client to use Kubernetes discovery by having the `hazelcast-all`
(or `hazelcast-kubernetes`) JAR on your classpath and enabling Kubernetes in your Hazelcast configuration.

See the
https://github.com/hazelcast/hazelcast-kubernetes[Hazelcast Kubernetes Plugin documentation^]
for more details.

[[hazelcast-cloud-discovery-plugins-eureka]]
== Hazelcast Eureka

Hazelcast supports using https://github.com/Netflix/eureka[Eureka^] server as the discovery mechanism
with the use of https://github.com/hazelcast/hazelcast-eureka[Hazelcast Eureka Discovery plugin].

You can easily configure your Hazelcast member/client to use Eureka discovery by having the `hazelcast-eureka-one`
JAR on your classpath and enabling Eureka in your Hazelcast configuration.

See the
https://github.com/hazelcast/hazelcast-eureka[Hazelcast Eureka Plugin documentation^]
for more details.

[[hazelcast-cloud-discovery-plugins-zookeeper]]
== Hazelcast Zookeeper

Hazelcast supports using https://zookeeper.apache.org/[Zookeeper^] as the discovery mechanism
with the use of https://github.com/hazelcast/hazelcast-zookeeper[Hazelcast Zookeeper Discovery plugin].

You can easily configure your Hazelcast member/client to use Zookeeper discovery by having the `hazelcast-zookeeper`
JAR on your classpath and enabling Zookeeper in your Hazelcast configuration.

See the
https://github.com/hazelcast/hazelcast-zookeeper[Hazelcast Zookeeper Plugin documentation^]
for more details.

== Other Discovery Plugins

Apart from the officially maintained plugins listed above, there are a number of community plugins implementing
Hazelcast Discovery SPI:

* https://github.com/bitsofinfo/hazelcast-docker-swarm-discovery-spi[Hazelcast Docker Swarm Discovery Plugin]
* https://github.com/bitsofinfo/hazelcast-consul-discovery-spi[Hazelcast Consul Discovery Plugin]
* https://github.com/bitsofinfo/hazelcast-etcd-discovery-spi[Hazelcast Etcd Discovery Plugin]
* https://github.com/jkutner/hazelcast-heroku-discovery[Hazelcast Heroku Discovery Plugin]