= Framework Integration Plugins

Hazelcast provides the following integration plugins that
allow Hazelcast to integrate with other frameworks and applications.

== Hazelcast Hibernate 2LC

http://hibernate.org/[Hibernate^] is an object-relational mapping tool for the Java programming language.
It provides a framework for mapping an object-oriented domain model to a relational database and
enables developers to more easily write applications whose data outlives the application process.

https://github.com/hazelcast/hazelcast-hibernate[Hazelcast Hibernate plugin^] provides Hazelcast's own distributed
second level cache implementation for your Hibernate entities, collections and queries.

To use this plugin, add the `hazelcast-all` (or `hazelcast-hibernate*`) dependency into your classpath.

See the following for more details:

* https://github.com/hazelcast/hazelcast-hibernate[Hazelcast Hibernate Plugin documentation^].
* https://guides.hazelcast.org/springboot-hibernate/[Hazelcast Guides: Hibernate Second-Level Cache^]

== Spring Boot

Hazelcast is very well integrated with the whole https://spring.io/projects/spring-boot[Spring Boot^] ecosystem.
See the following resources for the details:

* https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-hazelcast[Spring Boot: Hazelcast^]
* https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-caching-provider-hazelcast[Spring Boot: Caching with Hazelcast^]
* https://guides.hazelcast.org/hazelcast-embedded-springboot/[Hazelcast Guides: Hazelcast with Spring Boot^]
* https://guides.hazelcast.org/caching-springboot/[Hazelcast Guides: Caching in SpringBoot Microservices^]
* https://guides.hazelcast.org/springboot-webfilter-session-replication/[Hazelcast Guides: Session Replication with Spring Boot^]

== Spring Integration

https://github.com/spring-projects/spring-integration[Spring Integration^] provides an extension for Hazelcast.
It includes, but is not limited to, the following features:

* Event-driven inbound channel adapter: Listens related Hazelcast data structure events and
sends event messages to the defined channel.
* Continuous query inbound channel adapter: Listens the modifications performed on specific map entries.
* Cluster monitor inbound channel adapter:  Listens the modifications performed on the cluster.
* Distributed SQL inbound channel adapter: Runs the defined distributed SQL and returns
the results in the light of iteration type.
* Outbound channel adapter: Listens the defined channel and writes the incoming messages to
the related distributed data structure.
* Leader election: Elects a cluster member, for example, for highly available
message consumer where only one member should receive messages.

See the
https://github.com/spring-projects/spring-integration-extensions/tree/master/spring-integration-hazelcast[Spring Integration Extension documentation^]
for more details.

== Spring Data Hazelcast

https://spring.io/projects/spring-data[Spring Data^] provides
a consistent, Spring-based programming model for data access while
preserving the features of the underlying data store.

https://github.com/hazelcast/spring-data-hazelcast[Spring Data Hazelcast plugin^] provides an implementation
of the https://github.com/spring-projects/spring-data-keyvalue[Spring Data Key Value^] abstraction, which
lets you use Hazelcast as the data store or a layer in between your application and the database.

See the
https://github.com/hazelcast/spring-data-hazelcast[Spring Data Hazelcast documentation^]
for more details.

== Quarkus

Hazelcast integrates well with the https://quarkus.io/[Quarkus framework^]. What's more is that, if you use
the client/server topology, then Hazelcast client works in the GraalVM native executable mode. That means that
you can use Hazelcast in your super-fast native Docker images.

See the following resources for more details:

* https://github.com/hazelcast/quarkus-hazelcast-client[Hazelcast Client for Quarkus documentation^]
* https://guides.hazelcast.org/hazelcast-client-quarkus/[Hazelcast Guides: Hazelcast Client with Quarkus^]

== Micronaut

Hazelcast can be used as a caching provider in the https://micronaut.io/[Micronaut^] framework.
See the following resources for more details:

* https://micronaut-projects.github.io/micronaut-cache/snapshot/guide/#hazelcast[Micronaut: Hazelcast Support^]
* https://guides.hazelcast.org/caching-micronaut/[Hazelcast Guides: Caching in Micronaut Microservices^]

== Hazelcast JCA Resource Adapter

Hazelcast JCA Resource Adapter is a system-level software driver which
can be used by a Java application to connect to the Hazelcast cluster.
Using this adapter, you can integrate Hazelcast into Java EE containers.
After a proper configuration, Hazelcast can participate in the standard Java EE transactions.

See the
https://github.com/hazelcast/hazelcast-ra[Hazelcast JCA Resource Adapter documentation^]
for more details.

== Hazelcast DynaCache

https://www.ibm.com/support/knowledgecenter/en/linuxonibm/liaag/cache/pubwasdynacachoverview.htm[DynaCache^] by IBM is
used to store objects, and later, based on some data matching rules, to retrieve those objects and serve them from its cache.
This plugin is for Liberty Profile which is a lightweight profile of IBM WebSphere Application Server.

In the Liberty Profile, you can use a dynamic cache engine in order to cache your data.
With this plugin, you can use Hazelcast as a cache provider.

See the
https://github.com/hazelcast/hazelcast-dynacache[Hazelcast DynaCache documentation^]
for more details.

== MuleSoft

Hazelcast is embedded within a MuleSoft container as an out-of-the-box offering.
For a proper integration you should edit the `mule-deploy.properties` file to have the following entry:

```
loader.override=com.hazelcast
```