= Web Session Replication Plugins

You can use Hazelcast to replicate your web session in a number of environments.

== Filter Based Web Session Replication

This plugin (a.k.a. Generic Web Session Replication) provides
HTTP session replication capabilities across a Hazelcast cluster in order to
handle failover cases. Assuming you have multiple web servers with load balancers;
if one server goes down, your users on that server are directed to one of
the other live servers, but their sessions are not lost. Using this plugin backs up
these HTTP sessions; it clusters them automatically.

See the https://github.com/hazelcast/hazelcast-wm[Filter Based Web Session Replication documentation^]
for more details.

== Tomcat Based Web Session Replication

Tomcat based web session replication is offered through Hazelcast Tomcat Session Manager.
It is a container specific module that enables session replication for
JEE Web Applications without requiring changes to the application.

See the following for more details:

* https://github.com/hazelcast/hazelcast-tomcat-sessionmanager[Tomcat Based Web Session Replication documentation^]
* https://guides.hazelcast.org/springboot-tomcat-session-replication[Hazelcast Guides: Tomcat Session Replication with Spring Boot and Hazelcast^]

== Jetty Based Web Session Replication

Jetty based web session replication is offered through Hazelcast Jetty Session Manager.
It is a container specific module that enables session replication for
JEE Web Applications without requiring changes to the application.

See the https://www.eclipse.org/jetty/documentation/current/configuring-sessions-hazelcast.html[Jetty: Persistent Sessions with Hazelcast^]
for more details.