= Consistency and Replication Model

== A Brief Overview of Consistency and Replication in Distributed Systems

Partitioning and replication are the two common techniques used together in
distributed databases to achieve scalable, available and transparent data distribution.
The data space is divided into partitions, each of which contains
a distinct portion of the overall data set. For these partitions, multiple copies called replicas
are created. Partition replicas are distributed among the cluster members.
Each member is assigned to at most a single replica for a partition.
In this setting, different replication techniques can be used to access the data and
keep the replicas in sync on updates. The technique being used directly affects
the guarantees and properties a distributed data store provides, due to
the CAP (**C**onsistency, **A**vailability and **P**artition Tolerance) principle.

One aspect of replication techniques is about where a replicated data set is
accessed and updated. For instance, primary-copy systems first elect
a replica, which can be called as primary, master, etc., and use that
replica to access the data. Changes in the data on the primary replica are
propagated to other replicas. This approach has different namings, such as
_primary-copy_, _single-master_, _passive replication_. The primary-copy technique is
a powerful model as it prevents conflicts, deadlocks among the replicas.
However, primary replicas can become bottlenecks.
On the other hand, we can have a different technique by eliminating
the primary-copy and treating each replica as equal. These systems can
achieve a higher level of availability as a data entry can be accessed and
updated using any replica. However, it can become more difficult to keep
the replicas in sync with each other.

Replication techniques also differ in how updates are propagated among replicas.
One option is to update each replica as part of a single atomic transaction, called as
_eager replication_ or _synchronous replication_. Consensus algorithms apply
this approach to achieve strong consistency on a replicated data set.
The main drawback is the amount of coordination and communication required while
running the replication algorithm. CP systems implement consensus algorithms under the hood.
Another option is the _lazy replication_ technique, which is also called as
_asynchronous replication_. Lazy replication algorithms execute updates on replicas with
separate transactions. They generally work with best-effort.
By this way, the amount of coordination among the replicas are degraded and
data can be accessed in a more performant manner. Yet, it can happen that
a particular update is executed on some replicas but not on others, which causes
replicas to diverge. Such problems can be resolved with different approaches, such as
_read-repair_, _write-repair_, _anti-entropy_. Lazy replication techniques are
popular among AP systems.