= Exactly-once, At-least-once or At-most-once Execution

Hazelcast, as an AP product, does not provide the exactly-once guarantee.
In general, Hazelcast tends to be an at-least-once solution.

In the following failure case, exactly-once guarantee can be broken:
When the target member of a pending invocation leaves the cluster while
the invocation is waiting for a response, that invocation is re-submitted to
its new target due to the new partition table. It can be that, it has
already been executed on the leaving member and backup updates are propagated to
the backup replicas, but the response is not received by the caller.
If that happens, the operation will be executed twice.

In the following failure case, invocation state becomes indeterminate:
As explained above, when an invocation does not receive a response in time,
invocation fails with an `OperationTimeoutException`. This exception does not
say anything about outcome of the operation, that means operation may not be
executed at all, it may be executed once or twice (due to member left case explained above).