= Timeouts

The following properties and configuration elements define timeouts
for several aspects of connections.

For cluster and members:

* xref:clusters:network-configuration.adoc#tcp-ip-element[connection-timeout-seconds]:
Maximum amount of time the member is going to try to connect
to the cluster before giving up. Setting it to a too low value could
mean that a member is not able to connect to a cluster. Setting it to a too
high value means that member startup could slow down because of longer timeouts.
Increasing this value is recommended
if you have many IPs listed and the members cannot properly build up the cluster.
Its default value is 5 seconds.
* xref:clusters:failure-detector-configuration.adoc#ping-failure-detector[timeout-milliseconds]:
Amount of milliseconds until a ping attempt is considered failed if there was
no reply. Its default value is 1000 milliseconds.
* xref:ROOT:system-properties.adoc[hazelcast.connect.all.wait.seconds]: Timeout in seconds to connect
all other cluster members when a member is joining to a cluster. 
* xref:ROOT:system-properties.adoc[hazelcast.socket.connect.timeout.seconds]: Socket connection timeout in seconds.
The connection is blocked until either it is established or refused or this timeout passes.
Default is 0, means infinite.
* xref:clusters:failure-detector-configuration.adoc#phi-accrual-failure-detector[hazelcast.max.no.heartbeat.seconds]:
Maximum timeout of heartbeat in seconds for a member to assume it is dead.
This is the timeout which defines when a cluster member is suspected because it has not sent any heartbeats.
It is used in the xref:clusters:failure-detector-configuration.adoc#deadline-failure-detector[deadline] and
xref:clusters:failure-detector-configuration.adoc#phi-accrual-failure-detector[phi accrual failure detector] configurations.

For clients:

* xref:clients:java.adoc#configuring-client-connection-retry[cluster-connect-timeout-millis]:
Timeout value in milliseconds for the client to give up to connect to the current cluster.
Its default value is -1, i.e., infinite.
For the default value, client will not stop trying to connect to the target cluster
(infinite timeout). If the xref:clients:java.adoc#blue-green-mechanism[failover client] is used with the default value of
this configuration element, the failover client will try to connect alternative
clusters after 120000 ms (2 minutes). For any other value, both the client and
the failover client will use this as it is.
* xref:clients:java.adoc#setting-connection-timeout[connection-timeout]: Timeout in milliseconds
to accept the client connection requests by the members.
* xref:clients:java.adoc#client-system-properties[hazelcast.client.heartbeat.timeout]: Timeout
in milliseconds for the heartbeat messages sent by the client to members.
If no messages pass between the client and member within
the given time, the connection will be closed.

