= Configure Hibernate Second-Level Cache

**Code Sample**: See the https://github.com/hazelcast/hazelcast-code-samples/tree/master/spring/spring-hibernate-2ndlevel-cache[sample application^]
for Hibernate second Level Cache configuration.

== Spring Boot

If you are using Spring Boot, all you need is to modify your `application.properties`:

[source,yaml]
----
spring:
  jpa:
    properties:
      hibernate:
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region:
            factory_class: com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory
          # configuration of Hazelcast client
          hazelcast:
            instance_name: my-instance
      javax:
        persistence:
          sharedCache:
            # Only entities marked with Cacheable will use 2nd level cache
            mode: ENABLE_SELECTIVE
----

== Non-Boot Spring
If you are using Hibernate with Hazelcast as a second level cache provider, you can easily configure your
`LocalSessionFactoryBean` to use a Hazelcast instance by passing Hazelcast instance name. That way, you can use the
same `HazelcastInstance` as Hibernate L2 cache instance.

[tabs]
====
Java::
+
--
[source,java]
----
@Value("${hz.instance.name}")
private String hazelcastInstanceName;
@Bean
public LocalSessionFactoryBean sessionFactory() throws Exception {
    LocalSessionFactoryBean bean = new LocalSessionFactoryBean();

    Properties hibernateProperties = new Properties();
    hibernateProperties.put("hibernate.cache.region.factory_class", "com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory");
    // need to specify Hazelcast connection parameter, such as instance name
    hibernateProperties.put("hibernate.cache.hazelcast.instance_name", hazelcastInstanceName);

    hibernateProperties.put("hibernate.dialect", "org.hibernate.dialect.MySQLDialect");
    bean.setHibernateProperties(hibernateProperties);
    bean.setDataSource(dataSource());
    bean.setPackagesToScan("com.example");
    return bean;
}
----
--
XML::
+
--
[source,xml]
----
...
<bean id="sessionFactory"
      class="org.springframework.orm.hibernate3.LocalSessionFactoryBean"
	  scope="singleton">
    <property name="dataSource" ref="dataSource"/>
    <property name="hibernateProperties">
        <props>
            ...
            <prop key="hibernate.cache.region.factory_class">com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory</prop>
            <!-- need to specify Hazelcast connection parameter, such as instance name -->
            <prop key="hibernate.cache.hazelcast.instance_name">${hz.instance.name}</prop>
        </props>
    </property>
    ...
</bean>
----
--
====




**Hibernate RegionFactory Classes**

* `com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory`
* `com.hazelcast.hibernate.HazelcastCacheRegionFactory`

See the https://github.com/hazelcast/hazelcast-hibernate#configuring-regionfactory[Configuring RegionFactory section^]
in the Hazelcast Hibernate GitHub repository for more information.