= Integrate with Spring

https://spring.io/[Spring] is a popular framework for writing enterprise-grade Java applications. https://spring.io/projects/spring-framework[Spring Framework] includes a range of libraries to reduce the need for boilerplate code and encourages a consistent structure for ease of maintenance. https://spring.io/projects/spring-boot[Spring Boot] further simplifies development by automatically configuring dependencies based on your classpath.

Hazelcast Platform is integrated with the Spring Framework and Spring Boot, allowing you to easily incorporate Hazelcast's fast data cache capabilities into your Spring applications.

== Why use Hazelcast with Spring?

Hazelcast can be used as a Spring cache manager or a JCache-compliant cache in the Spring Framework. Spring Boot automatically configures a Hazelcast member if Hazelcast is on the classpath.

By integrating Hazelcast into your Spring application, you can:

* Call Hazelcast's distributed map (IMap) directly with `@Autowired`.
* Use `@SpringAware` annotation on Hazelcast objects to enable dependency injection.
* Reduce the configuration needed to set up Hazelcast.

== Architecture options

You can embed Hazelcast members in the same Java process as your Spring application or deploy them separately in a client/server topology. See xref:deploy:choosing-a-deployment-option.adoc[].

== Supported versions
// Do we need this?

**Spring Framework**

Supported: 4.3 and higher

Latest tested: 5.3

**Spring Boot**

Supported:

Latest tested: