= Integrate with Spring

https://spring.io/[Spring] is a popular framework for writing enterprise-grade Java applications. The https://spring.io/projects/spring-framework[Spring Framework] includes a range of libraries to reduce the need for boilerplate code and encourages a consistent structure for ease of maintenance. https://spring.io/projects/spring-boot[Spring Boot] further simplifies development by automatically configuring applications on your classpath.

Hazelcast Platform is integrated with the Spring Framework and Spring Boot, allowing you to easily incorporate Hazelcast's fast data cache capabilities into your Spring applications.

== Why use Hazelcast with Spring?

You can use Hazelcast to enhance your Spring applications with caching and session replication.

* **Cache**: you can use Hazelcast as a Spring cache manager or a JCache-compliant cache, as described in the https://docs.spring.io/spring-boot/reference/io/caching.html#io.caching.provider.hazelcast[Spring Boot documentation].

* **Hibernate second-level cache**: you can use Hazelcast as a second-level cache in your https://hibernate.org/[Hibernate] `LocalSessionFactoryBean` configuration.

* **Session replication**: you can use Hazelcast to replicate session data across multiple web applications or microservices. Hazelcast provides xref:plugins:web-session-replication.adoc[plugins] for several web servers, including Spring's default web server, Tomcat.

Using Spring also makes it easier to work with Hazelcast. You can:

* Autowire Hazelcast objects, such as the distributed map (IMap), without needing to configure a Hazelcast member first. Spring Boot automatically configures a Hazelcast member if Hazelcast is on the classpath.
* Use `@SpringAware` annotation on Hazelcast objects to enable dependency injection inside classes processed by Hazelcast, such as `EntryProcessor` and `Callable`.
* Reduce the configuration needed to set up Hazelcast.

== Architecture options

You can embed Hazelcast members in the same Java process as your Spring application or deploy them separately in a client/server topology. See xref:deploy:choosing-a-deployment-option.adoc[].

== Supported versions

Hazelcast supports the following Spring Framework versions:

* **Supported**: 5.3

* **Latest tested**: 6.2
