= Spring IO

If Hazelcast is on the classpath and a suitable configuration is found, Spring Boot auto-configures a link:https://docs.hazelcast.org/docs/5.5.0/javadoc/com/hazelcast/core/HazelcastInstance.html[HazelcastInstance] that you can inject in your application.

NOTE: Hazelcast can be used as a JCache compliant cache or as a Spring org.springframework.cache.CacheManager compliant cache.
When setting 'spring.cache.type' to `hazelcast`, Spring Boot will use the org.springframework.cache.CacheManager based implementation.
If you want to use Hazelcast as a JCache compliant cache, set 'spring.cache.type' to `jcache`.
If you have multiple JCache compliant cache providers and want to force the use of Hazelcast, you have to link:https://docs.spring.io/spring-boot/reference/io/caching.html#io.caching.provider.jcache[explicitly set the JCache provider].

Spring Boot first attempts to create a client by checking the following configuration options:

* The presence of a link:https://docs.hazelcast.org/docs/5.5.0/javadoc/com/hazelcast/client/config/ClientConfig.html[hazelcast.client.config.ClientConfig] bean
* A configuration file defined by the spring.hazelcast.config[] property.
* The presence of the `hazelcast.client.config` system property.
* A `hazelcast-client.xml` in the working directory or at the root of the classpath.
* A `hazelcast-client.yaml` (or `hazelcast-client.yml`) in the working directory or at the root of the classpath.

If a client can not be created, Spring Boot attempts to configure an embedded server.
If you define a link:https://docs.hazelcast.org/docs/5.5.0/javadoc/com/hazelcast/config/Config.html[com.hazelcast.config.Config] bean, Spring Boot uses that.
If your configuration defines an instance name, Spring Boot tries to locate an existing instance rather than creating a new one.

You could also specify the Hazelcast configuration file to use through configuration, as shown in the following example:

[source,yaml]
----
spring:
  hazelcast:
    config: "classpath:config/my-hazelcast.xml"
----

Otherwise, Spring Boot tries to find the Hazelcast configuration from the default locations: `hazelcast.xml` in the working directory or at the root of the classpath, or a YAML counterpart in the same locations.
We also check if the `hazelcast.config` system property is set.

TIP: By default, link:https://docs.hazelcast.org/docs/5.5.0/javadoc/com/hazelcast/spring/context/SpringAware.html[com.hazelcast.spring.context.SpringAware] on Hazelcast components is supported.
The link:https://docs.hazelcast.org/docs/5.5.0/javadoc/com/hazelcast/core/ManagedContext.html[com.hazelcast.core.ManagedContext] can be overridden by declaring a link:https://docs.spring.io/spring-boot/api/java/org/springframework/boot/autoconfigure/hazelcast/HazelcastConfigCustomizer.html[HazelcastConfigCustomizer] bean with an link:https://docs.spring.io/spring-framework/docs/6.2.x/javadoc-api/org/springframework/core/annotation/Order.html[org.springframework.core.annotation.Order] higher than zero.

NOTE: Spring Boot also has link:https://docs.spring.io/spring-boot/reference/io/caching.html#io.caching.provider.hazelcast[explicit caching support for Hazelcast].
If caching is enabled, the link:https://docs.hazelcast.org/docs/5.5.0/javadoc/com/hazelcast/core/HazelcastInstance.html[HazelcastInstance] is automatically wrapped in a link:https://docs.spring.io/spring-framework/docs/6.2.x/javadoc-api/org/springframework/cache/CacheManager.html[CacheManager] implementation.

