= Creating Clusters
[[creating-cluster]]

You can create clusters using the `cluster-name` configuration
element.

You can separate and group your clusters in a simple way by specifying cluster names.
Example groupings can be by *development*, *production*, *test*, *app*, etc.
The following is an example declarative configuration.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    <cluster-name>production</cluster-name>
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  cluster-name: production
----
====

You can also define the cluster configuration programmatically.
A JVM can host multiple Hazelcast instances. Each Hazelcast instance can only
participate in one group. Each Hazelcast instance only joins to its own group
and does not interact with other groups. The following code example creates
three separate Hazelcast instances--`h1` belongs to the `production` cluster,
while `h2` and `h3` belong to the `development` cluster.

[source,java]
----
include::ROOT:example$/GroupingClusters.java[tag=groupingclusters]
----