= Deadline Failure Detector

_Deadline Failure Detector_ uses an absolute timeout for missing/lost
heartbeats. After timeout, a member is considered as crashed/unavailable
and marked as suspected.

_Deadline Failure Detector_ has the following configuration properties:

* `hazelcast.heartbeat.interval.seconds`: This is the interval at which
member heartbeat messages are sent to each other.
* `hazelcast.max.no.heartbeat.seconds`: This is the timeout which defines
when a cluster member is suspected because it has not sent any heartbeats.

To use _Deadline Failure Detector_, the configuration property
`hazelcast.heartbeat.failuredetector.type` should be set to `"deadline"`.

**Declarative Configuration:**

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <properties>
        <property name="hazelcast.heartbeat.failuredetector.type">deadline</property>
        <property name="hazelcast.heartbeat.interval.seconds">5</property>
        <property name="hazelcast.max.no.heartbeat.seconds">120</property>
    </properties>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  properties:
    hazelcast.heartbeat.failuredetector.type: deadline
    hazelcast.heartbeat.interval.seconds: 5
    hazelcast.max.no.heartbeat.seconds: 120
----
====

**Programmatic Configuration:**

[source,java]
----
Config config = ...;
config.setProperty("hazelcast.heartbeat.failuredetector.type", "deadline");
config.setProperty("hazelcast.heartbeat.interval.seconds", "5");
config.setProperty("hazelcast.max.no.heartbeat.seconds", "120");
[...]
----

NOTE: _Deadline Failure Detector_ is the default failure detector in Hazelcast.

