= Discovery Mechanisms
:page-aliases: clusters:discovery-mechanisms.adoc
[[discovery-mechanisms]]

A Hazelcast cluster is a network of cluster members that run Hazelcast.
Cluster members  automatically join together to form a cluster. This automatic
joining takes place with various discovery mechanisms that the cluster members
use to find each other.

Please note that, after a cluster is formed, communication between cluster members
is always via TCP/IP, regardless of the discovery mechanism used.

Hazelcast uses the following discovery mechanisms.

[[auto-detection]]
== Auto Detection

By default, Hazelcast tries to automatically detect a member's runtime environment and apply rules to help members discover each other in those environments.

NOTE: Auto Detection is not recommended for production.

Hazelcast can detect the following environments:

- xref:deploy:deploying-on-aws.adoc[AWS]
- xref:deploy:deploying-on-azure.adoc[Azure]
- xref:deploy:deploying-on-gcp.adoc[GCP]
- xref:deploy:deploying-in-kubernetes.adoc[Kubernetes]

If Hazelcast does not detect any of these environments, it falls back to <<multicast, Multicast>>.

[[tcp]]
== TCP

You can configure Hazelcast to be a full TCP/IP cluster. See
xref:discovering-by-tcp.adoc[Discovering Members by TCP] for configuration details.

[[multicast]]
== Multicast

With this mechanism, Hazelcast allows cluster members to find each other
using the multicast communication. See
xref:discovering-by-multicast.adoc[Discovering Members by Multicast].

If you prefer to use this mechanism, make sure that your network is secure.
Since multicast packets are being broadcasted, any member from anywhere can join
the cluster with the appropriate cluster name, so you have less control on the cluster.

Note also that if User Datagram Protocol (UDP) is blocked, as it is for most of the production environments,
discovering with multicast does not work.

[[eureka-cloud-discovery]]
== Eureka Cloud Discovery

Hazelcast supports the Eureka V1 discovery.
See the xref:plugins:cloud-discovery.adoc#hazelcast-cloud-discovery-plugins-eureka[Cloud Discovery Plugins: Hazelcast Eureka section].

[[zookeeper-cloud-discovery]]
== Zookeeper Cloud Discovery

This discovery mechanism provides a service based discovery strategy by using
Apache Curator to communicate with your Zookeeper server.
See the hazelcast-cloud-discovery-plugins-zookeeper, Cloud Discovery Plugins: Hazelcast Zookeeper section>>.

[[hazelcast-for-pcf]]
== Hazelcast for Tanzu VMware

Using a clickable Hazelcast Tile for VMWare (former Pivotal Cloud Foundry), you can
deploy your Hazelcast cluster on PCF. This feature is provided as a Hazelcast
plugin.
See the xref:deploy:deploying-in-vmware-tanzu.adoc[Deploying in VMware Tanzu section].