= Discovering Java Clients
[[discovering-native-clients]]

Hazelcast members and native Java clients can find each other with multicast
discovery plugin. This plugin is implemented using xref:extending-hazelcast:discovery-spi.adoc[Hazelcast Discovery SPI].
You should configure the plugin both at Hazelcast members and Java clients in order to
use multicast discovery.

To configure your cluster to have the multicast discovery plugin, follow
these steps:

* Set the `enabled` attribute of the `hazelcast.discovery.enabled`
property to `true`.
* Add multicast discovery strategy configuration to your XML file,
i.e., `<discovery-strategies>` element.

The following is an example declarative configuration.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <properties>
        <property name="hazelcast.discovery.enabled">true</property>
    </properties>
    <network>
        <join>
            <discovery-strategies>
                <discovery-strategy class="com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy" enabled="true">
                    <properties>
                        <property name="group">224.2.2.3</property>
                        <property name="port">54327</property>
                    </properties>
                </discovery-strategy>
            </discovery-strategies>
        </join>
    </network>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  properties:
    hazelcast.discovery.enabled: true
  network:
    join:
      discovery-strategies:
        discovery-strategy:
          enabled: true
          class: com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy
          properties:
            group: 224.2.2.3
            port: 54327
----
====

The following are the multicast discovery plugin configuration
properties with their descriptions:

* `group`: String value that is used to set the multicast group,
so that you can isolate your clusters.
* `port`: Integer value that is used to set the multicast port.
