= Discovering Members by Auto Detection
[[discovering-members-auto-detection]]

Auto Detection is a good way to start playing with Hazelcast. It tries to automatically detect the appropriate
discovery plugin and apply it to your Hazelcast configuration. Assuming you have `hazelcast-all`
on your classpath and your runtime is Kubernetes, Hazelcast automatically applies
the xref:discovery-mechanisms.adoc#kubernetes-cloud-discovery[Kubernetes discovery mechanism].

Below is a table with minimal requirements for each environment.

.Environment Requirements
[cols="2,5a"]
|===

|Environment|Requirements

|xref:discovery-mechanisms.adoc#hazelcast-cloud-discovery-plugins-aws[AWS]
|AWS EC2 requires the following points:

* Security Group with the port 5701 open
* IAM role with the `ec2:DescribeInstances` permission attached to the EC2 Instance

|xref:discovery-mechanisms.adoc#hazelcast-cloud-discovery-plugins-azure[Azure]
|Azure requires having Azure managed identity with the `READ` role attached to your Azure Virtual Machine.

|xref:discovery-mechanisms.adoc#hazelcast-cloud-discovery-plugins-gcp[GCP]
|GCP requires having Cloud API (at minimum Read Only to Compute Engine API) access attached to your VM Instance.

|xref:discovery-mechanisms.adoc#hazelcast-cloud-discovery-plugins-kubernetes[Kubernetes]
| Kubernetes requires applying the
https://raw.githubusercontent.com/hazelcast/hazelcast/master/kubernetes-rbac.yaml[RBAC permissions^].

|===