= Failure Detector Configuration
[[failure-detector-configuration]]

A failure detector is responsible to determine if a member in the cluster is
unreachable or crashed. The most important problem in failure detection is to
distinguish whether a member is still alive but slow or has crashed. But according
to the famous http://dl.acm.org/citation.cfm?doid=3149.214121[FLP result^],
it is impossible to distinguish a crashed member from a slow one in an asynchronous
system. A workaround to this limitation is to use unreliable failure detectors.
An unreliable failure detector allows a member to suspect that others have failed,
usually based on liveness criteria but it can make mistakes to a certain degree.

Hazelcast has the following built-in failure detectors: Deadline Failure Detector
and Phi Accrual Failure Detector.

There is also a Ping Failure Detector, that, if enabled, works in parallel with
the above ones, but identifies
the failures on OSI Layer 3 (Network Layer). This detector is by default disabled.

Note that, Hazelcast also offers failure detectors for its Java client.
See the xref:clients:java.adoc#java-client-failure-detectors[Client Failure Detectors section] for more information.
