= Phi Accrual Failure Detector

Phi Accrual Failure Detector keeps track of the intervals between heartbeats
in a sliding window of time and measures the mean and variance of these
samples and calculates a value of suspicion level (Phi). The value of phi
increases when the period since the last heartbeat gets longer. If the network
becomes slow or unreliable, the resulting mean and variance increase, there needs
to be a longer period for which no heartbeat is received before the member is suspected. 

The following is an example configuration with property descriptions.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <properties>
        <property name="hazelcast.heartbeat.failuredetector.type">phi-accrual</property> <1>
        <property name="hazelcast.heartbeat.interval.seconds">1</property> <2>
        <property name="hazelcast.max.no.heartbeat.seconds">60</property> <3>
        <property name="hazelcast.heartbeat.phiaccrual.failuredetector.threshold">10</property> <4>
        <property name="hazelcast.heartbeat.phiaccrual.failuredetector.sample.size">200</property> <5>
        <property name="hazelcast.heartbeat.phiaccrual.failuredetector.min.std.dev.millis">100</property> <6>
    </properties>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  properties:
    hazelcast.heartbeat.failuredetector.type: phi-accrual <1>
    hazelcast.heartbeat.interval.seconds: 1 <2>
    hazelcast.max.no.heartbeat.seconds: 60 <3>
    hazelcast.heartbeat.phiaccrual.failuredetector.threshold: 10 <4>
    hazelcast.heartbeat.phiaccrual.failuredetector.sample.size: 200 <5>
    hazelcast.heartbeat.phiaccrual.failuredetector.min.std.dev.millis: 100 <6>
----

Java Member API::
+
[source,java]
----
Config config = ...;
config.setProperty("hazelcast.heartbeat.failuredetector.type", "phi-accrual"); <1>
config.setProperty("hazelcast.heartbeat.interval.seconds", "1"); <2>
config.setProperty("hazelcast.max.no.heartbeat.seconds", "60"); <3>
config.setProperty("hazelcast.heartbeat.phiaccrual.failuredetector.threshold", "10"); <4>
config.setProperty("hazelcast.heartbeat.phiaccrual.failuredetector.sample.size", "200"); <5>
config.setProperty("hazelcast.heartbeat.phiaccrual.failuredetector.min.std.dev.millis", "100"); <6>
[...]
----
====
<1> The value must be `phi-accrual`.
<2> xref:deadline-detector.adoc#heartbeat-interval[Interval] at which member heartbeat messages are sent to each other.
<3> Timeout which defines when a cluster member is suspected because it has not sent any heartbeats.
Since _Phi Accrual Failure Detector_ is adaptive to network conditions, a much lower `hazelcast.max.no.heartbeat.seconds` can be defined than
_Deadline Failure Detector_'s xref:deadline-detector.adoc#heartbeat-timeout[timeout].
<4> The phi threshold for suspicion. After calculated phi exceeds this threshold, a member
is considered as unreachable and marked as suspected. A low threshold allows to
detect member crashes/failures faster but can generate more mistakes and cause
wrong member suspicions. A high threshold generates fewer mistakes but is slower
to detect actual crashes/failures. `phi = 1` means likeliness that we will make a mistake is about `10%`. The likeliness
is about `1%` with `phi = 2`, `0.1%` with `phi = 3` and so on. Default phi threshold is 10.
<5> Number of samples to keep for history. Its default value is 200.
<6> Minimum standard deviation to use for the normal distribution used when calculating phi.
Too low standard deviation might result in too much sensitivity.