= Data Structures
:description: To allow your data structures to resolve your user code, you must reference the required namespace in the data structure configuration. You can configure the same namespace for multiple data structures.
:page-enterprise: true
:page-beta: false

{description}

Any data structure without a specific {ucn} definition in its configuration uses the `default` namespace, if it has been configured. For further information on defining a `default` namespace, see the xref:clusters:ucn-non-associated.adoc[] topic.

WARNING: If your data structure configuration specifies a namespace that has not been configured, a fatal error is returned when an operation is performed on that data structure.

To configure {ucn} for your data structure using static configuration, complete the following steps:

. If not already open, open the _hazelcast_ configuration file in your preferred editor and scroll to your data structure configuration section
. Add the following to the end of your data structure configuration:
+
[tabs]
====
XML::
+
[source,xml]
----
    <user-code-namespace>myNameSpace</user-code-namespace>
----
YAML::
+
[source,yaml]
----
   user-code-namespace: "myNameSpace"
----
====
. Save the file
== Example Multimap Configuration Section
The following extract shows the full configuration, including the {ucn} definition, for a Multimap data structure:
[tabs]
====
XML::
+
[source,xml]
----
<multimap name="default">
    <backup-count>1</backup-count>
    <async-backup-count>0</async-backup-count>
    <binary>true</binary>
    <value-collection-type>SET</value-collection-type>
    <entry-listeners>
        <entry-listener include-value="true" local="true">com.hazelcast.examples.EntryListener</entry-listener>
    </entry-listeners>
    <split-brain-protection-ref>splitBrainProtectionRuleWithThreeNodes</split-brain-protection-ref>
    <merge-policy batch-size="100">PutIfAbsentMergePolicy</merge-policy>
    <user-code-namespace>myNameSpace</user-code-namespace>
</multimap>
----
YAML::
+
[source,yaml]
----
multimap:
    default:
      backup-count: 1
      async-backup-count: 0
      binary: true
      value-collection-type: SET
      entry-listeners:
        - class-name: com.hazelcast.examples.EntryListener
          include-value: true
          local: true
      split-brain-protection-ref: splitBrainProtectionRuleWithThreeNodes
      merge-policy:
        batch-size: 100
        class-name: PutIfAbsentMergePolicy
      user-code-namespace: "myNameSpace"
----
====