= Migrate from {ucd}
:description: {ucn} improves and extends the capabilities of {ucd} and is applicable to more use cases. Hazelcast recommends that {enterprise-product-name} users deprecate their {ucd} implementations and migrate to using {ucn}.
:page-enterprise: true
:page-beta: false

{description}

To migrate your existing {ucd}, enable {ucn} and complete the configuration as described in the xref:clusters:ucn-enable.adoc[] topic.

There are several note-worthy differences between {ucd} and {ucn} which need to be accounted for when migrating:

* {ucn} does not have any configuration elements for Hazelcast Clients, all static configuration is managed in member configurations.
This means that resources deployed statically need to be referencable by all members of the cluster. See xref:clusters:ucn-member-side.adoc[] for more information.
* Resources deployed with {ucd} were essentially added to the member classpath, however {ucn} introduces the Namespace concept which allows these resources to be separated. This separation allows conflicting classes to exist in separate namespaces without issue, however data structures will need to reference the correct namespace to access the relevant resources. To achieve similar behaviour to {ucd} in {ucn}, configure your resources in the `default` namespace, which means they will be available to all data structures which do not explicitly define a namespace already.
* {ucn} does not support loading resources from the classpath, and they should be defined from static locations instead. Resources, including classpath classes, can still be uploaded by clients to the cluster but this will need to be done through the programmatic API. See xref:clusters:ucn-dynamic-client.adoc[] for more information.
* Resources in {ucn} can be dynamically added or replaced at runtime. This provides various benefits, but care should be taken to ensure that
resources are not removed from actively running operations as this could cause errors. See xref:clusters:ucn-dynamic-config.adoc[] for more information.