= Non-associated Namespaces
:description: You can configure a default namespace with resources that can be used by any data structure without any associated {ucn} defined, or, for example, a partition loss listener. A default namespace is also useful when you are using an API that is not namespace-aware.
:page-enterprise: true
:page-beta: true

{description}

You can use static or dynamic configuration to define your `default` namespace.

== Static Configuration

You can define your `default` namespace either programmatically or in the _hazelcast_ configuration file.

For further information on static configuration, see the xref:clusters:ucn-static-config.adoc[] section.

=== Programmatically

To configure a `default` namespace programmatically, add the following lines to your code:

[source,java]
----
UserCodeNamespaceConfig userCodeNamespaceConfig = new UserCodeNamespaceConfig();
        userCodeNamespaceConfig.setName("default"); 
        userCodeNamespaceConfig.addClass(loadClass("usercodenamespaces.required_class"));
        config.getNamespacesConfig().addNamespaceConfig(userCodeNamespaceConfig);
----

=== Configuration File

To configure a `default` namespace using static configuration in the _hazelcast_ configuration file, complete the following steps:

. If not already open, open the _hazelcast_ configuration file in your preferred editor and scroll to the {ucn} section

. Define the name of the namespace as `default`, as follows:
+
[tabs]
====
XML::
+
[source,xml]
----
<user-code-namespaces enabled="true">
    :
    <user-code-namespace name="default">
    </user-code-namespace>
----

YAML::
+
[source,yaml]
----
user-code-namespaces:
   enabled: true
   :
   default:
----
====  

. Define the resources
+
To define a resource, you must provide an identifier for the resource, the resource type, and the location (URL) in which the resource can be found.
+
The resource type can be either JAR or JAR-In-Zip; the following extract provides examples for both of these resource types:
+
[tabs]
====
XML::
+
[source,xml]
----
<user-code-namespaces enabled="true">
    :
    <user-code-namespace name="default">
        <jar id="jarID">
            <url>file:./src/class/ucnDefaults/MyJarFile.jar</url>
        </jar>
        <jars-in-zip id="MyJARsInZIPFileID">
            <url>file:./src/class/ucnDefaults/MyJarZIP.jar</url>
        </jars-in-zip>
    </user-code-namespace>
----

YAML::
+
[source,yaml]
----
user-code-namespaces:
   enabled: true
   :
   default:
    - id: jarID
      url: "file:./src/class/ucnDefaults/MyJarFile.jar"
    - id: MyJARsInZIPFileID
      url: "file:./src/class/ucnDefaults/MyJarZIP.jar"
----
====  

. Save the file

== Dynamic Configuration

To configure a default namespace using dynamic configuration, add the following to your _member.java_ file:

[source,java]
----
UserCodeNamespaceConfig userCodeNamespaceConfig = new UserCodeNamespaceConfig("default");
        config.getNamespacesConfig().addNamespaceConfig(userCodeNamespaceConfig);
----

For further information on dynamic configuration, see the xref:clusters:ucn-dynamic-config.adoc[] topic.