= Enable {ucn}
:description: For security reasons, you must enable {ucn} using static configuration. You can do this programmatically, or using the hazelcast configuration file.
:page-enterprise: true
:page-beta: true

{description}

== Enable Programmatically

To enable {ucn} programmatically, create a _member.java_ file, add the following, then save the file to your configuration folder:

[source,jave]
----
package com.hazelcast.namespace.staticconfig.classconfig;

import com.hazelcast.config.Config;
import com.hazelcast.config.UserCodeNamespaceConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;

public class Member {

    public static void main(String[] args) {
        Config config = new Config();
        config.getNamespacesConfig().setEnabled(true);
    }
}
----

== Enable in Configuration File

To enable {ucn} using the _hazelcast_ configuration file, complete the following steps:

. Open the _hazelcast_ configuration file in your preferred editor
+
The _hazelcast_ configuration file can be either an XML or YAML file. 

. Scroll to the bottom of the file
. Add the following:
+
[tabs]
====
XML::
+
[source,xml]
----
<user-code-namespaces enabled="true">
----

YAML::
+
[source,yaml]
----
user-code-namespaces:
   enabled: true
----
====  

== Complete the Configuration

You can continue your configuration as follows: 

* In the _hazelcast_ configuration file, as described in the xref:ucn-static-config.adoc[] section
* Using static programmatic configuration, as described in the xref:clusters:ucn-static-programmatic.adoc[] topic 
* Using dynamic configuration, as described in the xref:ucn-dynamic-config.adoc[] section
