= Member Configuration
:description: {ucn} are referenced by name, and can be statically configured in the hazelcast configuration file. You can specify JAR and JAR-In-Zip resources in the configuration file.
:page-enterprise: true
:page-beta: true

{description}

To configure {ucn} using the _hazelcast_ configuration file, in either XML or YAML format, complete the following steps:

. If not already open, open the _hazelcast_ configuration file in your preferred editor and scroll to the {ucn} section
. If required, add a `java-serialization-filter` to verify classes when loaded into the class loader during namespace deployment
+
For further information on the configuration of the `java-serialization-filter`, see the xref:serialization:serialization-configuration.adoc[] topic.

. Define the name of the namespace under the line in which you enabled {ucn}, as follows:
+
[tabs]
====
XML::
+
[source,xml]
----
<user-code-namespaces enabled="true">
    :
    <user-code-namespace name="myNameSpace">
    </user-code-namespace>
----

YAML::
+
[source,yaml]
----
user-code-namespaces:
   enabled: true
   :
   myNameSpace:
----
====  

. Define the resources
+
To define a resource, you must provide an identifier for the resource, the resource type, and the location (URL) in which the resource can be found.
+
You can define multiple {ucn}, if required, by repeating steps 3 and 4 for your other namespaces.
+
The resource type can be either JAR or JAR-In-Zip; the following extract provides examples for both of these resource types:
+
[tabs]
====
XML::
+
[source,xml]
----
<user-code-namespaces enabled="true">
    :
    <user-code-namespace name="myNameSpace">
        <jar id="jarID">
            <url>file:./src/class/usercodedeployment/MyJarFile.jar</url>
        </jar>
        <jars-in-zip id="MyJARsInZIPFileID">
            <url>file:./src/class/usercodedeployment/MyJarZIP.jar</url>
        </jars-in-zip>
    </user-code-namespace>
----

YAML::
+
[source,yaml]
----
user-code-namespaces:
   enabled: true
   :
   myNameSpace:
    - id: jarID
      url: "file:./src/class/usercodedeployment/MyJarFile.jar"
    - id: MyJARsInZIPFileID
      url: "file:./src/class/usercodedeployment/MyJarZIP.jar"
----
====  
+
NOTE: If you want to define Class resources, you can use programmatic configuration. For further information on programmatic configuration, see the xref:clusters:ucn-static-programmatic.adoc[] topic.

. Save the file

Before you can use these namespaces, you must define which data structures use which of your configured namespaces. For further information on configuring the namespace used by your data structure, see the xref:clusters:ucn-data-structures.adoc[] topic.

NOTE: You can configure the `default` namespace as a fallback for situations where the data structure does not have a defined namespace. For further information on configuring the `default` namespace, see the xref:clusters:ucn-non-associated.adoc[] topic. 