= {ucn}
:description: {ucn} provide a container for Java classpath resources, such as user code and accompanying artifacts like property files. This provides namespace isolation to ensure that access to resources in different namespaces can be managed through configuration.
:page-enterprise: true
:page-beta: false

{description}

NOTE: This approach replaces the deprecated {ucd} method of adding your resources to make them available for your user-defined functions. For information on migrating your {ucd} to {ucn}, see the xref:clusters:ucn-migrate-ucd.adoc[] topic. The original {ucd} information has been retained to support your migration in the xref:clusters:legacy-ucd.adoc[] section. 

Your resources can be run on a Hazelcast cluster to support your business logic. For example, you might want to use your resources in one of the following:

* MapStore
* Split brain events
* `ExecutorService` runnable
To use {ucn}, you must enable it as described in the xref:clusters:ucn-enable.adoc[] topic.

User-defined functions are associated with {ucn} using the namespace names. Named data structures each define a single namespace name; you can configure the same namespace name for multiple data structures. You can also configure the `default` namespace; for example, to provide resources for a user-defined function that is not associated with a data structure. For further information on the `default` namespace, see the xref:clusters:ucn-non-associated.adoc[] topic. Your resources are located using an URL. For example, your resources could be located on your member or client with an URL such as _\file:///opt/hz/lib/calc.jar_ or _classpath:///com/acme/myClass_. 

WARNING: If your data structure is associated with a namespace that has not been configured, a fatal error is returned when an operation is performed on that data structure.

You can configure {ucn} in the following ways:

* Static. This configuration must exist on start-up and is defined using XML or YAML files, or programmatically. For further information on static configuration, see the xref:ucn-static-config.adoc[] section
* Dynamic. This configuration allows you to deploy resources from your client. This method allows you to update your {ucn} at runtime, which means that the next call for a data structure associated with the namespace uses the updated resources. For further information on dynamic configuration, see the xref:ucn-dynamic-config.adoc[] section
+
NOTE: When using dynamic configuration, long-running executions are not restarted and continue to use the previous namespace resources until you manually restart them.
+
You can define resources in your dynamic configuration as follows:
+
[%header,cols="1,2"]
|===
|Resource |Description
|Class
|Use to deploy a single Java class instance; for example `MyEntryProcessor.class`.
This is the best way to deploy a small amount of code, in a single class, from your application class path to the cluster.

|JAR
|Use to to deploy a single JAR file; for example, `All_Entry_processors.jar`.
You can include additional dependencies using shading when the JAR is produced.
This is the best way to package non-trivial code for deployment. 

|JARS IN ZIP
|Use to deploy a ZIP containing multiple JAR files; for example, `All_Entry_Processors.zip`.
This is the best way to package JAR files and dependencies for larger deployments, or where additional dependencies are used without repackaging.
|===

You can define different {ucn} by providing a name and the URLs used to locate the resources. Multiple data structures can reference the same namespace.

You can follow the provided code examples to support your use of the API configuration, as described in the link:https://github.com/hazelcast/hazelcast-code-samples/user-code-namespaces/README.md[Code Samples GitHub repo^].