= Choosing an Application Topology
:description: Hazelcast offers two topologies to use Hazelcast: embedded in a Java application or in a client/server topology. To help you choose a topology that meets your requirements, this topic describes each option.
:page-aliases: ROOT:topologies.adoc
:url-cloud-signup: https://viridian.hazelcast.com/sign-in?next=/

You can deploy Hazelcast in two topologies, depending on where you want the Hazelcast members to run:

- *Embedded mode:* Hazelcast members run in the same Java process as your application.
- *Client/server mode:* Hazelcast members run remotely outside your application, allowing you to scale them independently and connect to them through any of the supported clients.

TIP: If you don't want to deploy your own self-managed cluster, try link:{url-cloud-signup}[Hazelcast {hazelcast-cloud} Managed Services] for free.

== Comparing Topologies

This table compares embedded mode and client/server mode in terms of latency, scalability, and available programming languages.

[cols="h,a,a"]
.Comparison of Hazelcast Topologies
|===
| |Embedded|Client/Server

|Low-latency
|Yes
|If used with xref:clients:java.adoc#configuring-client-near-cache[Near Cache] to store frequently used data in the client's local memory.

|Scalability
|The application and the cluster must be scaled together
|You can scale the cluster independently of your application

|Supported clients
| Java
|
[.tablelist]
include::ROOT:partial$clients.adoc[]

|===

== Embedded Mode

Hazelcast is written in Java, which means that Java developers can integrate, or embed, it as a library in their applications. This topology is called _embedded_ mode.

All you need to do is add the Hazelcast JAR file to the application’s classpath and start a member with the Java API. Then all the benefits of Hazelcast are available right inside the application.

image::ROOT:single-embedded.svg[A single Hazelcast member is embedded in a Java application,200]

In this mode, each instance of your application
starts a Hazelcast member, and all members automatically form their own cluster. To interact with the cluster, you use a local member in your application.

image::ROOT:multi-embedded.svg[A cluster of Hazelcast members are embedded in Java applications,600]

If you are a Java developer working in an IDE, this is a convenient
way to run a cluster on your development machine. There is nothing
stopping you from starting your program several times to get a
cluster on the same physical machine.

The main advantage of embedded mode is that all your Java
classes are visible to Hazelcast. This way, you don't need to add classes to your members for tasks such as entry processing or submitting jobs.

xref:getting-started:get-started-java.adoc[Get started with Hazelcast embedded].

== Client/Server Mode

In client/server mode, the Hazelcast cluster is independent of your application, which means that they can be independently scaled.
To interact with the cluster, you use one of the available clients.

image::ROOT:client-server-pc-mobile.svg[Client/Server Mode,600]

Client/server mode has advantages, including more predictable and reliable
performance, easier identification of problem causes and, most importantly, better scalability.
When you need to scale in this mode, just add more Hazelcast members. You
can address client and server scalability concerns separately.

Client/server mode also provides higher availability. If there are any issues in running either
your application or Hazelcast members, the issue and any potential failure is isolated from the rest
of the application and members.

Get started with client/server:

- xref:getting-started:get-started-docker.adoc[Docker]
- xref:getting-started:get-started-cli.adoc[CLI]
- xref:getting-started:get-started-binary.adoc[Binary]