= Kubernetes/OpenShift Deployment
[[deploying-in-kubernetes]]

Hazelcast provides a few methods to simplify deploying Hazelcast cluster into Kubernetes-based environments. For production-grade Kubernetes deployment, use Helm chart or Kubernetes/OpenShift Operator.

== Quick Start

If you just want to play with Hazelcast on Kubernetes, execute the following commands to create Hazelcast cluster
with 3 members into `default` namespace using the `default` Service Account.

[source,shell]
----
kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast-kubernetes/master/rbac.yaml
kubectl run hazelcast-1 --image=hazelcast/hazelcast:$HAZELCAST_VERSION
kubectl run hazelcast-2 --image=hazelcast/hazelcast:$HAZELCAST_VERSION
kubectl run hazelcast-3 --image=hazelcast/hazelcast:$HAZELCAST_VERSION
----

Hazelcast members automatically discovers themselves using the
https://github.com/hazelcast/hazelcast-kubernetes[Hazelcast Kubernetes Discovery plugin^]
and therefore form one Hazelcast cluster.

== Helm Chart

https://helm.sh/[Helm^] is a package manager for Kubernetes. Hazelcast is distributed in a form of Helm Charts:

* https://github.com/hazelcast/charts/tree/master/stable/hazelcast[hazelcast/hazelcast^]
* https://github.com/hazelcast/charts/tree/master/stable/hazelcast-enterprise[hazelcast/hazelcast-enterprise^]

See the https://github.com/hazelcast/charts[Hazelcast Helm Charts documentation^]
for more details.

== Kubernetes/OpenShift Operator

Kubernetes Operators are software extensions to Kubernetes which help you create and manage your applications.
You can deploy and manage Hazelcast using the following Operators:

* https://hub.docker.com/r/hazelcast/hazelcast-operator[hazelcast/hazelcast-operator^]: Hazelcast Operator hosted on Docker Hub
* https://hub.docker.com/r/hazelcast/hazelcast-enterprise-operator[hazelcast/hazelcast-enterprise-operator^]: Red Hat certified Hazelcast Enterprise Operator hosted on Docker Hub
* https://catalog.redhat.com/software/containers/hazelcast/hazelcast-enterprise-operator/5eb3bf9bac3db90370945f59[registry.connect.redhat.com/hazelcast/hazelcast-enterprise-operator^]: Hazelcast Enterprise Operator hosted on Red Hat Container Catalog

There are a few different ways in using Hazelcast Operators:

* kubectl/oc instructions: See the https://github.com/hazelcast/hazelcast-operator[Hazelcast Operator documentation^].
* OpenShift Web Console: OpenShift provides a way to deploy operators from its UI.
* OperatorHub instructions: Check Operator Hub for https://operatorhub.io/operator/hazelcast-operator[Hazelcast^] and https://operatorhub.io/operator/hazelcast-enterprise-operator[Hazelcast Enterprise^].