= Deploying on Kubernetes
:description: Discover ways to deploy Hazelcast clusters in Kubernetes environments.

[[deploying-in-kubernetes]]

{description}

== Limitations

Hazelcast CP Subsystem can be used safely in Kubernetes only if xref:cp-subsystem:configuration.adoc#cp-subsystem-configuration[CP Subsystem Persistence] is enabled (Enterprise Feature). Otherwise, a CP Subsystem Group may not recover after scaling the cluster or a rolling upgrade.

== Quickstart

If you just want to play with Hazelcast on Kubernetes, execute the following commands to create a Hazelcast cluster
with 3 members in the `default` namespace using the `default` Service Account.

[source,shell,subs="attributes+"]
----
kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast/master/kubernetes-rbac.yaml
kubectl run hazelcast-1 --image=hazelcast/hazelcast:{full-version}
kubectl run hazelcast-2 --image=hazelcast/hazelcast:{full-version}
kubectl run hazelcast-3 --image=hazelcast/hazelcast:{full-version}
----

Hazelcast members <<discovering-members-in-kubernetes-automatically, automatically discover themselves>> and form one Hazelcast cluster.

NOTE: For production-grade Kubernetes deployment, use Helm chart or Hazelcast Platform Operator.

== Helm Chart

https://helm.sh/[Helm^] is a package manager for Kubernetes. Hazelcast is distributed in a form of Helm Charts:

* https://github.com/hazelcast/charts/tree/master/stable/hazelcast[hazelcast/hazelcast^]
* https://github.com/hazelcast/charts/tree/master/stable/hazelcast-enterprise[hazelcast/hazelcast-enterprise^]

See the https://github.com/hazelcast/charts[Hazelcast Helm Charts documentation^]
for more details.

== Hazelcast Platform Operator for Kubernetes/OpenShift

Kubernetes Operators are software extensions to Kubernetes which help you create and manage your applications. Hazelcast Platform Operator automates common management tasks such as configuring, creating, and scaling Hazelcast clusters on Kubernetes and Red Hat OpenShift. By taking care of manual deployment and life-cycle management, Hazelcast Platform Operator makes it simpler to work with Hazelcast clusters.

See the https://docs.hazelcast.com/operator/latest/[Hazelcast Platform Operator Documentation] for more information and find details about deploying a Hazelcast cluster in Kubernetes and also connecting clients outside Kubernetes.

== Guides

Explore some step-by-step guides about how to use Hazelcast in Kubernetes.

=== Getting Started

* link:https://guides.hazelcast.org/kubernetes/[Deploy Hazelcast Cluster on Kubernetes]

=== Hazelcast Features

* link:https://guides.hazelcast.org/kubernetes-external-client/[Connect External Hazelcast Client to Kubernetes]
* link:https://guides.hazelcast.org/kubernetes-hpa/[Deploy Hazelcast Cluster with Kubernetes HPA]
* link:https://guides.hazelcast.org/kubernetes-ssl/[Enable SSL between Hazelcast Members and Clients on Kubernetes]
* link:https://guides.hazelcast.org/kubernetes-wan/[Use Hazelcast WAN Replication on Kubernetes]

=== Embedded and Sidecar Topologies

* link:https://guides.hazelcast.org/kubernetes-embedded/[Deploy Hazelcast Applications on Kubernetes]
* link:https://guides.hazelcast.org/kubernetes-sidecar/[Use Hazelcast as Sidecar Container]

=== Service Meshes

* link:https://guides.hazelcast.org/istio/[Use Hazelcast with Istio Environment]
* link:https://guides.hazelcast.org/linkerd/[Use Hazelcast with Linkerd Environment]
