= Kubernetes Operator (preview)
[[deploying-with-operator]]

NOTE: Hazelcast Enterpise Operator is currently in the early alpha preview stage, but it will soon become the preferred way of installing Hazelcast in Kubernetes/OpenShift environments.

The simplest way of installing and operating your Hazelcast cluster in the Kubernetes (and OpenShift) environments is to use Hazelcast Enterprise Operator.

== Deploy Hazelcast Enterprise Operator

You can deploy Hazelcast Enterprise Operator with the following `bundle.yaml` file.

[source,yaml]
----
include::ROOT:example$/bundle.yaml[tag=operator-bundle]
----

After you create `bundle.yaml`, you can apply it to your Kubernetes cluster with the following command.

[source,shell]
----
kubectl apply -f bundle.yaml
----

Note that by default Hazelcast Operator is installed into the `default` namespace. If you want to change it, you can either replace all `namespace: default` parameters in `bundle.yaml` or use https://kustomize.io/[Kustomize] to achieve it, for example, by creating the following `kustomization.yaml` file.

[source,yaml]
----
namespace: <your-namespace>
resources:
- bundle.yaml
----

Then, use Kustomize to apply `bundle.yaml` with namespace changed.

[source,shell]
----
kubectl apply -k .
----

At this point, your Hazelcast Enteprise Operator should be up and running in your Kubernetes cluster. You can check it with the following commands.

[source,shell]
----
kubectl logs deployment.apps/hazelcast-enterprise-controller-manager

2021-07-14T09:03:40.713Z        INFO    setup   Watching namespace: default
2021-07-14T09:03:41.524Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
2021-07-14T09:03:41.524Z        INFO    setup   starting manager
2021-07-14T09:03:41.525Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
...
----

== Create Secret with Hazelcast License Key

Hazelcast Enteprise needs to have license key specified, you should store it in the Kubernetes Secret.

[source,shell]
----
kubectl create secret generic hazelcast-license-key --from-literal=license-key=<YOUR LICENSE KEY>
----

== Start Hazelcast Enterprise Cluster

Finally, you can create `Hazelcast` Custom Resource file as `hazelcast-cr.yaml`.

[source,yaml]
----
include::ROOT:example$/hazlecast-cr.yaml[tag=hazelcast-cr]
----

Apply it with the following command to start the Hazelcast cluster.

[source,shell]
----
kubectl apply -f hazelcast-cr.yaml
----

After a moment, you can verify that Hazelcast cluster is up and running by checking the Hazelcast member logs.

[source,shell]
----
kubectl logs pod/hazelcast-sample-0
...
Members {size:3, ver:3} [
        Member [10.36.8.3]:5701 - ccf31703-de3b-4094-9faf-7b5d0dc145b2 this
        Member [10.36.7.2]:5701 - e75bd6e2-de4b-4360-8113-040773d858b7
        Member [10.36.6.2]:5701 - c3d105d2-0bca-4a66-8519-1cacffc05c98
]
...
----
