= Public Clouds
:description: Deploy a Hazelcast cluster in cloud environments including Hazelcast {hazelcast-cloud} Managed Services, Amazon AWS, Google Cloud Platform, and Azure.

{description}

All these environments support the following features:

- Allow members to discover each other automatically without static IP configuration.
- Prevent data loss by creating partition backups in other Availability Zones (AZ).

== Hazelcast {hazelcast-cloud} Managed Services

Deploy a Hazelcast application on xref:cloud:ROOT:overview.adoc[Hazelcast {hazelcast-cloud} Managed Services].

Learn more about xref:cloud:ROOT:developer-guide.adoc[developing applications for Hazelcast {hazelcast-cloud}]. 


[[hazelcast-cloud-discovery-plugins-aws]]
== Hazelcast AWS

Deploy a Hazelcast application on https://aws.amazon.com/[Amazon Web Services].

To deploy a cluster on Amazon EC2, ECS/EC2, or ECS/Fargate, see xref:deploy:deploying-on-aws.adoc[].

To deploy a cluster on Amazon EKS/Fargate or EKS/EC2, see xref:kubernetes:deploying-in-kubernetes.adoc[].

[[hazelcast-cloud-discovery-plugins-azure]]
== Hazelcast Azure

Deploy a Hazelcast application on https://azure.microsoft.com/en-us/[Microsoft Azure^]:

* xref:deploy:deploying-on-azure.adoc[Deploying a cluster on Azure Virtual Machines]
* xref:kubernetes:deploying-in-kubernetes.adoc#discovering-members-in-kubernetes-automatically[Deploying a cluster on Azure Kubernetes Service] (AKS)

[[hazelcast-cloud-discovery-plugins-gcp]]
== Hazelcast GCP

Deploy a Hazelcast application on https://cloud.google.com/compute/[Google Compute Engine^]:

* xref:deploy:deploying-on-gcp.adoc[Deploying a cluster on Compute Engine VM Instances]
* xref:kubernetes:deploying-in-kubernetes.adoc#discovering-members-in-kubernetes-automatically[Deploying a cluster on Google Kubernetes Engine] (GKE)

[[hazelcast-cloud-discovery-plugins-kubernetes]]
== Hazelcast Kubernetes

Deploy a Hazelcast application in https://kubernetes.io/[Kubernetes^] environments, including the following that we have tested: GKE, EKS, AKS, OpenShift, IBM Cloud, Minikube.

See xref:kubernetes:deploying-in-kubernetes.adoc[].

== Other Cloud Environments

To deploy Hazelcast in other cloud environments, check our list of xref:plugins:cloud-discovery.adoc[supported cloud plugins].