= Deploy a Cluster with the Enterprise Operator (Preview)
[[deploying-with-operator]]

NOTE: Hazelcast Enterprise Operator is currently in the early alpha preview stage, but it will soon become the preferred way of installing Hazelcast in Kubernetes/OpenShift environments.

The simplest way of installing and operating your Hazelcast Enterprise cluster in the Kubernetes (and OpenShift) environments is to use Hazelcast Enterprise Operator.

== Deploy Hazelcast Enterprise Operator

You can deploy Hazelcast Enterprise Operator by creating the following `bundle.yaml` file.

[source,yaml]
----
include::ROOT:example$/operator/bundle.yaml[]
----

Then, you can apply it to your Kubernetes cluster with the following command.

[source,shell]
----
kubectl apply -f bundle.yaml
----

At this point, your Hazelcast Enteprise Operator should be up and running. You can check it with the following command.

[source,shell]
----
kubectl logs deployment.apps/hazelcast-enterprise-controller-manager

2021-07-14T09:03:40.713Z        INFO    setup   Watching namespace: default
2021-07-14T09:03:41.524Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
2021-07-14T09:03:41.524Z        INFO    setup   starting manager
2021-07-14T09:03:41.525Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
...
----

== Customize Namespace (optional)

By default, Hazelcast Operator is installed into the `default` namespace. If you want to change it, you can either replace all `namespace: default` parameters in `bundle.yaml` or use https://kustomize.io/[Kustomize] to achieve it by creating the following `kustomization.yaml` file.

[source,yaml]
----
namespace: <your-namespace>
resources:
- bundle.yaml
----

Then, use Kustomize to apply `bundle.yaml` with the changed namespace.

[source,shell]
----
kubectl apply -k .
----

Note that you'll need to add a parameter `-n <your-namespace>` to all further commands.

== Create Secret with Hazelcast License Key

Hazelcast Enteprise requires having the license key specified as Kubernetes Secret.

NOTE: If you don't have Hazelcast Enterprise License Key, please check xref:deploy:using-enterprise-edition.adoc#requesting-a-license-key[Requesting a License Key]

[source,shell]
----
kubectl create secret generic hazelcast-license-key --from-literal=license-key=<YOUR LICENSE KEY>
----

== Start Hazelcast Enterprise Cluster

Finally, you can create `Hazelcast` Custom Resource file as `hazelcast.yaml`.

[source,yaml]
----
include::ROOT:example$/operator/hazelcast.yaml[]
----

Apply it with the following command to start the Hazelcast cluster.

[source,shell]
----
kubectl apply -f hazelcast.yaml
----

After a moment, you can verify that Hazelcast cluster is up and running by checking the Hazelcast member logs.

[source,shell]
----
kubectl logs pod/hazelcast-sample-0
...
Members {size:3, ver:3} [
        Member [10.36.8.3]:5701 - ccf31703-de3b-4094-9faf-7b5d0dc145b2 this
        Member [10.36.7.2]:5701 - e75bd6e2-de4b-4360-8113-040773d858b7
        Member [10.36.6.2]:5701 - c3d105d2-0bca-4a66-8519-1cacffc05c98
]
...
----

== Connect to Hazelcast from Outside Kubernetes

To connect to a Hazelcast cluster from outside Kubernetes, you need to configure the `expose-externally` field of your custom resource.


[source,yaml]
----
include::ROOT:example$/operator/hazelcast_expose_externally.yaml[]
----

After applying the configuration change in Kubernetes, each Hazelcast member will be exposed as a separate service.

[source,shell]
----
kubectl get service
NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)          AGE
hazelcast-sample     LoadBalancer   10.219.246.19    35.230.92.217   5701:30560/TCP   2m11s
hazelcast-sample-0   NodePort       10.219.254.192   <none>          5701:31890/TCP   2m11s
hazelcast-sample-1   NodePort       10.219.247.43    <none>          5701:32310/TCP   2m11s
hazelcast-sample-2   NodePort       10.219.243.16    <none>          5701:32585/TCP   2m11s
----

To connect to the cluster, you can add the external IP address of the LoadBalancer service to your Hazelcast client configuration.

You can configure the `expose-externally` field with the following properties:

* `type`: The way in which Hazelcast members are exposed to clients.
** `Unisocket`: Members are exposed via one Kubernetes service.
** `Smart`: Each member is exposed via a separate Kubernetes service.
* `discoveryServiceType`: Type of Kubernetes service used for discovering members in a Hazelcast cluster.
** `LoadBalancer` (default): Hazelcast client configuration `<load-balancer-external-ip>:5701`.
** `NodePort`: Hazelcast client configuration `<node-address>:<node-port>`.
* `memberAccess`: The way in which clients access Hazelcast members.
** `NodePortExternalIP` (default): Hazelcast clients are outside the Kubernetes network, so a client can access members only via the public IP address that's assigned to their Kubernetes nodes.
** `NodePortNodeName`: Hazelcast clients are inside the same network as the Kubernetes nodes, so clients can access a member by the hostname of its Kubernetes node.
** `LoadBalancer`: Hazelcast clients are outside the Kubernetes network and can access members via the the external IP assigned to the LoadBalancer service.

=== Start Management Center

You can monitor the Hazelcast cluster by starting the Management Center. You can create `ManagementCenter` Custom Resource file as `management-center.yaml`.

[source,yaml]
----
include::ROOT:example$/operator/management-center.yaml[]
----

WARNING: Parameters `persistence` and `hazelcastClusters` should only be set at creation of the Custom Resource. Any change to `persistence` will not affect the Management Center and any change to `hazelcastClusters` will force Management Center pod to be restarted.

Apply it with the following command to start the Management Center.

[source,shell]
----
kubectl apply -f management-center.yaml
----

After a moment, you can verify that Management Center is up and running by checking the Management Center logs.

[source,shell]
----
kubectl logs managementcenter-sample-0

...
2021-08-26 15:21:04,842 [ INFO] [MC-Client-dev.lifecycle-1] [c.h.w.s.MCClientManager]: MC Client connected to cluster dev.
2021-08-26 15:21:05,241 [ INFO] [MC-Client-dev.event-1] [c.h.w.s.MCClientManager]: Started communication with member: Member [10.36.8.3]:5701 - ccf31703-de3b-4094-9faf-7b5d0dc145b2
2021-08-26 15:21:05,245 [ INFO] [MC-Client-dev.event-1] [c.h.w.s.MCClientManager]: Started communication with member: Member [10.36.7.2]:5701 - e75bd6e2-de4b-4360-8113-040773d858b7
2021-08-26 15:21:05,251 [ INFO] [MC-Client-dev.event-1] [c.h.w.s.MCClientManager]: Started communication with member: Member [10.36.6.2]:5701 - c3d105d2-0bca-4a66-8519-1cacffc05c98
2021-08-26 15:21:07,234 [ INFO] [main] [c.h.w.Launcher]: Hazelcast Management Center successfully started at http://localhost:8080/
...
----

To access the Management Center dashboard, open the browser at address `http://$MANCENTER_IP:8080`.

[source,shell]
----
MANCENTER_IP=$( kubectl get service managementcenter-sample -o jsonpath='{.status.loadBalancer.ingress[0].ip}') 
----

== Clean up

Run the following commands to remove Hazelcast cluster, Management Center, Hazelcast License Key Secret, and Hazelcast Enterprise Operator.

[source,shell]
----
kubectl delete -f hazelcast.yaml
kubectl delete -f management-center.yaml
kubectl delete secret hazelcast-license-key
kubectl delete -f bundle.yaml
----
