= Public Clouds
[[deploying-in-cloud]]

Hazelcast can be deployed into different cloud providers. Thanks to dedicated
xref:plugins:cloud-discovery.adoc#hazelcast-cloud-discovery-plugins[Hazelcast Cloud Discovery plugins] there is no static IP configuration needed and
Hazelcast cluster is resilient to availability zone failures.

[[deploying-on-amazon-ec2]]
== Amazon Web Services

You can easily deploy your Hazelcast projects on AWS EC2 instances and ECS clusters. See the
information about xref:deploying-on-aws.adoc[]
for details.

[[deploying-on-microsoft-azure]]
== Microsoft Azure

You can easily deploy your Hazelcast projects on the Azure VM Instances and AKS clusters. See the
information about xref:plugins:cloud-discovery.adoc#hazelcast-cloud-discovery-plugins-azure[Hazelcast Azure Discovery plugin]
for details.

[[deploying-on-gcp]]
== Google Cloud Platform

You can easily deploy your Hazelcast projects on the Google Compute VM Instances and GKE clusters. See the
information about xref:plugins:cloud-discovery.adoc#hazelcast-cloud-discovery-plugins-gcp[Hazelcast GCP Discovery plugin]
for details.