= Manage {enterprise-product-name} license keys
:description: To use Hazelcast {enterprise-product-name}, you need an {enterprise-product-name} license key. This topic explains how to get a license key, install it on a member, and manage it.
:page-aliases: installing-license-keys.adoc, monitoring-license-keys.adoc, renewing-license-keys.adoc, deploy:updating-license-rest.adoc
:page-enterprise: true

{description}

== Get {enterprise-product-name} license key

// tag::get-license[]
Hazelcast {enterprise-product-name} requires a license key. You can get a
trial license from the link:https://hazelcast.com/get-started?utm_source=docs-website[Hazelcast website].

. Complete the form on the link:https://hazelcast.com/get-started?utm_source=docs-website[Hazelcast website]
. Check your email for an automated email from info@hazelcast.com
. You should have a license key that looks like:
+
[source,shell]
----
TrialLicense#10Nodes#eyJhbGxvd2VkTmF0aXZlTWVtb3J5U2l6ZSI6MTAwLCJhbGxvd2VkTnVtYmVyT2ZOb2RlcyI6MTAsImFsbG93ZWRUaWVyZWRTdG9yZVNpemUiOjAsImFsbG93ZWRUcGNDb3JlcyI6MCwiY3JlYXRpb25EYXRlIjoxNzUyMTU0ODYzLjMxODUyNzg2MSwiZXhwaXJ5RGF0ZSI6MTc1NDY5NzU5OS45OTk5OTk5OTksImZlYXR1cmVzIjpbMCwyLDMsNCw1LDYsNyw4LDEwLDExLDEzLDE0LDE1LDE3LDIxLDIyXSwiZ3JhY2VQZXJpb2QiOjAsImhhemVsY2FzdFZlcnNpb24iOjk5LCJvZW0iOmZhbHNlLCJ0cmlhbCI6dHJ1ZSwidmVyc2lvbiI6IlY3In0=.enSTWffnYK_rBdTC7LOVISPYYaEfwdM7giv8ZBH4iq2b5vHuA5U-OswteJUmF8jHXyyo9j0oKBWkvgxe6PBKAQ==
----
+
In any provided code examples in this documentation, you should replace any instances of <YOUR_LICENSE_KEY> with your specific license key.

// end::get-license[]

== Configure a license key on members

// tag::install-license[]
To use Hazelcast {enterprise-product-name}, you need to add a license
key for all members in a cluster.

NOTE: Hazelcast {enterprise-product-name} license keys are only required for members.
You don't need to set a license key for Java clients that are connected to members.

[tabs] 
==== 
XML:: 
+ 
-- 
Replace `<YOUR_LICENSE_KEY>` with your official license key.

[source,xml]
----
<hazelcast>
    <license-key><YOUR_LICENSE_KEY></license-key>
</hazelcast>
----
--

YAML::
+
--
Replace `<YOUR_LICENSE_KEY>` with your official license key.

[source,yaml]
----
hazelcast:
  license-key: <YOUR_LICENSE_KEY>
----
--
Java::
+
--
Replace `<YOUR_LICENSE_KEY>` with your official license key.
Add your license using the link:https://docs.hazelcast.org/docs/{ee-version}/javadoc/com/hazelcast/config/Config.html#setLicenseKey-java.lang.String-[`setLicenseKey()`] method:

[source,java]
----
Config config = new Config();
config.setLicenseKey( "<YOUR_LICENSE_KEY>" );
----
--

Environment Variable::
+
--
[source,shell]
----
HZ_LICENSEKEY=<YOUR_LICENSE_KEY>
----
--

System Property::
+
--
[source,shell]
----
-Dhazelcast.enterprise.license.key=<YOUR_LICENSE_KEY>
----
--
====

// end::install-license[]

// tag::monitor-license[]
== Monitor license keys

It's important to keep track of when your license key is due to expire. If you have an expired license, Hazelcast will not start.

When a license is about to expire, 
Hazelcast issues the following warning in the member logs:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ WARNING @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
HAZELCAST LICENSE WILL EXPIRE IN 29 DAYS.
Your Hazelcast cluster will stop working after this time.

Your license holder is customer@example-company.com, you should have them contact
our license renewal department, urgently on sales@hazelcast.com
or call us on +1 (650) 521-5453

Please quote license id CUSTOM_TEST_KEY
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

The frequency of these warnings varies depending on the time remaining before license expiry.

.Frequency of warnings about license expiration
[cols="1a,1a"]
|===
|Time until expiry|Warning frequency

|Two months
|Daily

|One month
|Hourly

|One week
|Every 30 minutes

|===

To get details about your current license, you can use <<mc, Management Center>>, the <<jmx, JMX API>>, or <<rest, REST API>>.

[[jmx]]
=== Get license details with JMX API

The MBean `HazelcastInstance.LicenseInfo` holds all license
details and can be accessed through Hazelcast's JMX port (if enabled). The
following parameters represent these details:

* `maxNodeCountAllowed`: Maximum members allowed to form a cluster under
the current license.
* [[expiry-date]]`expiryDate`: Expiration date of the current license.
* `typeCode`: Type code of the current license.
* `type`: Type of the current license.
* `ownerEmail`: Email of the current license's owner.
* `companyName`: Company name on the current license.

The following list shows license types and codes:

```
MANAGEMENT_CENTER(1, "Management Center"),
ENTERPRISE(0, "Enterprise"),
ENTERPRISE_SECURITY_ONLY(2, "Enterprise only with security"),
ENTERPRISE_HD(3, "Enterprise HD"),
CUSTOM(4, "Custom");
```

[[rest]]
=== Get license details using the REST API

You can access license details by sending a `GET` request to the `/license` endpoint.

```
curl -v http://localhost:5701/hazelcast/rest/license
```

Its output is similar to the following:

```json
{
  "licenseInfo": {
    "expiryDate": 4090168799999,
    "maxNodeCount": 99,
    "type": 3,
    "companyName": null,
    "ownerEmail": null,"keyHash":"OsLh4O6vqDuKEq8lOANQuuAaRnmDfJfRPrFSEhA7T3Y="
  }
}
```

[[mc]]
=== Get license details using Management Center

See xref:{page-latest-supported-mc}@management-center:ROOT:managing-licenses.adoc[] in the Management Center documentation.

// end::monitor-license[]

// tag::renew-license[]

== Renew a license key

License keys are valid for a certain period of time. For more information, see <<expiry-date, expiry date>>. To renew or upgrade, you can choose one of the following actions:

* Send an email to mailto:sales@hazelcast.com[Sales].
* Send an email to mailto:support@hazelcast.com[Support].
* Call your sales representative.

NOTE: If your license expires on a running cluster or Management Center,
*do not restart* the host device. Instead, contact Hazelcast Support to resolve any issues with an expired license.
[[rest-update-license]]

// end::renew-license[]

// tag::update-license[]

[[update]]
== Update a license key at runtime

When you receive the renewed or upgraded license, you can update it as follows:

. xref:maintain-cluster:shutdown.adoc[Shut down] the members.
. Update the license key -- see <<configuring-a-license-key-on-members, Configuring a License Key on Members>>.
. xref:maintain-cluster:restart-cluster.adoc[Restart] the members.

Alternatively, you can update the license key dynamically, without shutting down the members.
You can use any of the dynamic configuration options to update a license key at runtime. For further information on these options, see xref:configuration:dynamic-config.adoc#options[Adding Dynamic Configuration].

The example in this section uses the REST API option with its dedicated `/license` endpoint. To update a license key at runtime:

. xref:clients:rest.adoc#using-the-rest-endpoint-groups[Enable the REST API].
. Send a `POST` request to the `/license` endpoint:
+
```bash
curl --data "{cluster-name}&{password}&{license}" http://localhost:5001/hazelcast/rest/license
```
+
NOTE: The request parameters must be URL-encoded as described in the xref:clients:rest.adoc[REST Client section].
+
This command updates the license on all running Hazelcast members of the cluster.
If successful, you should see something like the following:

```json
{
  "status": "success",
  "licenseInfo": {
    "expiryDate": 1560380399161,
    "maxNodeCount": 10,
    "type": -1,
    "companyName": "ExampleCompany",
    "ownerEmail": "info@example.com",
    "keyHash": "ml/u6waTNQ+T4EWxnDRykJpwBmaV9uj+skZzv0SzDhs="
  },
  "message": "License updated at run time - please make sure to update the license in the persistent configuration to avoid losing the changes on restart."
}
```

If the update fails on some members, the whole operation fails, leaving the cluster in
a potentially inconsistent state where some members have been switched to the new license
while some have not. You must resolve this situation manually.

[WARNING]
====
By default, if a member shuts down after you dynamically update the license key, its license key will not be retained.

To persist the license key, you can either enable persistence for dynamic configuration or update your members' configuration to include the new license key before you restart them.

For further information, see the following topics:

* xref:configuration:dynamic-config.adoc#persistence[Enabling persistence for dynamic configuration].
* <<configuring-a-license-key-on-members, Configuring a License Key on Members>>.
====
