= Download Archives
[[installing-using-download-archives]]

This option provides the most flexibility and
all the tooling, but takes a little longer time.

NOTE: As a prerequisite, make sure you have Java installed on your system.
If you're using JDK 11 or later, see xref:running-in-modular-java.adoc[].
For the list of supported Java versions, see xref:supported-jvms.adoc[].

You can download and install Hazelcast yourself. You only need to:

* download the package `hazelcast-{page-component-version}.zip` or `hazelcast-{page-component-version}.tar.gz`
from https://hazelcast.org/download[hazelcast.org^]
* extract the downloaded `hazelcast-{page-component-version}.zip` or `hazelcast-{page-component-version}.tar.gz`
* and add the file `hazelcast-{page-component-version}.jar` to your classpath.

When you download and extract the Hazelcast ZIP or TAR.GZ package, you will
see the `start/stop.sh` (for Linux) and `start/stop.bat` (for Windows) scripts under the `/bin` directory.
These scripts start/stop a Hazelcast member. See the xref:getting-started:quickstart.adoc#creating-a-cluster[Quick Start section] to see the start scripts in action.

There are also some other scripts in the download archive whose usage descriptions
are given in their related sections including the xref:management:cluster-utilities.adoc#using-the-hz-cluster-admin-script[Using the `hz-cluster-admin` Script],
xref:cp-subsystem:management.adoc#cp-subsystem-management-apis[CP Subsystem Management APIs section] and
xref:maintain-cluster:monitoring.adoc#health-check-script[Using the hz-healthcheck Script] sections. You can also check the full list
of scripts in the `readme.html` of your download archive.