= Installing Hazelcast On-Premise
:page-aliases: installing-using-download-archives.adoc

You can install and deploy Hazelcast using the options described
in this section. 

[[installing-using-cli]]
== Package Manager

This is the fastest way of getting Hazelcast running. This option is for development purposes. For production, use the other deployment options explained on this page.

// tag::cli[]
. To install Hazelcast, use one of the following methods, depending on your operating system:
+
[tabs] 
==== 
Mac:: 
+ 
--

To install on macOS, use the Homebrew package manager.

[source,bash,subs="attributes+"]
----
brew tap hazelcast/hz
brew install hazelcast@{full-version}
----
--

Linux::
+
--

To install on Linux, you can use either of these package managers, depending on your Linux distribution:
ifdef::snapshot[]
.Debian
[source,shell]
----
wget -qO - https://repository.hazelcast.com/api/gpg/key/public | sudo apt-key add -
echo "deb https://repository.hazelcast.com/debian snapshot main" | sudo tee -a /etc/apt/sources.list
sudo apt update && sudo apt install hazelcast
----

.RPM
[source,shell]
----
wget https://repository.hazelcast.com/rpm/snapshot/hazelcast-rpm.repo -O hazelcast-snapshot-rpm.repo
sudo mv hazelcast-snapshot-rpm.repo /etc/yum.repos.d/
sudo yum install hazelcast
----
endif::[]
ifndef::snapshot[]
.Debian
[source,shell,subs="attributes+"]
----
wget -qO - https://repository.hazelcast.com/api/gpg/key/public | sudo apt-key add -
echo "deb https://repository.hazelcast.com/debian stable main" | sudo tee -a /etc/apt/sources.list
sudo apt update && sudo apt install hazelcast={full-version}
----

.RPM
[source,shell,subs="attributes+"]
----
wget https://repository.hazelcast.com/rpm/stable/hazelcast-rpm-stable.repo -O hazelcast-rpm-stable.repo
sudo mv hazelcast-rpm-stable.repo /etc/yum.repos.d/
sudo yum install hazelcast={full-version}
----
endif::[]
--
Windows::
+
--
At the moment, Hazelcast does not support any Windows package managers.

To get started with Hazelcast on Windows, you can use <<using-docker,Docker>>, the <<using-the-binary, binary distribution>>, or <<using-java, Java>>.
--
====

. Check that Hazelcast is installed.
+
[source,shell]
----
hz -V
----
+
You should see the version of both Hazelcast and the command-line client (CLI).

For more information about the package manager, see the link:https://github.com/hazelcast/hazelcast-packaging[GitHub repository].

// end::cli[]

[[installing-using-maven]]
== Maven

// tag::maven-install[]
Hazelcast runs on Java, which means you can add it as a dependency in your Java project.

The Java package includes both a member API and a Java client API. The member API is for xref:ROOT:topologies.adoc[embedded topologies] where you want to deploy and manage a cluster in the same Java Virtual Machine (JVM) as your applications. The Java client is for connecting to an existing member in a client/server topology.

. Download and install a xref:deploy:supported-jvms.adoc[supported JDK].
+
TIP: We recommend installing the link:https://adoptopenjdk.net[AdoptOpenJDK^].

. Add the following to your `pom.xml` file.
// end::maven-install[]
+
[tabs] 
==== 
Open Source:: 
+ 
-- 
// tag::maven-full-oss[]
ifdef::snapshot[]
[source,xml,subs="attributes+"]
----
<repositories>
    <repository>
        <id>snapshot-repository</id>
        <name>Maven2 Snapshot Repository</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
    </repository>
</repositories>

<dependencies>
   <dependency>
       <groupId>com.hazelcast</groupId>
       <artifactId>hazelcast</artifactId>
       <version>{full-version}</version>
   </dependency>
</dependencies>
----
endif::[]
ifndef::snapshot[]
[source,xml,subs="attributes+"]
----
<dependencies>
   <dependency>
       <groupId>com.hazelcast</groupId>
       <artifactId>hazelcast</artifactId>
       <version>{full-version}</version>
   </dependency>
</dependencies>
----
endif::[]
// end::maven-full-oss[]
--
Enterprise::
+
--
// tag::maven-full-ee[]
ifdef::snapshot[]
[source,xml,subs="attributes+"]
----
<repositories>
    <repository>
        <id>private-repository</id>
        <name>Hazelcast Private Repository</name>
        <url>https://repository.hazelcast.com/release/</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>com.hazelcast</groupId>
        <artifactId>hazelcast-enterprise</artifactId>
        <version>{full-version}</version>
    </dependency>
</dependencies>
----
endif::[]
ifndef::snapshot[]
[source,xml,subs="attributes+"]
----
<repositories>
    <repository>
        <id>private-repository</id>
        <name>Hazelcast Private Repository</name>
        <url>https://repository.hazelcast.com/release/</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>com.hazelcast</groupId>
        <artifactId>hazelcast-enterprise</artifactId>
        <version>{full-version}</version>
    </dependency>
</dependencies>
----
endif::[]
// end::maven-full-ee[]
--
====

[[installing-using-download-archives]]
== ZIP/TAR Packages

The ZIP/TAR packages provide the most flexibility and
all the tooling, but takes a little longer to install.

To download and install a package, do the following:

=== Open Source

// tag::download-package-oss[]
[tabs] 
==== 
Mac:: 
+ 
--
ifdef::snapshot[]
Go to the link:https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/{full-version}/[snapshot repository] and click the download link for the TAR file that has the most up-to-date timestamp in the *Last Modified* columns.
endif::[]
ifndef::snapshot[]
. Download a package from https://hazelcast.com/get-started/download/[hazelcast.com^].
. Extract the downloaded package.
endif::[]
--
Linux:: 
+ 
--
ifdef::snapshot[]
Go to the link:https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/{full-version}/[snapshot repository] and click the download link for the TAR file that has the most up-to-date timestamp in the *Last Modified* columns.
endif::[]
ifndef::snapshot[]
. Download a package from https://hazelcast.com/get-started/download/[hazelcast.com^].
. Extract the downloaded package.
endif::[]
--
Windows:: 
+
--
ifdef::snapshot[]
Go to the link:https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/{full-version}/[snapshot repository] and click the download link for the ZIP file that has the most up-to-date timestamp in the *Last Modified* columns.
endif::[]
ifndef::snapshot[]
. Download a package from https://hazelcast.com/get-started/download/[hazelcast.com^].
. Extract the downloaded package.
endif::[]
--
====
// end::download-package-oss[]

=== Enterprise

// tag::download-package-ee[]
[tabs] 
==== 
Mac:: 
+ 
--
[source,bash,subs="attributes+"]
----
curl 'https://repository.hazelcast.com/download/hazelcast-enterprise/hazelcast-enterprise-{full-version}.tar.gz' | tar xvzf -
----
--
Linux:: 
+ 
--
[source,bash,subs="attributes+"]
----
wget 'https://repository.hazelcast.com/download/hazelcast-enterprise/hazelcast-enterprise-{full-version}.tar.gz' | tar xvzf -
----
--
Windows:: 
+
--
Download and extract the link:https://repository.hazelcast.com/download/hazelcast-enterprise/hazelcast-enterprise-{full-version}.zip[Hazelcast ZIP file].
--
====
// end::download-package-ee[]


[[full-slim]]
== Full and Slim Distributions

Some installation options offer a full and slim distribution.

The full distribution contains all available Hazelcast connectors, libraries, and Management Center.

.What's included in the full distribution
[%collapsible]
====
[source,plain,subs="attributes+"]
----
├── LICENSE
├── NOTICE
├── bin
│   ├── common.sh
│   ├── hz-cli
│   ├── hz-cli.bat
│   ├── hz-cluster-admin
│   ├── hz-cluster-cp-admin
│   ├── hz-healthcheck
│   ├── hz-start
│   ├── hz-start.bat
│   ├── hz-stop
│   └── hz-stop.bat
├── config
│   ├── examples
│   │   ├── hazelcast-client-full-example.xml
│   │   ├── hazelcast-client-full-example.yaml
│   │   ├── hazelcast-client.yaml
│   │   ├── hazelcast-full-example.xml
│   │   ├── hazelcast-full-example.yaml
│   │   ├── hazelcast-security-hardened.yaml
│   │   └── hazelcast.yaml
│   ├── hazelcast-client.xml
│   ├── hazelcast.xml
│   ├── jmx_agent_config.yaml
│   ├── jvm-client.options
│   ├── jvm.options
│   └── log4j2.properties
├── custom-lib
│   ├── hazelcast-3-connector-impl-{full-version}.jar
│   ├── hazelcast-3.12.12.jar
│   └── hazelcast-client-3.12.12.jar
├── lib
│   ├── cache-api-1.1.1.jar
│   ├── hazelcast-3-connector-common-{full-version}.jar
│   ├── hazelcast-3-connector-interface-{full-version}.jar
│   ├── hazelcast-{full-version}.jar
│   ├── hazelcast-download.properties
│   ├── hazelcast-hibernate53-2.1.1.jar
│   ├── hazelcast-jet-avro-{full-version}.jar
│   ├── hazelcast-jet-cdc-debezium-{full-version}.jar
│   ├── hazelcast-jet-cdc-mysql-{full-version}.jar
│   ├── hazelcast-jet-cdc-postgres-{full-version}.jar
│   ├── hazelcast-jet-csv-{full-version}.jar
│   ├── hazelcast-jet-elasticsearch-7-{full-version}.jar
│   ├── hazelcast-jet-files-azure-{full-version}.jar
│   ├── hazelcast-jet-files-gcs-{full-version}.jar
│   ├── hazelcast-jet-files-s3-{full-version}.jar
│   ├── hazelcast-jet-grpc-{full-version}.jar
│   ├── hazelcast-jet-hadoop-all-{full-version}.jar
│   ├── hazelcast-jet-kafka-{full-version}.jar
│   ├── hazelcast-jet-kinesis-{full-version}.jar
│   ├── hazelcast-jet-protobuf-{full-version}.jar
│   ├── hazelcast-jet-python-{full-version}.jar
│   ├── hazelcast-jet-s3-{full-version}.jar
│   ├── hazelcast-sql-{full-version}.jar
│   ├── hazelcast-wm-4.0.jar
│   ├── jansi-2.1.0.jar
│   ├── jline-reader-3.19.0.jar
│   ├── jline-terminal-3.19.0.jar
│   ├── jline-terminal-jansi-3.19.0.jar
│   ├── jmx_prometheus_javaagent-0.14.0.jar
│   ├── log4j-api-2.14.0.jar
│   ├── log4j-core-2.14.0.jar
│   ├── log4j-slf4j-impl-2.14.0.jar
│   ├── picocli-3.9.0.jar
│   └── slf4j-api-1.7.30.jar
└── licenses
    ├── THIRD-PARTY.txt
    ├── apache-v2-license.
    ├── attribution.txt
    └── hazelcast-community-license.txt
├── management-center
│   ├── ThirdPartyNotices.txt
│   ├── bin
│   │   ├── mc-conf.bat
│   │   ├── mc-conf.sh
│   │   ├── mc-start.cmd
│   │   ├── mc-start.sh
│   │   ├── start.bat
│   │   ├── start.sh
│   │   └── user-lib
│   ├── hazelcast-management-center-{full-version}.jar
│   └── license.txt
└── release_notes.txt
----
====

The slim distribution excludes Management Center and connectors. You can use the slim version
to save memory and later include the additional components, as needed.

.What's included in the slim distribution
[%collapsible]
====
[source,plain,subs="attributes+"]
----
├── LICENSE
├── NOTICE
├── bin
│   ├── common.sh
│   ├── hz-cli
│   ├── hz-cli.bat
│   ├── hz-cluster-admin
│   ├── hz-cluster-cp-admin
│   ├── hz-healthcheck
│   ├── hz-start
│   ├── hz-start.bat
│   ├── hz-stop
│   └── hz-stop.bat
├── config
│   ├── examples
│   │   ├── hazelcast-client-full-example.xml
│   │   ├── hazelcast-client-full-example.yaml
│   │   ├── hazelcast-client.yaml
│   │   ├── hazelcast-full-example.xml
│   │   ├── hazelcast-full-example.yaml
│   │   ├── hazelcast-security-hardened.yaml
│   │   └── hazelcast.yaml
│   ├── hazelcast-client.xml
│   ├── hazelcast.xml
│   ├── jmx_agent_config.yaml
│   ├── jvm-client.options
│   ├── jvm.options
│   └── log4j2.properties
├── lib
│   ├── cache-api-1.1.1.jar
│   ├── hazelcast-{full-version}.jar
│   ├── hazelcast-download.properties
│   ├── hazelcast-hibernate53-2.1.1.jar
│   ├── hazelcast-sql-{full-version}.jar
│   ├── hazelcast-wm-4.0.jar
│   ├── jansi-2.1.0.jar
│   ├── jline-reader-3.19.0.jar
│   ├── jline-terminal-3.19.0.jar
│   ├── jline-terminal-jansi-3.19.0.jar
│   ├── jmx_prometheus_javaagent-0.14.0.jar
│   ├── log4j-api-2.14.0.jar
│   ├── log4j-core-2.14.0.jar
│   ├── log4j-slf4j-impl-2.14.0.jar
│   ├── picocli-3.9.0.jar
│   └── slf4j-api-1.7.30.jar
└── licenses
    ├── THIRD-PARTY.txt
    ├── apache-v2-license.txt
    └── hazelcast-community-license.txt
----
====
