= On-Premise

You can install and deploy Hazelcast using the options described
in this section. 

[[installing-using-cli]]
== CLI

This is the fastest way of getting Hazelcast running.
Currently, this option is intended for development purposes.
For production setups please use the other deployment options explained later in this chapter.

To install Hazelcast via command line interface, run the following commands:

[tabs] 
==== 
Homebrew:: 
+ 
-- 
[source,bash]
----
brew tap hazelcast/hz
brew install hazelcast
----
--

Debian::
+
[source,bash]
----
$ wget -qO - https://repository.hazelcast.com/api/gpg/key/public | sudo apt-key add -
$ echo "deb https://repository.hazelcast.com/debian stable main" | sudo tee -a /etc/apt/sources.list
$ sudo apt update && sudo apt install hazelcast
----

RPM::
+
[source,bash]
----
$ wget https://repository.hazelcast.com/rpm/hazelcast-rpm.repo -O hazelcast-rpm.repo
$ sudo mv hazelcast-rpm.repo /etc/yum.repos.d/
$ sudo yum install hazelcast
----
====

Then, you can use the following command on your terminal/command line
to start a standalone Hazelcast member:

[source,bash,subs="attributes+"]
----
hz start
----

For more information visit the GitHub repository
of the https://github.com/hazelcast/hazelcast-command-line[Command Line Interface (CLI)^].

[[installing-using-maven]]
== Maven

This option is the easiest way for Maven users
(typically Java developers), especially appropriate
for the embedded mode when Hazelcast is tightly coupled with the application.

NOTE: As a prerequisite, make sure you have Java installed on your system.
If you're using JDK 11 or later, see xref:running-in-modular-java.adoc[].
For the list of supported Java versions, see xref:supported-jvms.adoc[].

You can find Hazelcast in standard Maven repositories. If your
project uses Maven, you do not need to add
additional repositories to your `pom.xml` or add
`hazelcast-{page-component-version}.jar` file into your
classpath (Maven does that for you). Just add the following
lines to your `pom.xml`:

[tabs] 
==== 
Hazelcast Open Source Edition:: 
+ 
-- 

[source,xml,subs="attributes+"]
----
<dependencies>
    <dependency>
        <groupId>com.hazelcast</groupId>
        <artifactId>hazelcast</artifactId>
        <version>{page-component-version}</version>
    </dependency>
</dependencies>
----
--

Hazelcast Enterprise Edition::
+
[source,xml,subs="attributes+"]
----
<repositories>
    <!-- You need to define following repository: -->
    <repository>
        <id>Hazelcast Private Release Repository</id>
        <url>https://repository.hazelcast.com/release/</url>
    </repository>
    <!-- Optional repository if you want to use latest snapshots -->
    <repository>
        <id>Hazelcast Private Snapshot Repository</id>
        <url>https://repository.hazelcast.com/snapshot/</url>
    </repository>
</repositories>

<dependencies>
    <!-- You also need to define following dependencies: -->
    <dependency>
        <groupId>com.hazelcast</groupId>
        <artifactId>hazelcast-enterprise</artifactId>
        <version>{page-component-version}</version>
    </dependency>
    <!-- Optional dependency for including JavaDoc -->
    <dependency>
        <groupId>com.hazelcast</groupId>
        <artifactId>hazelcast-enterprise</artifactId>
        <version>{page-component-version}</version>
        <classifier>javadoc</classifier>
    </dependency>
</dependencies>
---- 
====

Above dependencies (`hazelcast` and `hazelcast-enterprise`) include both member and Java
client libraries of Hazelcast. A separate Java client module
and dependency do not exist.

[[installing-using-download-archives]]
== ZIP/TAR Packages

This option provides the most flexibility and
all the tooling, but takes a little longer time.

Hazelcast offers full and slim distribution packages:

* The `hazelcast-{page-component-version}` and `hazelcast-enterprise-{page-component-version}` ZIP/TAR
packages contain all Hazelcast Open Source and Enterprise features, respectively.
* The `hazelcast-{page-component-version}-slim` and `hazelcast-enterprise-{page-component-version}-slim` ZIP/TAR
packages exclude Management Center and connectors for distributed processing. You can use the slim version
to save memory and later include the additional components.

NOTE: As a prerequisite, make sure you have Java installed on your system.
If you're using JDK 11 or later, see xref:running-in-modular-java.adoc[].
For the list of supported Java versions, see xref:supported-jvms.adoc[].

You can download and install Hazelcast yourself. You only need to:

* download the package `hazelcast-{page-component-version}.zip` or `hazelcast-{page-component-version}.tar.gz`
from https://hazelcast.com/get-started/download/[hazelcast.com^]
* extract the downloaded package
* and add the file `hazelcast-{page-component-version}.jar` to your classpath.

When you download and extract the Hazelcast ZIP or TAR package, you will
see the `start/stop.sh` (for Linux) and `start/stop.bat` (for Windows) scripts under the `/bin` directory.
These scripts start/stop a Hazelcast member. See xref:getting-started:get-started-binary.adoc[] to see the start scripts in action.

There are also some other scripts in the packages whose usage descriptions
are given in their related sections including the xref:management:cluster-utilities.adoc#using-the-script-cluster-sh[Using the Script cluster.sh],
xref:cp-subsystem:management.adoc#cp-subsystem-management-apis[CP Subsystem Management APIs section] and
xref:management:health-check-monitoring.adoc#health-check-script[Using the hz-healthcheck Script] sections. You can also check the full list
of scripts in the `readme.html` which you can see when you extract the downloaded package.
