= Monitoring License Keys
:description: It's important to keep track of when your license key is due to expire. If you have an expired license, Hazelcast will not start.

{description}

When a license is about to expire, 
Hazelcast issues the following warning about approaching license expiry in the member logs:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ WARNING @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
HAZELCAST LICENSE WILL EXPIRE IN 29 DAYS.
Your Hazelcast cluster will stop working after this time.

Your license holder is customer@example-company.com, you should have them contact
our license renewal department, urgently on sales@hazelcast.com
or call us on +1 (650) 521-5453

Please quote license id CUSTOM_TEST_KEY
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

This frequency of these warnings depends on how long if left until the license expires:

.Frequency of warnings about license expiration
[cols="1a,1a"]
|===
|Time until expiry|Warning frequency

|Two months
|Daily

|One month
|Hourly

|One week
|Every 30 minutes

|===

To get details about your current license, you can use the Management Center, the JMX API, or the REST API.

== Getting License Details with the JMX API

The MBean `HazelcastInstance.LicenseInfo` holds all license
details and can be accessed through Hazelcast's JMX port (if enabled). The
following parameters represent these details:

* `maxNodeCountAllowed`: Maximum members allowed to form a cluster under
the current license.
* `expiryDate`: Expiration date of the current license.
* `typeCode`: Type code of the current license.
* `type`: Type of the current license.
* `ownerEmail`: Email of the current license's owner.
* `companyName`: Company name on the current license.

Following is the list of license types and type codes:

```
MANAGEMENT_CENTER(1, "Management Center"),
ENTERPRISE(0, "Enterprise"),
ENTERPRISE_SECURITY_ONLY(2, "Enterprise only with security"),
ENTERPRISE_HD(3, "Enterprise HD"),
CUSTOM(4, "Custom");
```

== Getting License Details with the REST API

You can access license details by sending a `GET` request to the `/license` endpoint.

```
curl -v http://localhost:5701/hazelcast/rest/license
```

Its output is similar to the following:

```json
{
  "licenseInfo": {
    "expiryDate": 4090168799999,
    "maxNodeCount": 99,
    "type": 3,
    "companyName": null,
    "ownerEmail": null,"keyHash":"OsLh4O6vqDuKEq8lOANQuuAaRnmDfJfRPrFSEhA7T3Y="
  }
}
```

== Getting License Details in Management Center

See xref:{page-latest-supported-mc}@management-center:ROOT:managing-licenses.adoc[] in the Management Center documentation.