= Updating a License Key at Runtime with the REST API
:description: You can use the /license endpoint of the REST API to update the license on a running member.

You can use the `/license` endpoint of the REST API to update the license on a running member.

. xref:clients:rest.adoc#using-the-rest-endpoint-groups[Enable the REST API].

WARNING: By default, if a member shuts down, its license key will not be persisted. To persist the license key, xref:configuration:dynamic-config.adoc#persistence[enable persistence for dynamic configuration].

== Update a License Key

To update the license of a running cluster, send a `POST`
request to the `/license` endpoint. 

```bash
curl --data "{cluster-name}&{password}&{license}" http://localhost:5001/hazelcast/rest/license
```

NOTE: The request parameters must be URL-encoded as described in the xref:clients:rest.adoc[REST Client section].

This command updates the license on all running Hazelcast members of the cluster.
If successful, you should see something like the following:

```json
{
  "status": "success",
  "licenseInfo": {
    "expiryDate": 1560380399161,
    "maxNodeCount": 10,
    "type": -1,
    "companyName": "ExampleCompany",
    "ownerEmail": "info@example.com",
    "keyHash": "ml/u6waTNQ+T4EWxnDRykJpwBmaV9uj+skZzv0SzDhs="
  },
  "message": "License updated at run time - please make sure to update the license in the persistent configuration to avoid losing the changes on restart."
}
```

If the update fails on some members, the whole operation fails, leaving the cluster in
a potentially inconsistent state where some members have been switched to the new license
while some have not. You must resolve this situation manually.