= Supported versions and compatibilities 
:description: This section provides information about the supported versions and interoperability of Hazelcast Platform and its modules.
:page-aliases: deploy:supported-jvms.adoc
:page-icons: font

{description}

== Semantic versioning

Hazelcast Platform uses https://semver.org/[semantic versioning] where versions appear in the following format:

`major.minor.patch`

For example, in Platform version 5.2.1, *5* is the major version, *2* is the minor version, and *1* is the patch version.

Semantic versioning separates new releases into three types:

* Major: This version may include  breaking changes.
* Minor: This version includes backward-compatible functionality.
* Patch: This version includes backward-compatible bug fixes.

=== API compatibility exceptions

According to semantic versioning, a Platform job written using the Pipeline API in a previous minor version should compile and have the same behavior in later minor versions.

However, note the following exceptions:

* Classes in the `com.hazelcast.jet.core` package provide only patch-level compatibility guarantees.
* Types and methods annotated with `@EvolvingApi` and `@Beta` provide only patch-level compatibility guarantee. These are typically new features where the API is subject to further changes.
* Types and methods annotated with `@PrivateApi`, and classes in the `impl` and `internal` packages do not provide any compatibility guarantees between versions. These APIs are not meant for public use.

== Supported architectures

Hazelcast Platform has been tested on the following system architectures.

|===
|Architecture | Supported

|x86_64
|From Platform 5.3

|AArch64/ARM64
|From Platform 5.3


|===

== Supported operating systems

Hazelcast Platform has been tested against the following operating systems. It may run on others which are not listed here.

// tag::supported-os[]
[options="header"]
.Supported Operating Systems
|===
|OS | Platform {full-version}

|RHEL 7, 8, 9
|✓

|Fedora 19, 28, 34
|✓

|Amazon Linux
|✓

|Debian
|✓

|Ubuntu
|✓

|Windows Server 2019
|✓

|Windows 10, 11footnote:dev[Suitable for the development of applications (or Hazelcast itself), _but not_ for production. Some features are not available or are not supported.]
|Supported for development

|macOSfootnote:dev[]
|Supported for development

|===
// end::supported-os[]

== Supported virtualization environments

Hazelcast Platform has been tested against the following virtualization environments. It may run on others which are not listed here.

.Supported Virtualization Environments
|===
|Environment | Platform {full-version}

|VMWare 6.x
|✓

|Docker 23, 27
|✓

|Kubernetes (1.4.x or newer)
|✓

|RedHat OpenShift
|✓

|===

== Supported public cloud environments

.Supported Cloud Environments
|===
|Environment | Platform {full-version}

|Amazon Web Services (AWS)
|✓

|Google Cloud Platform (GCP)
|✓

|Microsoft Azure
|✓

|RedHat OpenShift
|✓

|===


== Supported Java Virtual Machines

Hazelcast Platform runs on Java, and supports the following LTS JDKs. It may run on other JDK distributions which are not listed here.

// tag::supported-jvms[]
[options="header"]
.Supported JDKs
|===
|JDK | Platform {full-version}

|Amazon Corretto 17 and 21
|✓

|Azul Prime 17 and 21
|✓

|Azul Core 17 and 21
|✓

|Eclipse Temurin build of OpenJDK 17 and 21
|✓

|IBM Semeru Runtime 17 and 21
|✓

|Microsoft build of OpenJDK 17 and 21
|✓

|Oracle JDK 17 and JDK 21
|✓

|Red Hat build of OpenJDK 17 and 21
|✓

|===
// end::supported-jvms[]

== Compatibility

The following table shows compatibility between Hazelcast Platform, its management and monitoring components, and clients.

For each Platform version, you can see which versions of Management Center, Hazelcast Operator, CLC, and all official clients (Java, .NET, C++, Python, Node.js, Go) are recommended or supported. 

NOTE: The most recent version is shown in bold to indicate the recommended and most up-to-date option for that Platform version. If you are unsure which version to choose, always select the latest version for best compatibility and support.

[cols="1,2,3,4,5,6,7,8,9,10",options="header"]
.Compatibility at a glance
|===
|Platform version | Management Center | Operator | CLC | Java client | .NET | C++ | Python | Node.js | Go 

|5.5.x
|5.5.0 - *5.8.0*
|5.13 - *5.15*
|5.2.0 - *5.5.0*
|Same as Platform version
|4.0.0 - *5.5.1*
|5.3.1 - *5.4.0*
|4.0.0 - *5.5.0*
|4.0.0 - *5.3.0*
|1.0.0 - *1.4.2*

|5.4.x
|5.4.0 - *5.8.0*
|5.11 - *5.15*
|"
|"
|"
|4.0.0 - *5.4.0*
|"
|"
|"

|5.3.x
|5.3.0 - *5.8.0*
|5.8 - *5.15*
|"
|"
|"
|"
|"
|"
|"

|5.2.x
|5.2.0 - *5.8.0*
|5.6 - *5.15*
|"
|"
|"
|"
|"
|"
|"

|5.1.x
|5.1.0 - *5.8.0*
|N/A
|"
|"
|"
|"
|"
|"
|"

|5.0.x
|5.0.0 - *5.8.0*
|N/A
|"
|"
|"
|"
|"
|"
|"

|===

=== Compatibility guarantees

==== Cluster members

Hazelcast Platform members operating on the same major and minor Platform version are always compatible, regardless of the patch version.

Each minor version is always compatible with the previous minor version.

==== Management Center

All 5.x.y versions of Management Center are compatible with Hazelcast Platform 5.x.y versions. We recommend you use a version of Management Center at least as high as the Hazelcast Platform version in your cluster. For example, Management Center 5.1.1 may not support all the features of Hazelcast Platform 5.2, or vice versa. You should generally upgrade to the latest version of Management Center when available and refer to xref:{page-latest-supported-mc}@management-center:release-notes:releases.adoc[Management Center release notes] for details on each version.

==== Job states

Hazelcast Platform job states are only backward-compatible across the same minor versions.  A newer patch version is able to understand the job states only from the previous patch versions of the same minor version.

If you have a running job, using the rolling upgrades feature, you are able to upgrade the cluster to a newer patch version without losing the state of a running job. See xref:maintain-cluster:rolling-upgrades.adoc[Rolling Upgrades]. Also note that jobs must be resubmitted after a rolling upgrade to a newer minor version since they don't run during upgrades. See xref:pipelines:submitting-jobs.adoc[Submitting Jobs].

Hazelcast clients that submit jobs (currently only Java clients) are compatible with members running on the same minor version. This means that a client using an older or newer patch version is able to connect and submit a job to a cluster that's running a different patch version.

==== Command line tools

Hazelcast xref:management:cluster-utilities.adoc#hazelcast-command-line-tool[CLI] and xref:management:cluster-utilities.adoc#using-the-hz-cluster-admin-script[cluster admin] tools are backwards-compatible across the same minor versions.

==== Configuration files

XML and YAML configuration files provided with the Hazelcast Platform package are backward-compatible across the same minor versions. After upgrading a cluster to a new minor version, the configuration files for the previous version can be used without any modification.

==== Names of metrics

Hazelcast Platform sends metrics to Management Center and other means such as JMX. The names of these metrics may change across minor versions but not between patch versions.
