= Supported Versions and Compatibilities 
:description: This section provides the supported versions and interoperability of Hazelcast Platform and its modules.
:page-aliases: deploy:supported-jvms.adoc
:page-icons: font

{description}

== Semantic Versioning

Hazelcast Platform uses https://semver.org/[semantic versioning] where versions appear in the following format:

`MAJOR.MINOR.PATCH`

For example, in Platform version 5.2.0, *5* is the major version, *1* is the minor version, and *0* is the patch version.

Semantic versioning can be summarized as below:

* MAJOR version; when incompatible API changes are made
* MINOR version; when backward-compatible functionality is added
* PATCH version; when backward-compatible bugs are fixed

=== API Compatibility Exceptions

According to the above versioning summarization, for example, a Platform job written using Pipeline API in a previous minor version should compile in later minor versions.

However, there are following exceptions:

* Classes in `com.hazelcast.jet.core` package which form the only provide patch level compatibility guarantee.
* Types and methods annotated with `@EvolvingApi` only provide patch level compatibility guarantee. These are typically new features where the API is subject to further changes.
* Classes in the `impl` packages do not provide any compatibility guarantees between versions and are not meant for public use.

== Supported Operating Systems

Hazelcast Platform has been tested against the following operating systems.

// tag::supported-os[]
[options="header"]
.Supported Operating Systems
|===
|OS | Platform 5.2.x | Platform 5.1.x | Platform 5.0.x

|RHEL 7, 8
|???
|???
|???

|Fedora 17, 25
|???
|???
|???

|Windows Server 2016, 2019
|???
|???
|???

|macOS ???
|???
|???
|???

|Solaris ???
|???
|???
|???

|IBM zOS ???
|???
|???
|???

|AIX 7.2
|???
|???
|???

|===
// end::supported-os[]

== Supported Virtualization Environments

|===
|Environment | Platform 5.2.x | Platform 5.1.x | Platform 5.0.x

|VMWare ???
|???
|???
|???

|Docker ???
|???
|???
|???

|===

== Supported Public Cloud Environments

|===
|Environment | Platform 5.2.x | Platform 5.1.x | Platform 5.0.x

|AWS
|???
|???
|???

|GCP
|???
|???
|???

|Azure
|???
|???
|???

|Pivotal Cloud Foundry
|???
|???
|???

|RedHat OpenShift
|???
|???
|???

|===


== Supported Java Virtual Machines

Hazelcast runs on Java, so it needs a Java Virtual Machine (JVM). Hazelcast supports the latest and long-term support (LTS) versions of the Java Development Kit (JDK). However, the JVM in some JDKs may not be compatible with Hazelcast.

Hazelcast Platform {full-version} has been tested against the following JDKs.

TIP: If you install Hazelcast with Docker or a package manager, it comes with a supported JDK.

// tag::supported-jvms[]
[options="header"]
.Supported JDKs
|===
|JDK | Versions

|AdoptOpenJDK
|8 and 11

|Amazon Corretto
|8, 11 and 17

|Azul Zing
|8

|Azul Zulu
| 8, 11, and 17

|IBM SDK, Java Technology Edition
|8 (latest)

|Oracle
|8, 11, and 17

|Red Hat build of OpenJDK
|8, 11, and 17

|===
// end::supported-jvms[]

If you use version 11 or later of a JDK, see the following relevant sections:

* xref:running-in-modular-java.adoc[]: Talks about the
new module system and how you can run a Hazelcast
application on it.
* xref:security:tls-ssl.adoc#tlsssl-for-hazelcast-members[TLS/SSL for Hazelcast Members]: Lists
`TLSv1.3`, which comes with Java 11, as a supported TLS version.

== Compatibility Guarantees

=== Cluster Members

Hazelcast Platform members operating on the same major and minor cluster version are always compatible, regardless of the patch version.

Each minor version is always compatible with the previous one.

=== Management Center

The following table shows the versions of Platform and Management Center which can work together.

[options="header"]
.Compatibility with Management Center
|===
|Hazelcast Platform | Hazelcast Management Center

|5.0.x through 5.1.x
|5.1.x

|???
|???

|===

=== Job States

Platform job states are only backwards-compatible across the same minor versions; a newer patch version is able to understand the job state from the previous patch version.

This means that if you have a running job, using the Job Upgrade and Lossless Cluster Restart features you are able to upgrade the cluster to a newer patch version without losing the state of a running job.

=== Command Line Tools

Hazelcast xref:management:cluster-utilities.adoc#hazelcast-command-line-tool[CLI] and xref:management:cluster-utilities.adoc#using-the-hz-cluster-admin-script[cluster admin] tools are backwards-compatible across the same minor versions; you can start a member in a newer patch version, using a configuration file from the previous batch version.

=== Configuration Files

XML and YAML configuration files provided with the Hazelcast Platform package are backwards-compatible across the same minor versions; when upgrading a cluster to a new minor version, the XML/YAML configuration for the previous version can be used without any modification.

=== Metrics

Hazelcast Platform provides metrics to Management Center and also through other means such as JMX. The metrics names may change between minor versions but not between patch versions.
