= Authentication overview
:page-enterprise: true
:page-aliases: security-realms.adoc

NOTE: Authentication is the process of verifying the identity of a user, system, or entity before granting access to resources or services. It ensures that the person or system requesting access is who they claim to be, typically through credentials like passwords, biometrics, tokens, or multi-factor methods. Authentication is a critical security step in protecting data and systems from unauthorized access.

In Hazelcast, Authentication is used to verify the incoming connection has valid credentials configured.
Hazelcast supports several authentication types which can be configured for member-to-member, and client-to-member communication:

* xref:simple-authentication.adoc[Simple] - users and roles are configured directly within the member configuration,
* xref:ldap-authentication.adoc[LDAP] - LDAP server is used to verify credentials and load roles,
* xref:kerberos-authentication.adoc[Kerberos] - service tickets are used for authentication,
* xref:tls-authentication.adoc[TLS] - information from client-side TLS certificates (when TLS mutual authentication is enabled) are used for role assignment,
* xref:jaas-authentication.adoc[custom JAAS login modules] can be also used if other Hazelcast provided authentication mechanisms don't fully cover users needs.

During the authentication roles can be also assigned to the connecting clients and they are later used for the <<Authorization>>.

== Security Realms

Named security configurations called Security Realms are used to map an authentication mechanism to a Hazelcast protocol (client or member).
Security realms allow defining security configuration independently on the module which consumes it.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<hazelcast>
    <security enabled="true">
        <realms>
            <realm name="simpleRealm">
                <authentication>
                    <simple>
                        <user username="test" password="V3ryS3cr3tString">
                            <role>monitor</role>
                            <role>hazelcast</role>
                        </user>
                        <user username="man-center" password="HardToGuess">
                            <role>root</role>
                        </user>
                    </simple>
                </authentication>
            </realm>
        </realms>
        <client-authentication realm="simpleRealm"/>
    </security>
</hazelcast>
----
--

YAML::
+
--
[source,yaml]
----
hazelcast:
  security:
    enabled: true
    realms:
      - name: simpleRealm
        authentication:
          simple:
            users:
              - username: test
                password: 'V3ryS3cr3tString'
                roles:
                  - monitor
                  - hazelcast
              - username: man-center
                password: 'HardToGuess'
                roles:
                  - root
----
--

Java::
+
[source,java]
----
include::ROOT:example$/security/EnablingSecurity.java[tag=authn]
----
====

Besides authentication, Security Realms can contain also xref:identity-configuration.adoc[Identity] and a access-control-service configurations.


== Common Authentication Options

All Hazelcast provided authentication types support some common configuration parameters.

[cols="1,1,3"]
.Common Configuration Options
|===
| Option Name
| Default Value
| Description

| `skip-role`
| `false`
| When set to `true`, the authentication mechanism won't assign roles during the authentication. It'll only verify the credentials.

| `skip-identity`
| `false`
| When set to `true`, the authentication mechanism won't use the remote party name after the authentication.

| `skip-endpoint`
| `false`
| When set to `true`, the authentication mechanism won't use the remote party IP address name after the authentication.

|===

These are advanced configuration options and usually you don't need to touch them.

== Identity

A security configuration element where members and clients have their own credentials configured is called an Identity.
The Identity can be a username-password pair, a token, or a Kerberos ticket. Refer to xref:identity-configuration.adoc[Identity configuration] for more details.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<hazelcast>
    <security enabled="true">
        <realms>
            <realm name="aRealm">
                <authentication>
                    <ldap>
                        <!-- ... -->
                    </ldap>
                </authentication>
                <identity>
                    <username-password username="uid=hazelcast,ou=Services,dc=hazelcast,dc=com" password="theSecret"/>
                </identity>
            </realm>
        </realms>
        <member-authentication realm="aRealm"/>
        <client-authentication realm="aRealm"/>
    </security>
</hazelcast>
----
--

YAML::
+
--
[source,yaml]
----
hazelcast:
  security:
    enabled: true
    realms:
      - name: aRealm
        authentication:
          ldap:
#           ...
        identity:
          username-password:
            username: uid=hazelcast,ou=Services,dc=hazelcast,dc=com
            password: theSecret
    member-authentication:
      realm: aRealm
    client-authentication:
      realm: aRealm

----
--

Java::
+
[source,java]
----
include::ROOT:example$/security/EnablingSecurity.java[tag=identity]
----
====


== Authorization

Authorization is supported by Client protocol. During the authentication,
clients get roles assigned. Access is then controlled by
permissions assigned to the roles.

Authorization is not supported in member-to-member communication. All members
have unlimited access to the cluster data once they authenticate.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<hazelcast>
    <security enabled="true">
        <realms>
            <realm name="aRealm">
                <!-- ... -->
            </realm>
        </realms>
        <client-authentication realm="aRealm"/>
        <client-permissions>
            <all-permissions principal="man-center"/>
            <map-permission name="playground" principal="*">
                <actions>
                    <action>all</action>
                </actions>
            </map-permission>
        </client-permissions>
    </security>
</hazelcast>
----
--

YAML::
+
--
[source,yaml]
----
hazelcast:
  security:
    enabled: true
    realms:
      - name: aRealm  
#       ...
    client-authentication:
      realm: aRealm
    client-permissions:
      all:
        principal: man-center
      map:
        - name: playground
          principal: *
          actions:
            - all

----
--

Java::
+
[source,java]
----
include::ROOT:example$/security/EnablingSecurity.java[tag=authz]
----
====

See xref:client-authorization.adoc[] for more details.
