= Client Authorization
:page-enterprise: true

To protect your members from a malicious client, you can allow them to identify clients and restrict their permissions to access data in data structures or use features such as user code deployment.

The xref:security:authentication-overview.adoc[] describes how authentication is used for verifying credentials, and roles mapping. This section describes how the assigned role names are used to map permissions to clients.

Hazelcast client authorization is configured by a client permission
policy. Hazelcast has a default permission policy implementation that uses
permission configurations defined in the Hazelcast security configuration.
Default policy permission checks are made against instance types (map, queue, etc.),
instance names, instance actions (put, read, remove, add, etc.),
the client endpoint address (`ClusterEndpointPrincipal`), and client roles (`ClusterRolePrincipal`).

The default permission policy allows you to use comma separated names in the `principal`
attribute configuration.

[NOTE]
====
Unless part of the role name, don't include spaces when adding names to the `principal` attribute.

Hazelcast doesn't automatically remove spaces in role names. If you include spaces that aren't part of the name, permission isn't granted to the intended role. 

For example, if you configure permissions for the *admin* and *devel* roles using ``principal=" admin ,devel"``, the *admin* role isn't granted the permission.
====

You can define the instance and principal names as wildcards using the `"*"` character.
For more information, see xref:configuration:using-wildcards.adoc[Using Wildcards].

The endpoint names can use range characters `"-"` and `"*"` as described
in the xref:clusters:network-configuration.adoc#interfaces[Interfaces] section.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<hazelcast>
    ...
    <security enabled="true">
        <client-permissions>
            <!-- Principals 'admin' and 'root' from endpoint '127.0.0.1' have all permissions. -->
            <all-permissions principal="admin,root">
                <endpoints>
                    <endpoint>127.0.0.1</endpoint>
                </endpoints>
            </all-permissions>

            <!-- Principals named 'dev' from all endpoints have 'create', 'destroy',
            'put', 'read' permissions for map named 'myMap'. -->
            <map-permission name="myMap" principal="dev">
                <actions>
                    <action>create</action>
                    <action>destroy</action>
                    <action>put</action>
                    <action>read</action>
                </actions>
            </map-permission>

            <!-- All principals from endpoints '127.0.0.1' or matching to '10.10.*.*'
            have 'put', 'read', 'remove' permissions for map
            whose name matches to 'com.foo.entity.*'. -->
            <map-permission name="com.foo.entity.*">
                <endpoints>
                    <endpoint>10.10.*.*</endpoint>
                    <endpoint>127.0.0.1</endpoint>
                </endpoints>
                <actions>
                    <action>put</action>
                    <action>read</action>
                    <action>remove</action>
                </actions>
            </map-permission>

            <!-- Principals named 'dev' from endpoints matching either
            '192.168.1.1-100' or '192.168.2.*'
            have 'create', 'add', 'remove' permissions for all queues. -->
            <queue-permission name="*" principal="dev">
                <endpoints>
                    <endpoint>192.168.1.1-100</endpoint>
                    <endpoint>192.168.2.*</endpoint>
                </endpoints>
                <actions>
                    <action>create</action>
                    <action>add</action>
                    <action>remove</action>
                </actions>
            </queue-permission>

           <!-- All principals from all endpoints have transaction permission.-->
           <transaction-permission />
       </client-permissions>
    </security>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  security:
    enabled: true
    client-permissions:
      on-join-operation: RECEIVE
      all:
        principal: admin,root
        endpoints:
          - 127.0.0.1
      map:
        - name: myMap
          principal: dev
          endpoints:
            - 127.0.0.1
          actions:
            - create
            - destroy
            - put
            - read
      map:
        - name: com.foo.entity
          principal: dev
          endpoints:
            - 10.10.*.*
            - 127.0.0.1
          actions:
            - put
            - read
            - remove
      queue:
        - name: "*"
          principal: dev
          endpoints:
            - 192.168.1.1-100
            - 192.168.2.*
          actions:
            - create
            - add
            - remove
      transaction:
----
====

You can also define your own policy by implementing `com.hazelcast.security.IPermissionPolicy`.

[source,java]
----
package com.hazelcast.security;
/**
 * IPermissionPolicy is used to determine any Subject's
 * permissions to perform a security sensitive Hazelcast operation.
 *
 */
public interface IPermissionPolicy {
  void configure( SecurityConfig securityConfig, Properties properties );

  PermissionCollection getPermissions( Subject subject,
                                       Class<? extends Permission> type );

  void destroy();
}
----

Permission policy implementations can access client-permissions that are in the
configuration by using `SecurityConfig.getClientPermissionConfigs()` when
Hazelcast calls the `configure(SecurityConfig securityConfig, Properties properties)` method.

The `IPermissionPolicy.getPermissions(Subject subject, Class<? extends Permission> type)`
method is used to determine a client request that has been granted permission to
perform a security-sensitive operation.

The permission policy should return a `PermissionCollection` containing permissions
of the given type for the given `Subject`. The Hazelcast access controller calls
`PermissionCollection.implies(Permission)` on returning `PermissionCollection` and
decides whether the current `Subject` has permission to access the requested resources.

== Permissions

The following is the list of client permissions that can be configured on the member:

=== All permissions

The `<all-permissions>`` permission grants clients access to all data and features.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<all-permissions principal="principal">
    <endpoints>
        ...
    </endpoints>
</all-permissions>
----
--

YAML::
+
[source,yaml]
----
all:
  principal: principal
  endpoints:
    - ..
----
====

=== Management Permission

The `<management-permission>`` permission defines which
client principals/endpoints are allowed to perform management tasks.
The client specified in the following code example is used by Hazelcast Management Center
when it connects to clusters. To learn more about this client, see xref:{page-latest-supported-mc}@management-center:ROOT:connecting-members.adoc[].

[tabs]
====
XML::
+
--

[source,xml]
----
<management-permission principal="mcadmin">
    <endpoints>
        ...
    </endpoints>
</management-permission>
----
--

YAML::
+
[source,yaml]
----
management:
  principal: mcadmin
  endpoints:
    - ..
----
====

=== Map permission

Actions: all, create, destroy, index, intercept, listen, lock, put, read, remove .

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<map-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</map-permission>
----
--

YAML::
+
[source,yaml]
----
map:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Queue permission

Actions: add, all, create, destroy, listen, read, remove.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<queue-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</queue-permission>
----
--

YAML::
+
[source,yaml]
----
queue:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== MultiMap permission

Actions: all, create, destroy, listen, lock, put, read, remove.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<multimap-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
     </actions>
</multimap-permission>
----
--

YAML::
+
[source,yaml]
----
multimap:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Replicated map permission

Actions: all, create, destroy, index, intercept, listen, lock, put, read, remove.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<replicatedmap-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
     </actions>
</replicatedmap-permission>
----
--

YAML::
+
[source,yaml]
----
replicatedmap:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Topic permission

Actions: create, destroy, listen, publish.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<topic-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</topic-permission>
----
--

YAML::
+
[source,yaml]
----
topic:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Reliable topic permission

Actions: create, destroy, listen, publish.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<reliable-topic-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</reliable-topic-permission>
----
--

YAML::
+
[source,yaml]
----
reliable-topic:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== List permission

Actions: add, all, create, destroy, listen, read, remove.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<list-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</list-permission>
----
--

YAML::
+
[source,yaml]
----
list:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Set permission

Actions: add, all, create, destroy, listen, read, remove.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<set-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</set-permission>
----
--

YAML::
+
[source,yaml]
----
set:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Ringbuffer permission

Actions: add, put, read, create, destroy.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<ringbuffer-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</ringbuffer-permission>
----
--

YAML::
+
[source,yaml]
----
ringbuffer:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Lock permission

Actions: all, create, destroy, lock, read.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<lock-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</lock-permission>
----
--

YAML::
+
[source,yaml]
----
lock:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== AtomicLong permission

Actions: all, create, destroy, modify, read.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<atomic-long-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</atomic-long-permission>
----
--

YAML::
+
[source,yaml]
----
atomic-long:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== AtomicReference permission

Actions: all, create, destroy, modify, read.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<atomic-reference-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</atomic-reference-permission>
----
--

YAML::
+
[source,yaml]
----
atomic-reference:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====


=== CountDownLatch permission

Actions: all, create, destroy, modify, read.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<countdown-latch-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</countdown-latch-permission>
----
--

YAML::
+
[source,yaml]
----
countdown-latch:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== FlakeIdGenerator permission

Actions: all, create, destroy, modify, read.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<flake-id-generator-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</flake-id-generator-permission>
----
--

YAML::
+
[source,yaml]
----
flake-id-generator:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Semaphore permission

Actions: all, acquire, create, destroy, read, release.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<semaphore-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</semaphore-permission>
----
--

YAML::
+
[source,yaml]
----
semaphore:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Executor Service Permission

Actions: all, create, destroy

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<executor-service-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</executor-service-permission>
----
--

YAML::
+
[source,yaml]
----
executor-service:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Durable executor service permission

Actions: all, create, destroy.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<durable-executor-service-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</durable-executor-service-permission>
----
--

YAML::
+
[source,yaml]
----
durable-executor-service:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Scheduled executor service permission

Actions: all, create, destroy, read, modify.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<scheduled-executor-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</scheduled-executor-permission>
----
--

YAML::
+
[source,yaml]
----
scheduled-executor:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Cardinality estimator permission

Actions: all, create, destroy, read, modify.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<cardinality-estimator-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</cardinality-estimator-permission>
----
--

YAML::
+
[source,yaml]
----
cardinality-estimator:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== PN counter permission

Actions: all, create, destroy, read, modify.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<pn-counter-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</pn-counter-permission>
----
--

YAML::
+
[source,yaml]
----
pn-counter:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== Transaction permission

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<transaction-permission principal="principal">
    <endpoints>
        ...
    </endpoints>
</transaction-permission>
----
--

YAML::
+
[source,yaml]
----
transaction:
  principal: principal
  endpoints:
    - ..
----
====

=== Cache permission

Actions: all, create, destroy, listen, put, read, remove.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<cache-permission name="/hz/cache-name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</cache-permission>
----
--

YAML::
+
[source,yaml]
----
cache:
  - name: /hz/cache-name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

NOTE: The name provided in `cache-permission` must be the Hazelcast distributed
object name that corresponds to the `Cache` as described in
the xref:jcache:hazelcast-integration.adoc[JCache - Hazelcast Instance Integration section].

=== Vector Collection Permission (Beta)

Actions: all, create, destroy, put, read, remove, optimize

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<vector-collection-permission name="name" principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</vector-collection-permission>
----
--

YAML::
+
[source,yaml]
----
vector-collection:
  - name: name
    principal: principal
    endpoints:
      - ..
    actions:
      - ..
----
====

=== User Code Deployment Permission

Actions: all, deploy/

include::clusters:partial$ucn-migrate-tip.adoc[]

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<user-code-deployment-permission principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</user-code-deployment-permission>
----
--

YAML::
+
[source,yaml]
----
user-code-deployment:
  principal: principal
  endpoints:
    - ..
  actions:
    - ..
----
====

If you have migrated to {ucn}, use the following permissions:

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<user-code-namespace-permission principal="principal">
    <endpoints>
        ...
    </endpoints>
    <actions>
        ...
    </actions>
</user-code-namespace-permission>
----
--

YAML::
+
[source,yaml]
----
user-code-namespace:
  principal: principal
  endpoints:
    - ..
  actions:
    - ..
----
====

=== Configuration permission

This permission defines which
client principals/endpoints are allowed to
xref:configuration:dynamic-config.adoc[add data structure configurations at runtime].

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<config-permission principal="principal">
    <endpoints>
        <endpoint>...</endpoint>
    </endpoints>
</config-permission>
----
--

YAML::
+
[source,yaml]
----
config:
  principal: principal
  endpoints:
    - ..
----
====

=== Job permission

Actions:

- `submit`: Submit a new job, without uploading resources.
- `cancel`: Cancel a running job.
- `read`: Get or list information about a job (by ID or name) such as job configuration, job status, and
submission time.
+
WARNING: When you query a streaming source with SQL, Hazelcast runs that query as a job. As a result, clients with the `read` permission for jobs can see the SQL query and any parameters.
- `restart`: Suspend and resume a running job.
- `export-snapshot`: Export or read snapshots.
- `add-resources`: Upload resources and classes as well as jobs to members.
+
WARNING: Hazelcast can't check permissions in code that's uploaded with a job, If you enable this permission, clients can xref:pipelines:job-security.adoc[upload custom code] that ignores any configured permissions.
- `all`: Enable all actions.

All actions for job permissions also enable the `read` action. For example, if you enable the `create` action, the `read` action is automatically enabled as well.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<job-permission principal="principal">
    <actions>
        <action>...</action>
    </actions>
</job-permission>
----
--

YAML::
+
[source,yaml]
----
job:
  - principal: "principal"
    actions:
      - ..
----
====


=== Connector permission

You can give permissions to the following xref:integrate:connectors.adoc[connectors]:

- File
- Socket

Actions:

- `read`: Read data from sources.
- `write`: Write data to sinks.
- `all`: Enable all actions.

[tabs] 
==== 
XML:: 
+ 
-- 
.File Connector

```xml
<!-- It is currently only possible to give access to a whole directory, not to a single file. -->
<connector-permission name="file:directory_name">
    <actions>
        <action>...</action>
    </actions>
</connector-permission>
```

.Socket Connector

```xml
<connector-permission name="socket:host:port">
    <actions>
        <action>...</action>
    </actions>
</connector-permission>
```

--

YAML::
+
--
.File Connector

[source,yaml]
----
connector:
  - name: "file:directory_name"
    actions:
      - ..
----

.Socket Connector

[source,yaml]
----
connector:
  - name: "socket:host:port"
    actions:
      - ..
----

--
====

WARNING: To protect external systems from being reached by external connectors (JDBC, Mongo, S3, ...), use other means than Hazelcast client permissions.
Traditionally, this is done by enabling authentication on the external system and/or setting up firewall rules.

=== SQL permission

You can give clients permission to use the following xref:sql:sql-statements.adoc[SQL statements]:

- xref:sql:create-mapping.adoc[`CREATE MAPPING`]
- xref:sql:drop-mapping.adoc[`DROP MAPPING`]
- xref:sql:create-index.adoc[`CREATE INDEX`]
- xref:sql:create-view.adoc[`CREATE VIEW`]
- xref:sql:drop-view.adoc[`DROP VIEW`]
- xref:sql:create-data-connection.adoc[`CREATE DATA CONNECTION`]
- xref:sql:drop-data-connection.adoc[`DROP DATA CONNECTION`]
- xref:sql:show-resources.adoc[`SHOW RESOURCES`]

Actions:

- `create`: Use the `CREATE MAPPING` statement to create new mappings or replace existing ones.
- `destroy`: Use the `DROP MAPPING` statement to delete mappings.
- `create-index`: Use the `CREATE INDEX` statement to create a new index for a map.
- `create-view`: Use the `CREATE VIEW` statement to create new views or replace existing ones.
- `drop-view`: Use the `DROP VIEW` statement to delete an existing view.
- `create-dataconnection`: Use the `CREATE DATA CONNECTION` statement to create new data connections or replace existing ones.
- `drop-dataconnection`: Use the `DROP DATA CONNECTION` statement to delete data connections.
- `view-dataconnection`: Use the `SHOW RESOURCES` statement to view the resources and data types accessible via data connections.
- `all`: Enable all actions.

To apply permissions to certain mappings or data connections, provide their names in the `name` attribute. Or, you can apply permissions to all mappings and data connections using the `*` wildcard.

[tabs] 
==== 
XML:: 
+ 
-- 

.Apply permissions to a mapping
[source,xml]
----
<sql-permission name="mapping_name">
  <actions>
    <action>create</action>
    <action>destroy</action>
  </actions>
</sql-permission>
----

.Apply permissions to all mappings
[source,xml]
----
<sql-permission name="*">
  <actions>
    <action>create</action>
    <action>destroy</action>
  </actions>
</sql-permission>
----

.Apply permissions to a data connection
[source,xml]
----
<sql-permission name="data_connection_name">
  <actions>
    <action>drop-dataconnection</action>
    <action>view-dataconnection</action>
  </actions>
</sql-permission>
----
--

YAML::
+
--
.Apply permissions to a mapping

[source,yaml]
----
sql:
  - name: "mapping_name"
    actions:
      - create
      - destroy
----

.Apply permissions to all mappings
[source,yaml]
----
sql:
  - name: "*"
    actions:
      - create
      - destroy
----

.Apply permissions to a data connection

[source,yaml]
----
sql:
  - name: "data_connection_name"
    actions:
      - drop-dataconnection
      - view-dataconnection
----
--
====

[[handling-permissions-when-a-new-member-joins]]
=== Handling permissions when a new member joins

By default, the set of permissions defined in the leader member of a cluster is
distributed to new members that join, overriding their own permission
configurations, if any. However, you can configure a new member to join but keep its own set of permissions and even send these to the existing members in
the cluster. This can be done dynamically, without needing to restart the
cluster, using either one of the following configuration options:

* the `on-join-operation` configuration attribute
* the `setOnJoinPermissionOperation()` method

You can use these options to choose whether a new member joining to a cluster will
apply the client permissions stored in its own configuration, or use the ones
defined in the cluster. The behaviors that you specify with the configuration
are `RECEIVE`, `SEND` and `NONE`, which are described after the examples below.

The following examples show how to use both approaches:

**Declarative configuration:**

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<hazelcast>
    ...
    <security enabled="true">
        <client-permissions on-join-operation="SEND">
            <!-- ... -->
        </client-permissions>
    </security>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  security:
    enabled: true
    client-permissions:
      on-join-operation: SEND
----
====

**Programmatic configuration:**

[source,java]
----
Config config = new Config();
config.getSecurityConfig()
    .setEnabled(true)
    .setOnJoinPermissionOperation(OnJoinPermissionOperationName.SEND);
----

The behaviors are explained below:

* `RECEIVE`: Applies the permissions from the leader member in the
cluster before joining. This is the default value.
* `SEND`: Doesn't apply the permissions from the leader member before joining.
If security is enabled, then it refreshes or replaces the cluster wide
permissions with the ones in the new member after it joins.
This option is suitable for scenarios where you need to replace the
cluster-wide permissions without restarting the cluster.
* `NONE`: Neither applies pre-join permissions nor sends the local permissions
to the other members. It means that the new member doesn't send its own
permission definitions to the cluster, but keeps them when it joins. However,
after the join, when you update the permissions in the other cluster members,
those updates are also sent to the new member. Therefore, this option
is suitable for scenarios where you need to elevate privileges temporarily
on a single member (preferably a xref:management:cluster-utilities.adoc#enabling-lite-members[lite member]) for a
limited time period. The clients which need to use these temporary permissions
have to access the cluster through this single new member, meaning that you need
to configure the xref:clients:java.adoc#configure-cluster-routing-mode[SINGLE_MEMBER] cluster routing mode for such clients.
+
Note that the `create` and `destroy` permissions won't work when using
the `NONE` option, since the distributed objects need to be created/destroyed on all the members.
+
The following is an example for a scenario where `NONE` is used:
+
[source,java,options="nowrap"]
----
// temporary member, in the below case a lite member
Config config = new Config().setLiteMember(true);
PermissionConfig allPermission = new PermissionConfig(PermissionType.ALL, "*", null);
config.getSecurityConfig()
  .setEnabled(true)
  .setOnJoinPermissionOperation(OnJoinPermissionOperationName.NONE)
  .addClientPermissionConfig(allPermission);
HazelcastInstance hzLite = Hazelcast.newHazelcastInstance(config);

// temporary client connecting only to the lite member
String memberAddr = ...;
ClientConfig clientConfig = new ClientConfig();
clientConfig.getNetworkConfig().setSmartRouting(false)
  .addAddress(memberAddr);
HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);

// do operations with escalated privileges:
client.getMap("protectedConfig").put("master.resolution", "1920");

// shutdown the client and lite member
client.shutdown();
hzLite.shutdown();
----

[[deny-permissions]]
=== Deny permissions

Hazelcast employs additive access control as its default security mechanism.
When a client connects to a security-enabled cluster, it is initially granted
no permissions. As a result, access to protected resources is inherently denied
unless explicit permissions are configured and granted to specific roles.

The additive access control approach has limited expression capabilities and
is not well-suited for configurations involving simple exclusions.
For example, it's challenging to allow access to all maps except
the one named `"private"`.

To address this limitation, Hazelcast introduces the concept of deny permissions
(or deny rules).

Within the permission configuration, there is a `boolean` flag called `deny`
that enables permission subtraction.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<hazelcast>
    ...
    <security enabled="true">
        <client-permissions>
            <!-- Grant access to all maps. -->
            <map-permission name="*">
                <actions>
                    <action>all</action>
                </actions>
            </map-permission>
            <!-- Deny access to the "private" map. -->
            <map-permission name="private" deny="true">
                <actions>
                    <action>all</action>
                </actions>
            </map-permission>
       </client-permissions>
    </security>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  security:
    enabled: true
    client-permissions:
      map:
        - name: *
          actions:
            - all
        - name: private
          deny: true
          actions:
            - all
----
====

[[priority-of-grant-and-deny-permissions]]
=== Priority of grant and deny permissions

By default, when a permission is both granted and denied, the denial takes precedence.
In other words, if conflicting permissions exist, denial prevails.

In certain scenarios, it might be beneficial to reverse this behavior and give higher
priority to permission grants.
Hazelcast supports this by introducing the `boolean` flag `priority-grant`,
which can be set to `true`.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<hazelcast>
    ...
    <security enabled="true">
        <client-permissions  priority-grant="true">
        ...
       </client-permissions>
    </security>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  security:
    enabled: true
    client-permissions:
      priority-grant: false
----
====

[[permission-evaluation-table]]
==== Permission evaluation table

The table below illustrates how permission evaluation changes when `priority-grant` is configured:

[options="header"]
|============================================================================
| Permission Implication       | `priority-grant=false` (default) | `priority-grant=true`
| No Grant or Deny Implication | ❌                           | ✅
| Implication from Grant only  | ✅                          | ✅
| Implication from Deny only   | ❌                           | ❌
| Both Grant and Deny Imply    | ❌                           | ✅
|============================================================================

