= Logging Auditable Events
[[auditlog]]

Hazelcast Enterprise allows observing some important cluster events
using the Auditlog feature. Auditable events have a unique type ID;
they contain a timestamp and importance level.
The events may also contain a message and parameters.
Supported event type identifiers are listed in https://docs.hazelcast.org/docs/{page-component-version}/javadoc/com/hazelcast/auditlog/AuditlogTypeIds.html[`AuditlogTypeIds`^].

You can enable the auditlog feature in the configuration as follows:

**Declarative Configuration:**

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<hazelcast>
    ...
    <auditlog enabled="true" />
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  auditlog:
    enabled: true
----
====

**Programmatic Configuration:**

[source,java]
----
Config config = new Config();
config.getAuditLogConfig().setEnabled(true);
----

The default auditlog implementation uses Hazelcast logging configuration and writes the events
as log entries with the category name `"hazelcast.auditlog"`.

**Sample Log4j2 configuration writing auditable events to a Syslog:**

[source,xml]
----
<Configuration>
    <Appenders>
        <Syslog name="Syslog" format="RFC5424"
            host="syslog.acme.com" port="514" protocol="TCP"
            appName="Hazelcast" newLine="true" messageId="Audit" id="hz" />
    </Appenders>

     <Loggers>
        <Logger name="hazelcast.auditlog" level="debug">
            <AppenderRef ref="Syslog" />
        </Logger>
    </Loggers>
</Configuration>
----

== Auditlog SPI

The auditlog has its own SPI allowing you to provide your implementations.
Relevant classes and interfaces are located
in the https://docs.hazelcast.org/docs/{page-component-version}/javadoc/com/hazelcast/auditlog/package-summary.html[`com.hazelcast.auditlog` package^].

The central point of auditlog SPI is the
https://docs.hazelcast.org/docs/{page-component-version}/javadoc/com/hazelcast/auditlog/AuditlogService.html[`AuditlogService` interface^]
and its `log(...)` methods. Their implementations are responsible for
processing auditable events, e.g., writing them to a database.

`AuditlogService` also creates the
https://docs.hazelcast.org/docs/{page-component-version}/javadoc/com/hazelcast/auditlog/EventBuilder.html[`EventBuilder`^]
instances which are used to build
https://docs.hazelcast.org/docs/{page-component-version}/javadoc/com/hazelcast/auditlog/AuditableEvent.html[`AuditableEvents`^].

Another important piece in the SPI is the
https://docs.hazelcast.org/docs/{page-component-version}/javadoc/com/hazelcast/auditlog/AuditlogServiceFactory.html[`AuditlogServiceFactory` interface^].
The factory class allows the `AuditlogService` initialization based on parameters.