= Native Client Security
:page-enterprise: true

As described in xref:security:authentication-overview.adoc[authentication] and xref::client-authorization.adoc[authorization] sections you can define access control mechanisms for clients.

Java native client which is part of Hazelcast codebase, can be provided with an identity used for authentication to a cluster.
The identity of the connecting client is defined on the client side.
Usually, there are no security realms on the clients, but just identity
defined directly in the security configuration.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<hazelcast-client>
    ...
    <security>
      <username-password username="uid=member1,dc=example,dc=com" password="s3crEt"/>
    </security>
    ...
</hazelcast-client>
----
--

YAML::
+
[source,yaml]
----
hazelcast-client:
  security:
    username-password:
      username: uid=member1,dc=example,dc=com
      password: s3crEt
----
====

On the clients, you can use the same identity types as in security realms:

* `username-password`
* `token`
* `kerberos` (may require an additional security realm definition)
* `credentials-factory`

== Security Realms on the Client Side

Hazelcast offers limited support for security realms in native clients.
The configuration allows specifying JAAS login modules which can be referenced from
the Kerberos identity configuration.

[tabs]
====
XML::
+
--

[source,xml]
----
<security>
    <kerberos>
        <realm>ACME.COM</realm>
        <security-realm>krb5Initiator</security-realm>
    </kerberos>
    <realms>
        <realm name="krb5Initiator">
            <authentication>
                <jaas>
                    <login-module class-name="com.sun.security.auth.module.Krb5LoginModule" usage="REQUIRED">
                        <properties>
                            <property name="useTicketCache">true</property>
                            <property name="doNotPrompt">true</property>
                        </properties>
                    </login-module>
                </jaas>
            </authentication>
        </realm>
    </realms>
</security>
----
--

YAML::
+
[source,yaml]
----
security:
  kerberos:
    realm: ACME.COM
    security-realm: krb5Initiator
    realms:
      name: krb5Initiator
        authentication:
          jaas:
            class-name: com.sun.security.auth.module.Krb5LoginModule
            usage: REQUIRED
            properties:
              useTicketCache: true
              doNotPrompt: true
----
====
