= Security Debugging
[[security-debugging]]

The biggest part of business logic related to security
in Hazelcast is located in the `com.hazelcast.security` Java package.
You can investigate the issues by printing more debug info from this package.

An example Log4J2 configuration is shown below:

[source,xml]
----
<Configuration>
    <Loggers>
        <Logger name="com.hazelcast.security" level="ALL"/>
    </Loggers>
</Configuration>
----

== Java Security Debugging

Java is able to print the debug information about using the security components.
During the security troubleshooting, it's often helpful to print the additional
information by using the following system property:

```
-Djava.security.debug=all
```

See the
https://docs.oracle.com/javase/8/docs/technotes/guides/security/troubleshooting-security.html[Troubleshooting Security^]
Java guide for more information.

== TLS debugging

To assist with the TLS/SSL issues, you can use the following
system property:

```
-Djavax.net.debug=all
```

This property provides a lot of logging output including the TLS/SSL
handshake, that can be used to determine the cause of the problem. See the
http://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/ReadDebug.html[Debugging TSL/SSL Connections^]
guide for more information.