= Security Debugging
[[security-debugging]]
:page-enterprise: true

The biggest part of business logic related to security
in Hazelcast is located in the `com.hazelcast.security` Java package.
You can investigate the issues by printing more debug info from this package.

An example Log4J2 configuration is shown below:

[source,xml]
----
<Configuration>
    <Loggers>
        <Logger name="com.hazelcast.security" level="ALL"/>
    </Loggers>
</Configuration>
----

== Java Security Debugging

Java is able to print the debug information about using the security components.
During the security troubleshooting, it's often helpful to print the additional
information by using the following system property:

```
-Djava.security.debug=all
```

See the
https://docs.oracle.com/en/java/javase/17/security/troubleshooting-security.html[Troubleshooting Security^]
Java guide for more information.

== TLS debugging

To assist with the TLS issues, you can use the following
system property:

```
-Djavax.net.debug=all
```

This property provides a lot of logging output including the TLS
handshake, that can be used to determine the cause of the problem. See the
http://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/ReadDebug.html[Debugging TSL Connections^]
guide for more information.

== Kerberos debugging

Besides the `debug` option which is usually present in `Krb5LoginModule` implementations, there are 
Java system properties which might also help to identify issues by printing more output related to Kerberos authentication:

```
-Dsun.security.krb5.debug=true -Dsun.security.jgss.debug=true -Dcom.ibm.security.krb5.Krb5Debug=all -Dcom.ibm.security.jgss.debug=all
```
