= Simple authentication
[[simple-authentication]]

The simple authentication enables you to define users and their roles **directly** in the
Hazelcast member configuration.

The xref:default-authentication.adoc[default authentication] is based on the member's
identity configuration (when defined) or cluster name (otherwise); it does not
allow defining users and assigning them roles.

And when using the xref:jaas-authentication.adoc[JAAS-based authentication], you need
to provide your login modules themselves or set of enterprise level authentication implementations
(LDAP, Kerberos, etc.) which require additional infrastructure to have them working.

Simple authentication closes the gap between the default authentication and
advanced JAAS-based authentication methods.

An example security configuration with the simple authentication used for client protocol is shown below.
The configuration should be done on the member side.

[tabs] 
==== 
XML:: 
+ 
-- 

[source,xml]
----
<hazelcast>
    ...
    <security enabled="true">
        <realms>
            <realm name="simpleRealm">
                <authentication>
                    <simple>
                        <user username="test" password="a1234">
                            <role>monitor</role>
                            <role>hazelcast</role>
                        </user>
                        <user username="root" password="secret">
                            <role>admin</role>
                        </user>
                    </simple>
                </authentication>
            </realm>
        </realms>
        <client-authentication realm="simpleRealm" />
        <client-permissions>
            <all-permissions principal="admin" />
        </client-permissions>
    </security>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  security:
    enabled: true
    realms:
      - name: simpleRealm
      authentication:
        simple:
          users:
            - username: test
              password: 'a1234'
              roles:
                - monitor
                - hazelcast
    client-authentication:
      realm: simpleRealm
    client-permissions:
      all:
        principal: admin
----
====


