= TLS Authentication
:page-enterprise: true

Hazelcast is able to protect network communication using TLS.
The TLS mutual authentication is also supported. It means not only the
server side identifies itself to a client side (member, client, REST client, etc.),
but also the client side needs to prove its identity by using a TLS (X.509) certificate.

The `tls` authentication type verifies within the Hazelcast authentication
that the incoming connection already authenticated the client's TLS certificate.

This authentication type is able to parse a role name (or names) from the client's certificate
subject DN. The `roleAttribute` property specifies the attribute name (a part of the Subject's DN)
to be used as a role name in Hazelcast.

[tabs]
====
XML::
+
--

[source,xml]
----
<hazelcast>
    <network>
        <ssl enabled="true">
            <properties>
                <property name="mutualAuthentication">REQUIRED</property>
                <property name="keyStore">/opt/hazelcast-keystore.p12</property>
                <property name="keyStorePassword">secret.123</property>
                <property name="trustStore">/opt/hazelcast-truststore.p12</property>
                <property name="trustStorePassword">changeit</property>
            </properties>
        </ssl>
    </network>
    <security enabled="true">
        <realms>
            <realm name="tlsRealm">
                <authentication>
                    <tls roleAttribute="cn" />
                </authentication>
            </realm>
        </realms>
        <client-authentication realm="tlsRealm"/>
    </security>
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  network:
    ssl:
      enabled: true
      properties:
        mutualAuthentication: REQUIRED
        keyStore: /opt/hazelcast-keystore.p12
        keyStorePassword: secret.123
        trustStore: /opt/hazelcast-truststore.p12
        trustStorePassword: changeit
  security:
    enabled: true
    realms:
      - name: tlsRealm
        authentication:
          tls:
            roleAttribute: cn
    client-authentication:
      realm: tlsRealm
----
====

This `tls` authentication  uses `cn` attribute from the subject DN as the role name.
If the subject DN in the certificate is `cn=admin,ou=Devs,o=Hazelcast` for instance,
then the `"admin"` role name is assigned to the client.

[cols="1,1,3"]
.TLS Configuration Options
|===
| Option Name
| Default Value
| Description

| `roleAttribute`
| `cn`
| Name of an attribute in client certificate's distinguished name (DN), where the attribute value is used as a Role name.

|===
