= Distinctive Strengths

* It is open source.
* Hazelcast stores everything in-memory (RAM). It is designed to perform fast reads
and updates.
* Hazelcast is peer-to-peer; there is no single point of failure in a Hazelcast cluster;
each member in the cluster is configured to be functionally the same. They all store equal amounts
of data and do equal amounts of processing. You can embed Hazelcast in your
existing application or use it in client and server mode where your application is a
client to Hazelcast members.
* When the size of your memory and compute requirements increase, new members can
be dynamically joined to the Hazelcast cluster to scale elastically.
* Data is resilient to member failure. Data backups are distributed across the cluster.
This is a big benefit when a member in the cluster crashes as data is not lost.
Hazelcast keeps the backup of each data entry on multiple members. On a member
failure, the data is restored from the backup and the cluster continues to operate without downtime.
* Members are always aware of each other unlike in traditional key-value caching solutions.
* Hazelcast provides out-of-the-box distributed data structures.

Finally, Hazelcast has a vibrant open source community enabling it to be continuously developed.

Hazelcast is a fit when you need:

* analytic applications requiring big data processing by partitioning the data
* to retain frequently accessed data in the grid
* a cache, particularly an open source JCache provider with elastic distributed
scalability
* a primary data store for applications with utmost performance, scalability and
low-latency requirements
* an In-Memory NoSQL Key Value Store
* publish/subscribe communication at highest speed and scalability between applications
* applications that need to scale elastically in distributed and cloud environments
* a highly available distributed cache for applications
* an alternative to Coherence and Terracotta.
