= Before you Install Hazelcast
:description: Hazelcast comes in different formats and distributions to accomodate a variety of use cases and application topologies. Before you install Hazelcast, you should learn about the different options and choose one.

{description}

== Choosing a Distribution

Hazelcast is available in two distributions:

- *Full:* Includes Management Center and all connectors for distributed processing
- *Slim:* Excludes Management Center and connectors

The getting started tutorials use the full distribution to walk you through important features.

If you later decide that you do not need these features, you can use the slim version to save memory. For more information about these distributions, see xref:deploy:installing-upgrading.adoc#installing-using-download-archives[Full and Slim Packages].

== Choosing an Application Topology

You can use Hazelcast in two topologies, depending on where you want the Hazelcast servers (members) to run:

- Client/server mode: Hazelcast members run remotely outside of your application, allowing you to scale them independently and connect to them through any of the supported clients.
- Embedded mode: Hazelcast members run in the same Java process as your application.

For details about these topologies, see xref:ROOT:topologies.adoc[].

To get started with client/server mode, install Hazelcast with <<using-a-package-manager, the CLI>>, <<using-docker, Docker>>, or <<using-the-binary, the binary>>.

To get started with embedded mode, <<use-java, install Hazelcast in your Java project>>.