= Deploy Blue-Green Clusters
:description: This tutorial guides you on how you can use Hazelcast's blue-green deployment feature for your client to operate continuously when its connected cluster is down.

{description} The feature provides a client failover mechanism for rerouting the client connections to a different cluster without requiring a
client network configuration update or client restart. You can use it to manually redirect client traffic in order to perform maintenance or software updates,
as well as automatically redirect client traffic to a different cluster during a disaster recovery scenario.

This tutorial focuses on the disaster recovery scenario, and you will:

. Start an Enterprise cluster (blue)
. Start another Enterprise cluster (green)
. Configure a Java client to have the Blue-Green deployment's failover feature
. Connect this client to the first cluster
. Kill the first cluster and see that the client connects to the second one

NOTE: Blue-Green deployment is currently supported by Hazelcast's Java, Node.js and Go clients.

== Before You Begin

To complete this tutorial, you need the following:

[cols="1a,1a"]
|===
|Prerequisites|Useful resources

|Docker
|
link:https://docs.docker.com/docker-for-mac/install/[Install Docker for Mac]

link:https://docs.docker.com/engine/install/[Install Docker for Linux]

link:https://docs.docker.com/docker-for-windows/install/[Install Docker for Windows]

|Docker image for the full Hazelcast distribution
|xref:get-started-enterprise.adoc[Install Hazelcast Enterprise]

|Docker network with the name `hazelcast-network`
|Use the `docker network create hazelcast-network` command 

|===

== Step 1. Start an Enterprise Cluster (Blue)

In this step, you use the Hazelcast Enterprise Docker image to start a local single-member cluster called `blue`.
This step also installs your Enterprise license key.

Run the following command on the terminal:

[source,shell]
----
docker run \
    --network hazelcast-network \
    --rm \
    -e HZ_CLUSTERNAME=blue \
    -e HZ_LICENSEKEY=<your license key> \
    -p 5701:5701 hazelcast/hazelcast-enterprise:5.0
----

You should see your cluster name in the console along with the IP address of the Docker container running the Hazelcast member.

[source,shell]
----
2021-12-01 18:26:42,369 [ INFO] [main] [c.h.i.c.ClusterService]: [172.18.0.2]:5701 [blue] [5.0] 

Members {size:1, ver:1} [
	Member [172.18.0.2]:5701 - c00213e1-da50-4b5f-a53b-ccfe4a1ebeea this
]

2021-12-01 18:26:42,384 [ INFO] [main] [c.h.c.LifecycleService]: [172.18.0.2]:5701 [blue] [5.0] [172.18.0.2]:5701 is STARTED
----

== Step 2. Start another Enterprise Cluster (Green)

Similar to Step 1 above, start another local single-member cluster called `green`.

[source,shell]
----
docker run \
    --network hazelcast-network \
    --rm \
    -e HZ_CLUSTERNAME=green \
    -e HZ_LICENSEKEY=<your license key> \
    -p 5701:5701 hazelcast/hazelcast-enterprise:5.0
----

See the green cluster is formed:

[source,shell]
----
2021-12-01 18:28:46,299 [ INFO] [main] [c.h.i.c.ClusterService]: [172.18.0.3]:5701 [green] [5.0] 

Members {size:1, ver:1} [
	Member [172.18.0.3]:5701 - 72f5520c-8c27-4501-9199-a8da6b58c0b4 this
]

2021-12-01 18:28:46,321 [ INFO] [main] [c.h.c.LifecycleService]: [172.18.0.3]:5701 [green] [5.0] [172.18.0.3]:5701 is STARTED
----

Now, you have two separate Hazelcast Enterprise clusters running on your local.

== Step 3. Configure the Client

In this step, we are going to configure a client, so that it will initially connect to the `blue` cluster, and when
the `blue` cluster is down, it will automatically connect to the `green` cluster.

For this, we need to create two client configurations for the same client, and pass these to a failover configuration.

. Create the client configuration file for the `blue` cluster, called `client-blue.yaml` (or `client-blue.xml`).
+
[tabs] 
==== 
YAML:: 
+ 
-- 
[source,shell]
----
hazelcast-client:
  cluster-name: blue
  network:
    cluster-members:
      - 172.18.0.2
----
--

XML::
+
[source,shell]
----
<hazelcast-client>
    <cluster-name>blue</cluster-name>
    <network>
        <cluster-members>
            <address>172.18.0.2</address>
        </cluster-members>
    </network>
</hazelcast-client>
----
====
. Create the client configuration for the `green` cluster, called `client-green.yaml` (or `client-green.xml`).
+
[tabs] 
==== 
YAML:: 
+ 
-- 
[source,shell]
----
hazelcast-client:
  cluster-name: green
  network:
    cluster-members:
      - 172.18.0.3
----
--

XML::
+
[source,shell]
----
<hazelcast-client>
    <cluster-name>green</cluster-name>
    <network>
        <cluster-members>
            <address>172.18.0.3</address>
        </cluster-members>
    </network>
</hazelcast-client>
----
====
. Create the client failover configuration by passing the above two client configurations.
Name of this configuration file must be `hazelcast-client-failover.yaml` (or `hazelcast-client-failover.xml`).
+
[tabs] 
==== 
YAML:: 
+ 
-- 
[source,shell]
----
hazelcast-client-failover:
  try-count: 4
  clients:
    - client-blue.yaml
    - client-green.yaml
----
--

XML::
+
[source,shell]
----
<hazelcast-client-failover>
    <try-count>4</try-count>
    <clients>
        <client>client-blue.xml</client>
        <client>client-green.xml</client>
    </clients>
</hazelcast-client-failover>
----
====
+
In this failover configuration file, we are directing the client to connect to the clusters in the given order from top to bottom;
see xref:clients:java#ordering-of-clusters-when-clients-try-to-connect[Ordering of Clusters]. So, when you start the client
(see Step 4 below), it will initially connect to the blue cluster. Here is what may happen:

* When the blue cluster is gone, the client attempts to reconnect to it four times.
* If not successful, it will try to connect to the green cluster, again, four times.
* If these eight attempts are not successful, the client is shutdown.

== Step 4. Connect the Client to Blue Cluster

In this step, we start the client.

[source,java]
----
HazelcastInstance client = HazelcastClient.newHazelcastFailoverClient();
----

Assuming that the blue cluster is alive, you should see a log similar to the following on the blue cluster’s terminal, showing that the client is connected.

[source,shell]
----
2021-12-01 18:11:33,928 [ INFO] [hz.wizardly_taussig.priority-generic-operation.thread-0] [c.h.c.i.p.t.AuthenticationMessageTask]: [172.18.0.2]:5701 [blue] [5.0] Received auth from Connection[id=5, /172.18.0.2:5701->/172.18.0.1:61254, qualifier=null, endpoint=[172.18.0.1]:61254, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: bf2ba9e2-d6f5-4a63-af43-e8d5ed8174b4, client name: hz.client_1, client version: 5.0
----

You can also verify the client is connected on the client side's terminal.

[source,shell]
----
INFO: hz.client_1 [blue] [5.0] Trying to connect to [172.18.0.2]:5701
Dec 01, 2021 8:11:33 PM com.hazelcast.core.LifecycleService
INFO: hz.client_1 [blue] [5.0] HazelcastClient 5.0 (20210922 - dbaeffe) is CLIENT_CONNECTED
----

== Step 5. Kill the Blue Cluster

Now, let's kill the blue cluster and see the client is automatically connected to the green one.

. Shutdown the `blue` cluster on its terminal simply by pressing **Ctrl+C**.
. Verify that the client is connected to the green cluster on the cluster's and client's terminal.
+
[source,shell]
----
2021-12-01 18:11:33,928 [ INFO] [hz.wizardly_taussig.priority-generic-operation.thread-0] [c.h.c.i.p.t.AuthenticationMessageTask]: [172.18.0.3]:5701 [green] [5.0] Received auth from Connection[id=5, /172.18.0.3:5701->/172.18.0.2:62432, qualifier=null, endpoint=[172.18.0.2]:62432, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: bf2ba9e2-d6f5-4a63-af43-e8d5ed8174b4, client name: hz.client_1, client version: 5.0
----
+
INFO: hz.client_1 [green] [5.0] Trying to connect to [172.18.0.3]:5701
Dec 01, 2021 8:16:45 PM com.hazelcast.core.LifecycleService
INFO: hz.client_1 [green] [5.0] HazelcastClient 5.0 (20210922 - dbaeffe) is CLIENT_CONNECTED


NOTE: See xref:clients:java#blue-green-deployment-and-disaster-recovery[Blue-Green Deployment] if you're
interested in learning more about the topics introduced in this tutorial.
