= Hazelcast Editions and Distributions
:description: Hazelcast offers Open Source and Enterprise editions of its member software as well as full and slim distributions.
:page-aliases: before-you-begin.adoc

{description}

== Editions

Hazelcast Open Source edition is free and covered by Apache License, Version 2.0
and https://hazelcast.com/hazelcast-community-license/[Hazelcast Community License]. Permissions are granted
to use, reproduce, and distribute it along with any kind of open
source and closed source applications.

Hazelcast Enterprise is a commercial product that offers additional features to the Open Source edition, including the security suite and blue/green deployments for clients.

=== Features in Hazelcast Enterprise

The Enterprise edition of Hazelcast offers the following Enterprise features.

If a feature requires an Enterprise license, it is labelled [.enterprise]*Enterprise* in the documentation.

* xref:security:overview.adoc[Security suite]
* xref:wan:wan.adoc[]
* xref:cp-subsystem:persistence.adoc[]
* xref:deploy:deploying-in-vmware-tanzu.adoc[Deploying in VMware Tanzu]
* xref:kubernetes:deploying-in-kubernetes.adoc[Deploying in Openshift container platform]
* xref:maintain-cluster:monitoring.adoc#clustered-jmx-and-rest-via-management-center[Clustered REST]
* xref:maintain-cluster:monitoring.adoc#clustered-jmx-and-rest-via-management-center[Clustered JMX]
* xref:maintain-cluster:rolling-upgrades.adoc[Rolling upgrades]
* xref:storage:high-density-memory.adoc[]
* xref:storage:persistence.adoc[]
* xref:clients:java.adoc#blue-green-deployment-and-disaster-recovery[Blue/Green client support]
* xref:pipelines:job-update.adoc[Job updates]

NOTE: All pre-existing Hazelcast licenses such as the Pro/Enterprise/Enterprise HD licenses,
are valid for Hazelcast Platform.

== Full and Slim Distributions
[[full-slim]]

The following installation options offer a full and slim distribution:

- Docker
- ZIP/TAR Binaries
- Java

Other installation options offer only the full distribution.

The full distribution contains all available Hazelcast connectors, libraries, and Management Center.

.What's included in the full distribution
[%collapsible]
====
[source,plain,subs="attributes+"]
----
├── LICENSE
├── NOTICE
├── bin
│   ├── common.sh
│   ├── hz-cli
│   ├── hz-cli.bat
│   ├── hz-cluster-admin
│   ├── hz-cluster-cp-admin
│   ├── hz-healthcheck
│   ├── hz-start
│   ├── hz-start.bat
│   ├── hz-stop
│   └── hz-stop.bat
├── config
│   ├── examples
│   │   ├── hazelcast-client-full-example.xml
│   │   ├── hazelcast-client-full-example.yaml
│   │   ├── hazelcast-client.yaml
│   │   ├── hazelcast-full-example.xml
│   │   ├── hazelcast-full-example.yaml
│   │   ├── hazelcast-security-hardened.yaml
│   │   └── hazelcast.yaml
│   ├── hazelcast-client.xml
│   ├── hazelcast.xml
│   ├── jmx_agent_config.yaml
│   ├── jvm-client.options
│   ├── jvm.options
│   └── log4j2.properties
├── custom-lib
│   ├── hazelcast-3-connector-impl-{full-version}.jar
│   ├── hazelcast-3.12.12.jar
│   └── hazelcast-client-3.12.12.jar
├── lib
│   ├── cache-api-1.1.1.jar
│   ├── hazelcast-3-connector-common-{full-version}.jar
│   ├── hazelcast-3-connector-interface-{full-version}.jar
│   ├── hazelcast-{full-version}.jar
│   ├── hazelcast-download.properties
│   ├── hazelcast-hibernate53-2.1.1.jar
│   ├── hazelcast-jet-avro-{full-version}.jar
│   ├── hazelcast-jet-cdc-debezium-{full-version}.jar
│   ├── hazelcast-jet-cdc-mysql-{full-version}.jar
│   ├── hazelcast-jet-cdc-postgres-{full-version}.jar
│   ├── hazelcast-jet-csv-{full-version}.jar
│   ├── hazelcast-jet-elasticsearch-7-{full-version}.jar
│   ├── hazelcast-jet-files-azure-{full-version}.jar
│   ├── hazelcast-jet-files-gcs-{full-version}.jar
│   ├── hazelcast-jet-files-s3-{full-version}.jar
│   ├── hazelcast-jet-grpc-{full-version}.jar
│   ├── hazelcast-jet-hadoop-all-{full-version}.jar
│   ├── hazelcast-jet-kafka-{full-version}.jar
│   ├── hazelcast-jet-kinesis-{full-version}.jar
│   ├── hazelcast-jet-protobuf-{full-version}.jar
│   ├── hazelcast-jet-python-{full-version}.jar
│   ├── hazelcast-jet-s3-{full-version}.jar
│   ├── hazelcast-sql-{full-version}.jar
│   ├── hazelcast-wm-4.0.jar
│   ├── jansi-2.1.0.jar
│   ├── jline-reader-3.19.0.jar
│   ├── jline-terminal-3.19.0.jar
│   ├── jline-terminal-jansi-3.19.0.jar
│   ├── jmx_prometheus_javaagent-0.14.0.jar
│   ├── log4j-api-2.14.0.jar
│   ├── log4j-core-2.14.0.jar
│   ├── log4j-slf4j-impl-2.14.0.jar
│   ├── picocli-3.9.0.jar
│   └── slf4j-api-1.7.30.jar
└── licenses
    ├── THIRD-PARTY.txt
    ├── apache-v2-license.
    ├── attribution.txt
    └── hazelcast-community-license.txt
├── management-center
│   ├── ThirdPartyNotices.txt
│   ├── bin
│   │   ├── mc-conf.bat
│   │   ├── mc-conf.sh
│   │   ├── mc-start.cmd
│   │   ├── mc-start.sh
│   │   ├── start.bat
│   │   ├── start.sh
│   │   └── user-lib
│   ├── hazelcast-management-center-{full-version}.jar
│   └── license.txt
└── release_notes.txt
----
====

The slim distribution excludes Management Center and connectors. You can use the slim version
to save memory and later include the additional components, as needed.

To get a slim distribution, use one of the available xref:install-hazelcast.adoc[installation options], but add `-slim` to `{full-version}`: `{full-version}-slim`.

.What's included in the slim distribution
[%collapsible]
====
[source,plain,subs="attributes+"]
----
├── LICENSE
├── NOTICE
├── bin
│   ├── common.sh
│   ├── hz-cli
│   ├── hz-cli.bat
│   ├── hz-cluster-admin
│   ├── hz-cluster-cp-admin
│   ├── hz-healthcheck
│   ├── hz-start
│   ├── hz-start.bat
│   ├── hz-stop
│   └── hz-stop.bat
├── config
│   ├── examples
│   │   ├── hazelcast-client-full-example.xml
│   │   ├── hazelcast-client-full-example.yaml
│   │   ├── hazelcast-client.yaml
│   │   ├── hazelcast-full-example.xml
│   │   ├── hazelcast-full-example.yaml
│   │   ├── hazelcast-security-hardened.yaml
│   │   └── hazelcast.yaml
│   ├── hazelcast-client.xml
│   ├── hazelcast.xml
│   ├── jmx_agent_config.yaml
│   ├── jvm-client.options
│   ├── jvm.options
│   └── log4j2.properties
├── lib
│   ├── cache-api-1.1.1.jar
│   ├── hazelcast-{full-version}.jar
│   ├── hazelcast-download.properties
│   ├── hazelcast-hibernate53-2.1.1.jar
│   ├── hazelcast-sql-{full-version}.jar
│   ├── hazelcast-wm-4.0.jar
│   ├── jansi-2.1.0.jar
│   ├── jline-reader-3.19.0.jar
│   ├── jline-terminal-3.19.0.jar
│   ├── jline-terminal-jansi-3.19.0.jar
│   ├── jmx_prometheus_javaagent-0.14.0.jar
│   ├── log4j-api-2.14.0.jar
│   ├── log4j-core-2.14.0.jar
│   ├── log4j-slf4j-impl-2.14.0.jar
│   ├── picocli-3.9.0.jar
│   └── slf4j-api-1.7.30.jar
└── licenses
    ├── THIRD-PARTY.txt
    ├── apache-v2-license.txt
    └── hazelcast-community-license.txt
----
====