= Hazelcast Editions and Distributions
:description: Hazelcast offers Enterprise and Open Source editions of its member software, each available as either a full or slim distribution.
:page-aliases: before-you-begin.adoc

{description}

== Enterprise Edition

Hazelcast Enterprise edition is a commercial product that extends the Open Source offering to provide you with many benefits, including the security suite, blue/green deployments for clients, and a xref:support#customer-support.adoc[Hazelcast Customer Support] subscription. 

TIP: In this documentation, topics related to an Enterprise edition feature include an [.enterprise]*Enterprise* label.

The Enterprise edition offers the following features, which are not available in the Open Source edition:

* xref:security:overview.adoc[Security suite]
* xref:wan:wan.adoc[]
* xref:cp-subsystem:persistence.adoc[]
* xref:kubernetes:deploying-in-kubernetes.adoc[Deploying in Openshift container platform]
* xref:maintain-cluster:monitoring.adoc#clustered-jmx-and-rest-via-management-center[Clustered REST]
* xref:maintain-cluster:monitoring.adoc#clustered-jmx-and-rest-via-management-center[Clustered JMX]
* xref:maintain-cluster:rolling-upgrades.adoc[Rolling upgrades]
* xref:storage:high-density-memory.adoc[]
* xref:storage:persistence.adoc[]
* xref:clients:java.adoc#blue-green-deployment-and-disaster-recovery[Blue/Green client support]
* xref:pipelines:job-update.adoc[Job updates]

NOTE: All pre-existing Hazelcast licenses, such as the Pro/Enterprise/Enterprise HD licenses,
are valid for Hazelcast Platform.

== Open Source Edition

Hazelcast Open Source edition is free and covered by an Apache License, Version 2.0
and a https://hazelcast.com/hazelcast-community-license/[Hazelcast Community License]. 

The permissions granted in these licenses allow you to do the following:

* Use the Open Source edition
* Reproduce the Open Source edition
* Distribute the Open Source edition with any open and/or closed source applications

== Full and Slim Distributions
[[full-slim]]

The following installation options offer a full and slim distribution:

- Docker
- ZIP/TAR Binaries
- Java

Other installation options offer only the full distribution.

You can find more information on installing the Hazelcast editions in the following topics:

* For the Enterprise edition, see the xref:install-enterprise.adoc[] topic
* For the Open Source edition, see the xref:install-hazelcast.adoc[] topic

=== Full Distribution

The full distribution contains all available Hazelcast connectors, libraries, and Management Center.

.What's included in the full distribution
[%collapsible]
====
[source,plain,subs="attributes+"]
----
├── LICENSE
├── NOTICE
├── bin
│   ├── common.sh
│   ├── hz-cli
│   ├── hz-cli.bat
│   ├── hz-cluster-admin
│   ├── hz-cluster-cp-admin
│   ├── hz-healthcheck
│   ├── hz-start
│   ├── hz-start.bat
│   ├── hz-stop
│   └── hz-stop.bat
├── config
│   ├── examples
│   │   ├── hazelcast-client-full-example.xml
│   │   ├── hazelcast-client-full-example.yaml
│   │   ├── hazelcast-client.yaml
│   │   ├── hazelcast-full-example.xml
│   │   ├── hazelcast-full-example.yaml
│   │   ├── hazelcast-security-hardened.yaml
│   │   └── hazelcast.yaml
│   ├── hazelcast-client.xml
│   ├── hazelcast.xml
│   ├── jmx_agent_config.yaml
│   ├── jvm-client.options
│   ├── jvm.options
│   └── log4j2.properties
├── custom-lib
│   ├── hazelcast-3-connector-impl-{full-version}.jar
│   ├── hazelcast-3.12.12.jar
│   └── hazelcast-client-3.12.12.jar
├── lib
│   ├── cache-api-1.1.1.jar
│   ├── hazelcast-3-connector-common-{full-version}.jar
│   ├── hazelcast-3-connector-interface-{full-version}.jar
│   ├── hazelcast-{full-version}.jar
│   ├── hazelcast-download.properties
│   ├── hazelcast-hibernate53-2.1.1.jar
│   ├── hazelcast-jet-avro-{full-version}.jar
│   ├── hazelcast-jet-cdc-debezium-{full-version}.jar
│   ├── hazelcast-jet-cdc-mysql-{full-version}.jar
│   ├── hazelcast-jet-cdc-postgres-{full-version}.jar
│   ├── hazelcast-jet-csv-{full-version}.jar
│   ├── hazelcast-jet-elasticsearch-7-{full-version}.jar
│   ├── hazelcast-jet-files-azure-{full-version}.jar
│   ├── hazelcast-jet-files-gcs-{full-version}.jar
│   ├── hazelcast-jet-files-s3-{full-version}.jar
│   ├── hazelcast-jet-grpc-{full-version}.jar
│   ├── hazelcast-jet-hadoop-all-{full-version}.jar
│   ├── hazelcast-jet-kafka-{full-version}.jar
│   ├── hazelcast-jet-kinesis-{full-version}.jar
│   ├── hazelcast-jet-protobuf-{full-version}.jar
│   ├── hazelcast-jet-python-{full-version}.jar
│   ├── hazelcast-jet-s3-{full-version}.jar
│   ├── hazelcast-sql-{full-version}.jar
│   ├── hazelcast-wm-4.0.jar
│   ├── jansi-2.1.0.jar
│   ├── jline-reader-3.19.0.jar
│   ├── jline-terminal-3.19.0.jar
│   ├── jline-terminal-jansi-3.19.0.jar
│   ├── jmx_prometheus_javaagent-0.14.0.jar
│   ├── log4j-api-2.14.0.jar
│   ├── log4j-core-2.14.0.jar
│   ├── log4j-slf4j-impl-2.14.0.jar
│   ├── picocli-3.9.0.jar
│   └── slf4j-api-1.7.30.jar
└── licenses
    ├── THIRD-PARTY.txt
    ├── apache-v2-license.
    ├── attribution.txt
    └── hazelcast-community-license.txt
├── management-center
│   ├── ThirdPartyNotices.txt
│   ├── bin
│   │   ├── mc-conf.bat
│   │   ├── mc-conf.sh
│   │   ├── mc-start.cmd
│   │   ├── mc-start.sh
│   │   ├── start.bat
│   │   ├── start.sh
│   │   └── user-lib
│   ├── hazelcast-management-center-{full-version}.jar
│   └── license.txt
└── release_notes.txt
----
====

=== Slim Distribution

The slim distribution allows you to save memory by excluding Management Center and connectors. You add the additional components as required.

To install a slim distribution, you can use any of the available installation options by appending `-slim` to the version number in the command; for example, to install the slim distribution of {full-version}, use `{full-version}-slim`.

.What's included in the slim distribution
[%collapsible]
====
[source,plain,subs="attributes+"]
----
├── LICENSE
├── NOTICE
├── bin
│   ├── common.sh
│   ├── hz-cli
│   ├── hz-cli.bat
│   ├── hz-cluster-admin
│   ├── hz-cluster-cp-admin
│   ├── hz-healthcheck
│   ├── hz-start
│   ├── hz-start.bat
│   ├── hz-stop
│   └── hz-stop.bat
├── config
│   ├── examples
│   │   ├── hazelcast-client-full-example.xml
│   │   ├── hazelcast-client-full-example.yaml
│   │   ├── hazelcast-client.yaml
│   │   ├── hazelcast-full-example.xml
│   │   ├── hazelcast-full-example.yaml
│   │   ├── hazelcast-security-hardened.yaml
│   │   └── hazelcast.yaml
│   ├── hazelcast-client.xml
│   ├── hazelcast.xml
│   ├── jmx_agent_config.yaml
│   ├── jvm-client.options
│   ├── jvm.options
│   └── log4j2.properties
├── lib
│   ├── cache-api-1.1.1.jar
│   ├── hazelcast-{full-version}.jar
│   ├── hazelcast-download.properties
│   ├── hazelcast-hibernate53-2.1.1.jar
│   ├── hazelcast-sql-{full-version}.jar
│   ├── hazelcast-wm-4.0.jar
│   ├── jansi-2.1.0.jar
│   ├── jline-reader-3.19.0.jar
│   ├── jline-terminal-3.19.0.jar
│   ├── jline-terminal-jansi-3.19.0.jar
│   ├── jmx_prometheus_javaagent-0.14.0.jar
│   ├── log4j-api-2.14.0.jar
│   ├── log4j-core-2.14.0.jar
│   ├── log4j-slf4j-impl-2.14.0.jar
│   ├── picocli-3.9.0.jar
│   └── slf4j-api-1.7.30.jar
└── licenses
    ├── THIRD-PARTY.txt
    ├── apache-v2-license.txt
    └── hazelcast-community-license.txt
----
====