= Hazelcast Editions and Licenses
:description: Hazelcast has Open Source and Enterprise editions. Hazelcast Enterprise is the licensed commercial offering built on top of the Open Source product.

{description}

== Features in Hazelcast Open Source

The Open Source edition of Hazelcast offers the following features:

* Distributed computation, data structures, and events
* Streaming data processing
* Connectors to read from/write to systems like Apache Kafka, JMS, JDBC and HDMS
* Querying with SQL and predicates
* CP subsystem for distributed coordination use cases
* JCache implementation
* Replication of web sessions (filter, Tomcat, Jetty based)
* Administration and monitoring utilities including Management Center, JMX, metrics and diagnostics

== Features in Hazelcast Enterprise

The Enterprise edition of Hazelcast offers the following features in addition to the
ones listed above:

* High-Density Memory Store (off-heap memory)
* Persistence
* Lossless cluster restarts
* Rolling upgrades
* Job upgrades
* Unlimited members on Hazelcast Management Center (it is restricted to 3 members on the freely available version of Management Center)
* CP Subsystem Persistence
* Security Suite (RBAC, TLS, Mutual Auth, Client Certificates)
* WAN Replication (syncing data between two geo-replicated clusters)
* Blue/Green Deployments

NOTE: All preexisting Hazelcast licenses (former Pro/Enterprise/Enterprise HD licenses)
work with Hazelcast Platform.

== Open Source License

Hazelcast Open Source edition is free and covered by Apache License, Version 2.0
and https://hazelcast.com/hazelcast-community-license/[Hazelcast Community License]. Permissions are granted
to use, reproduce and distribute it along with any kind of open
source and closed source applications.

== Enterprise License

Hazelcast Enterprise edition is a commercial product of Hazelcast, Inc. and distributed under
a commercial license that must be acquired
before using it in any type of released software. Feel free to contact
http://hazelcast.com/contact/[Hazelcast sales department^]
for more information about commercial offers.