= Hazelcast Editions and Distributions
:description: Hazelcast offers {enterprise-product-name} and {open-source-product-name} versions of its software, each available as either a full or slim distribution.
:page-aliases: before-you-begin.adoc

{description}

== {enterprise-product-name}

Hazelcast {enterprise-product-name} is a commercial product that extends the {open-source-product-name} offering to provide you with many benefits, including the security suite, blue/green deployments for clients, and a xref:support#customer-support.adoc[Hazelcast Customer Support] subscription. 

TIP: In this documentation, topics related to an {enterprise-product-name} feature include an [.enterprise]*{enterprise-product-name}* label.

The {enterprise-product-name} offers the following features, which are not available in the {open-source-product-name} :

* xref:security:overview.adoc[Security suite]
* xref:wan:wan.adoc[]
* xref:cp-subsystem:persistence.adoc[]
* xref:kubernetes:deploying-in-kubernetes.adoc[Deploying in Openshift container platform]
* xref:maintain-cluster:monitoring.adoc#management-center[Clustered REST]
* xref:maintain-cluster:monitoring.adoc#management-center[Clustered JMX]
* xref:maintain-cluster:rolling-upgrades.adoc[Rolling upgrades]
* xref:storage:high-density-memory.adoc[]
* xref:storage:persistence.adoc[]
* xref:clients:java.adoc#blue-green-deployment-and-disaster-recovery[Blue/Green client support]
* xref:pipelines:job-update.adoc[Job updates]

NOTE: All pre-existing Hazelcast licenses, such as the Pro/Enterprise/Enterprise HD licenses,
are valid for Hazelcast Platform.

== {open-source-product-name}

Hazelcast {open-source-product-name} is free and covered by an Apache License, Version 2.0
and a https://hazelcast.com/hazelcast-community-license/?utm_source=docs-website[Hazelcast Community License]. 

The permissions granted in these licenses allow you to do the following:

* Use the {open-source-product-name} 
* Reproduce the {open-source-product-name} 
* Distribute the {open-source-product-name} with any open and/or closed source applications

== Full and Slim Distributions
[[full-slim]]

You can find more information on installing the Hazelcast editions in the following topics:

* For the {enterprise-product-name}, see the xref:install-enterprise.adoc[] topic
* For the {open-source-product-name}, see the xref:install-hazelcast.adoc[] topic

=== Full Distribution

The full distribution contains all available Hazelcast connectors, libraries, and Management Center.

.Full distribution content explanation
[%collapsible]
====
- `bin` — utility scripts for application management
- `config` - application configuration files (including reference examples)
- `lib` — application and dependency binaries
- `licenses` — application and dependency licenses
- `management-center` — bundled Management Center distribution
====

=== Slim Distribution

The slim distribution allows you to save memory by excluding Management Center and connectors. You add the additional components as required.

.Slim distribution content explanation
[%collapsible]
====
- `bin` — utility scripts for application management
- `config` - application configuration files (including reference examples)
- `lib` — application and dependency binaries
- `licenses` — application and dependency licenses
====
