= Hazelcast Editions and Distributions
:description: Hazelcast offers Enterprise and Open Source editions of its member software, each available as either a full or slim distribution.
:page-aliases: before-you-begin.adoc

{description}

== Enterprise Edition

Hazelcast Enterprise edition is a commercial product that extends the Open Source offering to provide you with many benefits, including the security suite, blue/green deployments for clients, and a xref:support#customer-support.adoc[Hazelcast Customer Support] subscription. 

TIP: In this documentation, topics related to an Enterprise edition feature include an [.enterprise]*Enterprise* label.

The Enterprise edition offers the following features, which are not available in the Open Source edition:

* xref:security:overview.adoc[Security suite]
* xref:wan:wan.adoc[]
* xref:cp-subsystem:persistence.adoc[]
* xref:kubernetes:deploying-in-kubernetes.adoc[Deploying in Openshift container platform]
* xref:maintain-cluster:monitoring.adoc#clustered-jmx-and-rest-via-management-center[Clustered REST]
* xref:maintain-cluster:monitoring.adoc#clustered-jmx-and-rest-via-management-center[Clustered JMX]
* xref:maintain-cluster:rolling-upgrades.adoc[Rolling upgrades]
* xref:storage:high-density-memory.adoc[]
* xref:storage:persistence.adoc[]
* xref:clients:java.adoc#blue-green-deployment-and-disaster-recovery[Blue/Green client support]
* xref:pipelines:job-update.adoc[Job updates]

NOTE: All pre-existing Hazelcast licenses, such as the Pro/Enterprise/Enterprise HD licenses,
are valid for Hazelcast Platform.

== Open Source Edition

Hazelcast {open-source-product-name} is free and covered by an Apache License, Version 2.0
and a https://hazelcast.com/hazelcast-community-license/?utm_source=docs-website[Hazelcast Community License]. 

The permissions granted in these licenses allow you to do the following:

* Use the Open Source edition
* Reproduce the Open Source edition
* Distribute the Open Source edition with any open and/or closed source applications

== Full and Slim Distributions
[[full-slim]]

The following installation options offer a full and slim distribution:

- Docker
- ZIP/TAR Binaries
- Java

Other installation options offer only the full distribution.

You can find more information on installing the Hazelcast editions in the following topics:

* For the Enterprise edition, see the xref:install-enterprise.adoc[] topic
* For the Open Source edition, see the xref:install-hazelcast.adoc[] topic

=== Full Distribution

The full distribution contains all available Hazelcast connectors, libraries, and Management Center.

.Full distribution content explanation
[%collapsible]
====
- `bin` — utility scripts for application management
- `config` - application configuration files (including reference examples)
- `lib` — application and dependency binaries
- `licenses` — application and dependency licenses
- `management-center` — bundled Management Center distribution
====

=== Slim Distribution

The slim distribution allows you to save memory by excluding Management Center and connectors. You add the additional components as required.

To install a slim distribution, you can use any of the available installation options by appending `-slim` to the version number in the command; for example, to install the slim distribution of {full-version}, use `{full-version}-slim`.

.Slim distribution content explanation
[%collapsible]
====
- `bin` — utility scripts for application management
- `config` - application configuration files (including reference examples)
- `lib` — application and dependency binaries
- `licenses` — application and dependency licenses
====
