= Hazelcast Editions and Licenses
:description: Hazelcast has Open Source and Enterprise editions. Hazelcast Enterprise is the licensed commercial offering built on top of the Open Source product.

{description}

== Features in Hazelcast Open Source

The Open Source edition of Hazelcast offers the following features:

* Distributed computation, data structures, and events
* Streaming data processing
* Connectors to read from/write to systems like Apache Kafka, JMS, JDBC and HDMS
* Querying with SQL and predicates
* CP subsystem for distributed coordination use cases
* JCache implementation
* Replication of web sessions (filter, Tomcat, Jetty based)
* Administration and monitoring utilities including Management Center, JMX, metrics and diagnostics

== Features in Hazelcast Enterprise

The Enterprise edition of Hazelcast offers the following features in addition to the
ones listed above:

* High-Density Memory Store (off-heap memory)
* Persistence
* Lossless cluster restarts
* Rolling upgrades
* Job upgrades
* Unlimited members on Hazelcast Management Center (it is restricted to 3 members on the freely available version of Management Center)
* CP Subsystem Persistence
* Security Suite (RBAC, TLS, Mutual Auth, Client Certificates)
* WAN Replication (syncing data between two geo-replicated clusters)
* Blue/Green Deployments

NOTE: All preexisting Hazelcast licenses (former Pro/Enterprise/Enterprise HD licenses)
work with Hazelcast Platform.

== Open Source License

Hazelcast Open Source edition is free and covered by Apache License, Version 2.0
and https://hazelcast.com/hazelcast-community-license/[Hazelcast Community License]. Permissions are granted
to use, reproduce and distribute it along with any kind of open
source and closed source applications.

== Enterprise License

== Full and Slim Distributions
[[full-slim]]

The following installation options offer a full and slim distribution:

- Docker
- ZIP/TAR Binaries
- Java

Other installation options offer only the full distribution.

You can find more information on installing the Hazelcast editions in the following topics:

* For the {enterprise-product-name}, see the xref:install-enterprise.adoc[] topic
* For the {open-source-product-name}, see the xref:install-hazelcast.adoc[] topic

=== Full Distribution

The full distribution contains all available Hazelcast connectors, libraries, and Management Center.

.Full distribution content explanation
[%collapsible]
====
- `bin` — utility scripts for application management
- `config` - application configuration files (including reference examples)
- `lib` — application and dependency binaries
- `licenses` — application and dependency licenses
- `management-center` — bundled Management Center distribution
====

=== Slim Distribution

The slim distribution allows you to save memory by excluding Management Center and connectors. You add the additional components as required.

To install a slim distribution, you can use any of the available installation options by appending `-slim` to the version number in the command; for example, to install the slim distribution of {full-version}, use `{full-version}-slim`.

.Slim distribution content explanation
[%collapsible]
====
- `bin` — utility scripts for application management
- `config` - application configuration files (including reference examples)
- `lib` — application and dependency binaries
- `licenses` — application and dependency licenses
====
