= Installing Hazelcast Enterprise
:description: To install Hazelcast Enterprise, you can use Docker, the binary, or Java. Then, to unlock the Enterprise features, you need to install your Enterprise license key.
:page-aliases: deploy:using-enterprise-edition.adoc

{description}

TIP: Hazelcast Enterprise is a commercial product that offers additional features to the Open Source edition, including the security suite and blue/green deployments for clients. If you're looking to get started with open source Hazelcast, see xref:install-hazelcast.adoc[].

== Using the Enterprise Docker Image

. link:https://docs.docker.com/get-docker/[Install Docker^].

. Check that Docker is correctly installed.
+
[source,bash]
----
docker version
----

. If you do not see a version number, see the link:https://docs.docker.com/config/daemon/[Docker docs^] for troubleshooting information.

. Pull the Hazelcast Docker image from Docker Hub.
+
[source,bash,subs="attributes+"]
----
docker pull hazelcast/hazelcast-enterprise:{full-version}
----

== Using the Enterprise Binary

Download and extract the binaries.

[tabs] 
==== 
Mac:: 
+ 
--
[source,bash,subs="attributes+"]
----
curl 'https://download.hazelcast.com/enterprise/hazelcast-enterprise-{full-version}.tar.gz' | tar xvzf -
----
--
Linux:: 
+ 
--
[source,bash,subs="attributes+"]
----
wget 'https://download.hazelcast.com/enterprise/hazelcast-enterprise-{full-version}.tar.gz' | tar xvzf -
----
--
Windows:: 
+
--
Download and extract the link:https://download.hazelcast.com/enterprise/hazelcast-enterprise-{full-version}.zip[Hazelcast ZIP file].
--
====

== Using the Enterprise JAR

Hazelcast runs on Java, which means you can add it as a dependency in your Java project.

The Java package includes both a member API and a Java client API. The member API is for xref:ROOT:topologies.adoc[embedded topologies] where you want to deploy and manage a cluster in the same Java Virtual Machine (JVM) as your applications. The Java client is for connecting to an existing member in a client/server topology.

. Download and install a xref:deploy:supported-jvms.adoc[supported JDK].
+
TIP: We recommend installing the link:https://adoptopenjdk.net[AdoptOpenJDK^].

. Add the following to your `pom.xml` file.
+
ifdef::snapshot[]
[source,xml,subs="attributes+"]
----
<repository>
  <id>private-repository</id>
  <name>Hazelcast Private Repository</name>
  <url>https://repository.hazelcast.com/release/</url>
  <releases>
      <enabled>true</enabled>
  </releases>
  <snapshots>
      <enabled>true</enabled>
  </snapshots>
</repository>

<dependencies>
  <dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-enterprise</artifactId>
    <version>{full-version}</version>
  </dependency>
</dependencies>
----
endif::[]
ifndef::snapshot[]
[source,xml,subs="attributes+"]
----
<repository>
  <id>private-repository</id>
  <name>Hazelcast Private Repository</name>
  <url>https://repository.hazelcast.com/release/</url>
  <releases>
      <enabled>true</enabled>
  </releases>
  <snapshots>
      <enabled>false</enabled>
  </snapshots>
</repository>

<dependencies>
  <dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-enterprise</artifactId>
    <version>{full-version}</version>
  </dependency>
</dependencies>
----
endif::[]

== Getting an Enterprise License Key

Hazelcast Enterprise requires a license key. You can get a
30-day trial license from the link:https://hazelcast.com/get-started[Hazelcast website].

[[license-key-format]]License keys have the following format:

```
<Hazelcast edition>#<Maximum members>#<License key>
```

- `<Hazelcast edition>`: Name of the product.
- `<Maximum members>`: Maximum number of members that may use the license at the same time.
- `<License key>`: Machine-readable license key.

The first two strings up to the second hash (#) character are optional. These strings just provide a way for you to know important information about the license key.

For example, both of the following formats are valid:

.Full-form license
```
HazelcastEnterprise#2Nodes#1q2w3e4r5t
```

.Short-form license
```
1q2w3e4r5t
```

NOTE: These licenses are examples and will not work if you install them on members.

== Installing a License Key

To use Hazelcast Enterprise, you need to install a license
key on your members.

NOTE: Hazelcast Enterprise license keys are required only for members.
You do not need to set a license key for Java clients that are connected to members.

[tabs] 
==== 
Binary:: 
+ 
-- 
Add the following to the `hazelcast.xml` file in your `hazelcast-{full-version}/config` directory.

[source,xml]
----
<hazelcast>
    <license-key>Your Enterprise License Key</license-key>
</hazelcast>
----
--

Docker:: 
+ 
-- 
Add your license to the `HZ_LICENSEKEY` environment variable.

[source,bash, subs="attributes+"]
----
docker run -e HZ_LICENSEKEY=<your_license_key> hazelcast/hazelcast-enterprise:{full-version}
----
--

Java::
+
--
Add your license to the `setLicenseKey()` method.

[source,java]
----
Config config = new Config();
config.setLicenseKey( "Your Enterprise License Key" );
----
--
====

== Next Steps

Complete a tutorial for xref:get-started-binary.adoc[binary], xref:get-started-docker.adoc[Docker], or xref:get-started-java.adoc[Java] to learn the fundamentals of Hazelcast, including:

- Starting a cluster
- Writing Data to memory
- Reading data from memory
- Monitoring a cluster with Management Center
- Simulating a member failure

If you need more information about managing your license key, see the following resources:

- xref:deploy:monitoring-license-keys.adoc[]
- xref:deploy:renewing-license-keys.adoc[]
- xref:deploy:updating-license-rest.adoc[]

To explore the features of Hazelcast Enterprise, see the following:

* xref:security:overview.adoc[Security suite]
* xref:wan:wan.adoc[]
* xref:cp-subsystem:persistence.adoc[]
* xref:deploy:deploying-in-vmware-tanzu.adoc[Deploying in VMware Tanzu]
* xref:deploy:deploying-in-kubernetes.adoc[Deploying in Openshift container platform]
* xref:maintain-cluster:monitoring.adoc#clustered-jmx-and-rest-via-management-center[Clustered REST]
* xref:maintain-cluster:monitoring.adoc#clustered-jmx-and-rest-via-management-center[Clustered JMX]
* xref:maintain-cluster:rolling-upgrades.adoc[Rolling upgrades]
* xref:storage:high-density-memory.adoc[]
* xref:storage:persistence.adoc[]
* xref:clients:java.adoc#blue-green-deployment-and-disaster-recovery[Blue/Green client support]
* xref:pipelines:job-update.adoc[Job updates]