= Getting Started with REST API
:description: This tutorial introduces you to enabling, running and using the REST API.

:page-enterprise: true

{description}

== Before You Begin

To complete this tutorial, you need the following:

[cols="1a,1a"]
|===
|Prerequisites|Useful resources

|Docker image for Hazelcast {enterprise-product-name} and an {enterprise-product-name} license
|xref:getting-started:enterprise-overview.adoc[]

|===

== Run REST With Minimum Configuration

== Step 1. Prepare The Configuration File

Create a hazelcast.yaml (or xml) configuration file with the following content and place it in the ~/config directory on your local machine.

[tabs]
====
XML::
+
--
[source,xml]
----
<hazelcast>
    <license-key>your license key</license-key> <1>
    <rest enabled="true">
        <security-realm>restRealm</security-realm>
    </rest>
    <security enabled="true">
        <realms>
            <realm name="restRealm">
                <authentication>
                    <simple>
                        <user username="restuser" password="restpassword">
                            <role>admin</role>
                        </user>
                    </simple>
                </authentication>
                <access-control-service>
                    <factory-class-name>com.hazelcast.internal.rest.access.DefaultAccessControlServiceFactory</factory-class-name>
                </access-control-service>
            </realm>
        </realms>
    </security>
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  license-key: <your license key> <1>
  rest:
    enabled: true
    security-realm: restRealm
  security:
    enabled: true
    realms:
      - name: restRealm
        authentication:
          simple:
            users:
              - username: 'restuser'
                password: 'restpassword'
                roles:
                  - admin
        access-control-service:
          factory-class-name: com.hazelcast.internal.rest.access.DefaultAccessControlServiceFactory
----
====
<1> Replace the `<your license key>` placeholder with your Hazelcast {enterprise-product-name} license key.

== Step 2. Start Hazelcast {enterprise-product-name} Server

To start the Hazelcast {enterprise-product-name} server, run the following command:

If you have XML config file:
[source,shell,subs="attributes+"]
----
docker run \
    -p 5701:5701 \
    -e JAVA_OPTS="-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.xml" -v ~/config:/opt/hazelcast/config_ext hazelcast/hazelcast-enterprise:{full-version}
----

If you have YAML config file:
[source,shell,subs="attributes+"]
----
docker run \
    -p 5701:5701 \
    -e JAVA_OPTS="-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml" -v ~/config:/opt/hazelcast/config_ext hazelcast/hazelcast-enterprise:{full-version}
----

This command starts the member and configures it, using your configuration file.
Here, `~/config` is the path to the directory in which you saved the configuration file.
If you saved the configuration file somewhere else, you should replace this path.

You should see a message in the console indicating that the REST service is enabled, similar to the following:

[source,shell,subs="attributes+"]
----
com.hazelcast.internal.rest.init.RestServiceImpl
INFO: [192.168.0.24]:5701 [dev] [5.5.0-SNAPSHOT] Hazelcast REST Service is enabled on port: 8443 with security realm: restRealm and access control service: com.hazelcast.internal.rest.access.DefaultAccessControlService
----

== Step 3. Access the REST API and Swagger UI

The REST API is running on port 8443.
You can access the Swagger UI at: http://localhost:8443/swagger-ui/index.html

== Step 4. Obtain a Token to Access All Endpoints
To obtain a token, send a POST request to the endpoint at /hazelcast/rest/api/v1/token.

*Using Swagger UI:*

- Open the Swagger UI at http://localhost:8443/swagger-ui/index.html.
- Navigate to the token endpoint under the *JWT Token Controller* section.
- Click the *Try it out* button.
- Set the request body as follows:

[source,json]
----
{
  "username": "restuser",
  "password": "restpassword"
}
----

- Click the *Execute* button.

*Using cURL:*

- Run the following command in your terminal.

[source,shell]
----
curl -X 'POST' \
  'http://localhost:8443/hazelcast/rest/api/v1/token' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "restuser",
  "password": "restpassword"
}'
----

== Step 5. Use the Token For Authorization

Add the token as an Authorization header in all requests.

*Using Swagger UI:* Click the *Authorize* button and enter the token in the provided field.

*Using cURL:* Add the token to your requests as follows, replacing <add token here> placeholder with your actual token.
[source,shell]
----
-H 'Authorization: Bearer <add token here>'
----

Example request with cURL:

[source,shell]
----
curl -X 'GET' \
'http://localhost:8443/hazelcast/rest/api/v1/cluster' \
-H 'Authorization: Bearer <add token here>'
----

== Next Steps

If you're interested in learning more about the topics introduced in this tutorial, see: 

* xref:maintain-cluster:enterprise-rest-api.adoc[Enterprise REST API].
