= Getting Started with REST API
:description: This tutorial introduces you to enabling, running and using the REST API.

:page-enterprise: true

{description}

== Before You Begin

To complete this tutorial, you need the following:

[cols="1a,1a"]
|===
|Prerequisites|Useful resources

|Install Hazelcast {enterprise-product-name}
|xref:getting-started:install-enterprise.adoc[]

|If you are using Hazelcast's slim distribution, you must add `hazelcast-enterprise-rest-{full-version}.jar` to your member's classpath to use the REST API. If you are working with the full distribution, this additional step is not needed.
|xref:getting-started:editions.adoc#slim-distribution[Slim Distribution]

|If you installed Hazelcast with Java using Maven, add the following dependency to your pom.xml file.
[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-enterprise-rest</artifactId>
    <version>{full-version}</version>
</dependency>
----
|xref:getting-started:install-enterprise.adoc#using-maven[Using Maven]

|===

== Run REST With Minimum Configuration

== Step 1. Prepare The Configuration File

The following presents the content of the file:

[tabs]
====
XML::
+
--
[source,xml]
----
<hazelcast>
    <rest enabled="true">
        <security-realm>restRealm</security-realm>
    </rest>
    <security enabled="true">
        <realms>
            <realm name="restRealm">
                <authentication>
                    <simple>
                        <user username="restuser" password="restsecret">
                            <role>admin</role>
                        </user>
                    </simple>
                </authentication>
                <access-control-service>
                    <factory-class-name>com.hazelcast.internal.rest.access.DefaultAccessControlServiceFactory</factory-class-name>
                </access-control-service>
            </realm>
        </realms>
    </security>
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  rest:
    enabled: true
    security-realm: restRealm
  security:
    enabled: true
    realms:
      - name: restRealm
        authentication:
          simple:
            users:
              - username: 'restuser'
                password: 'restpassword'
                roles:
                  - admin
        access-control-service:
          factory-class-name: com.hazelcast.internal.rest.access.DefaultAccessControlServiceFactory
----

Java::
+
[source,java]
----
Config config = new Config()
	.setRestConfig(new RestConfig()
		.setEnabled(true)
		.setSecurityRealm("restRealm")
	)
	.setSecurityConfig(new SecurityConfig()
		.setEnabled(true)
		.addRealmConfig("restRealm", new RealmConfig()
			.setSimpleAuthenticationConfig(
				new SimpleAuthenticationConfig()
					.addUser("restuser", "restpassword", "admin")
			)
			.setAccessControlServiceConfig(
				new AccessControlServiceConfig()
					.setFactoryClassName(DefaultAccessControlServiceFactory.class.getName())
			)
		)
	);
----
====

== Step 2. Start Hazelcast {enterprise-product-name} Server

To start the Hazelcast {enterprise-product-name} server, follow these steps:

*Using Hazelcast Distribution*

- Navigate to the unzipped folder `hazelcast-enterprise-5.5.0-SNAPSHOT`.
- Start the Hazelcast server with the following command:

[source,shell]
----
HAZELCAST_CONFIG=path/to/config/file/your-config-file HAZELCAST_LICENSE_KEY=<PUT YOUR LICENSE KEY> ./bin/hz start
----

NOTE: Make sure to replace the `<PUT YOUR LICENSE KEY>` placeholder with your Hazelcast {enterprise-product-name} license key and path/to/config/file/your-config-file with the actual path to your configuration file.

You should see a message in the console indicating that the REST service is enabled, similar to the following:

[source,shell,subs="attributes+"]
----
com.hazelcast.internal.rest.init.RestServiceImpl
INFO: [192.168.0.24]:5701 [dev] [5.5.0-SNAPSHOT] Hazelcast REST Service is enabled on port: 8443 with security realm: restRealm and access control service: com.hazelcast.internal.rest.access.DefaultAccessControlService
----

== Step 3. Access the REST API and Swagger UI

The REST API is running on port 8443.
You can access the Swagger UI at: http://localhost:8443/swagger-ui/index.html

== Step 4. Obtain a Token to Access All Endpoints
To obtain a token, send a POST request to the endpoint at /hazelcast/rest/api/v1/token.

*Using Swagger UI:*

- Open Swagger UI.
- Navigate to the token endpoint under the *JWT Token Controller* section.
- Set the request body as follows:
```
{
  "username": "restuser",
  "password": "restsecret"
}
```
- Click the *Execute* button.

*Using cURL:*

- Run the following command in your terminal.

[source,shell]
----
curl -X 'POST' \
  'http://localhost:8443/hazelcast/rest/api/v1/token' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "restuser",
  "password": "restpassword"
}'
----

== Step 5. Use the Token For Authorization

Add the token as an Authorization header in all requests.

*Using Swagger UI:* Click the *Authorize* button and enter the token in the provided field.

*Using cURL:* Add the token as follows, replacing <add token here> placeholder with your actual token.

[source,shell]
----
curl -X 'GET' \
'http://localhost:8443/hazelcast/rest/api/v1/cluster' \
-H 'Authorization: Bearer <add token here>'
----

== Next Steps

If you're interested in learning more about the topics introduced in this tutorial, see: 

* xref:maintain-cluster:enterprise-rest-api.adoc[Enterprise REST API].
