= Get Started with Hazelcast Enterprise
:description: This guide gets you started with Hazelcast Enterprise by explaining installation options, getting a license key, and managing a license key.
:page-aliases: deploy:using-enterprise-edition.adoc

{description}

TIP: Hazelcast Enterprise is a commercial product that offers additional features to the open source distribution, including the security suite and blue/green deployments for clients. If you're looking to get started with open source Hazelcast, see xref:install-hazelcast.adoc[].

== Installing Hazelcast Enterprise

Hazelcast Enterprise is available in binary ZIP/TAR files, a Docker image, or a JAR file.

=== Using the Enterprise Docker Image

. link:https://docs.docker.com/get-docker/[Install Docker^].

. Check that Docker is correctly installed.
+
[source,bash]
----
docker version
----

. If you do not see a version number, see the link:https://docs.docker.com/config/daemon/[Docker docs^] for troubleshooting information.

. Pull the Hazelcast Docker image from Docker Hub.
+
[source,bash,subs="attributes+"]
----
docker pull hazelcast/hazelcast-enterprise:{full-version}
----

=== Using the Enterprise Binary

Download and extract the binaries.

[tabs] 
==== 
Mac:: 
+ 
--
[source,bash,subs="attributes+"]
----
curl 'https://download.hazelcast.com/enterprise/hazelcast-enterprise-{full-version}.tar.gz' | tar xvzf -
----
--
Linux:: 
+ 
--
[source,bash,subs="attributes+"]
----
wget 'https://download.hazelcast.com/enterprise/hazelcast-enterprise-{full-version}.tar.gz' | tar xvzf -
----
--
Windows:: 
+
--
Download and extract the link:https://download.hazelcast.com/enterprise/hazelcast-enterprise-{full-version}.zip[Hazelcast ZIP file].
--
====

=== Using the Enterprise JAR

Hazelcast runs on Java, which means you can add it as a dependency in your Java project.

The Java package includes both a member API and a Java client API. The member API is for xref:ROOT:topologies.adoc[embedded topologies] where you want to deploy and manage a cluster in the same Java Virtual Machine (JVM) as your applications. The Java client is for connecting to an existing member in a client/server topology.

. Download and install a xref:deploy:supported-jvms.adoc[supported JDK].
+
TIP: We recommend installing the link:https://adoptopenjdk.net[AdoptOpenJDK^].

. Add the following to your `pom.xml` file.
+
[source,xml,subs="attributes+"]
----
<repository>
  <id>private-repository</id>
  <name>Hazelcast Private Repository</name>
  <url>https://repository.hazelcast.com/release/</url>
  <releases>
      <enabled>true</enabled>
  </releases>
  <snapshots>
      <enabled>false</enabled>
  </snapshots>
</repository>

<dependencies>
  <dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-enterprise</artifactId>
    <version>{full-version}</version>
  </dependency>
</dependencies>
----

== Getting an Enterprise License Key

Hazelcast Enterprise requires a license key. You can get a
30-day trial license from the link:https://hazelcast.com/get-started[Hazelcast website].

[[license-key-format]]License keys have the following format:

```
<Hazelcast edition>#<Maximum members>#<License key>
```

- `<Hazelcast edition>`: Name of the product.
- `<Maximum members>`: Maximum number of members that may use the license at the same time.
- `<License key>`: Machine-readable license key.

The first two strings up to the second hash (#) character are optional. These strings just provide a way for you to know important information about the license key.

For example, both of the following license keys are valid:

.Full-form license
```
HazelcastEnterprise#2Nodes#1q2w3e4r5t
```

.Short-form license
```
1q2w3e4r5t
```

== Configuring Members with a License Key

To use Hazelcast Enterprise, you need to set your provided license
key using one of the configuration methods shown below.

NOTE: Hazelcast Enterprise license keys are required only for members.
You do not need to set a license key for Java clients that are connected to members.

[tabs] 
==== 
Hazelcast XML:: 
+ 
-- 
Add the following to the `hazelcast.xml` file in your `hazelcast-{full-version}/config` directory.

[source,xml]
----
<hazelcast>
    <license-key>Your Enterprise License Key</license-key>
</hazelcast>
----
--

Docker XML:: 
+ 
-- 
Add the following to the `hazelcast-docker.xml` file in your `hazelcast-{full-version}/config` directory.

[source,xml]
----
<hazelcast>
    <license-key>Your Enterprise License Key</license-key>
</hazelcast>
----
--

YAML::
+
--

[source,yaml]
----
hazelcast:
  license-key: Your Enterprise License Key
----
--
Java::
+
--
[source,java]
----
Config config = new Config();
config.setLicenseKey( "Your Enterprise License Key" );
----
--
Spring XML::
+
--
[source,xml]
----
<hz:config>
    <hz:license-key>Your Enterprise License Key</hz:license-key>
</hz:config>
----
--

JVM System Property::
+
--
Add the following to the command where you start a member.

[source,shell]
----
-Dhazelcast.enterprise.license.key=Your Enterprise License Key
----
--
====

== Upgrading or Renewing a License Key

License keys are often valid only for a certain period of time. To upgrade or renew a license key, you can do one of the following:

- Email mailto:sales@hazelcast.com[Sales].

- Email mailto:support@hazelcast.com[Support].

- Call your sales representative.

To install the new license, replace the license key on each member host and restart each member one at a time. If you want to temporarily add a new license key to a running cluster, you can use the <<rest-update-license, REST API>>.

NOTE: If your license expires in a running cluster or Management Center,
do not restart any of the cluster members or the Management Center JVM.
Reach out to Hazelcast Support to resolve any issues with an expired license.

== Keeping Track of License Keys

It's important to keep track of when your license key is due to expire. If you have an expired license, Hazelcast will not start. If you have an expired license or if your current license is nearing expiry, 
Hazelcast issues the following warning about approaching license expiry in the member logs and xref:{page-latest-supported-mc}@management-center:managing-licenses.adoc[Management Center]:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ WARNING @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
HAZELCAST LICENSE WILL EXPIRE IN 29 DAYS.
Your Hazelcast cluster will stop working after this time.

Your license holder is customer@example-company.com, you should have them contact
our license renewal department, urgently on sales@hazelcast.com
or call us on +1 (650) 521-5453

Please quote license id CUSTOM_TEST_KEY
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

This frequency of these warnings depends on how long if left until the license expires:

.Frequency of warnings about license expiration
[cols="1a,1a"]
|===
|Time until expiry|Warning frequency

|Two months
|Daily

|One month
|Hourly

|One week
|Every 30 minutes

|===

You can get the details of your Enterprise license using the JMX API
or the REST API.

=== JMX API

The MBean `HazelcastInstance.LicenseInfo` holds all the relative license
details and can be accessed through Hazelcast's JMX port (if enabled). The
following parameters represent these details:

* `maxNodeCountAllowed`: Maximum members allowed to form a cluster under
the current license.
* `expiryDate`: Expiration date of the current license.
* `typeCode`: Type code of the current license.
* `type`: Type of the current license.
* `ownerEmail`: Email of the current license's owner.
* `companyName`: Company name on the current license.

Following is the list of license ``type``s and ``typeCode``s:

```
MANAGEMENT_CENTER(1, "Management Center"),
ENTERPRISE(0, "Enterprise"),
ENTERPRISE_SECURITY_ONLY(2, "Enterprise only with security"),
ENTERPRISE_HD(3, "Enterprise HD"),
CUSTOM(4, "Custom");
```

=== REST

You can access the license details by issuing a `GET` request through the
REST API (if enabled; see the xref:clients:rest.adoc#using-the-rest-endpoint-groups[REST Endpoint Groups section])
on the `/license` resource, as shown below.

```
curl -v http://localhost:5701/hazelcast/rest/license
```

Its output is similar to the following:

```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5701 (#0)
> GET /hazelcast/rest/license HTTP/1.1
> Host: localhost:5701
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 165
<
{"licenseInfo":{"expiryDate":4090168799999,"maxNodeCount":99,"type":3,"companyName":null,"ownerEmail":null,"keyHash":"OsLh4O6vqDuKEq8lOANQuuAaRnmDfJfRPrFSEhA7T3Y="}}
```

[[rest-update-license]]To update the license of a running cluster, you can issue a `POST`
request through the REST API (if enabled; see the xref:clients:rest.adoc#using-the-rest-endpoint-groups[REST Endpoint Groups section]) on the `/license` as shown below:

```
curl --data "${CLUSTERNAME}&${PASSWORD}&${LICENSE}" http://localhost:5001/hazelcast/rest/license
```

NOTE: The request parameters must be properly URL-encoded as described in the xref:clients:rest.adoc[REST Client section].

The above command updates the license on all running Hazelcast members of the cluster.
If successful, the response looks as follows:

```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5001 (#0)
> POST /hazelcast/rest/license HTTP/1.1
> Host: 127.0.0.1:5001
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 164
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 164 out of 164 bytes
< HTTP/1.1 200 OK
< Content-Type: application/javascript
< Content-Length: 364
<
* Connection #0 to host 127.0.0.1 left intact
{"status":"success","licenseInfo":{"expiryDate":1560380399161,"maxNodeCount":10,
"type":-1,"companyName":"ExampleCompany","ownerEmail":"info@example.com",
"keyHash":"ml/u6waTNQ+T4EWxnDRykJpwBmaV9uj+skZzv0SzDhs="},
"message":"License updated at run time - please make sure to update the license
in the persistent configuration to avoid losing the changes on restart."}
```

As the message in the above example indicates, the license is updated only at runtime.
The persistent configuration of each member needs to be updated manually to ensure that
the license change is not lost on restart. The same message is logged as a warning in
each member's log.

It is only possible to update to a license that expires at the same time or after
the current license. The new license allows the same list of features (within which
there may be some compatible feature replacements) and may allow different number
of members provided that it is at least as large as the allowed number in the old license. 

If, for any reason, updating the license fails on some members (member does not respond,
license is not compatible, etc.), the whole operation fails, leaving the cluster in
a potentially inconsistent state (some members have been switched to the new license
while some have not). It is up to you to resolve this situation manually.

== Next Steps

Try a getting started tutorial for xref:get-started-binary.adoc[binary], xref:get-started-docker.adoc[Docker], or xref:get-started-java.adoc[Java].

Explore the features of Hazelcast Enterprise:

* xref:security:overview.adoc[Security suite]
* xref:wan:wan.adoc[]
* xref:cp-subsystem:persistence.adoc[]
* xref:deploy:deploying-in-vmware-tanzu.adoc[Deploying in VMware Tanzu]
* xref:deploy:deploying-in-kubernetes.adoc[Deploying in Openshift container platform]
* xref:maintain-cluster:monitoring.adoc#clustered-jmx-and-rest-via-management-center[Clustered REST]
* xref:maintain-cluster:monitoring.adoc#clustered-jmx-and-rest-via-management-center[Clustered JMX]
* xref:maintain-cluster:rolling-upgrades.adoc[Rolling upgrades]
* https://jet-start.sh/docs/enterprise/lossless-restart[Lossless cluster restart]
* xref:storage:high-density-memory.adoc[]
* xref:storage:persistence.adoc[]
* xref:clients:java.adoc#blue-green-deployment-and-disaster-recovery[Blue/Green client support]
* xref:pipelines:job-update.adoc[Job updates]