= Getting Started with REST API Using Docker
:description: This tutorial introduces you to enabling, running and using the REST API.

:page-enterprise: true

{description}

== Before You Begin

To complete this tutorial, you need the following:

[cols="1a,1a"]
|===
|Prerequisites|Useful resources

|Docker image for Hazelcast {enterprise-product-name} full distribution and an {enterprise-product-name} license
|xref:getting-started:enterprise-overview.adoc[]

|===

== Run REST With Minimum Configuration

== Step 1. Prepare The Configuration File

Create a hazelcast.yaml (or xml) configuration file with the following content and place it in the ~/config directory on your local machine.

[tabs]
====
XML::
+
--
[source,xml]
----
<hazelcast>
    <license-key>your license key</license-key> <1>
    <rest enabled="true">
        <security-realm>restRealm</security-realm>
    </rest>
    <security enabled="true">
        <realms>
            <realm name="restRealm">
                <authentication>
                    <simple>
                        <user username="restuser" password="restpassword">
                            <role>admin</role>
                        </user>
                    </simple>
                </authentication>
                <access-control-service>
                    <factory-class-name>com.hazelcast.internal.rest.access.DefaultAccessControlServiceFactory</factory-class-name>
                </access-control-service>
            </realm>
        </realms>
    </security>
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  license-key: <your license key> <1>
  rest:
    enabled: true
    security-realm: restRealm
  security:
    enabled: true
    realms:
      - name: restRealm
        authentication:
          simple:
            users:
              - username: 'restuser'
                password: 'restpassword'
                roles:
                  - admin
        access-control-service:
          factory-class-name: com.hazelcast.internal.rest.access.DefaultAccessControlServiceFactory
----
====
<1> Replace the `<your license key>` placeholder with your Hazelcast {enterprise-product-name} license key.

== Step 2. Start Hazelcast {enterprise-product-name} Server

To start the Hazelcast {enterprise-product-name} server, run the following command:

[tabs]
====
Using XML Config::
+
--
[source,shell,subs="attributes+"]
----
docker run \
    -p 5701:5701 -p 8443:8443\
    -e JAVA_OPTS="-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.xml" -v ~/config:/opt/hazelcast/config_ext hazelcast/hazelcast-enterprise:{full-version}
----
--

Using YAML Config::
+
[source,shell,subs="attributes+"]
----
docker run \
    -p 5701:5701 -p 8443:8443\
    -e JAVA_OPTS="-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml" -v ~/config:/opt/hazelcast/config_ext hazelcast/hazelcast-enterprise:{full-version}
----
====

This command starts the member and configures it, using your configuration file.
Here, `~/config` is the path to the directory in which you saved the configuration file.

You should see a message in the console indicating that the REST service is enabled, similar to the following:

[source,shell,subs="attributes+"]
----
com.hazelcast.internal.rest.init.RestServiceImpl
INFO: [192.168.0.24]:5701 [dev] [5.5.0-SNAPSHOT] Hazelcast REST Service is enabled on port: 8443 with security realm: restRealm and access control service: com.hazelcast.internal.rest.access.DefaultAccessControlService
----

== Step 3. Access the REST API and Swagger UI

The REST API is running on port 8443.
You can access the https://swagger.io/tools/swagger-ui/[Swagger UI] at: http://localhost:8443/swagger-ui/index.html. This UI lets you see detailed documentation of every possible Hazelcast REST API, and try those APIs in the cluster.

== Step 4. Obtain a Token to Access All Endpoints
To obtain a token, send a POST request to the endpoint at /hazelcast/rest/api/v1/token.

[tabs]
=====
Using Swagger UI::
+
- Open the Swagger UI at http://localhost:8443/swagger-ui/index.html.
- Navigate to the token endpoint under the *JWT Token Controller* section.
- Click the `Try it out` button.
- Set the request body as follows:
+
[source,json]
----
{
  "username": "restuser",
  "password": "restpassword"
}
----
+
- Click the `Execute` button.

Using cURL::
- Run the following command in your terminal.
+
[source,shell]
----
curl -X 'POST' \
  'http://localhost:8443/hazelcast/rest/api/v1/token' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "restuser",
  "password": "restpassword"
}'
----
=====

== Step 5. Execute a Hazelcast REST Call

You need to add the token as Authorization header in all requests, otherwise you will get access denied response.

[tabs]
====
Using Swagger UI::
+
Click the `Authorize` button and enter the token in the provided field. After successful authorization, any subsequent requests made using the Swagger UI will add the token into the proper request header automatically.
+
*Example request with Swagger UI:*
+
- Navigate to the `/hazelcast/rest/api/v1/cluster` endpoint under the *Cluster Controller* section.
- Click the `Try it out` button.
- Click the `Execute` button.

Using cURL::
+
When you want to access a  Hazelcast REST endpoint, then you need to add the token to your requests as follows, replacing <add token here> placeholder with your actual token.
+
[source,shell]
----
-H 'Authorization: Bearer <add token here>'
----
+
*Example request with cURL:*
+
[source,shell]
----
curl -X 'GET' \
'http://localhost:8443/hazelcast/rest/api/v1/cluster' \
-H 'Authorization: Bearer <add token here>'
----
====

== Next Steps

If you're interested in learning more about the topics introduced in this tutorial, see: 

* xref:maintain-cluster:enterprise-rest-api.adoc[Enterprise REST API].
