= Install Hazelcast
:description: You can install Hazelcast in many ways, including from a package manager, a binary, a Docker image, or embedding it in your Java projects.
:page-box-number: 1

{description}

++++
<div id="userMap">
<div class="content"><a href="install-hazelcast.html"><div class="box box1">Install Hazelcast</div></a></div>
<div class="arrow">↓</div>
<div class="content"><a href="get-started-binary.html"><div class="box box2">Start a Local Cluster</div></a></div>
++++

== Choosing a Distribution

Hazelcast is available in two distributions:

- *Full:* Includes Management Center and all connectors for distributed processing
- *Slim:* Excludes Management Center and connectors

These getting started tutorials use the full distribution to walk you through important features.

If you later decide that you do not need these features, you can use the slim version to save memory. For more information on these distributions, see xref:deploy:installing-upgrading.adoc#installing-using-download-archives[ZIP/TAR Packages].

== Choosing an Application Topology

You can use Hazelcast in two topologies, depending on where you want the Hazelcast servers (members) to run:

- Client/server mode: Hazelcast members run remotely outside of your application, allowing you to scale them independently and connect to them through any of the supported clients.
- Embedded mode: Hazelcast members run in the same Java process as your application.

For details about these topologies, see xref:ROOT:topologies.adoc[].

To get started with client/server mode, install Hazelcast with a <<using-a-package-manager, package manager>>, <<using-docker, Docker>>, or <<using-the-binary, from binary>>.

To get started with embedded mode, <<use-java, install Hazelcast in your Java project>>.

== Using a Package Manager

. To install the Hazelcast CLI, use one of the following package managers depending on your operating system:
+
[tabs] 
==== 
Mac:: 
+ 
--

To install the CLI on macOS, use the Homebrew package manager.

[source,bash]
----
brew tap hazelcast/hz
brew install hazelcast
----
--

Linux::
+
--

To install the CLI on Linux, you can use either of these package managers, depending on your Linux distribution:

.Debian
[source,shell]
----
wget -qO - https://repository.hazelcast.com/api/gpg/key/public | sudo apt-key add -
echo "deb https://repository.hazelcast.com/debian stable main" | sudo tee -a /etc/apt/sources.list
sudo apt update && sudo apt install hazelcast
----

.RPM
[source,shell]
----
wget https://repository.hazelcast.com/rpm/hazelcast-rpm.repo -O hazelcast-rpm.repo
sudo mv hazelcast-rpm.repo /etc/yum.repos.d/
sudo yum install hazelcast
----
--
Windows::
+
--
At the moment, Hazelcast does not support any Windows package managers.

To get started with Hazelcast on Windows, you can use <<using-docker,Docker>>, the <<using-the-binary, binary distribution>>, or <<using-java, Java>>.
--
====

. Check that the CLI is installed.
+
[source,shell]
----
hz-cli -V
----
+
You should see your installed version of Hazelcast:
+
[source,shell,subs="attributes+"]
----
Hazelcast: {page-component-version}
----

== Using Docker

. link:https://docs.docker.com/get-docker/[Install Docker^].

. Check that Docker is correctly installed.
+
[source,bash]
----
docker version
----

. If you do not see a version number, see the link:https://docs.docker.com/config/daemon/[Docker docs^] for troubleshooting information.

. Pull the Hazelcast Docker image from Docker Hub.
+
[source,bash,subs="attributes+"]
----
docker pull hazelcast/hazelcast:{page-component-version}
----

== Using the Binary

Download the archive and extract the binaries.

[tabs] 
==== 
Mac:: 
+ 
--
[source,bash,subs="attributes+"]
----
curl '{distribution-link-mac-linux}' | tar xvzf -
----
--
Linux:: 
+ 
--
[source,bash,subs="attributes+"]
----
wget '{distribution-link-mac-linux}' | tar xvzf -
----
--
Windows:: 
+
--
Download and extract the link:{distribution-link-windows}[Hazelcast archive for Windows].
--
====


== Using Java

Hazelcast runs on Java, which means you can add it as a dependency in your Java project.

The Java package includes both a member API and a Java client API. The member API is for xref:ROOT:topologies.adoc[embedded topologies] where you want to deploy and manage a cluster in the same Java Virtual Machine (JVM) as your applications. The Java client is for connecting to an existing member in a client/server topology.

. Download and install a xref:deploy:supported-jvms.adoc[supported JDK].
+
TIP: We recommend installing the link:https://adoptopenjdk.net[AdoptOpenJDK^].

. If you're using Maven, create a new project and add the following to your `pom.xml` file.
+
[source,xml,subs="attributes+"]
----
<dependencies>
   <dependency>
       <groupId>com.hazelcast</groupId>
       <artifactId>hazelcast</artifactId>
       <version>{page-component-version}</version>
   </dependency>
</dependencies>
----

. If you aren't using a build tool, add the `hazelcast.jar` dependency to your classpath.

== Next Steps

To continue learning about Hazelcast, xref:get-started-binary.adoc[start a local cluster].
