= Install Hazelcast
:description: This guide gets you started with open source Hazelcast by explaining distribution options, application topologies, and installation options.

{description}

TIP: Looking for Hazelcast Enterprise? See xref:get-started-enterprise.adoc[].

== Choosing a Distribution

Hazelcast is available in two distributions:

- *Full:* Includes Management Center and all connectors for distributed processing
- *Slim:* Excludes Management Center and connectors

These getting started tutorials use the full distribution to walk you through important features.

If you later decide that you do not need these features, you can use the slim version to save memory. For more information about these distributions, see xref:deploy:installing-upgrading.adoc#installing-using-download-archives[Full and Slim Packages].

== Choosing an Application Topology

You can use Hazelcast in two topologies, depending on where you want the Hazelcast servers (members) to run:

- Client/server mode: Hazelcast members run remotely outside of your application, allowing you to scale them independently and connect to them through any of the supported clients.
- Embedded mode: Hazelcast members run in the same Java process as your application.

For details about these topologies, see xref:ROOT:topologies.adoc[].

To get started with client/server mode, install Hazelcast with <<using-a-package-manager, the CLI>>, <<using-docker, Docker>>, or <<using-the-binary, the binary>>.

To get started with embedded mode, <<use-java, install Hazelcast in your Java project>>.

[[using-a-package-manager]]
== Using the CLI

include::common:partial$/cli/install.adoc[]

== Using Docker

. link:https://docs.docker.com/get-docker/[Install Docker^].

. Check that Docker is correctly installed.
+
[source,bash]
----
docker version
----

. If you do not see a version number, see the link:https://docs.docker.com/config/daemon/[Docker docs^] for troubleshooting information.

. Pull the Hazelcast Docker image from Docker Hub.
+
[source,bash,subs="attributes+"]
----
docker pull hazelcast/hazelcast:{full-version}
----

== Using the Binary

Download the archive and extract the binaries.

[tabs] 
==== 
Mac:: 
+ 
--
[source,bash,subs="attributes+"]
----
curl 'https://download.hazelcast.com/download.jsp?version=hazelcast-{full-version}&type=tar&p=' | tar xvzf -
----
--
Linux:: 
+ 
--
[source,bash,subs="attributes+"]
----
wget 'https://download.hazelcast.com/download.jsp?version=hazelcast-{full-version}&type=tar&p=' | tar xvzf -
----
--
Windows:: 
+
--
Download and extract the link:https://download.hazelcast.com/download.jsp?version=hazelcast-{full-version}&p=[Hazelcast archive for Windows].
--
====


== Using Java

Hazelcast runs on Java, which means you can add it as a dependency in your Java project.

The Java package includes both a member API and a Java client API. The member API is for xref:ROOT:topologies.adoc[embedded topologies] where you want to deploy and manage a cluster in the same Java Virtual Machine (JVM) as your applications. The Java client is for connecting to an existing member in a client/server topology.

. Download and install a xref:deploy:supported-jvms.adoc[supported JDK].
+
TIP: We recommend installing the link:https://adoptopenjdk.net[AdoptOpenJDK^].

. If you're using Maven, create a new project and add the following to your `pom.xml` file.
+

[source,xml,subs="attributes+"]
----
<dependencies>
   <dependency>
       <groupId>com.hazelcast</groupId>
       <artifactId>hazelcast</artifactId>
       <version>{full-version}</version>
   </dependency>
</dependencies>
----

. If you aren't using a build tool, link:https://repo1.maven.org/maven2/com/hazelcast/hazelcast/{full-version}/hazelcast-{full-version}.jar[download the Hazelcast JAR file] and add it to your classpath.

== Next Steps

To continue learning about Hazelcast, start a local cluster, using xref:get-started-docker.adoc[Docker], xref:get-started-binary.adoc[the binary], or xref:get-started-java.adoc[Java].
