= Installing Hazelcast {open-source-product-name}
:description: You can install the {open-source-product-name} of Hazelcast, using the command line interface (CLI), Docker, the binary, or Java.
:page-aliases: installing-using-download-archives.adoc, deploy:running-in-modular-java.adoc

{description}

NOTE: These instructions apply only to the {open-source-product-name}. If you have a license, which allows you to take advantage of the additional features offered by {enterprise-product-name}, follow the instructions in the xref:install-enterprise.adoc[] topic.

We recommend that you learn more about the benefits of an {enterprise-product-name} license to ensure that you do not require any of the additional functionality or support before you install {open-source-product-name}. If you continue with the {open-source-product-name} installation, you can move your {open-source-product-name} members to {enterprise-product-name} at any time if you subsequently want to benefit from the {enterprise-product-name} functionality without downtime. 

For further information on the available {enterprise-product-name} features and on moving members from an {open-source-product-name} cluster to a target {enterprise-product-name} cluster, see xref:migrate:community-to-enterprise.adoc[].

== Distributions

Both slim and full distributions are available. For further information on the available editions and distributions, see the xref:editions.adoc[] topic.

You must use one of the following installation methods if you want to install the slim distribution:

* <<Using Docker>>
* <<Using the Binary>>
* <<Using Java>>

To install a slim distribution, append `-slim` to the version number in the commands shown in the following sections; for example, to install the slim distribution of {os-version}, use `{os-version}-slim`.

== Using a Package Manager

Hazelcast offers package managers for Linux and Mac operating systems.

Package managers are the fastest way of installing Hazelcast. This option is for development purposes and is only available for Hazelcast {open-source-product-name}. For production, use the other deployment options explained on this page.

// tag::cli[]
. To install Hazelcast, use one of the following methods, depending on your operating system:
+
[tabs] 
==== 
Mac:: 
+ 
--

To install on macOS, use the Homebrew package manager.
ifdef::snapshot[]

[source,bash,subs="attributes+"]
----
brew tap hazelcast/hz
brew install hazelcast@{os-version}
----

--

Linux::
+
--

. Check that you have the GNU Wget package installed. You'll use Wget to download the GPG keys for the Hazelcast package.
+
```bash
wget -V
```
+
If you do not see a version number, download and install link:https://www.gnu.org/software/wget/[Wget^].
+

. Use either of these package managers to install Hazelcast, depending on your Linux distribution:
+
ifdef::snapshot[]

.Debian
[source,shell]
----
wget -qO - https://repository.hazelcast.com/api/gpg/key/public | gpg --dearmor | sudo tee /usr/share/keyrings/hazelcast-archive-keyring.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/hazelcast-archive-keyring.gpg] https://repository.hazelcast.com/debian snapshot main" | sudo tee -a /etc/apt/sources.list
sudo apt update && sudo apt install hazelcast={os-version}
----
+
.RPM
[source,shell]
----
wget https://repository.hazelcast.com/rpm/snapshot/hazelcast-rpm.repo -O hazelcast-snapshot-rpm.repo
sudo mv hazelcast-snapshot-rpm.repo /etc/yum.repos.d/
sudo yum install hazelcast
----
+
endif::[]
+
ifndef::snapshot[]

.Debian
[source,shell,subs="attributes+"]
----
wget -qO - https://repository.hazelcast.com/api/gpg/key/public | gpg --dearmor | sudo tee /usr/share/keyrings/hazelcast-archive-keyring.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/hazelcast-archive-keyring.gpg] https://repository.hazelcast.com/debian stable main" | sudo tee -a /etc/apt/sources.list
sudo apt update && sudo apt install hazelcast={os-version}
----
+
.RPM
[source,shell,subs="attributes+"]
----
wget https://repository.hazelcast.com/rpm/stable/hazelcast-rpm-stable.repo -O hazelcast-rpm-stable.repo
sudo mv hazelcast-rpm-stable.repo /etc/yum.repos.d/
sudo yum install hazelcast-{os-version}
----
+
endif::[]
--
Windows::
+
--
Hazelcast does not yet support any Windows package managers.

To get started with Hazelcast on Windows, you can use xref:get-started-docker.adoc[Docker], the xref:get-started-binary.adoc[binary distribution], or xref:get-started-java.adoc[Java].
--
====

. Check that Hazelcast is installed.
+
[source,shell]
----
hz -V
----
+
You should see the version of both Hazelcast and the command-line client (CLI).
// end::cli[]
. xref:get-started-cli.adoc[Start the cluster].

For more information about the package manager, see the link:https://github.com/hazelcast/hazelcast-packaging[GitHub repository].

== Using Docker

// tag::docker[]
. link:https://docs.docker.com/get-docker/[Install Docker^].

. Check that Docker is correctly installed.
+
[source,bash]
----
docker version
----

. If you do not see a version number, see the link:https://docs.docker.com/config/daemon/[Docker docs^] for troubleshooting information.
// end::docker[]
. xref:get-started-docker.adoc[Start the cluster].

== Using the Binary

Download the latest snapshot archive and extract the binaries.

// tag::binary[]
[tabs] 
==== 
Mac:: 
+ 
--
ifdef::snapshot[]
Go to the link:https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/{full-version}/[snapshot repository] and click the download link for the TAR file that has the most up-to-date timestamp in the *Last Modified* columns.
endif::[]
ifndef::snapshot[]
. Download a package from https://hazelcast.com/get-started/download/[hazelcast.com^].
. Extract the downloaded package.
endif::[]
--
Linux:: 
+ 
--
ifdef::snapshot[]
Go to the link:https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/{full-version}/[snapshot repository] and click the download link for the TAR file that has the most up-to-date timestamp in the *Last Modified* columns.
endif::[]
ifndef::snapshot[]
. Download a package from https://hazelcast.com/get-started/download/[hazelcast.com^].
. Extract the downloaded package.
endif::[]
--
Windows:: 
+
--
ifdef::snapshot[]
Go to the link:https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/{full-version}/[snapshot repository] and click the download link for the ZIP file that has the most up-to-date timestamp in the *Last Modified* columns.
endif::[]
ifndef::snapshot[]
. Download a package from https://hazelcast.com/get-started/download/[hazelcast.com^].
. Extract the downloaded package.
endif::[]
--
====
// end::binary[]

To start the cluster, see xref:get-started-binary.adoc[].

== Using Java

// tag::java[]
To install Hazelcast with Java, you can use one of the following:

- Maven
- JAR file
- Modular Java
// end::java[]

=== Using Maven

// tag::maven[]
Hazelcast runs on Java, which means you can add it as a dependency in your Java project.

The Java package includes both a member API and a Java client API. The member API is for xref:deploy:choosing-a-deployment-option.adoc[embedded topologies] where you want to deploy and manage a cluster in the same Java Virtual Machine (JVM) as your applications. The Java client is for connecting to an existing member in a client/server topology, such as xref:cloud:ROOT:overview.adoc[Hazelcast {hazelcast-cloud}].

. Download and install a xref:deploy:supported-jvms.adoc#supported-java-virtual-machines[supported JDK].

. Add the following to your `pom.xml` file.
// end::maven[]
+
--
// tag::maven-full[]
ifdef::snapshot[]
[source,xml,subs="attributes+"]
----
<repositories>
    <repository>
        <id>snapshot-repository</id>
        <name>Maven2 Snapshot Repository</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
    </repository>
</repositories>

<dependencies>
   <dependency>
       <groupId>com.hazelcast</groupId>
       <artifactId>hazelcast</artifactId>
       <version>{full-version}</version>
   </dependency>
</dependencies>
----
endif::[]
ifndef::snapshot[]
[source,xml,subs="attributes+"]
----
<dependencies>
   <dependency>
       <groupId>com.hazelcast</groupId>
       <artifactId>hazelcast</artifactId>
       <version>{full-version}</version>
   </dependency>
</dependencies>
----
endif::[]
// end::maven-full[]
--

. xref:get-started-java.adoc[Start the cluster].

=== Using the JAR

If you aren't using a build tool:

ifdef::snapshot[]
* link:https://repo1.maven.org/maven2/com/hazelcast/hazelcast/{os-version}/hazelcast-{os-version}.jar[download the Hazelcast JAR file]
endif::[]
ifndef::snapshot[]
* link:https://repo1.maven.org/maven2/com/hazelcast/hazelcast/{full-version}/hazelcast-{full-version}.jar[download the Hazelcast JAR file]
endif::[]
* add it to your classpath.

=== Using Modular Java

// tag::modular[]
You can use Hazelcast as a module in the http://openjdk.java.net/projects/jigsaw/[Java Platform Module System] (JPMS).

To run your application with Hazelcast
libraries on the modulepath, use the `com.hazelcast.core` for `hazelcast-{os-version}.jar` module name.

The JPMS comes with stricter visibility rules. It affects
Hazelcast which uses the internal Java API to reach the best performance results.

Hazelcast needs the `java.se` module and access to the following Java
packages:

* `java.base/jdk.internal.ref`
* `java.base/java.nio` _(reflective access)_
* `java.base/sun.nio.ch` _(reflective access)_
* `java.base/java.lang` _(reflective access)_
* `jdk.management/com.ibm.lang.management.internal` _(reflective access)_
* `jdk.management/com.sun.management.internal` _(reflective access)_
* `java.management/sun.management` _(reflective access)_

You can provide access to these packages by using
`--add-exports` and `--add-opens` (for reflective access) Java arguments.

.Running a Member on the Classpath
[source,bash,subs="attributes+"]
----
java --add-modules java.se \
  --add-exports java.base/jdk.internal.ref=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED \
  --add-opens java.base/java.nio=ALL-UNNAMED \
  --add-opens java.base/sun.nio.ch=ALL-UNNAMED \
  --add-opens java.management/sun.management=ALL-UNNAMED \
  --add-opens jdk.management/com.ibm.lang.management.internal=ALL-UNNAMED \
  --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED \
  -jar hazelcast-{os-version}.jar
----

.Running a Member on the Modulepath
[source,bash]
----
java --add-modules java.se \
  --add-exports java.base/jdk.internal.ref=com.hazelcast.core \
  --add-opens java.base/java.lang=com.hazelcast.core \
  --add-opens java.base/java.nio=com.hazelcast.core \
  --add-opens java.base/sun.nio.ch=com.hazelcast.core \
  --add-opens java.management/sun.management=com.hazelcast.core \
  --add-opens jdk.management/com.ibm.lang.management.internal=com.hazelcast.core \
  --add-opens jdk.management/com.sun.management.internal=com.hazelcast.core \
  --module-path lib \ <1>
  --module com.hazelcast.core/com.hazelcast.core.server.HazelcastMemberStarter
----
<1> This example expects the `hazelcast-{os-version}.jar` file in the `lib` directory.

// end::modular[]

== Next Steps

To continue learning about Hazelcast, start a local cluster, using xref:get-started-docker.adoc[Docker], xref:get-started-binary.adoc[the binary], or xref:get-started-java.adoc[Java].
