= Install Hazelcast {open-source-product-name}
:description: You can install the {open-source-product-name} of Hazelcast using a package manager, Docker, or the binary. Alternatively, you can add Hazelcast as a dependency in your Java project.
:page-aliases: installing-using-download-archives.adoc, deploy:running-in-modular-java.adoc

{description}

NOTE: These instructions apply only to the {open-source-product-name}. If you have an {enterprise-product-name} license, follow the instructions in xref:install-enterprise.adoc[].

We recommend that you learn more about the benefits of an {enterprise-product-name} license to ensure that you do not require any of the additional functionality or support before you install {open-source-product-name}. If you continue with the {open-source-product-name} installation, you can move your {open-source-product-name} members to {enterprise-product-name} at any time if you subsequently want to benefit from the {enterprise-product-name} functionality without downtime. 

For further information on {enterprise-product-name} features, see xref:editions.adoc[]. To migrate from {open-source-product-name} to {enterprise-product-name}, see xref:migrate:rolling-restart.adoc[].

== Distributions

Both slim and full distributions are available:

* <<Use Docker>>
* <<Use the binary>>

xref:getting-started:editions.adoc#full-slim[Further information on the available editions and distributions].

== Use a package manager

Hazelcast offers package managers for Linux and macOS operating systems.

Package managers are the fastest way to install Hazelcast. This option is for development purposes and is only available for Hazelcast {open-source-product-name}. For production, use the other deployment options explained on this page.

// tag::cli[]
. To install Hazelcast, use the appropriate command for your operating system:
+
[tabs] 
==== 
Mac:: 
+ 
--

To install on macOS, use the Homebrew package manager.

[source,bash,subs="attributes+"]
----
brew tap hazelcast/hz
brew install hazelcast@{os-version}
----

--

Linux::
+
--

You can use either of these package managers to install Hazelcast, depending on your Linux distribution:

.Debian

[source,shell,subs="attributes+"]
----
sudo apt-get install -y --no-upgrade wget gpg coreutils \
  && wget -qO - https://repository.hazelcast.com/api/gpg/key/public | gpg --dearmor | sudo tee /usr/share/keyrings/hazelcast-archive-keyring.gpg > /dev/null \
  && echo "deb [signed-by=/usr/share/keyrings/hazelcast-archive-keyring.gpg] https://repository.hazelcast.com/debian stable main" | sudo tee -a /etc/apt/sources.list \
  && sudo apt update && sudo apt install hazelcast={os-version}
----

.RPM
[source,shell,subs="attributes+"]
----
sudo yum -y install wget \
  && wget https://repository.hazelcast.com/rpm/stable/hazelcast-rpm-stable.repo -O hazelcast-rpm-stable.repo \
  && sudo mv hazelcast-rpm-stable.repo /etc/yum.repos.d/ \
  && sudo yum install hazelcast-{os-version}
----

--
Windows::
+
--
Hazelcast does not yet support any Windows package managers.

To get started with Hazelcast on Windows, you can use xref:get-started-docker.adoc[Docker], the xref:get-started-binary.adoc[binary distribution], or xref:get-started-java.adoc[Java].
--
====

. Check that Hazelcast Platform is correctly installed, using the following command:
+
[source,shell]
----
hz -V
----
+
You should see the version of both Hazelcast and the command-line client (CLI).
// end::cli[]

For more information about the packages, see the link:https://github.com/hazelcast/hazelcast-packaging[GitHub repository].

== Use Docker

// tag::docker[]
. link:https://docs.docker.com/get-docker/[Install Docker^].

. Check that Docker is correctly installed.
+
[source,bash,subs="attributes+"]
----
docker version
----
+
If you do not see a version number, see the link:https://docs.docker.com/config/daemon/[Docker docs^] for troubleshooting information.
. Pull the latest Docker image
+
[source,shell,subs="attributes+"]
----
docker pull hazelcast/hazelcast:{os-version}
----
// end::docker[]

== Use the binary

Download the latest snapshot archive and extract the binaries.

// tag::binary[]
--
. Download a package from https://hazelcast.com/community-edition-projects/downloads/?utm_source=docs-website[hazelcast.com^].
. Extract the downloaded package.
--
// end::binary[]

== Use Java

// tag::java[]
To install Hazelcast with Java, you can use one of the following:

- Maven
- JAR file
- Modular Java
// end::java[]

=== Use Maven

// tag::maven[]
Hazelcast runs on Java, which means you can add it as a dependency in your Java project.

The Java package includes both a member API and a Java client API. The member API is for xref:deploy:choosing-a-deployment-option.adoc[embedded topologies] where you want to deploy and manage a cluster in the same Java Virtual Machine (JVM) as your applications. The Java client is for connecting to an existing member in a client/server topology, such as xref:cloud:ROOT:overview.adoc[Hazelcast {hazelcast-cloud}].

. Download and install a xref:deploy:supported-jvms.adoc#supported-java-virtual-machines[supported JDK].

. Add the following to your `pom.xml` file.
// end::maven[]
+
--
// tag::maven-full[]

[source,xml,subs="attributes+"]
----
<dependencies>
   <dependency>
       <groupId>com.hazelcast</groupId>
       <artifactId>hazelcast</artifactId> <1>
       <version>{os-version}</version> <2>
   </dependency>
</dependencies>
----
<1> Hazelcast {open-source-product-name} dependency.
<2> Hazelcast {open-source-product-name} version.

// end::maven-full[]
--

// Only support OS non-SNAPSHOTs
ifndef::snapshot[]
=== Use the JAR

If you aren't using a build tool:

* link:https://repo.maven.apache.org/maven2/com/hazelcast/hazelcast/{os-version}/hazelcast-{os-version}.jar[download the Hazelcast JAR file]
* add it to your classpath.
endif::[]

== Use modular Java

// tag::modular[]
You can use Hazelcast as a module in the http://openjdk.java.net/projects/jigsaw/[Java Platform Module System] (JPMS).

To run your application with Hazelcast libraries on the module path, use `com.hazelcast.core` for the `hazelcast-{os-version}.jar` module name.

If you use JPMS, it enforces stricter visibility rules and Hazelcast uses the internal Java API to reach the best performance results.

Hazelcast needs the `java.se` module and access to the following Java
packages:

* `java.base/jdk.internal.ref`
* `java.base/java.nio` _(reflective access)_
* `java.base/sun.nio.ch` _(reflective access)_
* `java.base/java.lang` _(reflective access)_
* `jdk.management/com.ibm.lang.management.internal` _(reflective access)_
* `jdk.management/com.sun.management.internal` _(reflective access)_
* `java.management/sun.management` _(reflective access)_

You can provide access to these packages by using simple
`--add-exports` and `--add-opens` (for reflective access) Java arguments.

// end::modular[]

.Run a member on the classpath
[source,bash,subs="attributes+"]
----
java --add-modules java.se \
  --add-exports java.base/jdk.internal.ref=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED \
  --add-opens java.base/java.nio=ALL-UNNAMED \
  --add-opens java.base/sun.nio.ch=ALL-UNNAMED \
  --add-opens java.management/sun.management=ALL-UNNAMED \
  --add-opens jdk.management/com.ibm.lang.management.internal=ALL-UNNAMED \
  --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED \
  -jar hazelcast-{os-version}.jar
----

.Run a member on the module path
[source,bash,subs="attributes+"]
----
java --add-modules java.se \
  --add-exports java.base/jdk.internal.ref=com.hazelcast.core \
  --add-opens java.base/java.lang=com.hazelcast.core \
  --add-opens java.base/java.nio=com.hazelcast.core \
  --add-opens java.base/sun.nio.ch=com.hazelcast.core \
  --add-opens java.management/sun.management=com.hazelcast.core \
  --add-opens jdk.management/com.ibm.lang.management.internal=com.hazelcast.core \
  --add-opens jdk.management/com.sun.management.internal=com.hazelcast.core \
  --module-path lib \ <1>
  --module com.hazelcast.core/com.hazelcast.core.server.HazelcastMemberStarter
----
<1> This example requires the `hazelcast-{os-version}.jar` file in the `lib` directory.

== Next steps

To continue learning about Hazelcast, start a local cluster using xref:get-started-docker.adoc[Docker], xref:get-started-binary.adoc[the binary], or xref:get-started-java.adoc[Java].
