= Installing Hazelcast Open Source
:description: You can install the Open Source edition of Hazelcast, using the command line interface (CLI), Docker, the binary, or Java.

{description}

TIP: Looking for Hazelcast Enterprise? See xref:get-started-enterprise.adoc[].

== Using a Package Manager

Hazelcast offers package managers for Linux and Mac operating systems.

// tag::cli[]
. To install Hazelcast, use one of the following methods, depending on your operating system:
+
[tabs] 
==== 
Mac:: 
+ 
--

To install on macOS, use the Homebrew package manager.

[source,bash,subs="attributes+"]
----
brew tap hazelcast/hz
brew install hazelcast@{full-version}
----
--

Linux::
+
--

To install on Linux, you can use either of these package managers, depending on your Linux distribution:
ifdef::snapshot[]
.Debian
[source,shell]
----
wget -qO - https://repository.hazelcast.com/api/gpg/key/public | gpg --dearmor | sudo tee /usr/share/keyrings/hazelcast-archive-keyring.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/hazelcast-archive-keyring.gpg] https://repository.hazelcast.com/debian snapshot main" | sudo tee -a /etc/apt/sources.list
sudo apt update && sudo apt install hazelcast
----

.RPM
[source,shell]
----
wget https://repository.hazelcast.com/rpm/snapshot/hazelcast-rpm.repo -O hazelcast-snapshot-rpm.repo
sudo mv hazelcast-snapshot-rpm.repo /etc/yum.repos.d/
sudo yum install hazelcast
----
endif::[]
ifndef::snapshot[]
.Debian
[source,shell,subs="attributes+"]
----
wget -qO - https://repository.hazelcast.com/api/gpg/key/public | gpg --dearmor | sudo tee /usr/share/keyrings/hazelcast-archive-keyring.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/hazelcast-archive-keyring.gpg] https://repository.hazelcast.com/debian stable main" | sudo tee -a /etc/apt/sources.list
sudo apt update && sudo apt install hazelcast={full-version}
----

.RPM
[source,shell,subs="attributes+"]
----
wget https://repository.hazelcast.com/rpm/stable/hazelcast-rpm-stable.repo -O hazelcast-rpm-stable.repo
sudo mv hazelcast-rpm-stable.repo /etc/yum.repos.d/
sudo yum install hazelcast={full-version}
----
endif::[]
--
Windows::
+
--
At the moment, Hazelcast does not support any Windows package managers.

To get started with Hazelcast on Windows, you can use <<using-docker,Docker>>, the <<using-the-binary, binary distribution>>, or <<using-java, Java>>.
--
====

. Check that Hazelcast is installed.
+
[source,shell]
----
hz -V
----
+
You should the version of both Hazelcast and the command-line client (CLI).

For more information about the package manager, see the link:https://github.com/hazelcast/hazelcast-packaging[GitHub repository].
// end::cli[]

== Using Docker

. link:https://docs.docker.com/get-docker/[Install Docker^].

. Check that Docker is correctly installed.
+
[source,bash]
----
docker version
----

. If you do not see a version number, see the link:https://docs.docker.com/config/daemon/[Docker docs^] for troubleshooting information.

. Pull the Hazelcast Docker image from Docker Hub.
+
[source,bash,subs="attributes+"]
----
docker pull hazelcast/hazelcast:{full-version}
----

== Using the Binary

Download the archive and extract the binaries.

[tabs] 
==== 
Mac:: 
+ 
--
ifdef::snapshot[]
Go to the link:https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/{full-version}/[snapshot repository] and click the download link for the TAR file that has the most up-to-date timestamp in the *Last Modified* columns.
endif::[]
ifndef::snapshot[]
[source,bash,subs="attributes+"]
----
wget -O - 'https://repository.hazelcast.com/download/hazelcast/hazelcast-{full-version}.tar.gz' | tar xvzf -
----
endif::[]
--
Linux:: 
+ 
--
ifdef::snapshot[]
Go to the link:https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/{full-version}/[snapshot repository] and click the download link for the TAR file that has the most up-to-date timestamp in the *Last Modified* columns.
endif::[]
ifndef::snapshot[]
[source,bash,subs="attributes+"]
----
wget -O - 'https://repository.hazelcast.com/download/hazelcast/hazelcast-{full-version}.tar.gz' | tar xvzf -
----
endif::[]
--
Windows:: 
+
--
ifdef::snapshot[]
Go to the link:https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/{full-version}/[snapshot repository] and click the download link for the ZIP file that has the most up-to-date timestamp in the *Last Modified* columns.
endif::[]
ifndef::snapshot[]
Download and extract the link:https://github.com/hazelcast/hazelcast/releases/download/hazelcast-{full-version}.zip[Hazelcast ZIP file].
endif::[]
--
====


== Using Java

Hazelcast runs on Java, which means you can add it as a dependency in your Java project.

The Java package includes both a member API and a Java client API. The member API is for embedded topologies where you want to deploy and manage a cluster in the same Java Virtual Machine (JVM) as your applications. The Java client is for connecting to an existing member in a client/server topology, such as xref:cloud:ROOT:overview.adoc[Hazelcast {hazelcast-cloud} Managed Services].

. Download and install a xref:deploy:supported-jvms.adoc[supported JDK].
+
TIP: We recommend installing the link:https://adoptopenjdk.net[AdoptOpenJDK^].

. If you're using Maven, create a new project and add the following to your `pom.xml` file.
+
ifdef::snapshot[]
[source,xml,subs="attributes+"]
----
<repositories>
    <repository>
        <id>snapshot-repository</id>
        <name>Maven2 Snapshot Repository</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
    </repository>
</repositories>

<dependencies>
   <dependency>
       <groupId>com.hazelcast</groupId>
       <artifactId>hazelcast</artifactId>
       <version>{full-version}</version>
   </dependency>
</dependencies>
----
endif::[]
ifndef::snapshot[]
[source,xml,subs="attributes+"]
----
<dependencies>
   <dependency>
       <groupId>com.hazelcast</groupId>
       <artifactId>hazelcast</artifactId>
       <version>{full-version}</version>
   </dependency>
</dependencies>
----
endif::[]

. If you aren't using a build tool, link:https://repo1.maven.org/maven2/com/hazelcast/hazelcast/{full-version}/hazelcast-{full-version}.jar[download the Hazelcast JAR file] and add it to your classpath.

== Next Steps

To continue learning about Hazelcast, start a local cluster, using xref:get-started-docker.adoc[Docker], xref:get-started-binary.adoc[the binary], or xref:get-started-java.adoc[Java].
