= Installing Hazelcast Open Source
:description: You can install the Open Source edition of Hazelcast, using the command line interface (CLI), Docker, the binary, or Java.

{description}

TIP: Looking for Hazelcast Enterprise? See xref:get-started-enterprise.adoc[].

[[using-a-package-manager]]
== Using the CLI

include::common:partial$/cli/install.adoc[]

== Using Docker

. link:https://docs.docker.com/get-docker/[Install Docker^].

. Check that Docker is correctly installed.
+
[source,bash]
----
docker version
----

. If you do not see a version number, see the link:https://docs.docker.com/config/daemon/[Docker docs^] for troubleshooting information.

. Pull the Hazelcast Docker image from Docker Hub.
+
[source,bash,subs="attributes+"]
----
docker pull hazelcast/hazelcast:{full-version}
----

== Using the Binary

Download the archive and extract the binaries.

[tabs] 
==== 
Mac:: 
+ 
--
ifdef::snapshot[]
Go to the link:https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/{full-version}/[snapshot repository] and click the download link for the TAR file that has the most up-to-date timestamp in the *Last Modified* columns.
endif::[]
ifndef::snapshot[]
[source,bash,subs="attributes+"]
----
wget 'https://download.hazelcast.com/download.jsp?version=hazelcast-{full-version}&type=tar&p=' | tar xvzf -
----
endif::[]
--
Linux:: 
+ 
--
ifdef::snapshot[]
Go to the link:https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/{full-version}/[snapshot repository] and click the download link for the TAR file that has the most up-to-date timestamp in the *Last Modified* columns.
endif::[]
ifndef::snapshot[]
[source,bash,subs="attributes+"]
----
wget 'https://download.hazelcast.com/download.jsp?version=hazelcast-{full-version}&type=tar&p=' | tar xvzf -
----
endif::[]
--
Windows:: 
+
--
ifdef::snapshot[]
Go to the link:https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/{full-version}/[snapshot repository] and click the download link for the ZIP file that has the most up-to-date timestamp in the *Last Modified* columns.
endif::[]
ifndef::snapshot[]
Download and extract the link:https://download.hazelcast.com/download.jsp?version=hazelcast-{full-version}&p=[Hazelcast archive for Windows].
endif::[]
--
====


== Using Java

Hazelcast runs on Java, which means you can add it as a dependency in your Java project.

The Java package includes both a member API and a Java client API. The member API is for xref:ROOT:topologies.adoc[embedded topologies] where you want to deploy and manage a cluster in the same Java Virtual Machine (JVM) as your applications. The Java client is for connecting to an existing member in a client/server topology.

. Download and install a xref:deploy:supported-jvms.adoc[supported JDK].
+
TIP: We recommend installing the link:https://adoptopenjdk.net[AdoptOpenJDK^].

. If you're using Maven, create a new project and add the following to your `pom.xml` file.
+
ifdef::snapshot[]
[source,xml,subs="attributes+"]
----
<repositories>
    <repository>
        <id>snapshot-repository</id>
        <name>Maven2 Snapshot Repository</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
    </repository>
</repositories>

<dependencies>
   <dependency>
       <groupId>com.hazelcast</groupId>
       <artifactId>hazelcast</artifactId>
       <version>{full-version}</version>
   </dependency>
</dependencies>
----
endif::[]
ifndef::snapshot[]
[source,xml,subs="attributes+"]
----
<dependencies>
   <dependency>
       <groupId>com.hazelcast</groupId>
       <artifactId>hazelcast</artifactId>
       <version>{full-version}</version>
   </dependency>
</dependencies>
----
endif::[]

. If you aren't using a build tool, link:https://repo1.maven.org/maven2/com/hazelcast/hazelcast/{full-version}/hazelcast-{full-version}.jar[download the Hazelcast JAR file] and add it to your classpath.

== Next Steps

To continue learning about Hazelcast, start a local cluster, using xref:get-started-docker.adoc[Docker], xref:get-started-binary.adoc[the binary], or xref:get-started-java.adoc[Java].
