= Installing Hazelcast Enterprise
:description: pass:q[To install xref:editions.adoc[Hazelcast Enterprise], you can use Docker, the binary, or Java. Then, to unlock the Enterprise features, you need to install your Enterprise license key.]
:page-aliases: deploy:using-enterprise-edition.adoc, get-started-enterprise.adoc

{description}

TIP: Hazelcast Enterprise is a commercial product that offers additional features to the Open Source edition, including the security suite and blue/green deployments for clients. If you're looking to get started with open source Hazelcast, see xref:install-hazelcast.adoc[].

== Using the Enterprise Docker Image

// tag::docker[]
. link:https://docs.docker.com/get-docker/[Install Docker^].

. Check that Docker is correctly installed.
+
[source,bash]
----
docker version
----

. If you do not see a version number, see the link:https://docs.docker.com/config/daemon/[Docker docs^] for troubleshooting information.

. Pull the Hazelcast Docker image from Docker Hub.
+
[source,bash,subs="attributes+"]
----
docker pull hazelcast/hazelcast-enterprise:{full-version}
----
// end::docker[]
. xref:get-started-docker.adoc[Start the cluster].

== Using the Enterprise Binary

Download and extract the binaries.

// tag::download-package-ee[]
[tabs] 
==== 
Mac:: 
+ 
--
[source,bash,subs="attributes+"]
----
curl -L 'https://repository.hazelcast.com/download/hazelcast-enterprise/hazelcast-enterprise-{full-version}.tar.gz' | tar xvzf -
----
--
Linux:: 
+ 
--
[source,bash,subs="attributes+"]
----
wget -O - 'https://repository.hazelcast.com/download/hazelcast-enterprise/hazelcast-enterprise-{full-version}.tar.gz' | tar xvzf -
----
--
Windows:: 
+
--
Download and extract the link:https://repository.hazelcast.com/download/hazelcast-enterprise/hazelcast-enterprise-{full-version}.zip[Hazelcast ZIP file].
--
====
// end::download-package-ee[]

To start the cluster, see xref:get-started-binary.adoc[].

== Using Enterprise Java

include::install-hazelcast.adoc[tag=java]

=== Using Maven

include::install-hazelcast.adoc[tag=maven]
+
--
// tag::maven-full-ee[]
ifdef::snapshot[]
[source,xml,subs="attributes+"]
----
<repositories>
    <repository>
        <id>private-repository</id>
        <name>Hazelcast Private Repository</name>
        <url>https://repository.hazelcast.com/release/</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>com.hazelcast</groupId>
        <artifactId>hazelcast-enterprise</artifactId>
        <version>{full-version}</version>
    </dependency>
</dependencies>
----
endif::[]
ifndef::snapshot[]
[source,xml,subs="attributes+"]
----
<repositories>
    <repository>
        <id>private-repository</id>
        <name>Hazelcast Private Repository</name>
        <url>https://repository.hazelcast.com/release/</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>com.hazelcast</groupId>
        <artifactId>hazelcast-enterprise</artifactId>
        <version>{full-version}</version>
    </dependency>
</dependencies>
----
endif::[]
// end::maven-full-ee[]
--

. xref:get-started-java.adoc[Start the cluster].

=== Using Modular Java

include::install-hazelcast.adoc[tag=modular]

== Getting an Enterprise License Key

include::deploy:enterprise-licenses.adoc[tag=get-license]

== Installing an Enterprise License Key

include::deploy:enterprise-licenses.adoc[tag=install-license]

== Next Steps

Learn more about xref:deploy:enterprise-licenses.adoc[Enterprise license keys].

Get started with the Hazelcast Enterprise features with a series of xref:enterprise-overview.adoc[tutorials].

.Explore the Hazelcast Enterprise features in more detail
[%collapsible]
====
* xref:security:overview.adoc[Security suite]
* xref:wan:wan.adoc[]
* xref:cp-subsystem:persistence.adoc[]
* xref:deploy:deploying-in-vmware-tanzu.adoc[Deploying in VMware Tanzu]
* xref:kubernetes:deploying-in-kubernetes.adoc[Deploying in Openshift container platform]
* xref:maintain-cluster:monitoring.adoc#clustered-jmx-and-rest-via-management-center[Clustered REST]
* xref:maintain-cluster:monitoring.adoc#clustered-jmx-and-rest-via-management-center[Clustered JMX]
* xref:maintain-cluster:rolling-upgrades.adoc[Rolling upgrades]
* xref:storage:high-density-memory.adoc[]
* xref:storage:persistence.adoc[]
* xref:clients:java.adoc#blue-green-deployment-and-disaster-recovery[Blue/Green client support]
* xref:pipelines:job-update.adoc[Job updates]
====