= Secure Cluster
:description: This tutorial guides you on securing the communication within a cluster using the TLS protocol.

{description} We recommend you to secure your deployments; without security, unauthorized members or clients may access
the cluster and use the cluster resources.

In this tutorial, you will:

. Prepare to enable the security feature (keystore)
. Start a Hazelcast Enterprise cluster with TLS enabled and configured
. Connect a client which is configured to be authorized
. Try to connect another client which does not respect to the security requirements

== Before You Begin

To complete this tutorial, you need the following:

[cols="1a,1a"]
|===
|Prerequisites|Useful resources

|Docker
|
link:https://docs.docker.com/docker-for-mac/install/[Install Docker for Mac]

link:https://docs.docker.com/engine/install/[Install Docker for Linux]

link:https://docs.docker.com/docker-for-windows/install/[Install Docker for Windows]

|Docker image for the full Hazelcast distribution
|xref:get-started-enterprise.adoc[Install Hazelcast Enterprise]

|Docker network with the name `hazelcast-network`
|Use the `docker network create hazelcast-network` command 

|===

== Step 1. Generate a keystore

To be able to enable TLS, you need to first create a keystore with a self-signed certificate,
if you already don't have.
The keystore will be then used as a parameter while starting the cluster members.

. Create a directory in which the keystore will be stored.
+
[source,shell]
----
mkdir keystore
----
. Generate the key pairs.
+
[source,shell]
----
keytool -validity 365 -genkeypair -alias server -keyalg EC -keystore ./keystore/server.keystore -storepass 123456 -keypass 123456 -dname CN=localhost
----
. Create the certificate file.
+
[source,shell]
----
keytool -export -alias server -keystore ./keystore/server.keystore -storepass 123456 -file ./keystore/server.crt
----
. Add the certificate to keystore.
+
[source,shell]
----
keytool -import -noprompt -alias server -keystore ./keystore/server.truststore -storepass 123456 -file ./keystore/server.crt
----

== Step 2. Start the Members with TLS Enabled

Start an Enterprise member using the following Docker command.

[source,shell]
----
docker run --name first-member --network hazelcast-network \
    --rm \
    -e HZ_CLUSTERNAME=hello-world \
    -e HZ_LICENSEKEY=<license key> \
    -e HZ_NETWORK_SSL_ENABLED=true \
    -v `pwd`/keystore:/keystore \
    -e "JAVA_OPTS=-Djavax.net.ssl.keyStore=/keystore/server.keystore -Djavax.net.ssl.keyStorePassword=123456
    -Djavax.net.ssl.trustStore=/keystore/server.truststore -Djavax.net.ssl.trustStorePassword=123456" \
    -p 5701:5701 hazelcast/hazelcast-enterprise:5.0
----

Start the second member.

[source,shell]
----
docker run --name second-member --network hazelcast-network \
    --rm \
    -e HZ_CLUSTERNAME=hello-world \
    -e HZ_LICENSEKEY=<license key> \
    -e HZ_NETWORK_SSL_ENABLED=true \
    -v `pwd`/keystore:/keystore \
    -e "JAVA_OPTS=-Djavax.net.ssl.keyStore=/keystore/server.keystore -Djavax.net.ssl.keyStorePassword=123456
    -Djavax.net.ssl.trustStore=/keystore/server.truststore -Djavax.net.ssl.trustStorePassword=123456" \
    -p 5702:5701 hazelcast/hazelcast-enterprise:5.0
----

== Step 3. Configure Security for the Client

???

== Step 4. Connect a Client

???

NOTE: See xref:security:overview.adoc[Securing a Cluster] if you're
interested in learning more about the topics introduced in this tutorial.

