= Authenticate Client Connections
:description: This tutorial guides you on securing the communication between a cluster member and client using the security feature's identity configuration.

{description} This way the member will accept and authorize connections from the clients which have the matching identity configurations.
We recommend you to secure your deployments; without security, unauthorized members or clients may access
the cluster and use the cluster resources.

In this tutorial, you will:

. Start a Hazelcast Enterprise member with security enabled and configured
. Connect a client which is configured to be authorized
. Try to connect another client which does not respect to the security requirements

== Before You Begin

To complete this tutorial, you need the following:

[cols="1a,1a"]
|===
|Prerequisites|Useful resources

|Trial license
|https://trialrequest.hazelcast.com/[Hazelcast website]

|Docker image for the full Hazelcast distribution
|xref:get-started-enterprise.adoc[Install Hazelcast Enterprise]

|===

== Step 1. Configure the Enterprise Member

Since the configuration for security is more detailed, you'll use a Hazelcast configuration file
and pass it to the Docker command, instead of giving all the configuration options in a single Docker command.

In an existing or new directory, place a `hazelcast.yaml` (or `xml`) file with the following content.

[tabs]
====
YAML::
+
--

[source,yaml]
----
hazelcast:
  cluster-name: hello-world
  license-key: <your license key> <1>
  security:
    enabled: true
    realms:
      - name: passwordRealm
        identity:
          username-password:
            username: member1
            password: s3crEt
  member-authentication:
    realm: passwordRealm
----
<1> Replace the `<your license key>` placeholder with your Hazelcast Enterprise license key.
--

XML::
+
[source,xml]
----
<hazelcast>
    <cluster-name>hello-world</cluster-name>
    <license-key>your license key</license-key> <1>
    <security enabled="true">
        <realms>
            <realm name="passwordRealm">
                <identity>
                    <username-password username="member1" password="s3crEt" />
                </identity>
            </realm>
        </realms>
        <member-authentication realm="passwordRealm" />
    </security>
</hazelcast>
----
<1> Replace with your actual Hazelcast Enterprise license key
====

With this configuration, you tell the member to accept connections only from the clients
having the credentials `member1` and `s3crEt`.

== Step 2. Start the Member

Run the following command.

[source,shell,subs="attributes+"]
----
docker run \
    --net=host \
    -e JAVA_OPTS="-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml" -v ~/config:/opt/hazelcast/config_ext hazelcast/hazelcast-enterprise:{full-version}
----

This command starts the member with the configuration provided in Step 1 above. 
Here, `~/config` is the path to the directory in which the configuration file resides.
You should replace it with the directory path you've created.

The member is up and running now:

[source,shell]
----
Members {size:1, ver:1} [
	Member [192.168.1.101]:5701 - cfc75512-a9c5-4798-bcca-450b7bf3c105 this
]
----

== Step 3. Connect a Client

You'll now connect a client in your preferred language to the cluster, having the security credentials configured on the member side.

[tabs]
====
Python::
+
--

. Create a new project in your preferred Python IDE
. Run `pip install hazelcast-python-client` in the IDE's terminal
. Create a Python file, e.g., `myPyClient.py` containing the following code.
+
[source,python]
----
import hazelcast

client = hazelcast.HazelcastClient(
    cluster_members=["192.168.1.101:5701"],
    cluster_name="hello-world",
    creds_username="member1",
    creds_password="s3crEt"
)

client.shutdown()
----
. Run `python myPyClient.py` in the IDE.
--

Go::
+

. In a terminal, create a new directory and go into it.
. Run `go mod init <name of the directory>`.
. Run `go get github.com/hazelcast/hazelcast-go-client`.
. While in this directory, create a `go` file (for example `main.go`) containing the following code.
+
[source,go]
----
package main

import (
	"context"

	"github.com/hazelcast/hazelcast-go-client"
)

func main() {
	ctx := context.TODO()
	config := hazelcast.Config{}
	cc := &config.Cluster
	cc.Network.SetAddresses("192.168.1.101:5701")
	cc.Name = "hello-world"
	creds := &cc.Security.Credentials
	creds.Username = "member1"
	creds.Password = "s3crEt"
	client, err := hazelcast.StartNewClientWithConfig(ctx, config)
	if err != nil {
		panic(err)
	}
	client.Shutdown(ctx)
}
----
. Run `go run main.go` in the terminal.

Java::
+

. Install the xref:getting-started:install-hazelcast.adoc#use-java[Java client library].
. In your preferred Java IDE, create a new project to include a class containing the following code.
+
[source,java]
----
import com.hazelcast.client.HazelcastClient;
import com.hazelcast.client.config.ClientConfig;

public class SecuredClient {
  public static void main(String[] args) {

ClientConfig clientConfig = new ClientConfig();
        clientConfig.setClusterName("hello-world");
        clientConfig.getSecurityConfig().setUsernamePasswordIdentityConfig("member1","s3crEt");
        HazelcastClient.newHazelcastClient(clientConfig);

  }
}
----
. Run the `SecuredClient` class in the IDE.

C Sharp::
+

. Install the latest http://hazelcast.github.io/hazelcast-csharp-client/4.0.1/doc/obtaining.html[C Sharp client library]
. In your preferred C# IDE, create a new project to include a class containing the following code.
+
[source,cs]
----
var username = "member1";
var password = "s3crEt";

var options = new HazelcastOptionsBuilder();
    .With(o => {
        o.Authentication.ConfigureUsernamePasswordCredentials(username, password);
    })
    .Build();

var client = await HazelcastClientFactory.StartNewClientAsync(options);
----
. Run this class in the IDE.

C++::
+

. Install the latest https://github.com/hazelcast/hazelcast-cpp-client/blob/v4.1.0/Reference_Manual.md#11-installing[C++ client library]
. In your preferred C++ IDE, create a new project to include a class containing the following code.
+
[source,cpp]
----
    hazelcast::client::client_config clientConfig;

    clientConfig.set_credentials(
            std::make_shared<hazelcast::client::security::username_password_credentials>("member1", "s3crEt"));

    clientConfig.set_cluster_name("hello-world");
    
    auto hz = hazelcast::new_client(std::move(clientConfig)).get();
----
. Run this class in the IDE.

Node.js::
+

. Install the Node.js client library: `npm install hazelcast-client`
. In your preferred Node.js IDE, create a new project to include the following script.
+
[source,javascript]
----
const { Client } = require('hazelcast-client');
class UsernamePasswordCredentials {
    constructor(username, password, endpoint) {
        this.username = username;
        this.password = password;
        this.endpoint = endpoint;
        this.factoryId = 1;
        this.classId = 1;
    }
    readPortable(reader) {
        this.username = reader.readString('username');
        this.endpoint = reader.readString('password');
        this.password = reader.readString('endpoint');
    }
    writePortable(writer) {
        writer.writeString('username', this.username);
        writer.writeString('password', this.password);
        writer.writeString('endpoint', this.endpoint);
    }
}
function usernamePasswordCredentialsFactory(classId) {
    if (classId === 1) {
        return new UsernamePasswordCredentials();
    }
    return null;
}
(async () => {
    try {
        const client = await Client.newHazelcastClient({
            clusterName: 'hello-world',
            serialization: {
                portableFactories: {
                    1: usernamePasswordCredentialsFactory
                }
            },
            customCredentials: new UsernamePasswordCredentials('member1', 's3crEt', '192.168.1.101:5701')
        });
        console.log(await client.getDistributedObjects());
    } catch (error) {
        console.error('Error occurred:', error);
    }
})();
----
. Run this script in the IDE.

====

When looking at the client terminal, you can see that the member side has authenticated and accepted the client connection.

[source,shell]
----
INFO:hazelcast.lifecycle:HazelcastClient 5.1 is STARTING
INFO:hazelcast.lifecycle:HazelcastClient 5.1 is STARTED
INFO:hazelcast.connection:Trying to connect to Address(host=127.0.0.1, port=5701)
INFO:hazelcast.lifecycle:HazelcastClient 5.1 is CONNECTED
INFO:hazelcast.connection:Authenticated with server Address(host=192.168.1.9, port=5701):63b2a2ce-85f6-413f-8ce9-6058a748e4b9, server version: 5.0, local address: Address(host=127.0.0.1, port=36006)
INFO:hazelcast.cluster:

Members [1] {
	Member 192.168.1.101:5701 - 63b2a2ce-85f6-413f-8ce9-6058a748e4b9
}

INFO:hazelcast.client:Client started
----

If you try to connect a client without any credentials or with credentials different than the configured ones on the member side,
you can see the connection is refused by the member.

[source,shell]
----
INFO:hazelcast.lifecycle:HazelcastClient 5.1 is STARTING
INFO:hazelcast.lifecycle:HazelcastClient 5.1 is STARTED
INFO:hazelcast.connection:Trying to connect to Address(host=127.0.0.1, port=5701)
INFO:hazelcast.connection:Connection(id=0, live=False, remote_address=None) closed. Reason: Failed to authenticate connection
WARNING:hazelcast.connection:Error during initial connection to Address(host=127.0.0.1, port=5701)
----

== Step 3. Shut Down the Cluster

Shut down the cluster you've created in this tutorial so that you can start a fresh one when you
move to the other tutorials. To shutdown, close the terminals in which the members are running or press kbd:[Ctrl+C] in each terminal.

== Next Steps

See xref:security:overview.adoc[Securing a Cluster] if you're
interested in learning more about the topics introduced in this tutorial.

Now that you've completed this tutorial, you can continue with xref:getting-started:wan.adoc[Replicate over WAN].

