= Getting Support
:description: Hazelcast provides two types of support: one for the community and one for paying customers.

{description}

== Community Support

Community support is for every Hazelcast user. You can use the following channels to get community support:

* https://github.com/hazelcast/hazelcast[Hazelcast GitHub] (for reporting issues through our GitHub repository)
* https://slack.hazelcast.com/[Hazelcast Community Slack^]
* https://groups.google.com/forum/#!forum/hazelcast[Mail Group^]
* http://www.stackoverflow.com/[StackOverflow^].

== Customer Support

Customer support is for paying Hazelcast customers.
See https://hazelcast.com/services/support/[hazelcast.com^] for the support options.
A support subscription from Hazelcast will allow you to get the most value out of your
selection of Hazelcast. Our customers benefit from rapid response times to technical
support inquiries, access to critical software patches, and other services which
will help you achieve increased productivity and quality. Learn more about Hazelcast support subscriptions:
https://hazelcast.com/pricing/

If your organization subscribes to Hazelcast support,
and you already have an account setup, you can login to your account and open
a support request using our ticketing system: https://hazelcast.zendesk.com/.

When submitting a ticket to the team, please provide as much information and data as possible:

* Make sure that all your environments are capturing Hazelcast diagnostics logs.
This a primary on diagnosing issues with Hazelcast environments.
* If your environments are not capturing diagnostics logs, please update them to capture diagnostics logs.
* Make note of your issue with a clear description of the issue for a title text.
This will allow the team to route the issue to the proper expert
* Make a note of the steps to reproduce if possible.
If not please capture the sequence of events that led to the problem.
* Write a complete description of the problem along with any error found.
* Capture any relevant screen shots and or errors noted.
* Create a support ticket on Hazelcast Zendesk support Portal.
* Attach the appropriate severity to the ticket.
* `PROD` issues that affect production are considered as severity 1.
* All other issues in other environments are considered severity 2 or 3 depending on urgency.
* `DEV` issues are considered as severity 3 and priority low.
* All other issues, e.g., questions or documentation review are considered as severity 3 or higher.

=== Adding Details to the Support Ticket

* When you open a support ticket add a concise title and description of the problem.
* Add steps to reproduce as best as you can document them so that support can attempt
to reproduce the problem. This includes Detailed description of incident – what happened and when. 
* Add a reproducible test case, this is optional - Hazelcast engineering may ask for it if required.
* Add details of use case. This is crucial as it helps support narrow down the features and
functionality in play when the problem occurred.
* Attach any specific errors found.
* Attach the complete logs files, i.e., Hazelcast logs.
* Attach Hazelcast process logs.
* Attach Hazelcast health monitor logs.
* Attach thread dumps from all members.
* Attach heap dumps.
* Add networking logs.
* Specify the time of incident.
* When providing Hazelcast logs, please make sure that the system and
environment details that are captured at system startup are included, even if you truncate the logs.
* Add Hazelcast diagnostic logs. Please do not truncate diagnostics logs. They only capture Hazelcast
systems specific information and details.
* Please make sure that the logs capture data around the date and time of the incident.

Please consider the above for prompt help from the team and note that the more information
is provided upfront the better.
Lastly, be prompt in your communication with Hazelcast support - helps to ensure timely resolution of issues.
