= Getting Support
:description: Hazelcast provides two types of support: one for the community and one for paying customers.

{description}

== Community Support

Community support is for every Hazelcast user. You can use the following channels to get community support:

* https://github.com/hazelcast/hazelcast[Hazelcast GitHub] (for reporting issues through our GitHub repository)
* https://slack.hazelcast.com/[Hazelcast Community Slack^].

== Customer Support

Customer support is for paying Hazelcast customers.
See https://hazelcast.com/services/support/[hazelcast.com^] for the support options.
A support subscription from Hazelcast will allow you to get the most value out of your
selection of Hazelcast. Our customers benefit from rapid response times to technical
support inquiries, access to critical software patches, and other services which
will help you achieve increased productivity and quality. Learn more about Hazelcast support subscriptions:
https://hazelcast.com/pricing/

If your organization subscribes to Hazelcast support,
and you already have an account setup, you can login to your account and open
a support request using our ticketing system:  https://support.hazelcast.com/s/.

When submitting a ticket to the team, please provide as much information and data as possible:

* Make sure that all your environments are capturing Hazelcast diagnostics logs.
This a primary on diagnosing issues with Hazelcast environments.
* If your environments are not capturing diagnostics logs, please update them to capture diagnostics logs.
* Make note of your issue with a clear description of the issue for a title text.
This will allow the team to route the issue to the proper expert
* Make a note of the steps to reproduce if possible.
If not please capture the sequence of events that led to the problem.
* Write a complete description of the problem along with any error found.
* Capture any relevant screenshots and or errors noted.
* Create a support ticket on https://support.hazelcast.com/s/[Hazelcast Support Portal].
* Attach the appropriate severity to the ticket.

=== Severity levels

* Level 1 is only for current outages in production environments, where there is no workaround.
* Level 2 is for current outages in production environments, but a workaround exists (e.g. directing users to static content).
* Level 3 is for issues in development, low-impact production issues, or to support analysis of a production issue which is no longer ongoing.
* Level 4 is for questions, suggestions, and all other issues.

=== Adding Details to the Support Ticket

* When you open a support ticket add a concise title and description of the problem.
* Add steps to reproduce as best as you can document them so that support can attempt
to reproduce the problem. This includes Detailed description of incident – what happened and when. 
* Add a reproducible test case, this is optional - Hazelcast engineering may ask for it if required.
* Add details of use case. This is crucial as it helps support narrow down the features and
functionality in play when the problem occurred.
* Attach any specific errors found.
* Attach the complete logs files, i.e., Hazelcast logs.
* Attach Hazelcast process logs.
* Attach Hazelcast health monitor logs.
* Attach thread dumps from all members.
* Attach heap dumps.
* Add networking logs.
* Specify the time of incident.
* When providing Hazelcast logs, please make sure that the system and
environment details that are captured at system startup are included, even if you truncate the logs.
* Add Hazelcast diagnostic logs. Please do not truncate diagnostics logs. They only capture Hazelcast
systems specific information and details.
* Please make sure that the logs capture data around the date and time of the incident.

Please consider the above for prompt help from the team and note that the more information
is provided upfront the better.
Lastly, be prompt in your communication with Hazelcast support - helps to ensure timely resolution of issues.

== Developer Resources

* Hazelcast source code can be found at https://github.com/hazelcast/hazelcast[GitHub/Hazelcast^].
This is also where you can contribute and report issues.
* Hazelcast API can be found at https://docs.hazelcast.org/docs/latest/javadoc/[hazelcast.org/docs/Javadoc^].
* Code samples can be downloaded from https://github.com/hazelcast/hazelcast-code-samples[GitHub/hazelcast-code-samples^].
* More use cases and resources can be found at http://www.hazelcast.com[hazelcast.com^].
* xref:getting-started:support.adoc[Support information].