= Replicate over WAN
:description: This tutorial guides you to synchronize multiple Hazelcast clusters, which are connected by WANs, to the same state.

{description} If you have maps or caches in your clusters and you want the data stored in these clusters to be replicated,
you can use the WAN Replication feature; it keeps multiple Hazelcast clusters in sync by replicating their state over WAN.

WAN Replication can work in two modes:

* Active-Passive: It is useful for failover scenarios where you want to replicate an active cluster to one or more passive clusters,
for the purpose of maintaining a backup. If the active cluster becomes unavailable, you can redirect the application traffic to the passive cluster.
* Active-Active: It is useful for geographically distributed clusters. In this mode each cluster replicates to all other clusters.

This tutorial is for the Active-Active mode, and you will:

. Start a Hazelcast Enterprise cluster with WAN Replication configured
. Start another cluster with WAN Replication configured
. Create the same map in these clusters with data in it
. Update some map entries in one cluster and see the updates replicated to the other one

== Before You Begin

To complete this tutorial, you need the following:

[cols="1a,1a"]
|===
|Prerequisites|Useful resources

|Docker
|
link:https://docs.docker.com/docker-for-mac/install/[Install Docker for Mac]

link:https://docs.docker.com/engine/install/[Install Docker for Linux]

link:https://docs.docker.com/docker-for-windows/install/[Install Docker for Windows]

|Docker image for the full Hazelcast distribution
|xref:get-started-enterprise.adoc[Install Hazelcast Enterprise]

|Docker network with the name `hazelcast-network`
|Use the `docker network create hazelcast-network` command 

|===

== Step 1. Start the First Cluster

???

== Step 2. Start the Second Cluster

???

== Step 3. Create the Maps

???

== Step 4. Update Map Entries

???

NOTE: See xref:wan:wan.adoc[Synchronizing Data Across Clusters] if you're
interested in learning more about the topics introduced in this tutorial.
