[[configuring-connections-to-external-data-stores]]
= Configuring Connections to Data Links
:description: You can define reusable connections to data link in your members' configuration files or with the Java member API. When you have a configured connection, you can then use it in the Pipeline API, SQL mappings, and MapStores.
:page-beta: true

{description}

== Quickstart Configuration

To configure a connection to the data link, you must provide a unique identifier for the connection as well as a factory that creates the connection.

This example configuration defines connections to both a MySQL database and a H2 data store.

[tabs]
====
XML::
+
--
[source,xml]
----
<hazelcast>
  <data-link name="my-mysql-database">
    <class-name>com.hazelcast.datalink.JdbcDataLink</class-name>
    <properties>
      <property name="jdbcUrl">jdbc:mysql://mysql.example.org:3306</property>
      <property name="username">my_user</property>
      <property name="password">my_password</property>
    </properties>
    <shared>true</shared>
  </data-link>
  <data-link name="my-other-database">
    <class-name>com.hazelcast.datalink.JdbcDataLink</class-name>
    <properties>
      <property name="jdbcUrl">jdbc:h2:mem:my-other-database</property>
    </properties>
    <shared>true</shared>
  </data-link>
</hazelcast>
----
--

YAML::
+
--
[source,yaml]
----
hazelcast:
  data-link:
    my-mysql-database:
      class-name: com.hazelcast.datalink.JdbcDataLink
      properties:
        jdbcUrl: jdbc:mysql://mysql.example.org:3306
        username: my_user
        password: my_password
      shared: true
    my-other-database:
      class-name: com.hazelcast.datalink.JdbcDataLink
      properties:
        jdbcUrl: jdbc:h2:mem:my-other-database
      shared: true
----
--

Java::
+
--
[source,java]
----
config
  .addDataLinkConfig(
    new DataLinkConfig("my-mysql-database")
      .setClassName(JdbcDataLink.class.getName())
      .setProperty("jdbcUrl", "jdbc:mysql://mysql.example.org:3306")
      .setProperty("username", "my_user")
      .setProperty("password", "my_password")
      .setShared(true)
  )
  .addDataLink(
    new DataLinkConfig("my-other-database")
      .setClassName(JdbcDataLink.class.getName())
      .setProperty("jdbcUrl", "jdbc:h2:mem:my-other-database")
      .setShared(true)
  );
----
--
====

== Configuration Options for Data Links

The data link has the following configuration options:

If you are using Java to configure the Mapstore, use the link:https://docs.hazelcast.org/docs/{full-version}/javadoc/com/hazelcast/config/DataLinkConfig.html[`DataLinkConfig` object].

.Data Link configuration options
[cols="1a,1a",options="header"]
|===
|Option|Description|Default|Example


|`name` (required)
|The unique identifier for the data link.

|`class-name` (required)
|The name of a `com.hazelcast.datalink.DataLink` implementation that creates instances of a data link connection.

|`properties`
|Any configuration properties that the factory in the `class-name` configuration expects to receive.

|`shared`
|Whether the factory in the `class-name` configuration returns reusable connections for use in different MapStores, jobs, and SQL mappings. The behavior of this configuration depends on the implementation of the factory. The default value is `true`.

|===

[[factories]]
== Pre-Built Factories

Hazelcast comes with the following pre-built factories that you can configure in the `class-name` configuration:

.Factories
[cols="1a,1a,1a",options="header"]
|===
|Factory|Description|Properties

|`com.hazelcast.datalink.JdbcDataLink`
|Connect to a data link that supports JDBC. Supported data links include MySQL, PostgreSQL, and H2.
|For available configuration properties see link:https://github.com/brettwooldridge/HikariCP#gear-configuration-knobs-baby[HikariCP configuration]. This implementation is based on link:https://github.com/brettwooldridge/HikariCP[HikariDataSource]. All properties are passed directly to `HikariConfig`. 

|===

If there are more JDBC connections used on a single member from a single job, they will share the same data store and connection pool.

NOTE: If you use the slim distribution of Hazelcast with a built-in data link factory, make sure that you have an appropriate driver on your cluster's classpath.

== Related Resources

You can also add new data links dynamically at runtime, see xref:configuration:dynamic-config.adoc[dynamic configuration].

== Next Steps

Use your configured connection:

- Build a data pipeline with the xref:integrate:jdbc-connector.adoc[Pipeline API].
- Query your data link, using a xref:sql:mapping-to-jdbc.adoc[SQL mapping].
- Build a cache with a xref:mapstore:configuring-a-generic-mapstore.adoc[MapStore].
