= Job Security
:description: The Jet API allows you to upload custom code as well as access data outside of Hazelcast such as files on the device that's running a member. As a result, it's important to be aware of how to secure your Hazelcast member against malicious uses of the Jet API.

{description}

To secure your cluster against malicious jobs, you have the following options:

- <<disabling-code-uploads, Disable code uploads>>: Do not allow applications to submit Java classes along with a job.
- <<disabling-the-jet-engine, Disable the Jet engine>>: Do not allow any jobs to run on the cluster.
+
NOTE: You cannot run SQL queries when the Jet engine is disabled.
- <<controlling-access-to-jobs, Control which clients have permission to work with jobs>> (Enterprise).

WARNING: The open source distribution of Hazelcast does not include security settings. To secure your Hazelcast members against clients misusing jobs, you can only <<disabling-code-uploads, disable code uploads>> or the <<disabling-the-jet-engine, whole Jet engine>>.

== Disabling Code Uploads

When submitting a job to a member, you have the option of uploading some of your own classes for the cluster to run with the job. This code is not subject to any xref:security:native-client-security.adoc[client permissions] that you may have set up. For example, if you restrict clients' write access to a map, the uploaded code bypasses those restrictions and can write to the map.

NOTE: If you're using Hazelcast in xref:getting-started:get-started-java.adoc[embedded mode], this feature is disabled by default.

To disable this feature, use the following configuration:

[tabs] 
==== 
XML:: 
+ 
--
[source,xml]
----
<jet enabled="true" resource-upload-enabled="false">
  ...
</jet>
----
--
YAML:: 
+ 
--
[source,yaml]
----
jet:
  enabled: true
  resource-upload-enabled: true
----
--
Java:: 
+ 
--
[source,java]
----
Config config = new Config();
JetConfig jetConfig = config.getJetConfig();
jetConfig.setEnabled(true).setResourceUploadEnabled(true);
HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
----
--
====

== Disabling the Jet Engine

If you don't plan on using the Jet engine, it's safer to disable it. This way, your members don't start Jet, keeping your members safe from malicious jobs.

WARNING: Disabling Jet also disables <<disabling-code-uploads, code uploads>> and xref:query:sql-overview,adoc[SQL queries].

NOTE: If you're using Hazelcast in xref:getting-started:get-started-java.adoc[embedded mode], this feature is disabled by default.

To disable this feature, use the following configuration:

[tabs] 
==== 
XML:: 
+ 
--
[source,xml]
----
<jet enabled="false">
  ...
</jet>
----
--
YAML:: 
+ 
--
[source,yaml]
----
jet:
  enabled: false
----
--
Env:: 
+ 
--
[source,shell]
----
HZ_JET_RESOURCE-UPLOAD-ENABLED=true
----
Java:: 
+ 
--
[source,java]
----
Config config = new Config();
JetConfig jetConfig = config.getJetConfig();
jetConfig.setEnabled(false);
HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
----
--
====

== Controlling Access to Jobs

In Hazelcast Enterprise, you can restrict access to jobs, using the following xref:security:native-client-security.adoc[client permissions]:

- Job permissions: Restrict what clients can do with jobs.
- Connector permissions: Restrict read and write access for each connector.

=== Job Permissions

When the <<disabling-code-uploads, code uploads>> and the <<disabling-the-jet-engine, Jet engine>> are enabled, all clients are unrestricted in what they can do with jobs.

To restrict clients, you can set the following permissions:

- `submit`: Submit a new job, without uploading resources.
- `cancel`: Cancel a running job.
- `read`: Get or list information about a job (by ID or name) such as job configuration, job status, and
submission time.
- `suspend`: Suspend a running job.
- `resume`: Resume a suspended job.
- `export-snapshot`: Export the snapshot.
- `add-resources`: Upload resources and classes as well as jobs to members.
+
NOTE: Hazelcast cannot check permissions in code that's uploaded with a job, If you enable this permission, clients can upload custom code that ignores any configured permissions.
- `all`: Enable all actions.

NOTE: All actions for job permissions also enable the `read` action. For example if you enable the `submit` action, the `read` action is automatically enabled as well.

=== Connector Permissions

By default, xref:sources-sinks.adoc[connectors] can read and write data that you may want to keep secure.

For example, the file connector gives jobs access to all files on your members' local filesystems. As a result, a job could use this connector to read SSH keys and log them to the console.

[source,java]
----
Pipeline pipeline = Pipeline.create();
pipeline.readFrom(Sources.files("/Users/ali/.ssh"))
  .writeTo(Sinks.logger());
----

You can set the following permissions for each connector:

- `read`: Read data from sources.
- `write`: Write data to sinks.
- `all`: Enable all actions.

NOTE: If you use the data structure connectors such as the IMap connector, you must also have certain xref:security:native-client-security.adoc[permissions] on those data structures. For example, to read from map sources, you must add the `create` and `read` permissions for those maps. If you use the IMap connector to write to map sinks, you must add the `create` and `put` permissions for those maps.

== Related Resources

For information on how to set client permissions, see xref:security:native-client-security.adoc[].