name: Adoc to HTML

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Convert adoc
      run: |
        npm i asciidoctor
        asciidoctor ../../docs/modules/whats-new/whats-new.adoc
        mv ../../docs/modules/whats-new/whats-new.adoc ../../docs/modules/whats-new/index.adoc
        
