name: Backport Testing
env:
  GH_TOKEN: ${{ secrets.DEVOPSHAZELCAST_PAT_FOR_MONOREPO }}
  GH_TOKEN_OUTER: ${{ secrets.DEVOPSHAZELCAST_PAT_FOR_MONOREPO }}
  GH_TOKEN_OUTER_2: ${{ secrets.GH_PAT }}
  GH_TOKEN_OUTER_3: ${{ secrets.DOCKERHUB_USERNAME }}

on:
  pull_request:
     
jobs:
  forwardport:
    uses: ./.github/workflows/backport-workflow.yml
    secrets: inherit
    
  backport:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # ensure the backport target branch is checked out, too
          fetch-depth: 0
          ref: v/5.5
