name: Backport Testing

on:
  pull_request:
     
jobs:
  forwardport:
    uses: ./.github/workflows/backport-workflow.yml
    secrets: inherit
    
  backport:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # ensure the backport target branch is checked out, too
          fetch-depth: 0
          ref: v/5.5
