name: Test external links

on:
  workflow_dispatch:
jobs:
  test-external-links:
    runs-on: ubuntu-latest

    steps:
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,job,workflow
          text: "🙏 Thanks Candace! 🙏"
          channel: "#docs-notifications"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DOCS }}
