name: Vale PR linter

on:
  pull_request:
    branches:
      - main
     
jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.GH_TOKEN }}
      - run: sudo apt-get install -y asciidoctor
      - uses: errata-ai/vale-action@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          vale_flags: "--config=hz-vale/.vale.ini --glob=*.adoc"
