name: Docs validation

on:
  pull_request:
    branches: [main, 'v/*']
  workflow_dispatch:

jobs:
  validate-docs:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4
      - name: Validate Docs
        uses: fantkolja/hazelcast-docs/.github/actions/validate@feature/validate-docs-slack-notification
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DOCS }}
