name: Docs validation

on:
  pull_request:
    branches: [main, 'v/*']
  workflow_dispatch:

jobs:
  validate-docs:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4
      - name: Validate Docs
        uses: hazelcast/hazelcast-docs-tools/.github/actions/validate-docs@actions/v1
